//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <YogaFrameworkA/NSObject-Protocol.h>

@class BCAABundleContext;

@protocol BCAABundleActivator <NSObject>
- (void)bundleDidStart:(BCAABundleContext *)arg1;

@optional
- (void)bundleDidStop:(BCAABundleContext *)arg1;
@end

