//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError;
@protocol _TtP17AWESpeCategoryKit20ListResponseProtocol_;

@protocol _TtP17AWESpeCategoryKit18DataChangeProtocol_

@optional
- (void)onListDidReloadData;
- (void)onLoadMoreListDataEndWithReason:(long long)arg1 success:(_Bool)arg2 response:(id <_TtP17AWESpeCategoryKit20ListResponseProtocol_>)arg3 error:(NSError *)arg4;
- (void)onLoadMoreListDataStartWithReason:(long long)arg1;
- (void)onFetchListDataEndWithReason:(long long)arg1 success:(_Bool)arg2 response:(id <_TtP17AWESpeCategoryKit20ListResponseProtocol_>)arg3 error:(NSError *)arg4;
- (void)onFetchListDataStartWithReason:(long long)arg1;
- (void)onLoadPlaceholderDataEndWithSuccess:(_Bool)arg1 response:(id <_TtP17AWESpeCategoryKit20ListResponseProtocol_>)arg2 error:(NSError *)arg3;
- (void)onLoadPlaceholderDataStart;
@end

