//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class FlowIMCocoError;

@protocol _TtP7FlowIMX31FlowIMConnectionServiceDelegate_
- (void)onConnectionFailedWithState:(long long)arg1 error:(FlowIMCocoError *)arg2;
- (void)onChangeConnectionStatusWithState:(long long)arg1;

@optional
- (void)onChangeReachabilityStatus:(_Bool)arg1;
@end

