//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC7FlowIMX17FlowIMDBQueueTask;

@protocol _TtP7FlowIMX28FlowIMDBQueueCheckerDelegate_
- (void)onTaskTimeout:(_TtC7FlowIMX17FlowIMDBQueueTask *)arg1;
@end

