//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSIndexPath, NSString, UICollectionReusableView, UICollectionView, UICollectionViewCell, UIScrollView;

@protocol _TtP7FlowKit30MessagingListViewEventListener_

@optional
- (void)scrollViewDidChangeAdjustedContentInset:(UIScrollView *)arg1;
- (void)scrollViewDidScrollToTop:(UIScrollView *)arg1;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)arg1;
- (void)scrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)arg1;
- (void)scrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
- (void)collectionView:(UICollectionView *)arg1 didEndDisplayingSupplementaryView:(UICollectionReusableView *)arg2 forElementOfKind:(NSString *)arg3 at:(NSIndexPath *)arg4;
- (void)collectionView:(UICollectionView *)arg1 willDisplaySupplementaryView:(UICollectionReusableView *)arg2 forElementKind:(NSString *)arg3 at:(NSIndexPath *)arg4;
- (void)collectionView:(UICollectionView *)arg1 didEndDisplaying:(UICollectionViewCell *)arg2 forItemAt:(NSIndexPath *)arg3;
- (void)collectionView:(UICollectionView *)arg1 willDisplay:(UICollectionViewCell *)arg2 forItemAt:(NSIndexPath *)arg3;
@end

