//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, UIViewController;

@protocol _TtP22AWEKnowledgeSwiftBasic26ContainerLifeCycleProtocol_

@optional
- (void)onContainerViewDidSetup;
- (void)onContainerDidReceiveAwemeDeleteWithItemID:(NSString *)arg1;
- (void)onContainerDidReceiveMemoryWarning;
- (void)onContainerViewDidLayoutSubviews;
- (void)onContainerViewWillLayoutSubviews;
- (void)onContainerDidMoveToParent:(UIViewController *)arg1;
- (void)onContainerWillMoveToParent:(UIViewController *)arg1;
- (void)onContainerViewDidDisappear;
- (void)onContainerViewWillDisappear;
- (void)onContainerViewDidAppear;
- (void)onContainerViewWillAppear;
- (void)onContainerViewDidLoad;
@end

