//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UICollectionView, UIScrollView;

@protocol _TtP22AWEKnowledgeSwiftBasic30ListContainerLifeCycleProtocol_

@optional
- (void)onScrollViewDidEndScrollingAnimationWithScrollView:(UIScrollView *)arg1;
- (void)onScrollViewDidEndDeceleratingWithScrollView:(UIScrollView *)arg1;
- (void)onScrollViewDidEndDraggingWithScrollView:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)onScrollViewWillEndDraggingWithScrollView:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (void)onScrollViewWillBeginDraggingWithScrollView:(UIScrollView *)arg1;
- (void)onScrollViewDidScrollWithScrollView:(UIScrollView *)arg1;
- (void)onSetupCollectionViewWithCollectionView:(UICollectionView *)arg1;
@end

