//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class PushMessageBaseObject;

@protocol _TtP7FlowIMX31FlowIMConnectionServiceReceiver_
- (void)onMessageReceivedWithMessage:(PushMessageBaseObject *)arg1;
@end

