//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSIndexPath, UICollectionView, UICollectionViewCell;

@protocol _TtP23BDMultiContentContainer37BaseContentListCollectionViewProtocol_

@optional
- (void)onCollectionView:(UICollectionView *)arg1 didEndDisplaying:(UICollectionViewCell *)arg2 forItemAt:(NSIndexPath *)arg3;
- (void)onCollectionView:(UICollectionView *)arg1 willDisplay:(UICollectionViewCell *)arg2 forItemAt:(NSIndexPath *)arg3;
@end

