//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IESMMCameraConfig, UIView;
@protocol VERecorderPublicProtocol;

@protocol _TtP9CameraKit35CameraSessionManagerPreloadProtocol_
+ (id <VERecorderPublicProtocol>)preloadCreateCameraInstanceWith:(UIView *)arg1 imageDuet:(_Bool)arg2 cameraConfig:(IESMMCameraConfig *)arg3 completion:(void (^)(void))arg4;
- (void)bindCameraActionMessageWith:(void (^)(NSNumber *, NSError *, id))arg1;
- (void)resetCameraConfigWith:(id <VERecorderPublicProtocol>)arg1 contentView:(UIView *)arg2 config:(IESMMCameraConfig *)arg3;
- (void)setCameraPreloadFlag;
@end

