//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWEAwemeModel, NSString, _TtC22AWEKnowledgeSwiftBasic22FullPageSectionContext;

@protocol _TtP22AWEKnowledgeSwiftBasic33FullPageBaseItemViewModelProtocol_
- (void)configWithSectionContext:(_TtC22AWEKnowledgeSwiftBasic22FullPageSectionContext *)arg1 model:(AWEAwemeModel *)arg2;
@property(nonatomic, readonly) double itemHeight;
@property(nonatomic, readonly) id sectionConfig;
@property(nonatomic, readonly) _TtC22AWEKnowledgeSwiftBasic22FullPageSectionContext *sectionContext;
@property(nonatomic, readonly) AWEAwemeModel *model;
@property(nonatomic, readonly) NSString *identifier;
@end

