//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UICollectionView;

@protocol _TtP23BDMultiContentContainer33BaseContentListDataUpdateProtocol_

@optional
- (void)listDidPerformBatchUpdates:(UICollectionView *)arg1;
- (void)listDidReloadData:(UICollectionView *)arg1;
- (void)onModelDidUpdateWithModel:(id)arg1;
- (void)onListDidReset;
@end

