//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UICollectionViewCell, _TtC22AWEKnowledgeSwiftBasic25FullPageBaseItemViewModel;

@protocol _TtP22AWEKnowledgeSwiftBasic34FullPageBaseItemControllerProtocol_
- (void)viewControllerDidDisappear:(_Bool)arg1;
- (void)viewControllerDidAppear:(_Bool)arg1;
- (void)sectionControllerDidEndDisplaying;
- (void)sectionControllerWillDisplay;
- (void)cellDidEndDisplayWithCell:(UICollectionViewCell *)arg1 viewModel:(id)arg2;
- (void)cellWillDisplayWithCell:(UICollectionViewCell *)arg1 viewModel:(id)arg2;
- (void)configCellWithCell:(UICollectionViewCell *)arg1 viewModel:(id)arg2;
- (Class)cellClass;
- (id)initWithViewModel:(_TtC22AWEKnowledgeSwiftBasic25FullPageBaseItemViewModel *)arg1;
@property(nonatomic, copy) CDUnknownBlockType requireLoginBlock;
@property(nonatomic, copy) CDUnknownBlockType heightDidChangeBlock;
@property(nonatomic, copy) CDUnknownBlockType getSectionContainerBlock;
@property(nonatomic, readonly) double height;
@property(nonatomic, retain) _TtC22AWEKnowledgeSwiftBasic25FullPageBaseItemViewModel *viewModel;
@end

