//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMCameraConfig, _TtC9CameraKit13CameraSession, _TtC9CameraKit16CameraSessionKey, _TtC9CameraKit19CameraSessionConfig;
@protocol VERecorderPublicProtocol, _TtP9CameraKit31CameraSessionSwitchSubscription_;

@protocol _TtP9CameraKit28CameraSessionManagerProtocol_ <NSObject>
- (void)restoreCameraConfig;
- (void)saveCameraConfig;
- (_Bool)switchToCameraSessionWith:(_TtC9CameraKit16CameraSessionKey *)arg1 error:(id *)arg2 updateContextBlock:(void (^)(id <_TtP9CameraKit21CameraContextProtocol_>))arg3 completion:(void (^)(void))arg4;
- (void)addSubscription:(id <_TtP9CameraKit31CameraSessionSwitchSubscription_>)arg1;
- (void)releaseCameraSessionWith:(_TtC9CameraKit16CameraSessionKey *)arg1;
- (_TtC9CameraKit16CameraSessionKey *)createCameraSessionWith:(_TtC9CameraKit19CameraSessionConfig *)arg1 cameraConfig:(IESMMCameraConfig *)arg2;
- (void)setVECameraInstance:(id <VERecorderPublicProtocol>)arg1;
- (void)preloadCameraInstanceWith:(IESMMCameraConfig *)arg1;
@property(nonatomic, readonly) id <VERecorderPublicProtocol> vecamera;
@property(nonatomic, readonly) _Bool cameraControlPreload;
@property(nonatomic, readonly) _Bool cameraHasPrviousProload;
@property(nonatomic, readonly) _TtC9CameraKit13CameraSession *activeSession;
@end

