//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class _TtC9FlowAVSDK14FlowAudioFrame;

@protocol _TtP9FlowAVSDK24FlowAVAudioDataProcessor_ <NSObject>
- (_TtC9FlowAVSDK14FlowAudioFrame *)onProcessPlayFrame:(_TtC9FlowAVSDK14FlowAudioFrame *)arg1;
- (_TtC9FlowAVSDK14FlowAudioFrame *)onProcessRecordFrame:(_TtC9FlowAVSDK14FlowAudioFrame *)arg1;
@end

