//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol _TtP23BDMultiContentContainer19OverlayViewDelegate_ <NSObject>
- (void)overlayView:(UIView *)arg1 containerDidScrollTo:(struct CGPoint)arg2;
- (_Bool)overlayView:(UIView *)arg1 shouldResponseToTap:(struct CGPoint)arg2 from:(UIView *)arg3;
- (void)overlayView:(UIView *)arg1 didUpdateSize:(struct CGSize)arg2;
@end

