//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>
#import <AwemeCore/_TtP7FlowIMX28FlowIMBotConversationService_-Protocol.h>
#import <AwemeCore/_TtP7FlowIMX36FlowIMConversationService_Deprecated_-Protocol.h>

@class FlowIMGroupConversationTemplate, FlowIMImageModelV2, NSArray, NSDictionary, NSString, _TtC7FlowIMX26AutoGenConversationRequest, _TtC7FlowIMX28CancelAllChunkServiceRequest, _TtC7FlowIMX28MarkConversationInOutRequest, _TtC7FlowIMX28SearchLocalDBMessagesRequest, _TtC7FlowIMX29FlowIMGetConversationsRequest, _TtC7FlowIMX33FlowIMGetConversationsCursorModel, _TtC7FlowIMX33SearchLocalDBConversationsRequest, _TtC7FlowIMX34FlowIMGetConversationsBotIDRequest;
@protocol _TtP7FlowIMX18FlowIMConversation_, _TtP7FlowIMX33FlowIMConversationServiceDelegate_;

@protocol _TtP7FlowIMX25FlowIMConversationService_ <NSObject, _TtP7FlowIMX28FlowIMBotConversationService_, _TtP7FlowIMX36FlowIMConversationService_Deprecated_>
- (void)updateForbidSendMsgOf:(NSString *)arg1 value:(NSString *)arg2;
- (void)searchLocalDBMessagesWithReq:(_TtC7FlowIMX28SearchLocalDBMessagesRequest *)arg1 success:(void (^)(_TtC7FlowIMX29SearchLocalDBMessagesResponse *))arg2 fail:(void (^)(NSError *))arg3;
- (void)searchLocalDBConversationsWithReq:(_TtC7FlowIMX33SearchLocalDBConversationsRequest *)arg1 success:(void (^)(_TtC7FlowIMX34SearchLocalDBConversationsResponse *))arg2 fail:(void (^)(NSError *))arg3;
- (void)markConversationInOutWithReq:(_TtC7FlowIMX28MarkConversationInOutRequest *)arg1 success:(void (^)(_TtC7FlowIMX19FlowIMEmptyResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)cancelAllChunkServiceWithReq:(_TtC7FlowIMX28CancelAllChunkServiceRequest *)arg1 success:(void (^)(_TtC7FlowIMX19FlowIMEmptyResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)updateConversationStatusOf:(NSString *)arg1 status:(long long)arg2 completion:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg3;
- (void)getAllConversationUnreadWithSuccess:(void (^)(long long, NSDictionary *))arg1 fail:(void (^)(FlowIMCocoError *))arg2;
- (long long)getConversationVersion;
- (long long)getBotUnreadCount;
- (long long)getSocialUnreadCount;
- (long long)getTotalUnreadCount;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createLocalGroupConversationWithConversationID:(NSString *)arg1 name:(NSString *)arg2 icon:(FlowIMImageModelV2 *)arg3 ext:(NSDictionary *)arg4;
- (void)asyncGetConversationLastMessageIndexOf:(NSString *)arg1 callback:(void (^)(long long))arg2;
- (long long)getConversationLastMessageIndexOf:(NSString *)arg1 caller:(NSString *)arg2 file:(NSString *)arg3;
- (void)asyncGetConversationWithConversationID:(NSString *)arg1 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)getConversationWithConversationID:(NSString *)arg1 caller:(NSString *)arg2 file:(NSString *)arg3;
- (void)getConversationBotIDsBy:(_TtC7FlowIMX34FlowIMGetConversationsBotIDRequest *)arg1 callback:(void (^)(_TtC7FlowIMX35FlowIMGetConversationsBotIDResponse *, FlowIMCocoError *))arg2;
- (void)asyncGetConversationListWithCursor:(_TtC7FlowIMX33FlowIMGetConversationsCursorModel *)arg1 callback:(void (^)(NSArray *, FlowIMCocoError *))arg2;
- (NSArray *)getConversationListWithCursor:(_TtC7FlowIMX33FlowIMGetConversationsCursorModel *)arg1 caller:(NSString *)arg2 file:(NSString *)arg3;
- (void)getConversationListBy:(_TtC7FlowIMX29FlowIMGetConversationsRequest *)arg1 callback:(void (^)(_TtC7FlowIMX30FlowIMGetConversationsResponse *))arg2;
- (void)asyncGetConversationListWithCallback:(void (^)(NSArray *, FlowIMCocoError *))arg1;
- (NSArray *)getConversationListWithCaller:(NSString *)arg1 file:(NSString *)arg2;
- (void)requestRecentConvMessagesWithScene:(long long)arg1;
- (void)updateConversationMetaInfoWithConversationID:(NSString *)arg1 createScene:(long long)arg2 success:(void (^)(void))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)updateConversationMetaInfoWithConversationID:(NSString *)arg1 name:(NSString *)arg2 success:(void (^)(void))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)refreshConversationMetaInfoBy:(NSString *)arg1 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)refreshConversationMetaInfoBy:(NSString *)arg1 extra:(NSDictionary *)arg2 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)getConversationMetaInfoByBot:(NSString *)arg1 extra:(NSDictionary *)arg2 forceRemote:(_Bool)arg3 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg4 fail:(void (^)(FlowIMCocoError *))arg5;
- (void)getConversationMetaInfoByBot:(NSString *)arg1 forceRemote:(_Bool)arg2 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)getConversationMetaInfoByBot:(NSString *)arg1 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)getConversationMetaInfoBy:(NSString *)arg1 forceRemote:(_Bool)arg2 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)getConversationMetaInfoBy:(NSString *)arg1 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)exitWithConversationID:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)clearHistoryWithConversationID:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)clearContextWithConversationID:(NSString *)arg1 success:(void (^)(NSString *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)autoGenConversationWithReq:(_TtC7FlowIMX26AutoGenConversationRequest *)arg1 success:(void (^)(_TtC7FlowIMX27AutoGenConversationResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)conversationAutoSpeak:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)dissolveConversationWithConversationID:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)markReadWithConversationID:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)updateMuted:(_Bool)arg1 for:(NSString *)arg2;
- (void)unpinWithConversationID:(NSString *)arg1 cellType:(long long)arg2 success:(void (^)(void))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)pinWithConversationID:(NSString *)arg1 cellType:(long long)arg2 success:(void (^)(void))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)deleteLocalConversationWith:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)batchDeleteUserConversationWithConversationIds:(NSArray *)arg1 conversationType:(long long)arg2 success:(void (^)(NSDictionary *))arg3 fail:(void (^)(FlowIMCocoError *))arg4;
- (void)deleteConversationWith:(NSString *)arg1 success:(void (^)(void))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)updateGroupConversationWithConversationID:(NSString *)arg1 template:(FlowIMGroupConversationTemplate *)arg2 joinedParticipants:(NSArray *)arg3 deletedParticipants:(NSArray *)arg4 success:(void (^)(void))arg5 fail:(void (^)(FlowIMCocoError *))arg6;
- (void)createGroupConversationFrom:(NSString *)arg1 with:(NSArray *)arg2 template:(FlowIMGroupConversationTemplate *)arg3 localMessages:(NSArray *)arg4 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg5 fail:(void (^)(FlowIMCocoError *))arg6;
- (void)createUserConversationWith:(NSString *)arg1 success:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)removeDelegate:(id <_TtP7FlowIMX33FlowIMConversationServiceDelegate_>)arg1;
- (void)addDelegate:(id <_TtP7FlowIMX33FlowIMConversationServiceDelegate_>)arg1;
@end

