//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP17AWESpeCategoryKit21PlayerControlProtocol_

@optional
- (void)onReplayWithTimes:(long long)arg1;
- (void)onPause;
- (void)onPlay;
@end

