//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP17AWESpeCategoryKit20AppLifeCycleProtocol_

@optional
- (void)appWillResignActive;
- (void)appDidBecomeActive;
- (void)appDidEnterBackground;
- (void)appWillEnterForeground;
@end

