//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/_TtP17AWESpeCategoryKit17ComponentProtocol_-Protocol.h>

@class NSDictionary;

@protocol _TtP21AWEKnowledgeSwiftImpl28HangoutListComponentProtocol_ <_TtP17AWESpeCategoryKit17ComponentProtocol_>

@optional
- (void)didLeaveWithParams:(NSDictionary *)arg1;
- (void)didLandingWithParams:(NSDictionary *)arg1;
- (void)didEnterWithParams:(NSDictionary *)arg1;
@end

