//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIScrollView;

@protocol _TtP15AWEPaySwiftImpl30TripBaseViewControllerDelegate_
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
@end

