//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIView;

@protocol _TtP23BDMultiContentContainer16StickerClickable_
- (_Bool)shouldResponseToTap:(struct CGPoint)arg1 from:(UIView *)arg2;
@end

