//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSError, NSURL, UIImage, _TtC23BDMultiContentContainer20ImageContentCellView;

@protocol _TtP23BDMultiContentContainer32BaseContentListImageCellProtocol_

@optional
- (void)onImageCellDidEndLoadPreviewImage:(id)arg1 image:(UIImage *)arg2 url:(NSURL *)arg3 error:(NSError *)arg4;
- (void)onImageCellDidEndLoadImage:(id)arg1 image:(UIImage *)arg2 url:(NSURL *)arg3 error:(NSError *)arg4;
- (void)onImageCellWillLoadImage:(id)arg1 cell:(_TtC23BDMultiContentContainer20ImageContentCellView *)arg2;
@end

