//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol _TtP18IESLiveRevenueImpl25IESLiveRFVoiceChatTracker_ <NSObject>
- (void)monitor:(NSString *)arg1 params:(NSDictionary *)arg2;
- (void)logInfo:(NSString *)arg1 params:(NSDictionary *)arg2;
- (void)trackEvent:(NSString *)arg1 params:(NSDictionary *)arg2;
@end

