//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP26AWERichContentAdapterBasic30AlbumSectionControllerProtocol_
- (id)getCurrentCellStickerManager;
- (struct CGRect)getCurrentImageContentRect;
- (struct CGRect)getCurrentImageRectInContent;

@optional
- (void)zoomCurrentImageToRatioRect:(struct CGRect)arg1 scale:(double)arg2 animated:(_Bool)arg3;
- (void)setCurrentImageZoomWrapperWithInfo:(id)arg1 animated:(_Bool)arg2 completion:(void (^)(void))arg3;
- (id)getCurrentImageZoomInfoWrapper;
- (void)updateAlbumContentModeLayout;
- (void)setImageContentInsetsWithInsets:(struct UIEdgeInsets)arg1 animated:(_Bool)arg2 duration:(double)arg3;
- (struct UIEdgeInsets)getImageContentInsets;
- (void)updateShrinkStateWithIsShrink:(_Bool)arg1 insets:(struct UIEdgeInsets)arg2 animated:(_Bool)arg3 animationDuration:(double)arg4;
- (id)getShrinkState;
@end

