//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>
#import <AwemeCore/_TtP7FlowIMX15IdentifableData_-Protocol.h>
#import <AwemeCore/_TtP7FlowIMX21FlowIMSafeMapCopyable_-Protocol.h>

@class FlowIMReferenceInfo, NSArray, NSDictionary, NSString, _TtC7FlowIMX20FlowIMSubMsgIndexKey;

@protocol _TtP7FlowIMX13FlowIMMessage_ <NSObject, _TtP7FlowIMX15IdentifableData_, _TtP7FlowIMX21FlowIMSafeMapCopyable_>
@property(nonatomic, readonly) long long errorCode;
@property(nonatomic, readonly) NSString *allTypingContentsText;
@property(nonatomic, readonly) NSArray *typingContents;
@property(nonatomic, readonly) long long typingUnitIndex;
@property(nonatomic, readonly) _TtC7FlowIMX20FlowIMSubMsgIndexKey *streamingSubMsgIndex;
@property(nonatomic, readonly) _TtC7FlowIMX20FlowIMSubMsgIndexKey *subMsgIndex;
@property(nonatomic, readonly) NSString *referMsgId;
@property(nonatomic, readonly) NSDictionary *subMessages;
@property(nonatomic, readonly) NSString *collectionId;
@property(nonatomic, readonly) _Bool replyFailed;
@property(nonatomic, readonly) NSString *loadingText;
@property(nonatomic, readonly) _Bool regenVisiblity;
@property(nonatomic, readonly) long long regenStatus;
@property(nonatomic, readonly) long long regenIndex;
@property(nonatomic, readonly) NSString *fetchToken;
@property(nonatomic, readonly) NSString *regenRootID;
@property(nonatomic, readonly) NSArray *regenMsgList;
@property(nonatomic, readonly) NSArray *tags;
@property(nonatomic, readonly) long long hasMore;
@property(nonatomic, readonly) NSString *botReplyMessageId;
@property(nonatomic, readonly) long long userType;
@property(nonatomic, readonly) NSString *origin_content;
@property(nonatomic, readonly) NSArray *searchReferences;
@property(nonatomic, readonly) NSArray *metaInfoItems;
@property(nonatomic, readonly) NSArray *metaInfos;
@property(nonatomic, readonly) _Bool thinkingTextFinished;
@property(nonatomic, readonly) NSString *thinkingText;
@property(nonatomic, readonly) NSString *text;
@property(nonatomic, readonly) _Bool isOnboarding;
@property(nonatomic, readonly) _Bool isFromCurrentUser;
@property(nonatomic, readonly) NSString *brief;
@property(nonatomic, readonly) long long messageStatus;
@property(nonatomic, readonly) long long imageUploadStatus;
@property(nonatomic, readonly) NSString *imageDataPath;
@property(nonatomic, readonly) _Bool sourceFromAsr;
@property(nonatomic, readonly) long long messageBodyVersion;
@property(nonatomic, readonly) NSArray *suggestQuestions;
@property(nonatomic, readonly) long long localIndex;
@property(nonatomic, readonly) long long feedbackType;
@property(nonatomic, readonly) NSString *conversationId;
@property(nonatomic, readonly) NSDictionary *bizExt;
@property(nonatomic, readonly) NSDictionary *ext;
@property(nonatomic, readonly) NSString *thinkingContent;
@property(nonatomic, readonly) NSString *content;
@property(nonatomic, readonly) FlowIMReferenceInfo *referenceInfo;
@property(nonatomic, readonly) NSString *senderId;
@property(nonatomic, readonly) long long receivingStatus;
@property(nonatomic, readonly) long long messageSendingStatus;
@property(nonatomic, readonly) NSString *bizContentType;
@property(nonatomic, readonly) long long contentType;
@property(nonatomic, readonly) long long createTime;
@property(nonatomic, readonly) long long serverIndex;
@property(nonatomic, readonly) NSString *sectionName;
@property(nonatomic, readonly) NSString *sectionId;
@property(nonatomic, readonly) NSString *messageId;
@property(nonatomic, readonly) NSString *localMessageId;
@end

