//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC7FlowIMX20UpdateBotTypeWrapper;
@protocol _TtP7FlowIMX9FlowIMBot_;

@protocol _TtP7FlowIMX24FlowIMBotServiceDelegate_
- (void)botInfoDidChange:(id <_TtP7FlowIMX9FlowIMBot_>)arg1 updateBotType:(_TtC7FlowIMX20UpdateBotTypeWrapper *)arg2;

@optional
- (void)botDidDelete:(id <_TtP7FlowIMX9FlowIMBot_>)arg1;
@end

