//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC13AWENoticeImpl36AWENoticeInteractionSegmentedControl;

@protocol _TtP13AWENoticeImpl44AWENoticeInteractionSegmentedControlDelegate_
- (void)segmentedControl:(_TtC13AWENoticeImpl36AWENoticeInteractionSegmentedControl *)arg1 didRepeatTapItemAt:(long long)arg2;
- (void)segmentedControl:(_TtC13AWENoticeImpl36AWENoticeInteractionSegmentedControl *)arg1 didSelectItemAt:(long long)arg2;
@end

