//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWEMusicDetailResponse, NSArray, NSError;

@protocol _TtP28AWEDetailCollectionSwiftImpl40MusicDetailHeaderRegionLifecycleProtocol_

@optional
- (void)onRelatedDataEndWithMusicList:(NSArray *)arg1;
- (void)onFetchDataEndWithSuccess:(_Bool)arg1 response:(AWEMusicDetailResponse *)arg2 error:(NSError *)arg3;
- (void)onContainerViewDidDisappear;
- (void)onContainerViewWillDisappear;
- (void)onContainerViewDidAppear;
- (void)onContainerViewWillAppear;
- (void)onContainerViewDidLoad;
@end

