//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol _TtP7FlowIMX15IdentifableData_
@property(nonatomic, readonly) NSString *messageId;
@end

