//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIScrollView;

@protocol _TtP23BDMultiContentContainer33BaseContentListScrollViewProtocol_

@optional
- (void)onScrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)onScrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)onScrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint *)arg3;
- (void)onScrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)onScrollViewDidScroll:(UIScrollView *)arg1;
@end

