//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol _TtP18IESLiveRevenueImpl31IESLiveRFVoiceChatAIStateAction_ <NSObject>
- (void)didStateChangeFromState:(long long)arg1 toState:(long long)arg2;
@end

