//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/_TtP23BDMultiContentContainer33BaseContentListDataUpdateProtocol_-Protocol.h>
#import <AwemeCore/_TtP23BDMultiContentContainer33BaseContentListScrollViewProtocol_-Protocol.h>
#import <AwemeCore/_TtP23BDMultiContentContainer37BaseContentListCollectionViewProtocol_-Protocol.h>

@protocol _TtP23BDMultiContentContainer32BaseContentListComponentProtocol_ <_TtP23BDMultiContentContainer33BaseContentListScrollViewProtocol_, _TtP23BDMultiContentContainer37BaseContentListCollectionViewProtocol_, _TtP23BDMultiContentContainer33BaseContentListDataUpdateProtocol_>
@end

