//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class PushMessageBaseObject, _TtC7FlowIMX22FlowIMConnectionConfig;
@protocol _TtP7FlowIMX31FlowIMConnectionServiceDelegate_, _TtP7FlowIMX31FlowIMConnectionServiceReceiver_;

@protocol _TtP7FlowIMX23FlowIMConnectionService_ <NSObject>
- (void)removeReceiverWithReceiver:(id <_TtP7FlowIMX31FlowIMConnectionServiceReceiver_>)arg1;
- (void)addReceiverWithReceiver:(id <_TtP7FlowIMX31FlowIMConnectionServiceReceiver_>)arg1;
- (void)removeDelegateWithDelegate:(id <_TtP7FlowIMX31FlowIMConnectionServiceDelegate_>)arg1;
- (void)addDelegateWithDelegate:(id <_TtP7FlowIMX31FlowIMConnectionServiceDelegate_>)arg1;
- (_Bool)sendMessage:(PushMessageBaseObject *)arg1;
- (_Bool)reachabilityStatus;
- (_Bool)isConnected;
- (void)stopConnection;
- (void)startConnectionWithConfig:(_TtC7FlowIMX22FlowIMConnectionConfig *)arg1;
@property(nonatomic, readonly) long long connectionState;
@end

