//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class FlowIMImageModelV2, FlowIMMainBotSubConversationRequest, FlowIMRecommendBotOnboarding, NSDictionary, NSString, _TtC7FlowIMX27GetConversationBotIDRequest, _TtC7FlowIMX28CreateBotConversationRequest, _TtC7FlowIMX28FlowIMSubConversationRequest, _TtC7FlowIMX29FlowIMSubConversationResponse, _TtC7FlowIMX33CreateLocalBotConversationRequest, _TtC7FlowIMX39ConvertLocalConversationToRemoteRequest, _TtC7FlowIMX42CreateLocalAndRemoteBotConversationRequest;
@protocol _TtP7FlowIMX18FlowIMConversation_, _TtP7FlowIMX9FlowIMBot_;

@protocol _TtP7FlowIMX28FlowIMBotConversationService_
- (void)genFakeLocalOnboardingMessageWithConversationId:(NSString *)arg1 botId:(NSString *)arg2 onboarding:(FlowIMRecommendBotOnboarding *)arg3 success:(void (^)(NSArray *))arg4 fail:(void (^)(FlowIMCocoError *))arg5;
- (void)getConversationBotIDWithReq:(_TtC7FlowIMX27GetConversationBotIDRequest *)arg1 success:(void (^)(_TtC7FlowIMX28GetConversationBotIDResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)asyncGetDBBotConversationWithBotID:(NSString *)arg1 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)getDBBotConversationWithBotID:(NSString *)arg1;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createTempMainBotSubConversationWithConversationID:(NSString *)arg1 iconImage:(FlowIMImageModelV2 *)arg2 name:(NSString *)arg3 ext:(NSDictionary *)arg4;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createTempBotConversationWithConversationID:(NSString *)arg1 name:(NSString *)arg2;
- (void)createLocalBotConversationWithReq:(_TtC7FlowIMX33CreateLocalBotConversationRequest *)arg1 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createLocalBotConversationWithReq:(_TtC7FlowIMX33CreateLocalBotConversationRequest *)arg1;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createLocalBotConversationWithBotInfo:(id <_TtP7FlowIMX9FlowIMBot_>)arg1;
- (void)createBotConversationWithReq:(_TtC7FlowIMX28CreateBotConversationRequest *)arg1 success:(void (^)(_TtC7FlowIMX29CreateBotConversationResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)convertLocalConversationToRemoteWithReq:(_TtC7FlowIMX39ConvertLocalConversationToRemoteRequest *)arg1 success:(void (^)(_TtC7FlowIMX40ConvertLocalConversationToRemoteResponse *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)createLocalAndRemoteBotConversationWithReq:(_TtC7FlowIMX42CreateLocalAndRemoteBotConversationRequest *)arg1 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createLocalAndRemoteBotConversationWithReq:(_TtC7FlowIMX42CreateLocalAndRemoteBotConversationRequest *)arg1;
- (void)createCaseSubConversationWithCaseId:(long long)arg1 name:(NSString *)arg2 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg3;
- (void)createCollectSubConversationWithCollectionId:(NSString *)arg1 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createCollectSubConversationWithCollectionId:(NSString *)arg1;
- (void)createLocalMainBotSubConversationWithReq:(_TtC7FlowIMX28FlowIMSubConversationRequest *)arg1 callback:(void (^)(_TtC7FlowIMX29FlowIMSubConversationResponse *))arg2;
- (_TtC7FlowIMX29FlowIMSubConversationResponse *)createLocalMainBotSubConversationWithRequest:(_TtC7FlowIMX28FlowIMSubConversationRequest *)arg1;
- (void)createMainBotSubConversationWithLocalConversationID:(NSString *)arg1 success:(void (^)(NSString *))arg2 fail:(void (^)(FlowIMCocoError *))arg3;
- (void)createMainBotSubConversationWithReq:(FlowIMMainBotSubConversationRequest *)arg1 success:(void (^)(NSString *))arg2 fail:(void (^)(FlowIMCocoError *))arg3 callback:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg4;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createMainBotSubConversationWithMessageID:(NSString *)arg1 ext:(NSDictionary *)arg2 name:(NSString *)arg3;
- (id <_TtP7FlowIMX18FlowIMConversation_>)createMainBotSubConversationWithMessageID:(NSString *)arg1;
- (void)mainBotConversationWithSuccess:(void (^)(id <_TtP7FlowIMX18FlowIMConversation_>))arg1 fail:(void (^)(FlowIMCocoError *))arg2;
- (id <_TtP7FlowIMX18FlowIMConversation_>)mainBotConversation;
@end

