//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIGestureRecognizer;

@protocol _TtP9FlowUIKit26FlowNavChildViewController_

@optional
- (_Bool)shouldNavBeginWithGestureRecognizer:(UIGestureRecognizer *)arg1;
- (_Bool)shouldNavBeRequiredToFailByOtherGestureRecognizer:(UIGestureRecognizer *)arg1;
@end

