//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol _TtP9FlowAVSDK27FlowAVSessionEngineListener_
- (void)avSessionEngineWithDidVideoDeviceStateChanged:(long long)arg1 type:(long long)arg2;
- (void)avSessionEngineWithDidAudioCaptureDeviceStoped:(_Bool)arg1;
- (void)avSessionEngineWithDidReceiveUplinkAudioVolume:(long long)arg1;
- (void)avSessionEngineWithDidReceiveDownlinkAudioVolume:(long long)arg1;
@end

