//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIGestureRecognizer;

@protocol _TtP9FlowUIKit38FlowPagingMainTableViewGestureDelegate_
- (_Bool)mainTableViewGestureRecognizer:(UIGestureRecognizer *)arg1 shouldRecognizeSimultaneouslyWith:(UIGestureRecognizer *)arg2;
@end

