//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol _TtP7FlowIMX18FlowIMConversation_;

@protocol _TtP7FlowIMX33FlowIMConversationServiceDelegate_ <NSObject>

@optional
- (void)conversationTotalUnreadChanged:(long long)arg1 socialCount:(long long)arg2 botCount:(long long)arg3;
- (void)conversationTotalUnreadChanged:(long long)arg1;
- (void)conversationDidCreateRemote:(id <_TtP7FlowIMX18FlowIMConversation_>)arg1 from:(NSString *)arg2;
- (void)conversationDidForceDelete:(id <_TtP7FlowIMX18FlowIMConversation_>)arg1;
- (void)conversationHistoryDidClear:(id <_TtP7FlowIMX18FlowIMConversation_>)arg1;
- (void)conversationContextDidClear:(id <_TtP7FlowIMX18FlowIMConversation_>)arg1;
- (void)conversationLastMessageChanged:(id <_TtP7FlowIMX18FlowIMConversation_>)arg1;
- (void)conversationInfosChanged:(NSArray *)arg1;
@end

