//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, _TtC18IESLiveRevenueImpl23IESLiveRFVoiceChatModel;

@protocol _TtP18IESLiveRevenueImpl26IESLiveRFVoiceChatProvider_ <NSObject>
- (long long)getCurrentAIState;
- (void)reloadWithAuthorID:(long long)arg1 trackParams:(NSDictionary *)arg2;
- (void)forceQuitVoiceChat;
- (_Bool)isInVoiceChat;
- (void)reset;
- (void)openRulePage;
- (void)interrupt;
- (void)muteAudioCapture:(_Bool)arg1;
- (void)stopVoiceChatWithReason:(long long)arg1;
- (void)startVoiceChat;
@property(nonatomic, readonly) double remainTimePercent;
@property(nonatomic, readonly) long long state;
@property(nonatomic, readonly) _Bool isMute;
@property(nonatomic, readonly) _TtC18IESLiveRevenueImpl23IESLiveRFVoiceChatModel *model;
@end

