//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEControllerProtocol-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit18DataChangeProtocol_-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit20AppLifeCycleProtocol_-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit21PlayerControlProtocol_-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit26ContainerLifeCycleProtocol_-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit29TabContainerLifeCycleProtocol_-Protocol.h>
#import <AwemeCore/_TtP17AWESpeCategoryKit30ListContainerLifeCycleProtocol_-Protocol.h>

@protocol _TtP17AWESpeCategoryKit17ComponentProtocol_ <AWEControllerProtocol, _TtP17AWESpeCategoryKit20AppLifeCycleProtocol_, _TtP17AWESpeCategoryKit26ContainerLifeCycleProtocol_, _TtP17AWESpeCategoryKit30ListContainerLifeCycleProtocol_, _TtP17AWESpeCategoryKit29TabContainerLifeCycleProtocol_, _TtP17AWESpeCategoryKit18DataChangeProtocol_, _TtP17AWESpeCategoryKit21PlayerControlProtocol_>
@end

