//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDictionary, NSString, TTHttpTask;

@protocol _TtP7BDADSDK20BasicAbilityDelegate_
- (_Bool)monitor:(NSString *)arg1 value:(NSDictionary *)arg2 category:(NSDictionary *)arg3 extra:(NSDictionary *)arg4;
- (_Bool)trackURLs:(NSArray *)arg1 trackLabel:(NSString *)arg2 cid:(NSString *)arg3 extraData:(NSDictionary *)arg4 logExtra:(NSString *)arg5;
- (_Bool)trackLog:(NSString *)arg1 tag:(NSString *)arg2 level:(long long)arg3;
- (_Bool)trackAdEvent:(NSString *)arg1 tag:(NSString *)arg2 extra:(NSDictionary *)arg3 adExtra:(NSDictionary *)arg4;
- (_Bool)trackEvent:(NSString *)arg1 extra:(NSDictionary *)arg2;
- (TTHttpTask *)requestForJsonFrom:(NSString *)arg1 params:(NSDictionary *)arg2 method:(long long)arg3 needCommonParams:(_Bool)arg4 headerField:(NSDictionary *)arg5 priority:(long long)arg6 requestSerializer:(Class)arg7 responseSerializer:(Class)arg8 completion:(void (^)(NSError *, id, TTHttpResponse *))arg9;
- (TTHttpTask *)requestForBinaryFrom:(NSString *)arg1 params:(NSDictionary *)arg2 method:(long long)arg3 needCommonParams:(_Bool)arg4 headerField:(NSDictionary *)arg5 priority:(long long)arg6 requestSerializer:(Class)arg7 responseSerializer:(Class)arg8 completion:(void (^)(NSError *, NSData *, TTHttpResponse *))arg9;
@end

