//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIScrollView;

@protocol _TtP17AWESpeCategoryKit29TabContainerLifeCycleProtocol_

@optional
- (void)onTabContainerScrollViewDidScroll:(UIScrollView *)arg1;
- (void)onTabContainerViewDidLayoutSubviews;
- (void)onTabContainerViewWillLayoutSubviews;
- (void)onTabContainerViewDidDisappear;
- (void)onTabContainerViewWillDisappear;
- (void)onTabContainerViewDidAppear;
- (void)onTabContainerViewWillAppear;
@end

