//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol ACCAIEditConflictManagerSubscription <NSObject>
- (void)AIEditorConflictHeadChange;

@optional
- (NSString *)AIEditorConflictTipsWithScene:(unsigned long long)arg1 disableBy:(unsigned long long)arg2;
@end

