//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol ACCEditServiceProtocol;

@protocol ACCEditSessionLifeCircleEvent <NSObject>

@optional
- (void)frameRenderWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)failedToPlayWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)executeSceneFirstRenderWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)sensorialRenderWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)prepareDoneWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)coverRemoveVisibleWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)firstRenderWithEditService:(id <ACCEditServiceProtocol>)arg1;
- (void)onCreateEditSessionCompletedWithEditService:(id <ACCEditServiceProtocol>)arg1;
@end

