//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol ACCRealLivePhotoServiceSubscriber <NSObject>

@optional
- (void)livePhotoDidChangeMode:(unsigned long long)arg1;
- (void)livePhotoWillChangeMode:(unsigned long long)arg1;
@end

