//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class ACCTextStickerInputController, NSArray, NSString, UITextView;

@protocol ACCTextStickerInputControllerDelegate <NSObject>

@optional
- (void)textStickerInputController:(ACCTextStickerInputController *)arg1 textView:(UITextView *)arg2 onReplaceText:(NSString *)arg3 withRange:(struct _NSRange)arg4;
- (void)textStickerInputController:(ACCTextStickerInputController *)arg1 onExtraInfoDidChanged:(NSArray *)arg2;
- (void)textStickerInputController:(ACCTextStickerInputController *)arg1 didUpdateSearchStatus:(_Bool)arg2 Keyword:(NSString *)arg3 searchType:(unsigned long long)arg4;
@end

