//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AEKTrackBindingStrategy;

@protocol AEKTrackBindingSubscription <NSObject>

@optional
- (void)strategyDidExec:(id <AEKTrackBindingStrategy>)arg1 operationType:(unsigned long long)arg2;
- (void)strategyWillExec:(id <AEKTrackBindingStrategy>)arg1;
@end

