//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;
@protocol AESoundFXListItemModelProtocol, AESoundFXPanelControllerDelegate;

@protocol AESoundFXPanelControllerProtocol <NSObject>
- (void)dismiss:(_Bool)arg1 completion:(void (^)(void))arg2;
- (double)panelHeight;
- (void)showPanelWithTargetItem:(id <AESoundFXListItemModelProtocol>)arg1 targetTab:(NSString *)arg2 completion:(void (^)(void))arg3;
- (void)showPanel:(void (^)(void))arg1;
@property(nonatomic) __weak id <AESoundFXPanelControllerDelegate> delegate;
@end

