//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol ACCMusicModelProtocol;

@protocol AESoundFXListItemModelProtocol <NSObject>
- (void)resetItemState;
- (id <ACCMusicModelProtocol>)musicModel;
- (long long)currentPlayState;
- (void)updatePlayState:(long long)arg1;
@end

