//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AFDAudioPlayerManagerProtocol;

@protocol AFDAudioPlayerManagerDelegate <NSObject>
- (void)playerManagerPlaying:(id <AFDAudioPlayerManagerProtocol>)arg1 currentTime:(double)arg2;
- (void)playerManagerDidFailed:(id <AFDAudioPlayerManagerProtocol>)arg1;
- (void)playerManagerDidFinished:(id <AFDAudioPlayerManagerProtocol>)arg1;
- (void)playerManagerDidStopped:(id <AFDAudioPlayerManagerProtocol>)arg1;
- (void)playerManagerDidPaused:(id <AFDAudioPlayerManagerProtocol>)arg1;
- (void)playerManagerDidStarted:(id <AFDAudioPlayerManagerProtocol>)arg1;
- (void)playerManagerLoadState:(id <AFDAudioPlayerManagerProtocol>)arg1;
@end

