//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEImageAlbumImageModel;

@protocol AFDAlbumContentModeDelegate <NSObject>
- (unsigned long long)setContentModeWithOriginMode:(unsigned long long)arg1 index:(long long)arg2 model:(AWEImageAlbumImageModel *)arg3;
@end

