//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIViewController;
@protocol AFDAlbumTransitionUpdatePlayStateProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol;

@protocol AFDAlbumTransitionUpdatePlayStateProtocol <NSObject>
- (void)updatePlayStateWithAlbumHandler:(id <AFDAlbumTransitionUpdatePlayStateProtocol>)arg1 playVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg2;
@end

