//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AFDBookCommentControllerProtocol <NSObject>
- (void)showBookCommentInput:(NSString *)arg1 extraDict:(NSDictionary *)arg2;
@end

