//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEImageAlbumImageModel, NSDictionary, NSString, UIImage;
@protocol AFDClipContentViewDelegate, AFDRichContentPageContextProtocol;

@protocol AFDClipContentViewProtocol <NSObject>
- (void)setAlbumContentMode:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)setIsInFullPage:(_Bool)arg1 animated:(_Bool)arg2;
- (void)resetImageModel;
- (void)setModel:(AWEImageAlbumImageModel *)arg1 placeholderImage:(UIImage *)arg2 index:(long long)arg3 totalCount:(long long)arg4 logExtra:(NSDictionary *)arg5;
@property(nonatomic, copy) CDUnknownBlockType imageLoadFinished;
@property(nonatomic, copy) CDUnknownBlockType imageCompletionBlock;
@property(nonatomic, copy) CDUnknownBlockType updateContentSizeBlock;
@property(nonatomic) unsigned long long scene;
@property(nonatomic, copy) NSString *referString;
@property(nonatomic, copy) NSString *enterFrom;
@property(nonatomic) unsigned long long albumContentMode;
@property(nonatomic) _Bool isInFullPage;
@property(nonatomic) long long totalCount;
@property(nonatomic) long long index;
@property(nonatomic, retain) id <AFDRichContentPageContextProtocol> pageContext;
@property(nonatomic, retain) AWEAwemeModel *aweme;
@property(nonatomic) __weak id <AFDClipContentViewDelegate> delegate;

@optional
- (struct CGRect)currentContentRect;
- (void)stop;
- (void)pause;
- (void)play;
@end

