//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEVideoModel, UIView;
@protocol AFDClipVideoPlayerAdapterProtocol, IESVideoPlayerProtocol;

@protocol AFDClipVideoPlayerAdapterProtocol <NSObject>
- (void)stop;
- (void)pause;
- (void)play;
- (void)updateWithAnotherPlayerAdapter:(id <AFDClipVideoPlayerAdapterProtocol>)arg1;
- (id <IESVideoPlayerProtocol>)takeAwayPlayerController;
- (void)seekToTime:(double)arg1;
- (struct CGRect)updateVideoScaleModeIsInFullPage:(_Bool)arg1 albumContentMode:(unsigned long long)arg2;
@property(nonatomic, copy) CDUnknownBlockType didReadyBlock;
@property(nonatomic, copy) CDUnknownBlockType playbackTimeBlock;
@property(nonatomic, copy) CDUnknownBlockType playerWillLoopPlayingBlock;
@property(nonatomic, readonly) _Bool isPlayerReady;
@property(nonatomic) _Bool muted;
@property(nonatomic) _Bool enableSR;
@property(nonatomic) __weak UIView *containerView;
@property(nonatomic, readonly) id <IESVideoPlayerProtocol> playerController;
@property(nonatomic, readonly) UIView *playerView;
@property(nonatomic, retain) AWEVideoModel *video;

@optional
- (void)updateWithAnotherPlayerAdapter:(id <AFDClipVideoPlayerAdapterProtocol>)arg1 repeated:(_Bool)arg2;
@end

