//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AFDFastReplyViewLifeCycle <NSObject>

@optional
- (void)fastReplyDidSend;
- (void)fastReplyDidClickedWithType:(unsigned long long)arg1;
- (void)fastReplyDidDismiss;
- (void)fastReplyDidShow;
@end

