//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, UIViewController;
@protocol AFDFullPageFeedContainerViewControllerProtocol;

@protocol AFDFullPageFeedContainerViewControllerDelegate <NSObject>

@optional
- (void)fullPageFeedImageLoadFinishWithAweme:(AWEAwemeModel *)arg1 index:(long long)arg2;
- (void)fullPageFeedWillPlayModel:(AWEAwemeModel *)arg1 index:(long long)arg2;
- (void)fullPageFeedViewDidAppear:(UIViewController<AFDFullPageFeedContainerViewControllerProtocol> *)arg1;
- (void)fullPageFeedViewDidDisappear:(UIViewController<AFDFullPageFeedContainerViewControllerProtocol> *)arg1;
@end

