//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, UIImage;
@protocol AFDFastReplyInputViewModeProtocol;

@protocol AFDFastReplyBusinessInputView <NSObject>

@optional
- (_Bool)fastReplyCanUpdateViewBeforeAppear;
- (_Bool)fastReplyShouldRecordLastContent;
- (_Bool)fastReplyShouldPlayEmojiAnimation;
- (void)fastReplyClicked:(unsigned long long)arg1 emojiImage:(UIImage *)arg2 emoji:(NSDictionary *)arg3;
- (_Bool)fastReplyIsShowingInputView;
- (id <AFDFastReplyInputViewModeProtocol>)fastReplyInputMode;
@end

