//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEURLModel, NSArray, NSString;

@protocol AFDFastReplyBusinessDataSource <NSObject>

@optional
- (_Bool)fastReplyNeedHideAfterSend;
- (NSArray *)fastReplyEmojis;
- (NSString *)fastReplyPlaceholder;
- (AWEURLModel *)fastReplyAvatarURL;
@end

