//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSObject;
@protocol AFDFastReplyTriggerRuleProtocol;

@protocol AFDFastReplyBusinessTriggerRule <NSObject>
- (NSObject<AFDFastReplyTriggerRuleProtocol> *)fastReplyTriggerRule;

@optional
- (_Bool)fastReplyShouldAvoidPriority;
- (_Bool)fastReplyShouldRespondTrigger:(id <AFDFastReplyTriggerRuleProtocol>)arg1;
@end

