//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AFDFastReplyBusinessDataSource-Protocol.h>
#import <AwemeCore/AFDFastReplyBusinessInputView-Protocol.h>
#import <AwemeCore/AFDFastReplyBusinessTracker-Protocol.h>
#import <AwemeCore/AFDFastReplyBusinessTriggerRule-Protocol.h>
#import <AwemeCore/AFDFastReplyViewLifeCycle-Protocol.h>

@class AWECommonButtonInfoModel, AWEPageContext, UIViewController;
@protocol AWEPlayInteractionContextProtocol;

@protocol AFDFastReplyBusinessStrategy <AFDFastReplyBusinessDataSource, AFDFastReplyBusinessInputView, AFDFastReplyBusinessTracker, AFDFastReplyViewLifeCycle, AFDFastReplyBusinessTriggerRule>
+ (_Bool)fastReplyRefactorCanShowWithModel:(AWECommonButtonInfoModel *)arg1 context:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg2;
+ (_Bool)fastReplyCanShowWithContext:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg1;
- (id)initWithContext:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg1;

@optional
- (void)fastReplySetViewController:(UIViewController *)arg1;
@end

