//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIScrollView, UIView;

@protocol AFDFullPageSliderContainerDelegate <NSObject>

@optional
- (void)sliderDidUpdatePaginatedProgressWithIndex:(long long)arg1 totalCount:(long long)arg2;
- (void)sliderScrollViewDidEndDragging:(UIScrollView *)arg1;
- (void)sliderScrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint)arg3;
- (void)sliderScrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)sliderScrollViewDidScroll:(UIScrollView *)arg1 lastContentOffset:(struct CGPoint)arg2;
- (void)sliderDidScrollTo:(long long)arg1 totalCount:(long long)arg2 slideMethod:(unsigned long long)arg3;
- (void)sliderDidCreateProgressView:(UIView *)arg1;
- (_Bool)sliderShouldAddProgressView;
@end

