//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AFDFastReplyBusinessTracker <NSObject>

@optional
- (NSDictionary *)fastReplyTrackerClickParamsWithClickType:(unsigned long long)arg1 emoji:(NSDictionary *)arg2;
- (NSDictionary *)fastReplyShowParams;
- (NSString *)fastReplyClickEvent;
- (NSString *)fastReplyShowEvent;
- (NSString *)fastReplyEnterMethod;
@end

