//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel;

@protocol AFDFamiliarGroupUtilsProtocol <NSObject>
+ (void)deduplicateFamiliarGroupItemIn:(AWEAwemeModel *)arg1 sourceType:(unsigned long long)arg2 isDuplicate:(_Bool (^)(NSString *))arg3;
@end

