//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AFDGeneralRedButtonDefaultInnerPushModel, AWEAwemeModel, NSMutableDictionary, NSString;

@protocol AFDGeneralRedButtonManageService <HTSService>
- (void)addActivityNameTrackParamsTo:(NSMutableDictionary *)arg1 forShootEnterFrom:(NSString *)arg2;
- (void)addActivityNameTrackParamsTo:(NSMutableDictionary *)arg1 forAweme:(AWEAwemeModel *)arg2;
- (void)addButtonEntranceParamsTo:(NSMutableDictionary *)arg1 forAweme:(AWEAwemeModel *)arg2 isClick:(_Bool)arg3;
- (void)addVideoPlayTrackParamsTo:(NSMutableDictionary *)arg1 forAweme:(AWEAwemeModel *)arg2;
- (void)updateGeneralRedButtonActionBlockIfNeededWithModel:(AWEAwemeModel *)arg1 enterFrom:(NSString *)arg2;
- (void)showGeneralButtonEcommercePostActivityInnerPush:(AFDGeneralRedButtonDefaultInnerPushModel *)arg1;
- (void)markGeneralButtonNotExitWithModel:(AWEAwemeModel *)arg1 buttonType:(NSString *)arg2;
- (void)markGeneralButtonExitWithModel:(AWEAwemeModel *)arg1 buttonType:(NSString *)arg2;
- (_Bool)isGeneralButtonHasExitedWithModel:(AWEAwemeModel *)arg1 buttonType:(NSString *)arg2;
- (_Bool)isCurrentGeneralButtonTypeInActivityWhiteList:(NSString *)arg1;
- (_Bool)isCurrentGeneralButtonTypeInHighPriorityList:(NSString *)arg1;
@end

