//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;
@protocol AFDLearningViewControllerDelegate;

@protocol AFDLearningViewControllerProtocol <NSObject>
@property(nonatomic) _Bool isFromRouterTransfer;
@property(nonatomic, copy) NSDictionary *logExtraDict;
@property(nonatomic, copy) NSString *enterMethod;
@property(nonatomic, copy) NSString *enterFrom;
@property(nonatomic) __weak id <AFDLearningViewControllerDelegate> delegate;

@optional
- (void)updataGlobalTrackerParams;
@end

