//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol AFDMentionListCacheModelProtocol;

@protocol AFDMentionListCacheManagerProtocol <NSObject>
- (id <AFDMentionListCacheModelProtocol>)mentionListCachedModelForKey:(NSString *)arg1 scene:(long long)arg2;
- (void)removeDefaultUserCache;
- (void)cacheWithModel:(id <AFDMentionListCacheModelProtocol>)arg1 forKey:(NSString *)arg2 scene:(long long)arg3;
- (void)selectUsers:(NSArray *)arg1;
@end

