//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEStoryProgressContainerView, UIWindow;

@protocol AFDProgressInteractionHotZoneManagerDelegate <NSObject>
- (UIWindow *)window;
- (AWEStoryProgressContainerView *)progressView;
- (_Bool)viewIsAppear;
- (_Bool)isHitFriendsProgressBarHotZoneOptimization;
- (_Bool)shouldRecognizeWindowGesture;
- (_Bool)shouldAssignMaskWindowDelegate;

@optional
- (_Bool)shouldResponseLongPressProgress;
- (_Bool)shouldAlignFeedProgressHotZone;
- (_Bool)shouldReduceHotZoneForWindowGestureWith:(double)arg1;
- (_Bool)shouldExpandPinchProgressHotZone;
- (_Bool)isSingleImage;
@end

