//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIView;

@protocol AFDPureModePinchable
- (UIView *)pinchBackgroundViewWithFrame:(struct CGRect)arg1;
- (UIView *)pinchTargetView;
- (_Bool)isContentReady;

@optional
- (void)resetPinchMode;
- (void)readdPinchTargetView;
- (unsigned long long)pinchTargetViewContentMode;
@end

