//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIPanGestureRecognizer, UIPinchGestureRecognizer;

@protocol AFDPinchable <NSObject>
- (_Bool)shouldResponseToPinchGesture:(UIPinchGestureRecognizer *)arg1;
- (_Bool)shouldResponseToPanGesture:(UIPanGestureRecognizer *)arg1;
- (void)handlePanGesture:(UIPanGestureRecognizer *)arg1;
- (void)handlePinchGesture:(UIPinchGestureRecognizer *)arg1;
@end

