//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEControllerProtocol-Protocol.h>
#import <AwemeCore/AWEViewControllerLifeCycle-Protocol.h>

@class AWEAwemeModel, NSDictionary, NSString, UIScrollView, UIViewController;
@protocol AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, IESVideoPlayerProtocol;

@protocol AFDPureModePageControllerProtocol <AWEControllerProtocol, AWEViewControllerLifeCycle>

@optional
- (void)appWillResignActive;
- (void)appDidBecomeActive;
- (void)didEndDisplaying;
- (void)willResignActive;
- (void)becomeActive;
- (void)showInScaleMode;
- (void)willEnterScaleMode:(_Bool)arg1;
- (void)containerDidLayoutSubviews;
- (void)inner_pinchTransitionDidFinish;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 subtitleInfoCallBack:(NSDictionary *)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 onMaskInfoCallBack:(NSString *)arg2 pts:(unsigned long long)arg3;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 updatePlayTime:(double)arg2 canPlayTime:(double)arg3 totalTime:(double)arg4;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackToAction:(long long)arg2;
- (void)containerDidPlayOrPause:(_Bool)arg1;
- (void)containerDidUpdateVideoController:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg1;
- (void)videoWillLoopTimes:(long long)arg1;
- (_Bool)canAutoPlayNextAweme:(long long)arg1;
- (_Bool)isInteracting;
- (void)didOuterPinchTransitionDidCancel;
- (void)didOuterPinchTransitionFinish;
- (void)didOuterPinchTransitionWillBegin;
- (void)containerDidEndDragging:(UIScrollView *)arg1;
- (void)containerWillBeginDragging:(UIScrollView *)arg1;
- (void)containerDidScroll:(UIScrollView *)arg1;
- (void)didBackFromAlbumDetail;
- (void)didUpdatePlayerController:(id <IESVideoPlayerProtocol>)arg1;
- (void)setHide:(_Bool)arg1;
- (void)didChangeAlbumIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)setData:(AWEAwemeModel *)arg1;
- (void)play;
- (void)pause;
- (void)setupWithParams:(NSDictionary *)arg1;
@end

