//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, UIScrollView, UIViewController;
@protocol AFDRichContentContainerViewControllerProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol;

@protocol AFDRichContentContainerDelegate <NSObject>
- (void)updateCurrentAwemeModel:(AWEAwemeModel *)arg1;

@optional
- (void)exitContainer;
- (void)imageZoomWillBounceWith:(unsigned long long)arg1 beginScale:(double)arg2 currentScale:(double)arg3;
- (void)currentImageEnterZoomState:(_Bool)arg1;
- (void)didConfigWithLandscapePlayViewController:(UIViewController<AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg1;
- (UIViewController<AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)getVideoControllerFromLandscape;
- (_Bool)isFromAlbumDetailPage;
- (_Bool)pinchViewcCanShowMultiMixVideo;
- (void)container:(id <AFDRichContentContainerViewControllerProtocol>)arg1 didPlayOrPause:(_Bool)arg2;
- (void)containerDidReadyForDisplay:(id <AFDRichContentContainerViewControllerProtocol>)arg1;
- (void)containerDidPlayOrPause:(_Bool)arg1;
- (void)containerDidUpdateVideoController:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg1;
- (void)videoWillLoopTimes:(long long)arg1;
- (_Bool)shouldStartProgressTimer;
- (_Bool)canAutoPlayNextAweme:(long long)arg1;
- (void)containerDidEndDragging:(UIScrollView *)arg1;
- (void)containerWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(struct CGPoint)arg3;
- (void)containerWillBeginDragging:(UIScrollView *)arg1;
- (void)containerDidScroll:(UIScrollView *)arg1;
- (void)didBackFromAlbumDetail;
- (void)didCancelBackFromAlbumDetail;
- (void)willBackFromAlbumDetail;
- (_Bool)isInteracting;
- (void)didChangeAlbumPreviewIndex:(long long)arg1;
- (void)didChangeAlbumIndex:(long long)arg1 slideMethod:(unsigned long long)arg2 animated:(_Bool)arg3;
- (void)didChangeAlbumIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)contentWillStartNextLoop;
- (void)didEndUpdateInteractionWithModel:(AWEAwemeModel *)arg1;
- (void)didChangePlayingModel:(AWEAwemeModel *)arg1;
@end

