//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView, UIViewController;
@protocol AFDPureModePageViewControllerProtocol, AFDRichContentContainerViewControllerProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol;

@protocol AFDRichContentPinchTransitionProtocol <NSObject>
- (void)updateWithOtherRichContentContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1 andPlayVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol> *)arg2 inPureModeVC:(UIViewController<AFDPureModePageViewControllerProtocol> *)arg3;
- (void)updateWithAwemePlayVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol> *)arg1 inPureModeVC:(UIViewController<AFDPureModePageViewControllerProtocol> *)arg2;
- (void)updateAlbumContainerWithOtherRichContentContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1 andPlayVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol> *)arg2 inPureModeVC:(UIViewController<AFDPureModePageViewControllerProtocol> *)arg3;
- (UIView *)getWaterFallTransitionTargetViewForContainerView:(UIView *)arg1;
- (UIView *)getPinchTargetViewForContainerView:(UIView *)arg1;
@end

