//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AFDRecommendPanelBubbleModel, AFDRecommendPanelQuickReplyParam, AFDRecommendPanelTextModel, AFDRecommendToFriendUserModel, AWEAwemeModel, AWEPageContext, AWEUserModel, NSArray, NSAttributedString, NSString;
@protocol AWEPlayInteractionContextProtocol;

@protocol AFDRecommendPostscriptManagerProtocol <NSObject>
+ (void)showRecommendToFriendBrowsePanel:(AFDRecommendPanelQuickReplyParam *)arg1 user:(AWEUserModel *)arg2;
+ (void)showRecommendToFriendInputPanel:(id)arg1 aweme:(AWEAwemeModel *)arg2;
+ (NSAttributedString *)subtitlePostscriptTextWithUserID:(NSString *)arg1 awemeModel:(AWEAwemeModel *)arg2 eventPreNode:(id)arg3;
+ (_Bool)canShowSubtitlePostscriptTextWithUserModel:(AWEUserModel *)arg1 awemeModel:(AWEAwemeModel *)arg2;
+ (AFDRecommendPanelTextModel *)itemTextModelWithUserModel:(AFDRecommendToFriendUserModel *)arg1 awemeModel:(AWEAwemeModel *)arg2;
+ (AFDRecommendPanelBubbleModel *)itemBubbleModelWithUserModel:(AFDRecommendToFriendUserModel *)arg1 awemeModel:(AWEAwemeModel *)arg2;
+ (NSArray *)postscriptBubbleRules;
+ (NSString *)guidePostscriptBubbleText;
+ (void)didShowGuidePostscriptBubble;
+ (_Bool)canShowGuidePostscriptBubble;
+ (NSString *)guidePostscriptImageURLString;
+ (void)didTapGuidePostscriptBtnWithModel:(AWEAwemeModel *)arg1 context:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg2;
+ (void)didShowGuidePostscriptBtnWithModel:(AWEAwemeModel *)arg1 context:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg2;
+ (_Bool)canShowGuidePostscriptBtnWithModel:(AWEAwemeModel *)arg1;
+ (_Bool)canRecommendTagShowPostscriptWithModel:(AWEAwemeModel *)arg1;
@end

