//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AFDRecommendToFriendPanelMessage <NSObject>

@optional
- (void)recommendPanelDidFilterUserWithUserID:(NSString *)arg1 awemeID:(NSString *)arg2;
- (void)refreshRecommendPanelWithAwemeID:(NSString *)arg1;
@end

