//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString, UIView;

@protocol AFDRichContentAlbumContainerProtocol <NSObject>
- (void)setAlbumFastPlay:(_Bool)arg1;
- (void)trackPinchZoomWithZoomType:(long long)arg1;
- (void)disableGraphicPlayTimeFeed:(_Bool)arg1;
- (void)retimeGraphicPlayTimeFeed;
- (void)trackGraphicPlayTimeFeed;
- (void)disableGraphicPlaytime:(_Bool)arg1;
- (void)retimeGraphicPlaytime;
- (void)trackGraphicPlaytime;
- (void)updateTailEntranceGuideViewConstraints:(double)arg1;
- (void)addTailEntranceGuideView:(UIView *)arg1;
- (void)zoomImageWithVisibleRatioRect:(struct CGRect)arg1 scale:(double)arg2 animated:(_Bool)arg3;
- (void)updateAlbumContentModeLayout;
- (void)setImageContentInsets:(struct UIEdgeInsets)arg1 animated:(_Bool)arg2 duration:(double)arg3;
- (struct UIEdgeInsets)getImageContentInsets;
- (void)updateShrinkState:(_Bool)arg1 insets:(struct UIEdgeInsets)arg2 animated:(_Bool)arg3 animationDuration:(double)arg4;
- (void)updateShrinkState:(_Bool)arg1 insets:(struct UIEdgeInsets)arg2 animated:(_Bool)arg3;
- (_Bool)getShrinkState:(struct UIEdgeInsets *)arg1;
- (void)clearImageContentViewTopInset;
- (void)updateImageContentViewTopInsetWithLeftInteractionMinY:(double)arg1 authorElementMinY:(double)arg2;
- (struct CGRect)getTemporaryImageViewRectWithMinWHRatio;
- (double)getImageContentTopInset;
- (struct CGSize)getImageViewSizeWithMaxWHRatio;
- (double)currentAlbumDuration;
- (_Bool)isMusicPlaying;
- (long long)currentSectionInnerIndex;
- (NSArray *)viewedImagesUri;
- (long long)viewedImagesCountWithItemID:(NSString *)arg1;
- (_Bool)isAlbumStopState;
- (void)showRichAwemeFullPageWithInsertIds:(NSArray *)arg1 highlightID:(NSString *)arg2 logExtra:(NSDictionary *)arg3 priorityType:(NSString *)arg4;
@property(nonatomic, readonly) _Bool hasTrackCaptionPicShow;
@end

