//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AFDRichContentAlbumContainerProtocol-Protocol.h>
#import <AwemeCore/AFDRichContentPinchTransitionProtocol-Protocol.h>
#import <AwemeCore/AWEAwemeBizPlayVideoProtocol-Protocol.h>
#import <AwemeCore/AWEAwemeDisplayViewController-Protocol.h>
#import <AwemeCore/AWEAwemePlayVideoTrackProtocol-Protocol.h>

@class AWEAwemeModel, AWEBaseListSectionController, NSIndexPath, NSNumber, NSString, Protocol, UICollectionViewCell, UIColor, UIGestureRecognizer, UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIPinchGestureRecognizer, UIViewController;
@protocol AFDAlbumMusicBeatsDelegate, AFDAlbumPlayFinishTrackTriggerOwner, AFDBroadcastContextProtocol, AFDCustomProgressDelegate, AFDPureModePageInteractionProtocol, AFDPureModePageMutiModelSourceProtocol, AFDRichContainerProgressControllerProtocol, AFDRichContentContainerDelegate, AFDRichContentContainerViewControllerProtocol, AFDRichContentListViewControllerProtocol, AFDRichContentPageContextProtocol, AFDRichContentProgressControllerDelegate, AFDSlidesViewProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoViewControllerProtocol, AWEAwemePlayVideoBaseContainer, AWEAwemePlayVideoProtocol, AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, AWEPlayVideoDelegate, AWEPlayVideoViewControllerContainerProtocol, AWEStoryContainerViewControllerDelegate, IESVideoPlayerProtocol;

@protocol AFDRichContentContainerViewControllerProtocol <AWEAwemeDisplayViewController, AWEAwemeBizPlayVideoProtocol, AWEAwemePlayVideoTrackProtocol, AFDRichContentAlbumContainerProtocol, AFDRichContentPinchTransitionProtocol>
- (void)showOverlayViews;
- (void)hiddenOverlayViews;
- (void)updatePaginatedProgress:(double)arg1;
- (void)resetFinishTrackTrigger;
- (void)transferFinishTrackTriggerTo:(id <AFDAlbumPlayFinishTrackTriggerOwner>)arg1;
- (void)createFinishTrackTriggerIfNeeded;
- (NSNumber *)currentDotFromCenter;
- (void)configBeforEnterToLandscapeFeed:(_Bool)arg1;
- (void)playFromBeginning;
- (id <AFDRichContainerProgressControllerProtocol>)richContainerProgressController;
- (void)setCustomProgressDelegate:(id <AFDCustomProgressDelegate>)arg1;
- (void)setProgressControllerDelegate:(id <AFDRichContentProgressControllerDelegate>)arg1;
- (void)setIsPinching:(_Bool)arg1;
- (void)playWithAnimation;
- (void)pauseWithAnimation;
- (void)forcePlay;
- (void)setContainerPlayEnable:(_Bool)arg1;
- (void)updatePlayerController:(id <IESVideoPlayerProtocol>)arg1 withPlayVideoVC:(id <AWEAwemePlayVideoProtocol>)arg2;
- (void)updateWithAwemePlayVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemeDisplayViewController><AWEAwemePlayVideoTrackProtocol><AWEAwemePlayVideoViewControllerProtocol> *)arg1;
- (void)updateSectionControllerWithOtherContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1;
- (void)updateAlbumProgressWithOtherContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1 andPlayerController:(id <IESVideoPlayerProtocol>)arg2;
- (void)hideContentView:(_Bool)arg1;
- (void)updateWithRichContentContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1 andPlayerController:(id <IESVideoPlayerProtocol>)arg2;
- (void)updateAlbumPlayStateWithOtherContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1 playVideoVC:(UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg2;
- (void)updateAlbumHandlerWithOtherContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1;
- (void)updateAlbumContainerWithOtherContainer:(id <AFDRichContentContainerViewControllerProtocol>)arg1;
- (void)updateWithSlidesView:(id <AFDSlidesViewProtocol>)arg1;
- (void)playTimer;
- (void)pauseTimer;
@property(nonatomic) _Bool notFadeOut;
@property(nonatomic, retain) UIColor *richBackgroundColor;
@property(nonatomic) unsigned long long forceBouncesType;
@property(nonatomic, readonly) double currentImageWHRatio;
@property(nonatomic, readonly) struct CGRect currentImageRectInContentOC;
@property(nonatomic, readonly) struct CGRect currentImageContentRectOC;
@property(nonatomic, readonly) _Bool isRefinedImageLayoutEnable;
@property(nonatomic, readonly) UIImageView *currentImageView;
@property(nonatomic, readonly) long long currentImageIndex;
@property(nonatomic, readonly) UICollectionViewCell *currentCell;
@property(nonatomic, readonly) double currentDuration;
@property(nonatomic, readonly) double currentProgress;
@property(nonatomic, readonly) long long currentIndex;
@property(nonatomic, readonly) long long currentSectionIndex;
- (double)currentLoadDuration;
- (void)setHasCovered:(_Bool)arg1;
- (_Bool)shouldResponseToPanGesture:(UIPanGestureRecognizer *)arg1;
- (void)handlePanGesture:(UIPanGestureRecognizer *)arg1;
- (_Bool)shouldResponseToPinchGesture:(UIPinchGestureRecognizer *)arg1;
- (void)handlePinchGesture:(UIPinchGestureRecognizer *)arg1;
- (_Bool)shouldRespondToEdgePanGesture:(UIPanGestureRecognizer *)arg1;
- (_Bool)isCollectionViewPanGesture:(UIPanGestureRecognizer *)arg1;
- (id)transitionContext;
- (void)rotateConfigAfterQuitFromLandscapeFeed:(UIViewController<AWEAwemePlayVideoViewControllerProtocol><AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg1;
- (_Bool)isContainAweme:(AWEAwemeModel *)arg1;
- (void)cycleUpdateCurrentSectionIndexBy:(long long)arg1;
- (NSIndexPath *)convertGlobalIndexToIndexPath:(long long)arg1;
- (void)syncUpdateCell;
- (void)scrollToAweme:(AWEAwemeModel *)arg1;
- (void)scrollToIndex:(long long)arg1 method:(unsigned long long)arg2 syncUpdateCell:(_Bool)arg3;
- (void)scrollToIndex:(long long)arg1 method:(unsigned long long)arg2;
- (void)scrollNoneSlideMethodToIndex:(long long)arg1 trackSlide:(_Bool)arg2;
- (void)setNeedGradientLayer:(_Bool)arg1;
- (_Bool)isSectionPlaying;
- (void)setNeedSetTargetContentOffset;
- (void)setIsPureModeFromAlbumDetail:(_Bool)arg1;
- (void)setContentScene:(unsigned long long)arg1;
- (AWEAwemeModel *)currentAwemeModel;
- (_Bool)tryToHandleTapStickerInPoint:(struct CGPoint)arg1;
- (_Bool)isLocationInInteractiveView:(struct CGPoint)arg1;
- (_Bool)handleLongPressGesture:(UILongPressGestureRecognizer *)arg1;
- (void)handleSingleClick;
- (_Bool)shouldHandleSingleClick;
- (_Bool)isContentLoading;
- (_Bool)isPlayingFirstStory;
- (_Bool)edgePan:(UIGestureRecognizer *)arg1;
- (void)buildInteractionControllerIfNeeded:(UIViewController *)arg1;
- (AWEBaseListSectionController *)currentSectionController;
- (id)controllerByProtocol:(Protocol *)arg1;
- (void)updateContainerPlayerDelegate:(id <AWEPlayVideoDelegate>)arg1;
@property(nonatomic, retain) NSNumber *usingLogExtraDictEnterMethod;
@property(nonatomic, retain) AWEAwemeModel *fromModel;
@property(nonatomic, copy) NSString *cityInfoString;
@property(nonatomic) _Bool forcePlayNextTime;
@property(nonatomic, readonly) id <AFDRichContentPageContextProtocol> contentPageContext;
@property(nonatomic) _Bool overlayInteractionEnabled;
@property(nonatomic) _Bool useMultiContentContainer;
@property(nonatomic) struct EngineVideoWrapper *videoWrapper;
@property(nonatomic) struct EngineAudioWrapper *audioWrapper;
@property(nonatomic) __weak id <AWEPlayVideoViewControllerContainerProtocol> container;
@property(nonatomic, readonly) id <AFDBroadcastContextProtocol> broadcastContext;
@property(nonatomic) __weak UIViewController *containerViewController;
@property(nonatomic) __weak id <AFDAlbumMusicBeatsDelegate> musicBeatsDelegate;
@property(nonatomic) __weak id <AWEAwemePlayVideoBaseContainer> baseContainerDelegate;
@property(nonatomic) __weak id <AFDRichContentContainerDelegate> containerDelegate;
@property(nonatomic) __weak id <AFDPureModePageMutiModelSourceProtocol> mutiModelDataSource;
@property(nonatomic) __weak id <AWEStoryContainerViewControllerDelegate> storyDelegate;
@property(nonatomic) __weak id <AFDPureModePageInteractionProtocol> pureModePageInteractionDelegate;
@property(nonatomic, readonly) UIViewController<AFDRichContentListViewControllerProtocol> *contentListViewController;
@property(nonatomic, readonly) UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoViewControllerProtocol> *videoController;
@end

