//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESVideoPlayerProtocol;

@protocol AFDRichContentPreviewable <NSObject>
- (void)didEndPreview:(_Bool)arg1;
- (id <IESVideoPlayerProtocol>)currentPlayerController;
@end

