//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AFDRichContentAlbumImageMsg;

@protocol AFDRichContentAlbumImageDelegateProtocol
- (void)imageConfigMsg:(AFDRichContentAlbumImageMsg *)arg1;

@optional
- (_Bool)needDelayInteractionController;
- (void)firstImageLoadFinished;
@end

