//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESVideoPlayerProtocol;

@protocol AFDRichContentHandlerProtocol <NSObject>
- (_Bool)shouldSpectialHandlePlayState;
- (void)updatePlayerController:(id <IESVideoPlayerProtocol>)arg1;
@end

