//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEImageAlbumImageModel, UIImageView;
@protocol AFDClipLivePhotoPlayerAdapterProtocol, AFDClipVideoPlayerAdapterProtocol;

@protocol AFDSlidesClipCellProtocol <NSObject>
- (struct CGRect)currentContentRect;
- (UIImageView *)stickersFetchCurrentImageView;
- (_Bool)stickersDidTap:(struct CGPoint)arg1;

@optional
- (void)updateWithAdapterContentModel:(AWEAwemeModel *)arg1 adapterCellModel:(AWEImageAlbumImageModel *)arg2 repeated:(_Bool)arg3;
- (void)updateWithAdapterContentModel:(AWEAwemeModel *)arg1 adapterCellModel:(AWEImageAlbumImageModel *)arg2;
@property(nonatomic, readonly) id <AFDClipLivePhotoPlayerAdapterProtocol> livePhotoContentDelegate;
@property(nonatomic, readonly) id <AFDClipVideoPlayerAdapterProtocol> videoContentDelegate;
@end

