//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AFDSectionUpdatable;

@protocol AFDSectionUpdatable <NSObject>
- (void)updateWithOtherSectionUpdatable:(id <AFDSectionUpdatable>)arg1;

@optional
- (void)updateWithNoOtherSectionProvided;
@end

