//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSNumber, UICollectionView;

@protocol AFDSlidesViewActionDelegate <NSObject>

@optional
- (void)sliderDidUpdateWithIndex:(long long)arg1;
- (double)currentPlayTimeForMusicBeats;
- (NSNumber *)currentDotFromCenter;
- (void)sliderFirstVisibleShowFinished;
- (void)sliderFirstVisibleLoadFinished:(NSDictionary *)arg1;
- (void)sliderFirstVisibleStartLoad:(NSDictionary *)arg1;
- (void)sliderWillStartNextLoop;
- (void)progressDidUpdateWithIndex:(long long)arg1 progress:(double)arg2 duration:(double)arg3 currentDotFromCenter:(NSNumber *)arg4 needScrollAnimation:(_Bool)arg5 animated:(_Bool)arg6;
- (void)progressDidUpdateWithIndex:(long long)arg1 progress:(double)arg2 duration:(double)arg3 animated:(_Bool)arg4;
- (void)sliderDidEndZooming;
- (void)sliderDidBeginZooming;
- (void)sliderDidScroll:(UICollectionView *)arg1;
- (void)sliderDidEndScrolling;
- (void)sliderDidEndDragging;
- (void)sliderWillBeingDragging;
@end

