//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AFDVideoProgressInteractionManagerDelegate <NSObject>
- (void)pauseAlbumTimer:(_Bool)arg1;
- (void)playAlbumWithProgressPercentage:(double)arg1;
- (void)playStoryAlbumWithProgressPercentage:(double)arg1;
- (_Bool)canPlayerPlayAfterTouch;

@optional
- (_Bool)isInPinchView;
- (void)touchActionCancelled;
@end

