//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEAwemePlayVideoOptimizeProtocol-Protocol.h>

@class AWEAwemeModel, NSArray, NSDictionary, NSNumber, UIView;
@protocol AWEAwemeBackgroundPlayAutoNextDelegate, AWEAwemePlayVideoProtocol, AWEPlayVideoDelegate, IESVideoPlayerDelegate, IESVideoPlayerProtocol;

@protocol AWEAwemePlayVideoProtocol <AWEAwemePlayVideoOptimizeProtocol>
@property(nonatomic) _Bool forceUsePlayerVideoPlayEndTracker;

@optional
- (UIView *)getPlayerBackgroundView;
- (void)removePlayerBackgroundViewIfNeeded;
- (void)updatePlayerBackgroundViewIfNeededWhenLandscape:(_Bool)arg1 fromHomepageHot:(_Bool)arg2;
- (void)updateShouldAdaptFullScreen:(_Bool)arg1;
- (void)updatePauseBySingleClick:(_Bool)arg1;
- (void)changePlayerDelegate:(id <AWEPlayVideoDelegate>)arg1;
- (_Bool)awe_play;
@property(nonatomic) _Bool pauseBySingleClick;
@property(nonatomic, readonly) CDUnknownBlockType playVideo;
- (void)resetScalingMode;
- (void)recreatePlayerAndPrepare;
- (NSArray *)supportedResolutionTypes;
- (unsigned long long)currentResolution;
- (void)setTTVideoEngineResolutionType:(unsigned long long)arg1;
- (void)setSubtitleSwitchOn:(_Bool)arg1;
- (void)setSubTitle:(NSDictionary *)arg1;
- (void)setMemoryResolution:(unsigned long long)arg1;
- (void)setManualResolution:(unsigned long long)arg1 completion:(void (^)(_Bool))arg2;
- (void)setPlayerResolution:(unsigned long long)arg1 completion:(void (^)(_Bool, unsigned long long))arg2;
- (_Bool)isAutoPlaying;
- (void)updatePlayerController:(id <IESVideoPlayerProtocol>)arg1 withPlayVideoVC:(id <AWEAwemePlayVideoProtocol>)arg2;
- (void)activatePlayAnimation;
- (void)playWithAnimation;
- (void)pauseWithAnimation;
- (_Bool)isPlaying;
- (void)setPlayerSeekTime:(double)arg1 completion:(void (^)(_Bool))arg2;
- (void)updateDefaultSeekToTime:(double)arg1;
- (void)reset;
- (_Bool)stop;
- (_Bool)pause;
- (_Bool)play;
- (_Bool)isShowPlayChangeForRemoteControl;
- (_Bool)isBackgroundPlaying;
- (_Bool)forbidResumePlayFromBackground;
- (_Bool)enableBackgroundPlay;
- (void)setEnableBackgroundPlay:(_Bool)arg1;
- (void)setBgAutoPlayModel:(AWEAwemeModel *)arg1;
- (void)setBgAutoPlayNextDelegate:(id <AWEAwemeBackgroundPlayAutoNextDelegate>)arg1;
@property(nonatomic) _Bool isFullScreen;
@property(nonatomic) _Bool isScrolledAutomatically;
@property(nonatomic) _Bool shouldAdaptFullScreenThree;
@property(nonatomic) _Bool useNormalCover;
@property(nonatomic) _Bool shouldAdaptFullScreen;
@property(nonatomic) long long coverContentMode;
@property(nonatomic) double defaultSeekToTime;
@property(nonatomic, readonly) NSNumber *videoDuration;
@property(nonatomic, readonly) double playStartTimestamp;
@property(nonatomic, readonly) double totalPlayTime;
@property(nonatomic, readonly) double currentPlaybackTime;
@property(nonatomic, readonly) long long loopTimes;
@property(nonatomic) long long playState;
@property(nonatomic) __weak id <IESVideoPlayerDelegate> videoPlayerDelegate;
@property(nonatomic) __weak id <AWEPlayVideoDelegate> playerDelegate;
@property(nonatomic, retain) id <IESVideoPlayerProtocol> playerController;
@property(nonatomic, retain) AWEAwemeModel *model;
@end

