//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, UIViewController;
@protocol AWEAwemeBaseVCMediaPlayerContainerProtocol, AWEAwemeBaseVCMediaPlayerProtocol;

@protocol AWEAwemeBaseVCMediaPlayerDecisionProtocol <NSObject>
+ (id <AWEAwemeBaseVCMediaPlayerProtocol>)mediaPlayerForModel:(AWEAwemeModel *)arg1 inContainer:(UIViewController<AWEAwemeBaseVCMediaPlayerContainerProtocol> *)arg2;
+ (long long)mediaTypeForModel:(AWEAwemeModel *)arg1 inContainer:(UIViewController<AWEAwemeBaseVCMediaPlayerContainerProtocol> *)arg2;
+ (_Bool)shouldHandleModel:(AWEAwemeModel *)arg1 inContainer:(UIViewController<AWEAwemeBaseVCMediaPlayerContainerProtocol> *)arg2;
+ (long long)defaultMediaTypeInContainer:(UIViewController<AWEAwemeBaseVCMediaPlayerContainerProtocol> *)arg1;
@end

