//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEAwemeGestureProtocol <NSObject>

@optional
- (_Bool)shouldResponsetoLongPress:(struct CGPoint)arg1;
@end

