//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary, NSIndexPath, NSString, UIScrollView, UITableViewCell, UIViewController;
@protocol AWEAwemeDetailTableViewControllerProtocol, AWEFeedTableViewCellViewControllerProtocol;

@protocol AWEAwemeDetailTableViewControllerDelegate <NSObject>

@optional
- (_Bool)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 shouldUseSearchEntranceBarStyleWithModel:(AWEAwemeModel *)arg2;
- (_Bool)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 shouldHideSearchEntranceWithModel:(AWEAwemeModel *)arg2;
- (void)cellViewControllerDidRenderFirstFrame:(id <AWEFeedTableViewCellViewControllerProtocol>)arg1;
- (NSDictionary *)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 extraURLParamsForScene:(long long)arg2 withModel:(AWEAwemeModel *)arg3;
- (NSDictionary *)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 extraParamsForEvent:(NSString *)arg2 withModel:(AWEAwemeModel *)arg3;
- (_Bool)detailTableViewControllerShouldPreventLivePauseWhenViewWillDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (_Bool)detailTableViewControllerNeedUpdateBottomBarWhenReload:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (_Bool)detailTableViewControllerFooterNeedBounces:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (_Bool)detailTableViewControllerShouldIgnoreThisLoadMore:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 scrollViewDidBeginDragging:(UIScrollView *)arg2;
- (void)detailTableViewControllerDidScroll:(UIScrollView *)arg1 detailVC:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg2 isScrollDown:(_Bool)arg3 index:(long long)arg4;
- (void)detailTableViewControllerWillExit:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 awemeModel:(AWEAwemeModel *)arg2 didChangePlaybackStateWithAction:(long long)arg3;
- (void)videoPlayerWillStartNextLoop:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)videoPlayerDidReadyForDisplay:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 awemeModel:(AWEAwemeModel *)arg2 playerPlayTime:(double)arg3 canPlayTime:(double)arg4 totalTime:(double)arg5;
- (void)detailTableViewControllerDidLoadFinish:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewControllerDidAppear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillAppear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerDidDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillScrollToNextItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewControllerDidScroll:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewControllerWillScrollToPreviousItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 refreshFooterDidShowAtIndex:(long long)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 scrollDidEndAtIndexPath:(NSIndexPath *)arg2 model:(AWEAwemeModel *)arg3;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 model:(AWEAwemeModel *)arg4;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 didPauseDisplayingCellWithCurrentPlayingTime:(double)arg2;
- (double)detailTableViewControllerInitialSeekTime:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
@end

