//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEAwemePlayVideoInteractionProtocol-Protocol.h>
#import <AwemeCore/AWEAwemePlayVideoProtocol-Protocol.h>

@class NSNumber, UIImage, UIPanGestureRecognizer, UIPinchGestureRecognizer;

@protocol AWEAwemeBizPlayVideoProtocol <AWEAwemePlayVideoProtocol, AWEAwemePlayVideoInteractionProtocol>

@optional
- (void)setPureMode:(_Bool)arg1;
- (NSNumber *)itemsCount;
- (NSNumber *)selectedItemIndex;
- (NSNumber *)indexProgressForVideo;
- (void)handleTapPoint:(struct CGPoint)arg1;
- (_Bool)shouldResponseToTapPoint:(struct CGPoint)arg1;
- (void)handlePanGesture:(UIPanGestureRecognizer *)arg1;
- (_Bool)shouldResponseToPanGesture:(UIPanGestureRecognizer *)arg1;
- (void)handlePinchGesture:(UIPinchGestureRecognizer *)arg1;
- (_Bool)shouldResponseToPinchGesture:(UIPinchGestureRecognizer *)arg1;
- (UIImage *)getVideoScreenShot;
- (void)hidePauseIcon;
- (void)resetPauseIcon;
- (void)setPauseHidden:(_Bool)arg1;
@property(nonatomic, retain) NSNumber *fromSlideUp;
@property(nonatomic, retain) NSNumber *detailSlide;
- (void)setNeedCorrectPauseFrame:(_Bool)arg1;
- (_Bool)videoIsPlayStarted;
- (void)prepareForDisplayWithoutCoverImage;
- (void)pauseWithAnimationUsingCustomPauseIcon:(UIImage *)arg1;
- (void)playWithAnimation;
- (void)pauseWithAnimation;
- (_Bool)pauseIfPlaying;
- (_Bool)pauseIfNotStop;
- (void)showPauseIcon;
- (_Bool)shouldPreventPlay;
- (void)setShouldPreventPlay:(_Bool)arg1;
@end

