//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary, NSIndexPath, UITableView, UITableViewCell, UIView;

@protocol AWEAwemeDetailBottomBarController <NSObject>
- (Class)contextClass;
- (void)setContext:(id)arg1;
- (UIView *)bottomBarView;
- (void)updateBottomBarWithAweme:(AWEAwemeModel *)arg1 updateTiming:(long long)arg2;
- (_Bool)canShowBottomBarForAweme:(AWEAwemeModel *)arg1;

@optional
- (void)bottomBarDidHidden;
- (void)bottomBarWillHidden;
- (void)bottomBarDidShow;
- (void)bottomBarWillShow;
- (UIView *)targetBottomView;
- (_Bool)updateWhenRotateDisable;
- (_Bool)isTryingToShowPanel;
- (void)preProcessBottomBarWithAweme:(AWEAwemeModel *)arg1 updateTiming:(long long)arg2;
- (void)updatePlayTime:(double)arg1 canPlayTime:(double)arg2 totalTime:(double)arg3;
- (void)updateLogExtraDict:(NSDictionary *)arg1;
- (void)cellDidEndDisplay:(UITableViewCell *)arg1;
- (void)cellDidEndDisplay:(AWEAwemeModel *)arg1 forRowAtIndexPath:(long long)arg2;
- (void)cellDidDisplay:(AWEAwemeModel *)arg1 forRowAtIndexPath:(long long)arg2;
- (void)cellWillDisplay:(UITableViewCell *)arg1 forRowAtIndexPath:(NSIndexPath *)arg2 tableView:(UITableView *)arg3;
- (void)updateCurrentIndexPath:(long long)arg1;
- (void)updateBottomBarAlpha:(double)arg1;
- (void)bottomBarAddedToContainer:(UIView *)arg1;
@end

