//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEAwemeModel;
@protocol IESVideoPlayerProtocol;

@protocol AWEAdVibrationManagerProtocol <HTSService>
- (void)removeCacheFor:(AWEAwemeModel *)arg1;
- (void)preloadVibrationResourceFor:(AWEAwemeModel *)arg1;
- (void)closeAdOperationGuide;
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangeStallState:(long long)arg2 actionType:(long long)arg3 reason:(unsigned long long)arg4;
- (void)onPlayerWillLoopPlaying:(id <IESVideoPlayerProtocol>)arg1;
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2;
@property(nonatomic, copy) CDUnknownBlockType playerCurrentPlaybackTime;
- (id)initWithAweme:(AWEAwemeModel *)arg1;
@end

