//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAlertCallbackWrapper, AWEAlertContainerInfo, AWEAlertContext, NSString;
@protocol AWEAlertEventProtocol, AWEAlertProtocol;

@protocol AWEAlertProtocol <NSObject>

@optional
- (void)onAlertCanceled;
- (_Bool)shouldCancelAllOtherPendingAlertsWhenShowed;
- (void)prepareWithCompletion:(void (^)(_Bool))arg1;
- (void)showWithContext:(AWEAlertContext *)arg1 onClose:(void (^)(_Bool))arg2;
- (void)showWithCloseCallback:(void (^)(_Bool))arg1;
- (_Bool)canShowAtEvent:(long long)arg1;
- (_Bool)canShow;
- (void)onAlertResumedWithContext:(AWEAlertContext *)arg1;
- (void)onAlertSuspendedWithContext:(AWEAlertContext *)arg1;
- (void)onAlertCanceledWithContext:(AWEAlertContext *)arg1;
- (AWEAlertContainerInfo *)containerBizInfoForEvent:(id <AWEAlertEventProtocol>)arg1;
- (unsigned long long)maxIndexToShow;
- (_Bool)shouldCancelAllOtherPendingAlertsWhenShowedWithContext:(AWEAlertContext *)arg1;
- (void)alertDismissByPopViewManager:(AWEAlertContext *)arg1;
- (void)prepareTimeoutCompletedWithContext:(AWEAlertContext *)arg1;
- (double)prepareTimeoutWithContext:(AWEAlertContext *)arg1;
- (_Bool)blockAllAlertWhenNotPreparedWithContext:(AWEAlertContext *)arg1;
- (void)prepareWithContext:(AWEAlertContext *)arg1 onCompletion:(void (^)(_Bool))arg2;
- (void)showTimeoutCompletedWithContext:(AWEAlertContext *)arg1;
- (double)showTimeoutWithContext:(AWEAlertContext *)arg1;
- (void)showWithContext:(AWEAlertContext *)arg1 callbackWrapper:(AWEAlertCallbackWrapper *)arg2;
- (_Bool)canShowWithContext:(AWEAlertContext *)arg1;
- (_Bool)isEqualToAlert:(id <AWEAlertProtocol>)arg1;
- (long long)alertPriorityForEvent:(id <AWEAlertEventProtocol>)arg1;
- (NSString *)alertIDForEvent:(id <AWEAlertEventProtocol>)arg1;
@end

