//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, UIView, UIViewController;
@protocol AWEPlayInteractionViewControllerProtocol, AWEPlayVideoViewControllerProtocol, IESVideoPlayerProtocol;

@protocol AWEAwemeLikeFireworksEggManagerProtocol <NSObject>
+ (void)removeCacheFor:(AWEAwemeModel *)arg1;
+ (void)preloadFireworkResourceFor:(AWEAwemeModel *)arg1;
- (void)reset;
- (void)viewDidDisappear;
- (id)initWithAweme:(AWEAwemeModel *)arg1;
- (void)onPlayerWillLoopPlaying:(id <IESVideoPlayerProtocol>)arg1;
- (void)onUpdatePlayerController:(id <IESVideoPlayerProtocol>)arg1 withPlayVideoVC:(UIViewController<AWEPlayVideoViewControllerProtocol> *)arg2;
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2;
@property(nonatomic, copy) CDUnknownBlockType toggleLeftInteractionContainer;
@property(nonatomic, copy) CDUnknownBlockType getLikeButton;
@property(nonatomic) __weak UIView *adPromptView;
@property(nonatomic) __weak UIViewController<AWEPlayVideoViewControllerProtocol> *playVideoViewController;
@property(nonatomic) __weak UIViewController<AWEPlayInteractionViewControllerProtocol> *playInteractionViewController;
@end

