//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIViewController;
@protocol AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, AWEPlayVideoViewControllerProtocol;

@protocol AWEAlbumDetailPageTransitionProtocol <NSObject>
- (UIViewController<AWEAwemeBizPlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)videoController;
- (long long)currentImageIndex;
- (void)updateAudioPlayWithPlayVideoVC:(UIViewController<AWEPlayVideoViewControllerProtocol> *)arg1;
- (void)scrollTo:(long long)arg1 method:(unsigned long long)arg2;
@end

