//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary;

@protocol AWEAdComponentsActionManager <NSObject>
+ (void)addAdActionWithParams:(NSDictionary *)arg1 aweme:(AWEAwemeModel *)arg2;
@end

