//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary, NSNumber, NSString;

@protocol AWEAwemePlayVideoTrackProtocol <NSObject>
- (NSDictionary *)internalLogExtraDict;
- (NSDictionary *)playerExtraTrackInfo;
- (NSString *)getPlayModeWithAutoPlayMode;
- (AWEAwemeModel *)repostFromModel;
- (AWEAwemeModel *)repostModel;
@property(nonatomic, copy) NSDictionary *logExtraDict;

@optional
@property(nonatomic, copy) NSDictionary *btmInfo;
@property(nonatomic, copy) NSDictionary *context;
@property(nonatomic) _Bool hasReportClickEnter;
@property(nonatomic, retain) NSNumber *clickEnter;
- (void)usingLogExtraEnterMethod:(_Bool)arg1;
- (double)systemVolumeWhenStartPlay;
@property(nonatomic, copy) CDUnknownBlockType trackAwemePlayTime;
- (void)setPlayerSpeedModePlayTimeTrackParams:(NSDictionary *)arg1;
- (NSDictionary *)playerSpeedModePlayTimeTrackParams;
- (void)setPlayerTrackerDisableOptions:(long long)arg1;
- (long long)playerTrackerDisableOptions;
- (void)setFixVideoPlayFinishTrack:(_Bool)arg1;
- (_Bool)fixVideoPlayFinishTrack;
- (void)setIsInBackgroundPlayMode:(_Bool)arg1;
- (_Bool)isInBackgroundPlayMode;
@property(nonatomic, copy) NSString *searchVideoMethod;
@property(nonatomic, copy) NSString *originEntryEnterMethod;
@property(nonatomic, copy) NSString *ruleId;
@property(nonatomic, copy) NSDictionary *adExtraData;
@property(nonatomic, copy) NSString *adEventName;
@property(nonatomic, retain) NSNumber *slideType;
@property(nonatomic, copy) NSString *reactId;
@property(nonatomic, copy) NSString *cityInfoString;
@property(nonatomic, copy) NSString *enterFrom;
@property(nonatomic, copy) NSString *referString;
@property(nonatomic, copy) NSString *pageType;
@end

