//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, Protocol;

@protocol AWEBaseControllerDIProtocol <NSObject>
- (NSArray *)controllersByProtocol:(Protocol *)arg1;
- (id)controllerByProtocol:(Protocol *)arg1;
@end

