//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEBasicModeMessage <NSObject>

@optional
- (void)enterBasicModeIsLogin:(_Bool)arg1;
- (void)basicModeDidChange:(_Bool)arg1;
@end

