//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UICollectionView;

@protocol AWEBaseListUpdateDelegate <NSObject>

@optional
- (void)listDidPerformBatchUpdatesWithCollectionView:(UICollectionView *)arg1;
- (void)listWillPerformBatchUpdatesWithCollectionView:(UICollectionView *)arg1;
- (void)listDidReloadDataWithCollectionView:(UICollectionView *)arg1;
- (void)listWillReloadDataWithCollectionView:(UICollectionView *)arg1;
@end

