//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, UIView;
@protocol AWEBDARifleView;

@protocol AWEBDARifleViewPopupEventProtocol <NSObject>

@optional
- (void)maskView:(UIView *)arg1;
- (void)loadFinish:(UIView<AWEBDARifleView> *)arg1;
- (void)loadFailed:(UIView<AWEBDARifleView> *)arg1;
- (void)rifleView:(UIView<AWEBDARifleView> *)arg1 didDragTo:(struct CGRect)arg2;
- (void)handleResignActive:(UIView<AWEBDARifleView> *)arg1;
- (void)handleBecomeActive:(UIView<AWEBDARifleView> *)arg1;
- (void)handleViewDidDisappear:(UIView<AWEBDARifleView> *)arg1;
- (void)handleViewDidAppear:(UIView<AWEBDARifleView> *)arg1;
- (void)rifleView:(UIView<AWEBDARifleView> *)arg1 closeWithParams:(NSDictionary *)arg2;
- (void)rifleView:(UIView<AWEBDARifleView> *)arg1 willLeaveStatus:(unsigned long long)arg2;
- (void)rifleView:(UIView<AWEBDARifleView> *)arg1 didEnterStatus:(unsigned long long)arg2;
- (void)willOpenPopupView;
@end

