//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEBaseListCollectionViewConfig, AWEBaseListSectionController, AWEBaseListSectionViewModel, NSArray, Protocol, UICollectionView, UICollectionViewLayout;
@protocol AWEBaseListViewControllerDataSource, AWEListKitLayoutBaseProtocol, UICollectionViewDelegate, UIScrollViewDelegate;

@protocol AWEBaseListViewControllerProtocol <NSObject>
@property(readonly, nonatomic) UICollectionView *awe_baseCollectionView;
@property(nonatomic) __weak id <UICollectionViewDelegate> awe_collectionViewDelegate;
@property(nonatomic) __weak id <UIScrollViewDelegate> awe_scrollViewDelegate;
@property(nonatomic) __weak id <AWEBaseListViewControllerDataSource> awe_listDataSource;
- (void)awelistkit_setDisableContentOffsetRestorationAnchor:(_Bool)arg1;
- (id)awe_businessProtocolDispatcher;
- (void)awe_registerBusinessProtocol:(Protocol *)arg1;
- (NSArray *)awe_visibleSectionControllers;
- (NSArray *)awe_visibleSectionViewModels;
- (AWEBaseListSectionController *)awe_sectionControllerForSectionViewModel:(AWEBaseListSectionViewModel *)arg1;
- (AWEBaseListSectionController *)awe_sectionControllerAtIndex:(long long)arg1;
- (void)awe_scrollToSectionViewModel:(AWEBaseListSectionViewModel *)arg1 scrollOptions:(long long)arg2 scrollDirection:(long long)arg3 scrollPosition:(unsigned long long)arg4 animated:(_Bool)arg5;
- (void)awe_scrollToSectionController:(AWEBaseListSectionController *)arg1 scrollOptions:(long long)arg2 scrollDirection:(long long)arg3 scrollPosition:(unsigned long long)arg4 animated:(_Bool)arg5;
- (void)awe_performUpdatesAnimated:(_Bool)arg1 sync:(_Bool)arg2 completion:(void (^)(_Bool))arg3;
- (void)awe_reloadSectionViewModels:(NSArray *)arg1;
- (void)awe_reloadList:(_Bool)arg1 completion:(void (^)(_Bool))arg2;
- (void)awe_reloadList:(_Bool)arg1;
- (void)awe_createCollectionViewWithConfig:(AWEBaseListCollectionViewConfig *)arg1 layout:(UICollectionViewLayout<AWEListKitLayoutBaseProtocol> *)arg2 block:(void (^)(UICollectionView *))arg3;
- (void)awe_createCollectionViewWithLayout:(UICollectionViewLayout<AWEListKitLayoutBaseProtocol> *)arg1 block:(void (^)(UICollectionView *))arg2;
- (void)awe_createCollectionViewWithBlock:(void (^)(UICollectionView *))arg1;
@end

