//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentMediaFeedMultiMediaCellBasicProtocol-Protocol.h>

@class AWEAwemeModel, AWECommentImageModel, PHLivePhoto, UIImage;

@protocol AWECommentMediaFeedImageCellProtocol <AWECommentMediaFeedMultiMediaCellBasicProtocol>
- (void)imagePreviewViewAppearState:(_Bool)arg1;
- (void)currentPreviewDidOffScreen;
- (void)currentPreviewDidOnScreen;
- (void)reloadPicture:(AWECommentImageModel *)arg1 commentCameraModel:(AWEAwemeModel *)arg2 miniSizeImage:(UIImage *)arg3 fullSizeImage:(UIImage *)arg4 livePhotoLocal:(PHLivePhoto *)arg5 livePhotoLocalCover:(UIImage *)arg6;
@property(nonatomic, copy) CDUnknownBlockType updateSmartBGColorBlock;
@property(nonatomic, copy) CDUnknownBlockType livePhotoPlayControlBlock;
@property(nonatomic, retain) AWEAwemeModel *awemeModel;
@end

