//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentListViewControllerDataProtocol-Protocol.h>
#import <AwemeCore/AWECommentListViewControllerExtraCompatProtocol-Protocol.h>
#import <AwemeCore/AWECommentListViewControllerObserverProtocol-Protocol.h>
#import <AwemeCore/AWECommentListViewControllerSectionEmbeddedAccessProtocol-Protocol.h>
#import <AwemeCore/AWECommentListViewControllerShowOrDismissProtocol-Protocol.h>

@class AWECommentPanelParams;
@protocol AWECommentListViewControllerPreProcessProtocol, AWECommentListViewControllerSettingProtocol, AWECommentPanelBaseParamsProtocol, AWECommentViewControllerStateProtocol, AWECommentViewControllerTrackerProtocol;

@protocol AWECommentListViewControllerProtocol <AWECommentListViewControllerDataProtocol, AWECommentListViewControllerObserverProtocol, AWECommentListViewControllerShowOrDismissProtocol, AWECommentListViewControllerSectionEmbeddedAccessProtocol, AWECommentListViewControllerExtraCompatProtocol>
@property(nonatomic, readonly) id <AWECommentViewControllerTrackerProtocol> tracker;
@property(nonatomic, readonly) id <AWECommentListViewControllerPreProcessProtocol> preProcess;
@property(nonatomic, readonly) id <AWECommentViewControllerStateProtocol> state;
@property(nonatomic, readonly) id <AWECommentListViewControllerSettingProtocol> setting;
@property(nonatomic, readonly) id <AWECommentPanelBaseParamsProtocol> baseParams;
@property(nonatomic, readonly) AWECommentPanelParams *initializedParams;
@end

