//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol AWECommentMediaFeedViewControllerAccessProtocol <NSObject>
- (unsigned long long)currentScene;
- (long long)currentDataCount;
- (UIView *)currentCommentInputView;
- (_Bool)isDownloadEnabled;
- (_Bool)supportInteraction;
@property(nonatomic, readonly) long long currentIndex;
@property(nonatomic, readonly) _Bool dismissByPublishComment;
@end

