//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentModel, NSString, NSURL, UIImage;

@protocol AWECommentPictureDownloaderProtocol <NSObject>
+ (void)createLivePhoto:(NSURL *)arg1 imageUrl:(NSURL *)arg2 completion:(void (^)(id <AWECommentLivePhotoDownloadCallBackInfo>))arg3;
+ (NSString *)obtainAbsolutePath:(NSString *)arg1;
+ (void)obtainLivePhotoResource:(NSString *)arg1 imageUrl:(NSString *)arg2 placeholderImage:(UIImage *)arg3 completion:(void (^)(id <AWECommentLivePhotoDownloadCallBackInfo>))arg4;
+ (void)savePictureToAlbumFor:(AWECommentModel *)arg1 mediaType:(unsigned long long)arg2 atIndex:(long long)arg3;
+ (_Bool)canDownloadPictureFor:(AWECommentModel *)arg1;
@end

