//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentListViewControllerObserverProtocol <NSObject>
@property(nonatomic, copy) CDUnknownBlockType exitLandscapeBlock;
@property(nonatomic, copy) CDUnknownBlockType setCloseMethod;
@property(nonatomic, copy) CDUnknownBlockType seekPlayerTimeBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewDidExitFullScreenBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewWillEnterFullScreenBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewDidChangeBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewDidSendBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewDidHideBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewWillHideBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewWillHideFromFullScreenDirectly;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewDidShowBlock;
@property(nonatomic, copy) CDUnknownBlockType commentInputViewWillShowBlock;
@property(nonatomic, copy) CDUnknownBlockType customizeDismissBlock;
@property(nonatomic, copy) CDUnknownBlockType partialFullPanelZoomOutBlock;
@property(nonatomic, copy) CDUnknownBlockType partialFullPanelZoomInBlock;
@property(nonatomic, copy) CDUnknownBlockType willAutoEnterPartialFullPanelBlock;
@property(nonatomic, copy) CDUnknownBlockType willAutoEnterPartialPanelBlock;
@property(nonatomic, copy) CDUnknownBlockType didEnterPartialPanelBlock;
@property(nonatomic, copy) CDUnknownBlockType enterPartialFullPanelBlock;
@property(nonatomic, copy) CDUnknownBlockType didShowBlock;
@property(nonatomic, copy) CDUnknownBlockType deallocCallback;
@property(nonatomic, copy) CDUnknownBlockType cancelDismissBlock;
@property(nonatomic, copy) CDUnknownBlockType commentAttitudeAction;
@property(nonatomic, copy) CDUnknownBlockType panProgress;
@property(nonatomic, copy) CDUnknownBlockType manualDismissCallback;
@property(nonatomic, copy) CDUnknownBlockType didDismissAfterPostComments;
@property(nonatomic, copy) CDUnknownBlockType didCompleteDismissBlock;
@property(nonatomic, copy) CDUnknownBlockType didDismissBlock;
@property(nonatomic, copy) CDUnknownBlockType deleteCommentFinished;
@property(nonatomic, copy) CDUnknownBlockType publishCommentFinished;
@property(nonatomic, copy) CDUnknownBlockType commentScrollViewDidScroll;
@property(nonatomic, copy) CDUnknownBlockType updateCommentCount;
@property(nonatomic, copy) CDUnknownBlockType obtainCommentInputView;
@property(nonatomic, copy) CDUnknownBlockType commentCollectionViewDidLoad;
@end

