//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentGlobalUniqueInstanceCacheInputProtocol-Protocol.h>
#import <AwemeCore/AWECommentGlobalUniqueInstancePostProtocol-Protocol.h>

@class NSArray, NSDictionary;
@protocol AWECommentScreenshotManagerProtocol, AWEInteractionElementPopoverProtocol;

@protocol AWECommentGlobalUniqueInstanceProtocol <AWECommentGlobalUniqueInstancePostProtocol, AWECommentGlobalUniqueInstanceCacheInputProtocol>
- (id <AWECommentScreenshotManagerProtocol>)screenshotManager;
- (void)drawScreenshot;
- (void)clearCommentPostCommonParams;
- (NSDictionary *)commentMediaFeedInteractionTrackParams:(NSArray *)arg1;
- (NSDictionary *)obtainCommentMediaFeedTrackParams;
- (NSDictionary *)obtainCommentPostCommonParams;
@property(nonatomic) _Bool commentTemplateTabWillApproachSkipVideoPausePage;
@property(nonatomic) long long multiImageInnerSlideCnt;
@property(nonatomic) double multiImageInnerSlideStartStamp;
@property(nonatomic, copy) NSDictionary *zeroCommentPostTrackParams;
@property(nonatomic, retain) id <AWEInteractionElementPopoverProtocol> interactionElementPopoverInstance;
@end

