//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentModel, AWEGiphySearchResultObject, UIView;

@protocol AWECommentGiphySearchResultDelegate <NSObject>
- (void)didSelectedGiphy:(AWEGiphySearchResultObject *)arg1 giphyView:(UIView *)arg2;

@optional
- (AWECommentModel *)currentCommentModel;
- (_Bool)notMatchGifDisplayCondition;
- (_Bool)hasTextInputContent;
- (_Bool)isGifSearchingInputing;
- (_Bool)isGifSearchingContentEmpty;
@end

