//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSIndexPath, NSString, UICollectionViewCell, UIScrollView, UITableViewCell, UIView;

@protocol AWECommentScrollViewAccessCommentCellContainerDelegate <NSObject>
- (void)container_scrollView:(UIScrollView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (void)container_scrollView:(UIScrollView *)arg1 didEndDisplayingFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)container_scrollView:(UIScrollView *)arg1 willDisplayFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)container_scrollView:(UIScrollView *)arg1 didEndDisplayingHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)container_scrollView:(UIScrollView *)arg1 willDisplayHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (UIView *)container_scrollView:(UIScrollView *)arg1 viewForFooterInSection:(long long)arg2;
- (UIView *)container_scrollView:(UIScrollView *)arg1 viewForHeaderInSection:(long long)arg2;
- (double)container_scrollView:(UIScrollView *)arg1 heightForFooterInSection:(long long)arg2;
- (double)container_scrollView:(UIScrollView *)arg1 heightForHeaderInSection:(long long)arg2;
- (double)container_scrollView:(UIScrollView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)container_scrollView:(UIScrollView *)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)container_shouldTriggerAccessCommentCell;
- (void)container_changeServiceContainerPage:(NSString *)arg1;

@optional
- (void)container_scrollViewC:(UIScrollView *)arg1 didEndDisplayingCell:(UICollectionViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)container_scrollViewC:(UIScrollView *)arg1 willDisplayCell:(UICollectionViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)container_scrollViewC:(UIScrollView *)arg1 cellOfContainer:(UICollectionViewCell *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (UICollectionViewCell *)container_scrollViewC:(UIScrollView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)container_scrollViewT:(UIScrollView *)arg1 didEndDisplayingCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)container_scrollViewT:(UIScrollView *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)container_scrollViewT:(UIScrollView *)arg1 cellOfContainer:(UITableViewCell *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (UITableViewCell *)container_scrollViewT:(UIScrollView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
@end

