//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentGeneralServiceSectionConfigModel, NSNumber, UIScrollView;

@protocol AWECommentListBusinessServiceContainerContextProtocol <NSObject>
- (UIScrollView *)currentList;
- (NSNumber *)identifierForBusinessServiceDataSourceInSection:(long long)arg1;
- (long long)businessServiceDataSourceCount;

@optional
- (AWECommentGeneralServiceSectionConfigModel *)configModelForSection:(long long)arg1;
- (long long)sectionForIdentifier:(NSNumber *)arg1;
- (void)updateReplyCountForSection:(long long)arg1 count:(long long)arg2;
- (NSNumber *)replyCountForSection:(long long)arg1;
@end

