//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentMediaPlayerProtocol-Protocol.h>

@class AWEAwemeModel, AWEPageContext, NSString, UICollectionViewCell;

@protocol AWECommentMediaFeedRichContentContainerViewControllerProtocol <AWECommentMediaPlayerProtocol>
- (AWEPageContext *)commonViewControllerContext;
- (void)scrollToIndex:(long long)arg1 syncUpdateCell:(_Bool)arg2;
- (void)updateModel:(AWEAwemeModel *)arg1;
- (void)updateReferString:(NSString *)arg1 enterFrom:(NSString *)arg2;
- (UICollectionViewCell *)currentCell;
@end

