//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray;

@protocol AWECommentMediaFeedViewControllerAbilityProtocol <NSObject>
- (void)exit:(unsigned long long)arg1;
- (void)appendMoreData:(NSArray *)arg1;
@property(nonatomic, copy) CDUnknownBlockType exitAfterPublishImage;
@property(nonatomic, copy) CDUnknownBlockType fetchCommentFeedTrackManager;
@property(nonatomic, copy) CDUnknownBlockType commentFeedShouldLoadMore;
@property(nonatomic, copy) CDUnknownBlockType commentFeedBeginLoadMore;
@property(nonatomic, copy) CDUnknownBlockType commentFeedLoadMoreCondition;
@property(nonatomic, copy) CDUnknownBlockType commentFeedLoadMoreStrategy;
@end

