//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentInputViewObserverProtocol <NSObject>
@property(nonatomic, copy) CDUnknownBlockType didExitPreviewPage;
@property(nonatomic, copy) CDUnknownBlockType willEnterPreviewPage;
@property(nonatomic, copy) CDUnknownBlockType willResumePreviousPlayer;
@property(nonatomic, copy) CDUnknownBlockType fetchActionTrackingModelBlock;
@property(nonatomic, copy) CDUnknownBlockType willPausePreviousPlayer;
@property(nonatomic, copy) CDUnknownBlockType willChangeFullscreen;
@property(nonatomic, copy) CDUnknownBlockType didRemoveFromSuperView;
@property(nonatomic, copy) CDUnknownBlockType prepareInput;
@property(nonatomic, copy) CDUnknownBlockType didSendAlbumVideoComment;
@property(nonatomic, copy) CDUnknownBlockType exitLandscapeBlock;
@end

