//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWECommentModel, AWEGrowingTextView;
@protocol AWECommentInputViewDelegate, AWEInputViewBusinessControllerProtocol, AWETextInputControllerProtocol;

@protocol AWECommentInputViewBasicInfoProtocol <NSObject>
@property(nonatomic) unsigned long long beginInputSource;
@property(nonatomic, readonly) id <AWEInputViewBusinessControllerProtocol> businessController;
@property(nonatomic, readonly) id <AWETextInputControllerProtocol> textInputController;
@property(nonatomic) __weak id <AWECommentInputViewDelegate> delegate;
@property(nonatomic, readonly) AWEGrowingTextView *textView;
@property(nonatomic, retain) AWECommentModel *generalCommentModel;
@property(nonatomic, retain) AWECommentModel *commentModel;
@property(nonatomic, retain) AWEAwemeModel *model;
@property(nonatomic) unsigned long long belongScene;
@end

