//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSString;

@protocol AWECommentPanelBaseParamsProtocol
@property(nonatomic) _Bool isFromXigua;
@property(nonatomic) _Bool isLandscape;
@property(nonatomic, copy) NSDictionary *logExtraDict;
@property(nonatomic, copy) NSString *enterMethod;
@property(nonatomic, copy) NSString *enterFrom;
@property(nonatomic, copy) NSString *referString;
@property(nonatomic) unsigned long long enterSource;
@property(nonatomic) unsigned long long colorMode;
@end

