//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommerceComponentActionProtocol-Protocol.h>
#import <AwemeCore/AWECommerceComponentsMonitorProtocol-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSString, UIViewController;
@protocol AWEPlayVideoViewControllerProtocol, IESVideoPlayerProtocol;

@protocol AWECommerceDispatcherProtocol <NSObject, AWECommerceComponentsMonitorProtocol, AWECommerceComponentActionProtocol>

@optional
- (void)updateSlidesAwemeProgressWithModel:(AWEAwemeModel *)arg1 duration:(double)arg2 totalCount:(long long)arg3 currentIndex:(long long)arg4 currentProgress:(double)arg5 slideMethod:(unsigned long long)arg6 direction:(NSString *)arg7;
- (void)richAwemeUpdateFromIndex:(long long)arg1 toIndex:(long long)arg2 isByHand:(_Bool)arg3 isFullPage:(_Bool)arg4;
- (void)onUpdatePlayerController:(id <IESVideoPlayerProtocol>)arg1 withPlayVideoVC:(UIViewController<AWEPlayVideoViewControllerProtocol> *)arg2;
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangeStallState:(long long)arg2 actionType:(long long)arg3 reason:(unsigned long long)arg4;
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2;
- (void)onPlayerWillLoopPlaying:(id <IESVideoPlayerProtocol>)arg1;
- (void)prepareForDisplay;
- (void)resume;
- (void)pause;
- (void)reset;
- (void)setHide:(_Bool)arg1;
- (void)didDisplay;
- (void)willDisplay;
- (void)setModel:(AWEAwemeModel *)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
@end

