//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentInputBasicPropertyProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewBasicInfoProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewBizProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewCommonAbilityProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewContentProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewObserverProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewStateInfoProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewTimingProtocol-Protocol.h>
#import <AwemeCore/AWECommentInputViewTrackerProtocol-Protocol.h>

@protocol AWECommentInputViewProtocol <AWECommentInputViewBasicInfoProtocol, AWECommentInputViewStateInfoProtocol, AWECommentInputViewContentProtocol, AWECommentInputViewCommonAbilityProtocol, AWECommentInputViewObserverProtocol, AWECommentInputViewTimingProtocol, AWECommentInputViewTrackerProtocol, AWECommentInputBasicPropertyProtocol, AWECommentInputViewBizProtocol>
@end

