//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;

@protocol AWECommentSectionVideoTitleAnchorProtocol <NSObject>

@optional
- (void)anchorDidShow:(NSString *)arg1 trackInfo:(NSDictionary *)arg2;
- (void (^)(void))anchorTapBlock:(NSString *)arg1;
- (NSArray *)anchorType;
@end

