//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPageContext, NSArray, NSIndexPath, NSString, UICollectionReusableView, UICollectionViewCell, UIScrollView, UITableViewCell, UITableViewHeaderFooterView;
@protocol AWECommentListBusinessServiceContainerContextProtocol;

@protocol AWECommentListBusinessServiceViewModelProtocol <NSObject>
- (double)heightForRowForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (NSString *)identifierForResuableViewAtIndexPath:(NSIndexPath *)arg1;
- (void)registerReusableView:(UIScrollView *)arg1 contextDelegate:(id <AWECommentListBusinessServiceContainerContextProtocol>)arg2 completionBlock:(void (^)(void))arg3;
- (long long)numberOfItemsForSection:(long long)arg1;
- (void)configContext:(AWEPageContext *)arg1;
@property(nonatomic) long long serviceID;
@property(nonatomic, copy) NSArray *insertCommentIDs;
@property(nonatomic, copy) NSArray *insertIDs;

@optional
- (void)footerDidEndDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)footerWillDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)headerDidEndDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)headerWillDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)reusableViewDidEndDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)reusableViewWillDisplayForIdentifier:(NSString *)arg1 atIndexPath:(NSIndexPath *)arg2;
- (void)configTFooter:(UITableViewHeaderFooterView *)arg1 identifier:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)configCFooter:(UICollectionReusableView *)arg1 identifier:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)configTCell:(UITableViewCell *)arg1 identifier:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (void)configCCell:(UICollectionViewCell *)arg1 identifier:(NSString *)arg2 atIndexPath:(NSIndexPath *)arg3;
- (NSString *)identifierForFooterAtIndexPath:(long long)arg1;
- (NSString *)identifierForHeaderAtIndexPath:(long long)arg1;
- (double)footerHeightForIdentifier:(NSString *)arg1 section:(long long)arg2;
- (double)headerHeightForIdentifier:(NSString *)arg1 section:(long long)arg2;
- (void)didSelectRowAtIndexPath:(NSIndexPath *)arg1;
- (void)changeServiceContainerPage:(NSString *)arg1;
@end

