//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentAudioContentViewProtocol;

@protocol AWECommentAudioContentViewDelegate <NSObject>
- (void)commentAudioContentViewPanGesture:(id <AWECommentAudioContentViewProtocol>)arg1 type:(unsigned long long)arg2 progress:(double)arg3;
- (void)commentAudioContentViewTapped:(id <AWECommentAudioContentViewProtocol>)arg1 type:(unsigned long long)arg2;
@end

