//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentMediaFeedMultiMediaCellBasicProtocol-Protocol.h>

@class AWEAwemeModel;

@protocol AWECommentMediaFeedVideoCellProtocol <AWECommentMediaFeedMultiMediaCellBasicProtocol>
- (void)configAweme:(AWEAwemeModel *)arg1;
@end

