//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSString, UIViewController;
@protocol AWECommentGeneralModelProtocol;

@protocol AWECommentSearchParentViewController <NSObject>
- (AWEAwemeModel *)awemeModel;
- (NSString *)referString;
- (void)dismissCommentSearchViewController:(UIViewController *)arg1 completion:(void (^)(void))arg2;
- (void)showCommentSearchViewController:(UIViewController *)arg1 completion:(void (^)(void))arg2;

@optional
- (id <AWECommentGeneralModelProtocol>)generalItemTrackModel;
- (unsigned long long)inputViewExternSceneForTrack;
- (NSString *)enterFrom;
@end

