//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, UIScrollView;
@protocol AWECommentSectionControllerContainerProtocol;

@protocol AWECommentListViewControllerSectionEmbeddedAccessProtocol <NSObject>
- (void)containerScrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)containerScrollViewDidEndScrollingAnimation:(UIScrollView *)arg1;
- (void)containerScrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)containerScrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)containerScrollViewDidScroll:(UIScrollView *)arg1;
- (_Bool)loadMoreCommentData:(NSDictionary *)arg1;
- (_Bool)refreshCommentData:(NSDictionary *)arg1;
- (double)commentLayoutFoldedHeight;
- (NSArray *)commentSectionControllerClassArray;
@property(nonatomic) unsigned long long sectionControllerContainerType;
@property(nonatomic) _Bool isSectionControllerContainer;
@property(nonatomic) __weak id <AWECommentSectionControllerContainerProtocol> sectionControllerContainerDelegate;
@property(nonatomic) _Bool isEmbeddedLandscape;
@property(nonatomic) _Bool isEmbeddedVC;
@end

