//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentAudioRefactorInputViewDelegate <NSObject>
- (void)dismissRecorderAnimation;
- (void)showRecorderAnimation;
- (struct CGRect)currentInputViewRect;
@end

