//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentCellTextConfigModel, UITableViewCell;

@protocol AWECommentNewFeedCellViewModelProtocol <NSObject>
- (void)setCommentCellTextConfig:(AWECommentCellTextConfigModel *)arg1;
- (void)preCalculate;
- (struct CGSize)cellSize;
- (void)renderOn:(UITableViewCell *)arg1;
@end

