//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECellTransitionProtocol <NSObject>
- (void)setCurrentCellContentMode:(unsigned long long)arg1;
- (unsigned long long)currentCellContentMode;
@end

