//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentPublishGuidanceEmoticonModel, NSDictionary, NSString;

@protocol AWECommentInputViewTrackerProtocol <NSObject>
- (NSString *)closeEditingMethodStringFromMethodType:(long long)arg1;
- (NSString *)enterEditingMethodStringFromMethodType:(long long)arg1;
- (NSDictionary *)postCommentTrackParams;
- (NSDictionary *)enterTextTrackParams;
@property(nonatomic, copy) NSDictionary *bizLogExtraDict;
@property(nonatomic, copy) NSDictionary *tmpMediaLogExtraDict;
@property(nonatomic, readonly) NSDictionary *monitorDict;
@property(nonatomic, copy) NSDictionary *tmpLogExtraDict;
@property(nonatomic, copy) NSDictionary *logExtraDict;
@property(nonatomic, copy) NSString *sendMethod;
@property(nonatomic, retain) AWECommentPublishGuidanceEmoticonModel *lastSelectedPublishRecommend;
@property(nonatomic) long long endEditingMethodType;
@property(nonatomic) long long oldBeginEditingMethodType;
@property(nonatomic) long long beginEditingMethodType;
@end

