//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentTabComponentLifeCycleProtocol <NSObject>

@optional
- (void)willDisplayPanelHeightChangeTransition:(double)arg1 isFullScreen:(_Bool)arg2;
- (void)onCommentUIThemeChange:(_Bool)arg1;
- (void)commentPanelDidDismiss;
- (void)commentPanelDidShow;
- (void)tabDidSelectedWithoutChange:(unsigned long long)arg1 from:(unsigned long long)arg2 method:(unsigned long long)arg3;
- (void)tabDidSelected:(unsigned long long)arg1 from:(unsigned long long)arg2 method:(unsigned long long)arg3;
- (void)tabWillDisappear;
- (void)tabWillAppear;
- (void)tabContainerViewDidDisappear;
- (void)tabContainerViewWillDisappear;
- (void)tabContainerViewDidAppear;
- (void)tabContainerViewWillAppear;
@end

