//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol AWECommentMediaUploaderProtocol <NSObject>
- (void)startUpload;
- (_Bool)startMediaUploadAuth:(void (^)(AWECommentUploadAuthResponse *, NSError *))arg1;
- (void (^)(AWECommentUploadAuthResponse *, NSError *))configUploadAuthCompletion;
- (NSDictionary *)generateAuthParams;
- (NSDictionary *)uploadBusinessAuthParams;
- (void)configUploader;
@property(nonatomic, copy) CDUnknownBlockType progressBlock;
@property(nonatomic, copy) CDUnknownBlockType mediaUploadCompletionBlock;
@property(nonatomic, copy) CDUnknownBlockType mediaUploadCompressCompletionBlock;
@property(nonatomic, copy) CDUnknownBlockType mediaUploadAuthCompletionBlock;
@end

