//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UICollectionViewCell, UITableViewCell;

@protocol AWECommentTemplateCellViewModel <NSObject>
- (void)calculateSize;
- (struct CGSize)cellSize;
- (void)renderOnCollectionCell:(UICollectionViewCell *)arg1;
- (void)renderOnTableCell:(UITableViewCell *)arg1;
@property(nonatomic, copy) CDUnknownBlockType userAction;
@property(nonatomic, copy) CDUnknownBlockType cellLayoutUpdate;

@optional
- (void)renderingViewDidEndDisplay;
- (void)renderingViewWillDisplay;
@end

