//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AWECommentMediaFeedLynxPlayInteractionViewControllerProtocol <NSObject>
- (void)containerInjectSchema:(NSString *)arg1 data:(NSString *)arg2;
@property(nonatomic, copy) CDUnknownBlockType userNameViewDidUpdateBlcok;
@end

