//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentTransitionInnerProviderLifeCycleProtocol-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class UIImageView, UIView, UIViewController;

@protocol AWECommentPartialScreenLeaveTransitionInnerContextProvider <NSObject, AWECommentTransitionInnerProviderLifeCycleProtocol>
- (void)commentPartialScreenLeaveTransition_playInteractionPanelInteractiveZoomInTransitionCompletionHandler;
- (void)commentPartialScreenLeaveTransition_playInteractionPanelZoomInTransitionCompletionHandler;
- (void)commentPartialScreenLeaveTransition_playInteractionPanelInteractiveZoomInTransitionHandlerWithProgress:(double)arg1;
- (void)commentPartialScreenLeaveTransition_playInteractionPanelAutoZoomOutTransitionHandler;
- (void)commentPartialScreenLeaveTransition_playInteractionPanelAutoZoomInTransitionHandler;
- (void)commentPartialScreenLeaveTransition_partialFullPanelZoomOutHandlerWithProgress:(double)arg1 state:(unsigned long long)arg2;
- (void)commentPartialScreenLeaveTransition_commentPanelResetTabbar;
- (UIView *)commentPartialScreenLeaveTransition_tabbarSnapshot;
- (UIImageView *)commentPartialScreenLeaveTransition_commentInputViewSnapShot;
- (UIViewController *)commentPartialScreenLeaveTransition_innerContextProviderContentVC;
- (UIViewController *)commentPartialScreenLeaveTransition_innerContextProviderVC;
- (_Bool)commentPartialScreenLeaveTransition_innerContextProvider_tabbarHiddenByComment;
- (_Bool)commentPartialScreenLeaveTransition_shouldShowCommentInputViewSnapshot;
@end

