//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentTransitionInnerProviderLifeCycleProtocol-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentAutoZoomTransitionInnerContextProvider <NSObject, AWECommentTransitionInnerProviderLifeCycleProtocol>
- (_Bool)commentAutoZoomTransition_innerContextProvider_tabbarHiddenByComment;
@end

