//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEPageContext;
@protocol AWECommentControlVideoStateProtocol, AWEShareGuideDelegate;

@protocol AWECommentListViewControllerFeedInteractionCompatProtocol <NSObject>
- (void)trackShowOnViewWithRealClickEvent;
- (double)getVideoHeightWhenShowCommentPanel;
- (double)getVideoHeightWhenShowCommentFullPanel;
@property(nonatomic) __weak id <AWEShareGuideDelegate> shareGuideDelegate;
@property(nonatomic) _Bool autoShow;
@property(nonatomic, retain) AWEAwemeModel *fromModel;
@property(nonatomic) __weak id <AWECommentControlVideoStateProtocol> videoStateChangeDelegate;
@property(nonatomic) __weak id videoPlayer;
@property(nonatomic) __weak AWEPageContext *feedPageContext;
@property(nonatomic) __weak id interactionViewController;
@property(nonatomic) _Bool hasHiddenPauseIcon;
@property(nonatomic) unsigned long long eventSource;
@end

