//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentInputViewStateInfoProtocol <NSObject>
- (_Bool)needContinueAudioPlay;
- (_Bool)showRiskUserAlertDialogBeforeComment;
- (double)emoticonShowAnimationDuration;
- (_Bool)isInputing;
- (_Bool)isShowingBoard;
- (double)inputViewTop;
- (_Bool)anonymousViewSelected;
@property(nonatomic, readonly) _Bool isChoosingPicture;
@property(nonatomic, readonly) _Bool keyboardWillHide;
@property(nonatomic, readonly) _Bool isShowingKeyboard;
@property(nonatomic, readonly) _Bool isAting;
@property(nonatomic, readonly) _Bool isFullscreen;
@property(nonatomic, readonly) unsigned long long inputSource;
@property(nonatomic) _Bool isInCommentManager;
@property(nonatomic) _Bool isOldHunterScene;
@property(nonatomic) _Bool isPublishingMediaAlbumVideo;
@property(nonatomic) _Bool commentContainerIsAppear;
@property(nonatomic) _Bool isContainerFullScreen;
@end

