//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol AWECommentMediaFeedMultiMediaCellBasicProtocol <NSObject>
- (void)recoverCellwithPureMode:(_Bool)arg1;
- (_Bool)isSlideEdge:(_Bool)arg1 isRight:(_Bool)arg2;
- (UIView *)mediaContainerView;
- (void)cellDidOffScreenFromHorizontal:(_Bool)arg1;
- (void)cellWillOffScreenFromHorizontal:(_Bool)arg1;
- (void)cellDidOnScreenFromHorizontal:(_Bool)arg1;
- (void)cellWillOnScreenFromHorizontal:(_Bool)arg1;
@property(nonatomic, copy) CDUnknownBlockType pureModeBlock;
@property(nonatomic, copy) CDUnknownBlockType doubleTapBlock;
@property(nonatomic) unsigned long long index;
@property(nonatomic) unsigned long long itemCount;

@optional
- (void)mediaFeedContainerViewDidDisAppear;
- (void)mediaFeedContainerViewDidAppear;
- (void)mediaFeedContainerViewWillDisappear;
- (void)mediaFeedContainerViewWillAppear;
@end

