//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;
@protocol AWECommentInputViewProtocol;

@protocol AWECommentInputViewManagerDelegate <NSObject>

@optional
- (void)custom_commentInputViewDanmakuSwitchButtonClicked;
- (_Bool)custom_commentInputViewShouldBeginEditing:(UIView<AWECommentInputViewProtocol> *)arg1;
- (_Bool)custom_commentInputViewCustomSendAction:(UIView<AWECommentInputViewProtocol> *)arg1;
- (_Bool)custom_commentInputViewShouldReturn:(UIView<AWECommentInputViewProtocol> *)arg1;
@end

