//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPageContext;
@protocol AWECommentPanelConfigurationProtocol;

@protocol AWECommentListViewControllerPrivateProtocol <NSObject>
- (AWEPageContext *)currentPageContext;
- (void)onInitFinish;
@property(nonatomic, retain) id <AWECommentPanelConfigurationProtocol> config;
@end

