//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentMediaMainVideoPlayerViewControllerDelegate <NSObject>
- (void)playerUpdatePlayTime:(double)arg1 canPlayTime:(double)arg2 totalTime:(double)arg3;
@end

