//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDate, UIImage;

@protocol AWECommentScreenshotManagerProtocol <NSObject>
- (void)resetScreenshotTime;
- (void)resetScreenshotImage;
- (NSDate *)currentScreenshotTime;
- (UIImage *)currentScreenshotImage;
- (void)drawScreenshot;
@end

