//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;
@protocol AWEAdCommentGuideView;

@protocol AWECommentGuideDelegate <NSObject>
- (void)closeAdCommentGuide:(UIView<AWEAdCommentGuideView> *)arg1;
@end

