//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentMediaPlayerProtocol-Protocol.h>

@class AWEAwemeModel, AWEUserModel, NSString, UIView, UIViewController;

@protocol AWECommentMediaMainVideoPlayerViewControllerProtocol <AWECommentMediaPlayerProtocol>
- (void)updateData:(AWEAwemeModel *)arg1 author:(AWEUserModel *)arg2 referString:(NSString *)arg3 enterFrom:(NSString *)arg4;
- (UIViewController *)playerViewController;
- (void)hidePauseButton:(_Bool)arg1;
- (long long)playState;
- (void)videoDidTap:(UIView *)arg1;
- (double)currentPlayerRate;
- (void)updatePlayerRate:(double)arg1;
- (void)playerSeekProgress:(double)arg1 completion:(void (^)(_Bool))arg2;
@end

