//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UICollectionViewCell;

@protocol AWECommentSectionControllerTimingProtocol <NSObject>
- (void)sectionDidEndDisplayingCell:(UICollectionViewCell *)arg1 index:(long long)arg2;
- (void)sectionWillDisplayCell:(UICollectionViewCell *)arg1 index:(long long)arg2 model:(id)arg3;
@end

