//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol AWECommentMediaFeedRichContentContainerViewControllerDelegate <NSObject>
- (_Bool)canPlayerPlayAfterTouch;
- (void)didUpdatePaginatedProgressWithIndex:(long long)arg1 totalCount:(long long)arg2;
- (void)richContainerDidCreateProgressView:(UIView *)arg1;
@end

