//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWECommentTransitionOuterProviderLifeCycleProtocol-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol AWECommentPinchFullScreenTransitionOuterContextProvider <NSObject, AWECommentTransitionOuterProviderLifeCycleProtocol>
- (UIView *)pinchFullScreen_outerNavBarSnapShot;
@end

