//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentEvaluationConfig, AWECommentEvaluationParams, NSString;
@protocol AWECommentEvaluationDataServiceProtocol, AWECommentEvaluationEventListenerProtocol;

@protocol AWECommentEvaluationCoreServiceProtocol <NSObject>
- (void)viewUpdateContainerTag:(NSString *)arg1;
- (void)viewUpdateTheme:(unsigned long long)arg1;
- (void)viewConfig:(AWECommentEvaluationConfig *)arg1 params:(AWECommentEvaluationParams *)arg2;
- (id <AWECommentEvaluationEventListenerProtocol>)eventListenerService;
- (id <AWECommentEvaluationDataServiceProtocol>)dataService;
@end

