//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentModel, AWECommentPublishParameterModel, NSArray, NSString;

@protocol AWECommentGlobalUniqueInstancePostProtocol <NSObject>

@optional
- (void)trackPostComment:(AWECommentPublishParameterModel *)arg1;
- (NSArray *)popCommentWithItemID:(NSString *)arg1;
- (void)pushComment:(AWECommentModel *)arg1 withItemID:(NSString *)arg2;
@end

