//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIView;

@protocol AWECommentListViewControllerShowOrDismissProtocol <NSObject>
- (void)dismissWithCloseMethod:(NSString *)arg1;
- (void)dismissWithAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)dismissWithAnimated:(_Bool)arg1;
- (void)dismiss;
- (void)showOnView:(UIView *)arg1 animated:(_Bool)arg2 refresh:(_Bool)arg3 scrollToTop:(_Bool)arg4 completion:(void (^)(void))arg5;
- (void)showOnView:(UIView *)arg1 animated:(_Bool)arg2 refresh:(_Bool)arg3 completion:(void (^)(void))arg4;
- (void)showOnView:(UIView *)arg1 completion:(void (^)(void))arg2;
@end

