//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWECommentModel, NSDictionary, NSString;

@protocol AWECommentCellProtocol <NSObject>
+ (NSString *)identifier;
- (void)resetLikesLabel;
@property(nonatomic) _Bool hiddenCommentContentAnimating;
@property(nonatomic) _Bool isFromXigua;
@property(nonatomic) long long sceneType;
@property(nonatomic, copy) NSString *referString;
@property(nonatomic, copy) NSDictionary *logExtraDict;
@property(nonatomic, copy) CDUnknownBlockType avatarOrNameTappedBlock;
@property(nonatomic, copy) CDUnknownBlockType truncationTokenTappedBlock;
@property(nonatomic, copy) CDUnknownBlockType likeButtonTappedBlock;
@property(nonatomic, retain) AWECommentModel *commentModel;
@end

