//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIViewController;

@protocol AWECommentTransitionOuterProviderLifeCycleProtocol <NSObject>

@optional
- (void)commentOuterProvider_transitionWillFinish:(long long)arg1 fromVC:(UIViewController *)arg2 toVC:(UIViewController *)arg3;
- (void)commentOuterProvider_transitionWillCancel:(long long)arg1 fromVC:(UIViewController *)arg2 toVC:(UIViewController *)arg3;
- (void)commentOuterProvider_transitionWillBegin:(long long)arg1 fromVC:(UIViewController *)arg2 toVC:(UIViewController *)arg3;
@end

