//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentViewControllerStateProtocol <NSObject>
@property(nonatomic, readonly) _Bool isCommentPanelInputViewFullscreen;
@property(nonatomic, readonly) _Bool isPictureChoosing;
@property(nonatomic, readonly) _Bool isDismissingToFullScreen;
@property(nonatomic, readonly) _Bool isCommentVCFullScreen;
@property(nonatomic, readonly) _Bool isSkipCommentPanelLifecycle;
@property(nonatomic, readonly) _Bool isCommentImageBrowsing;
@property(nonatomic) _Bool isShowing;
@end

