//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel;
@protocol AWECommentGeneralModelProtocol;

@protocol AWECommentListViewControllerDataProtocol <NSObject>
@property(nonatomic, retain) id <AWECommentGeneralModelProtocol> generalModel;
@property(nonatomic, retain) AWEAwemeModel *model;
@end

