//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;
@protocol AWECommentGeneralModelProtocol;

@protocol AWECommentInputBasicPropertyProtocol <NSObject>
@property(nonatomic) long long externalStartEditingMethodType;
@property(nonatomic) unsigned long long inputViewExternScene;
@property(nonatomic, retain) id <AWECommentGeneralModelProtocol> generalModel;
@property(nonatomic, copy) NSString *enterMethod;
@property(nonatomic, copy) NSString *enterFrom;
@property(nonatomic, copy) NSString *referString;
@property(nonatomic, copy) NSString *previousPage;
@end

