//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWECommentListViewControllerMediaSettingProtocol, AWECommentViewControllerContentSettingProtocol, AWECommentViewControllerInputViewSettingProtocol, AWECommentViewControllerPanelContainerSettingProtocol, AWECommentViewControllerTabSettingProtocol;

@protocol AWECommentListViewControllerSettingProtocol <NSObject>
@property(nonatomic, readonly) id <AWECommentListViewControllerMediaSettingProtocol> media;
@property(nonatomic, readonly) id <AWECommentViewControllerContentSettingProtocol> coreContent;
@property(nonatomic, readonly) id <AWECommentViewControllerInputViewSettingProtocol> input;
@property(nonatomic, readonly) id <AWECommentViewControllerTabSettingProtocol> tab;
@property(nonatomic, readonly) id <AWECommentViewControllerPanelContainerSettingProtocol> panelContainer;
@end

