//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AWECommentGlobalUniqueInstanceCacheInputProtocol <NSObject>

@optional
- (void)removeInputContentForItemID:(NSString *)arg1 commentID:(NSString *)arg2;
- (void)setInputContent:(NSDictionary *)arg1 forItemID:(NSString *)arg2 commentID:(NSString *)arg3;
- (NSDictionary *)inputContentForItemID:(NSString *)arg1 commentID:(NSString *)arg2;
@end

