//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AWECommentSLITrackProtocol <NSObject>
- (void)recordForOCWithSessionID:(NSString *)arg1 type:(unsigned long long)arg2 stage:(unsigned long long)arg3 extra:(NSDictionary *)arg4;
@end

