//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSError;
@protocol AWEDCFeedListResponseProtocol;

@protocol AWEDCFeedEventDataProtocol <NSObject>

@optional
- (NSDictionary *)customRequestArgs:(NSDictionary *)arg1 requestInfo:(struct AWEDCFeedListRequestInfo)arg2;
- (NSDictionary *)customRequestParams:(NSDictionary *)arg1 requestInfo:(struct AWEDCFeedListRequestInfo)arg2;
- (void)updateViewModelDataState:(long long)arg1;
- (void)listDidPerformBatchUpdates;
- (void)listWillPerformBatchUpdates;
- (void)listDidReloadData;
- (void)listWillReloadData;
- (void)onLoadMoreListDataEndWithReason:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2 error:(NSError *)arg3;
- (void)onLoadMoreListDataStartWithReason:(unsigned long long)arg1;
- (void)onFetchListDataFromHeaderDragWithReason:(unsigned long long)arg1;
- (void)onFetchListDataEndWithReason:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2 error:(NSError *)arg3;
- (void)onFetchListDataBeforeEndWithReason:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2;
- (void)onFetchListDataStartWithReason:(unsigned long long)arg1;
- (void)onRefreshBeStoppedWithRefreshReason:(unsigned long long)arg1;
- (void)onRefreshListDataStartWithRefreshReason:(unsigned long long)arg1;
- (void)onLoadPlaceholderDataEndWithResult:(unsigned long long)arg1 placeholderData:(NSArray *)arg2;
- (void)onLoadPlaceholderDataStart;
@end

