//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEBaseListSectionController, AWEDCFeedBaseCell, AWEDCFeedBaseSectionController, AWEDCFeedEnterModel, AWEDCFeedExitModel, NSIndexPath, NSString, UICollectionView, UICollectionViewCell, UIEvent, UIView;

@protocol AWEDCFeedEventLifecycleProtocol <NSObject>

@optional
- (void)themeReload;
- (void)themeBeginReload;
- (void)enterInsAtIndexPath:(NSIndexPath *)arg1 withModel:(AWEAwemeModel *)arg2 referString:(NSString *)arg3 selectedCell:(UICollectionViewCell *)arg4;
- (void)enterGraphicsDetailAtIndexPath:(NSIndexPath *)arg1 withModel:(AWEAwemeModel *)arg2 referString:(NSString *)arg3 selectedCell:(UICollectionViewCell *)arg4;
- (void)enterDetailVCAtIndexPath:(NSIndexPath *)arg1 withModel:(AWEAwemeModel *)arg2 referString:(NSString *)arg3 selectedCell:(UICollectionViewCell *)arg4;
- (void)willEnterDetailVCAtIndexPath:(NSIndexPath *)arg1 withModel:(AWEAwemeModel *)arg2 referString:(NSString *)arg3 selectedCell:(UICollectionViewCell *)arg4;
- (void)sectionControllerWillEnterWorkingRange:(AWEBaseListSectionController *)arg1;
- (void)sectionController:(AWEDCFeedBaseSectionController *)arg1 hitTestCell:(AWEDCFeedBaseCell *)arg2 targetView:(UIView *)arg3 event:(UIEvent *)arg4 model:(id)arg5;
- (void)sectionController:(AWEDCFeedBaseSectionController *)arg1 configCell:(AWEDCFeedBaseCell *)arg2 model:(id)arg3 index:(long long)arg4;
- (void)containerCollectionView:(UICollectionView *)arg1 skeletonDidEndDisplayingCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;
- (void)containerCollectionView:(UICollectionView *)arg1 skeletonWillDisplayCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;
- (void)containerCollectionView:(UICollectionView *)arg1 endDidSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (void)containerCollectionView:(UICollectionView *)arg1 startDidSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (void)containerCollectionView:(UICollectionView *)arg1 didSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (void)containerCollectionView:(UICollectionView *)arg1 didHighlightItemAtIndexPath:(NSIndexPath *)arg2;
- (void)containerCollectionView:(UICollectionView *)arg1 didEndDisplayingCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;
- (void)containerCollectionView:(UICollectionView *)arg1 willDisplayCell:(UICollectionViewCell *)arg2 forItemAtIndexPath:(NSIndexPath *)arg3;
- (void)applicationWillTerminate;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)appDidEnterBackground;
- (void)appWillEnterForeground;
- (void)exitContainerWithModel:(AWEDCFeedExitModel *)arg1;
- (void)enterContainerWithModel:(AWEDCFeedEnterModel *)arg1;
- (void)containerViewDidLayoutSubviews;
- (void)containerViewWillLayoutSubviews;
- (void)containerViewDidDisappear:(_Bool)arg1;
- (void)containerViewWillDisappear:(_Bool)arg1;
- (void)containerAfterViewDidAppear:(_Bool)arg1;
- (void)containerViewDidAppear:(_Bool)arg1;
- (void)containerViewWillAppear:(_Bool)arg1;
- (void)containerBeforeViewWillAppear:(_Bool)arg1;
- (void)containerViewDidLoad;
- (void)containerBeforeViewDidLoad;
@end

