//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEDCFeedBaseCellElement;

@protocol AWEDCFeedEventElementLifeCycleProtocol <NSObject>

@optional
- (void)elementDidReset:(AWEDCFeedBaseCellElement *)arg1;
- (void)elementDidConfigData:(AWEDCFeedBaseCellElement *)arg1;
@end

