//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIScrollView;

@protocol AWEDCFeedEventScrollViewProtocol <NSObject>

@optional
- (void)setContainerScrollEnabled:(_Bool)arg1;
- (void)containerScrollViewDidScroll:(UIScrollView *)arg1;
- (void)containerScrollViewDidScrollToTop:(UIScrollView *)arg1;
- (void)containerScrollViewDidScrollEndWithActive;
- (void)containerScrollViewDidScrollEndWithNotActive;
- (void)containerScrollViewDidEndScrollingAnimation:(UIScrollView *)arg1;
- (void)containerScrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)containerScrollViewWillBeginDecelerating:(UIScrollView *)arg1;
- (void)containerScrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)containerScrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)containerScrollViewWillBeginDragging:(UIScrollView *)arg1;
@end

