//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEDigitalWellbeingMessage <NSObject>

@optional
- (void)digitalWellbeingDidTransferredToTimeManager;
- (void)teenPersonalRecommendSwitchChanged:(_Bool)arg1;
- (void)unlockPageWillAppear;
- (void)unlockPageDidDismiss;
- (void)serverTeenModeDidChangeUnderFourTeenModeStatus;
- (void)serverTeenModeDidRecalculateUnderFourTeenTeenModeStatus:(_Bool)arg1;
- (void)isForceServerTeenModeDidChange:(_Bool)arg1;
- (void)serverTeenModeDidTakeEffectForFirstTime;
- (void)timeLockDidChange:(long long)arg1 isLogout:(_Bool)arg2;
- (void)teenModeDidChange:(_Bool)arg1 isLogout:(_Bool)arg2;
@end

