//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEDCFeedEventChunkProtocol <NSObject>

@optional
- (void)onChunkRequestEndWithRequestType:(unsigned long long)arg1;
- (void)onChunkRequestBeginWithRequestType:(unsigned long long)arg1;
@end

