//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEDCFeedSearchBarDelegateContext, NSDictionary, NSString;

@protocol AWEDCFeedTopAreaSearchDelegate <NSObject>

@optional
- (NSDictionary *)extraParamsWithEvent:(NSString *)arg1 currentParams:(NSDictionary *)arg2;
- (_Bool)enableCurrentTrack:(NSString *)arg1 extra:(NSDictionary *)arg2;
- (long long)fetchGuessWordIntervalWhenEnableTimer;
- (_Bool)shouldFetchGuessWordWithOption:(unsigned long long)arg1;
- (NSDictionary *)fetchGuessWordParamsWithOption:(unsigned long long)arg1 extra:(NSDictionary *)arg2;
- (NSDictionary *)searchBarClickParamsWithContext:(AWEDCFeedSearchBarDelegateContext *)arg1;
- (NSString *)searchBarClickURLWithContext:(AWEDCFeedSearchBarDelegateContext *)arg1;
- (void)searchBarDidClickedWithContext:(AWEDCFeedSearchBarDelegateContext *)arg1;
@end

