//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEDCFeedBaseSectionViewModel, NSDictionary, NSString;

@protocol AWEDCFeedEventActionProtocol <NSObject>

@optional
- (void)onCustomActionTriggeredWithName:(NSString *)arg1 sender:(id)arg2 params:(NSDictionary *)arg3 sectionViewModel:(AWEDCFeedBaseSectionViewModel *)arg4;
- (void)onCustomActionTriggeredWithName:(NSString *)arg1 sender:(id)arg2 params:(NSDictionary *)arg3;
- (void)onGeneralActionTriggeredWithType:(unsigned long long)arg1 sender:(id)arg2 params:(NSDictionary *)arg3 sectionViewModel:(AWEDCFeedBaseSectionViewModel *)arg4;
@end

