//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSIndexPath, UIScrollView, UITableViewCell, UIViewController;
@protocol AWEAwemeDetailTableViewControllerProtocol;

@protocol AWEDCFeedEventAwemeDetailDelegate <NSObject>

@optional
- (void)detailTableViewControllerWillExit:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerDidDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillDisappear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerDidAppear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewControllerWillAppear:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 scrollViewDidBeginDragging:(UIScrollView *)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 refreshFooterDidShowAtIndex:(long long)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 scrollDidEndAtIndexPath:(NSIndexPath *)arg2 model:(AWEAwemeModel *)arg3;
- (void)detailTableViewControllerDidScroll:(UIScrollView *)arg1 detailVC:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg2 isScrollDown:(_Bool)arg3 index:(long long)arg4;
- (void)detailTableViewControllerDidScroll:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewControllerWillScrollToNextItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewControllerWillScrollToPreviousItem:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 currentAwemeModel:(AWEAwemeModel *)arg2 targetIndex:(long long)arg3;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 awemeModel:(AWEAwemeModel *)arg2 didChangePlaybackStateWithAction:(long long)arg3;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 awemeModel:(AWEAwemeModel *)arg2 playerPlayTime:(double)arg3 canPlayTime:(double)arg4 totalTime:(double)arg5;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 didPauseDisplayingCellWithCurrentPlayingTime:(double)arg2;
- (void)detailTableViewController:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 model:(AWEAwemeModel *)arg4;
- (void)detailTableViewControllerVideoPlayerWillStartNextLoop:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewControllerVideoPlayerDidReadyForDisplay:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
- (void)detailTableViewControllerDidLoadFinish:(UIViewController<AWEAwemeDetailTableViewControllerProtocol> *)arg1;
@end

