//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSIndexPath, UICollectionView, UICollectionViewCell;

@protocol AWEDCFeedFeedClientShowVisibleCheckProtocol <NSObject>
- (_Bool)cellIsVisible:(UICollectionView *)arg1 cell:(UICollectionViewCell *)arg2 indexPath:(NSIndexPath *)arg3;
@end

