//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEPlayVideoDelegate-Protocol.h>
#import <AwemeCore/IESVideoPlayerDelegate-Protocol.h>

@class NSError, NSString;
@protocol AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, IESVideoPlayerProtocol;

@protocol AWEDPlayerDelegate <IESVideoPlayerDelegate, AWEPlayVideoDelegate>

@optional
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 didUpdateVRHeadPoseWithYaw:(double)arg2 pitch:(double)arg3 roll:(double)arg4;
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangeStallState:(long long)arg2;
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 playbackFailedWithError:(NSError *)arg2;
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 downloadProgressWithKey:(NSString *)arg2 videoId:(NSString *)arg3 cacheSize:(long long)arg4 mediaSize:(long long)arg5;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didUpdateVRHeadPoseWithYaw:(double)arg2 pitch:(double)arg3 roll:(double)arg4;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangeStallState:(long long)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 playbackFailedWithError:(NSError *)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 downloadProgressWithKey:(NSString *)arg2 videoId:(NSString *)arg3 cacheSize:(long long)arg4 mediaSize:(long long)arg5;
- (long long)scaleModeForVideoWithPlayer:(id <IESVideoPlayerProtocol>)arg1;
- (double)customTimerPeriodicWithPlayer:(id <IESVideoPlayerProtocol>)arg1;
- (void)iesPlayer:(id <IESVideoPlayerProtocol>)arg1 willInStallAction:(_Bool)arg2;
@end

