//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEDCFeedPageContext, NSArray, NSDictionary, NSError;
@protocol AWEDCFeedListResponseProtocol;

@protocol AWEDCFeedDataProcessorProtocol <NSObject>

@optional
- (void)onDidCancelRequestWithRequestType:(unsigned long long)arg1;
- (void)onDidEndCompletionWithRequestType:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2 error:(NSError *)arg3;
- (void)onDidEndProcessWithRequestType:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2 error:(NSError *)arg3;
- (void)asyncProcessDataArrayWithRequestType:(unsigned long long)arg1 modelArray:(NSArray *)arg2 args:(NSDictionary *)arg3 completion:(void (^)(NSArray *))arg4;
- (NSArray *)syncProcessDataArrayWithRequestType:(unsigned long long)arg1 modelArray:(NSArray *)arg2 args:(NSDictionary *)arg3;
- (NSArray *)filterDataArrayWithRequestType:(unsigned long long)arg1 dataArray:(NSArray *)arg2 args:(NSDictionary *)arg3;
- (void)onWillBeginProcessWithRequestType:(unsigned long long)arg1 response:(id <AWEDCFeedListResponseProtocol>)arg2 error:(NSError *)arg3;
- (void)onWillBeginRequestDataWithRequestType:(unsigned long long)arg1;
- (void)setupWithContext:(AWEDCFeedPageContext *)arg1;
@end

