//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray;

@protocol AWEDCFeedDislikeProtocol <NSObject>

@optional
- (void)didSelectDislikeWithModels:(NSArray *)arg1;
@end

