//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEDCFeedDislikeProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventActionProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventAwemeDetailDelegate-Protocol.h>
#import <AwemeCore/AWEDCFeedEventChunkProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventCommonLynxProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventDataProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventElementLifeCycleProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventFullPageFeedDelegate-Protocol.h>
#import <AwemeCore/AWEDCFeedEventLifecycleProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventPlayProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventRouterProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventScrollViewProtocol-Protocol.h>
#import <AwemeCore/AWEDCFeedEventTransitionProtocol-Protocol.h>

@protocol AWEDCFeedEventDispatcherProtocol <AWEDCFeedEventRouterProtocol, AWEDCFeedEventLifecycleProtocol, AWEDCFeedEventScrollViewProtocol, AWEDCFeedEventPlayProtocol, AWEDCFeedEventDataProtocol, AWEDCFeedDislikeProtocol, AWEDCFeedEventTransitionProtocol, AWEDCFeedEventActionProtocol, AWEDCFeedEventAwemeDetailDelegate, AWEDCFeedEventFullPageFeedDelegate, AWEDCFeedEventCommonLynxProtocol, AWEDCFeedEventChunkProtocol, AWEDCFeedEventElementLifeCycleProtocol>
@end

