//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol UIViewControllerTransitionCoordinator;

@protocol AWEDCFeedEventTransitionProtocol <NSObject>

@optional
- (void)containerViewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator>)arg2;
@end

