//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class NSURL;

@protocol AWEECLiveActivitySwiftAdaptorProtocol <HTSService>
- (_Bool)canHandle:(NSURL *)arg1;

@optional
- (void)registerCreateTakeOutLiveActivityXBridge;
@end

