//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMStickerModel, UIView;
@protocol AWEIMEmoticonContainerViewProtocol;

@protocol AWEEmoticonKeyboardHelperDelegate <NSObject>
- (void)emoticonKeyboard:(UIView<AWEIMEmoticonContainerViewProtocol> *)arg1 didSelectSticker:(AWEIMStickerModel *)arg2 selectedView:(UIView *)arg3;
- (void)emoticonKeyboardDidTapSearchItem:(UIView<AWEIMEmoticonContainerViewProtocol> *)arg1;
- (void)emoticonKeyboardSendButtonClicked:(UIView<AWEIMEmoticonContainerViewProtocol> *)arg1;

@optional
- (_Bool)needUpdateTypingAttributes;
@end

