//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol AWEECMarkAnchorCommentListDataLoaderProtocol <NSObject>
- (void)loadMoreCommentsWithParams:(NSDictionary *)arg1 completion:(void (^)(NSArray *, NSError *, _Bool))arg2;
- (void)fetchCommentsWithParams:(NSDictionary *)arg1 completion:(void (^)(NSArray *, NSError *, _Bool))arg2;
@end

