//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol AWEFormatLiveOuterRoomTransitionProtocol
- (void)willLeaveInnerRoomWithForce:(_Bool)arg1 reason:(NSString *)arg2 needRemoveFeed:(_Bool)arg3;
@end

