//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEFormatShareParams;

@protocol AWEFormatShareService <HTSService>
- (void)showPanelWithParams:(AWEFormatShareParams *)arg1;
@end

