//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol AWEFeedSafetyCheckResultMessage <NSObject>

@optional
- (void)didSafetyCheckRequestFinishWithUnsafeItemIDs:(NSArray *)arg1 referString:(NSString *)arg2;
@end

