//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEFeedTemplateAnchorViewDelegate <NSObject>
- (void)updateElementViewLayout;
- (void)anchorViewReset;
- (_Bool)shouldBusinessInvoke;
- (void)didShowDoubleLineStyleAnchor;
- (void)willShowDoubleLineStyleWithType:(unsigned long long)arg1;
@end

