//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSNumber, NSString;

@protocol AWEFeedRelatedVideoCardAIParseInfoViewDelegate <NSObject>
- (void)didCloseWithMethod:(NSString *)arg1;
- (void)didClickWithMethod:(NSString *)arg1;
- (void)didTapChapterWithTimestamp:(NSNumber *)arg1;
- (void)updateElementUI;
@end

