//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWERouterViewControllerProtocol-Protocol.h>

@class UIScrollView;

@protocol AWEFlowBotMessageViewControllerProtocol <AWERouterViewControllerProtocol>
- (void)setNaviExpandAction:(void (^)(void))arg1;
- (void)setNaviBackAction:(void (^)(void))arg1;
- (UIScrollView *)getScrollView;
@end

