//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEFullPageFeedPageModeSensitiveComponentProtocol <NSObject>

@optional
- (void)executePageModeChangeAnimationAfterHeaderHeightUpdate:(unsigned long long)arg1;
- (void)executePageModeChangeAnimation:(unsigned long long)arg1;
- (double)getDeltaHeightWhenPageModeChange:(unsigned long long)arg1;
- (void)onPageModeDidChage:(unsigned long long)arg1;
- (void)onPageModeWillChange:(unsigned long long)arg1;
@end

