//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWECodeGenCommonAnchorBasicInfoModel, AWEPageContext, NSDictionary, NSString, UIView;
@protocol AWEAwemePlayInteractionPresenterMethodDelegate><AWEAwemePlayInteractionPanelDelegate><AWEAwemePlayInteractionCommerceDelegate><AWEAwemePlayInteractionUIDisplayDelegate><AWEAwemePlayInteractionUpdateDelegate><AWEPlayInteractionViewControllerProtocol, AWEFeedAnchorBaseConfigProtocol, AWEFeedTemplateAnchorViewProtocol><AWEFeedTemplateAnchorViewPrivateProtocol;

@protocol AWEFeedTemplateAnchorBaseConfigProtocol <NSObject>
+ (_Bool)shouldShowAnchor:(AWEAwemeModel *)arg1;
+ (unsigned long long)templateAnchorType;
@property(copy, nonatomic) NSString *referString;
@property(nonatomic) __weak id <AWEAwemePlayInteractionPresenterMethodDelegate><AWEAwemePlayInteractionPanelDelegate><AWEAwemePlayInteractionCommerceDelegate><AWEAwemePlayInteractionUIDisplayDelegate><AWEAwemePlayInteractionUpdateDelegate><AWEPlayInteractionViewControllerProtocol> interactionViewController;
@property(nonatomic) __weak AWEPageContext *interactionContext;
@property(nonatomic) __weak id <AWEFeedAnchorBaseConfigProtocol> wrapperConfig;
@property(readonly, nonatomic) UIView<AWEFeedTemplateAnchorViewProtocol><AWEFeedTemplateAnchorViewPrivateProtocol> *anchorView;
@property(retain, nonatomic) AWECodeGenCommonAnchorBasicInfoModel *templateAnchorInfo;
@property(retain, nonatomic) AWEAwemeModel *model;
- (void)handleAnchorDetailPageDismissEventWithIdentifier:(id)arg1 trackMethodType:(long long)arg2;
- (void)handleAnchorDetailPageEnterEventWithIdentifier:(id)arg1 trackMethodType:(long long)arg2;
- (double)detailPageEnterTimeStamp;
- (void)trackerForDetailPageStay;
- (void)parentViewForAnchorContainerWillShowOnScreen;
- (NSDictionary *)paramsForTemplateAnchorViewTransfer;
- (NSDictionary *)trackerCommonParamsForTemplateAnchor;
- (NSDictionary *)trackerParamsForTemplateAnchorClick;
- (NSDictionary *)trackerParamsForTemplateAnchorShow;
- (_Bool)shouldBusinessInvoke;
- (void)didShowDoubleLineStyleAnchor;
- (void)willShowDoubleLineStyleWithType:(unsigned long long)arg1;
- (void)handlerTemplateAnchorViewClicked;
- (void)anchorViewWillShowOnSuperview;
- (void)updateWithAwemeModel:(AWEAwemeModel *)arg1 needPerformOnDisplay:(_Bool)arg2;
- (UIView<AWEFeedTemplateAnchorViewProtocol><AWEFeedTemplateAnchorViewPrivateProtocol> *)getAnchorViewWithModel:(AWEAwemeModel *)arg1;
- (void)addObservers;
- (void)anchorConfigReset;
- (void)anchorViewReset;
@end

