//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol AWEFullPageFeedDataContextProtocol <NSObject>
@property(nonatomic) unsigned long long sliderPlayMode;
@property(nonatomic, readonly) NSDictionary *logExtraDict;
@property(nonatomic, readonly) unsigned long long initialPageMode;
@property(nonatomic) unsigned long long currentPageMode;
@end

