//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol AWEFamiliarSettingsSubscriber <NSObject>

@optional
+ (void)updateFamiliarSettings:(NSDictionary *)arg1 fromRequest:(_Bool)arg2;
- (void)updateFamiliarSettings:(NSDictionary *)arg1 fromRequest:(_Bool)arg2;
@end

