//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, UIView, UIViewController;
@protocol AFDRichContentContainerViewControllerProtocol, AWEPlayVideoViewControllerProtocol;

@protocol AWEFeedAlbumPanelTransitionInnerContextProvider <NSObject>
- (NSArray *)getPendantViewArray;
- (void)switchPanelToTransparent:(_Bool)arg1;
- (double)panelHeight;
- (UIView *)progressBarView;
- (long long)progressBarType;
- (void)syncAudioController:(UIViewController<AWEPlayVideoViewControllerProtocol> *)arg1;
- (UIViewController<AWEPlayVideoViewControllerProtocol> *)audioController;
- (UIViewController<AFDRichContentContainerViewControllerProtocol> *)richContentContainer;
- (void)onAlbumPanelTransitionDidEnd:(unsigned long long)arg1 success:(_Bool)arg2;
- (void)onAlbumPanelTransitionWillBegin:(unsigned long long)arg1;
@end

