//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEShellViewControllerProtocol-Protocol.h>

@class NSString;

@protocol AWEFullPageFeedControllerProtocol <AWEShellViewControllerProtocol>
- (NSString *)itemID;
- (NSString *)enterFrom;
@end

