//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEReferenceTrackable-Protocol.h>

@class AWEAwemeModel, NSArray, NSDictionary, NSString, UIImage, UIPanGestureRecognizer, UIViewController;
@protocol AWEAwemeBizPlayVideoProtocol, AWEPlayInteractionViewControllerProtocol;

@protocol AWEFeedTabItemViewControllerProtocol <AWEReferenceTrackable>
- (void)pauseWithAnimation;
- (void)setScrollEnabled:(_Bool)arg1;
- (_Bool)canRefresh;
- (_Bool)currentTabIsTop;
- (void)animatedRefreshWithCompletion:(void (^)(void))arg1;
- (void)reload;
- (void)pause;
- (void)stop;
- (void)play;

@optional
- (void)updateUIWithLiveExsit:(_Bool)arg1;
- (void)setLoadingCenterOffset:(struct CGPoint)arg1;
- (void)configMultiTabParams:(NSDictionary *)arg1;
- (void)channelLandingTabWithParams:(NSDictionary *)arg1;
- (void)setTopbarFrame:(struct CGRect)arg1;
- (void)feedRefreshWithType:(long long)arg1 completion:(void (^)(void))arg2;
- (void)loadMoreFeed;
- (double)topPanDownFreeDistance;
- (UIViewController<AWEPlayInteractionViewControllerProtocol> *)currentInteractionController;
- (UIViewController<AWEAwemeBizPlayVideoProtocol> *)currentVideoController;
@property(nonatomic, readonly) long long type;
- (void)autoOpenGoodsInnerFeed;
- (_Bool)showRefreshAnimation;
- (void)onFamilarAwemeInsertBelowWithItemID:(NSString *)arg1 isFromUserProfile:(_Bool)arg2;
- (void)onAwemeExchange:(NSString *)arg1;
- (_Bool)onSegmentRepeatedClickWithIndex:(unsigned long long)arg1;
- (_Bool)slidingScrollViewShouldScrollWithPan:(UIPanGestureRecognizer *)arg1;
- (void)didScrollToConcernWillShowGuideIfNeeded:(_Bool)arg1;
- (void)setEnterTrackerInfo:(NSDictionary *)arg1;
- (void)setPreviousPageValue:(NSString *)arg1;
- (NSArray *)recentTenAwemeID;
- (NSDictionary *)currentAwemeInfo;
- (NSString *)currentAwemeAuthorID;
- (NSString *)currentAwemeID;
- (AWEAwemeModel *)currentAweme;
- (void)setRefreshMethod:(NSString *)arg1;
- (_Bool)isPlaying;
- (_Bool)isShowingFollowGroupPanel;
- (_Bool)isPlayingFirstStory;
- (_Bool)isShowingDislike;
- (_Bool)canMallPullSecondFloor;
- (_Bool)isVideoRelatedPanelShowing;
- (_Bool)isAITextPanelShowing;
- (_Bool)isLikeUserPanelShowing;
- (_Bool)isRelatedVideoPanelShowing;
- (_Bool)isCommentPanelShowing;
- (void)slientRefreshWithCompletion:(void (^)(void))arg1;
- (void)setAccessoriesHidden:(_Bool)arg1;
- (unsigned long long)maxReachedIndex;
- (void)reloadWithCompletionBlock:(void (^)(void))arg1;
- (void)setChannelIndex:(long long)arg1;
- (long long)channelIndex;
- (void)dragCancellation;
- (void)dragWithProgress:(double)arg1;
- (double)getPlayTimeStamp;
- (double)currentPlayingTime;
- (void)setPlayerAudioDevice:(unsigned long long)arg1;
- (void)setVolume:(float)arg1;
- (void)resetPauseIcon;
- (void)setPauseBySingleClick:(_Bool)arg1;
- (_Bool)pauseBySingleClick;
- (void)pauseWithAnimationUsingCustomPauseIcon:(UIImage *)arg1;
- (void)playWithAnimation;
- (void)willSetPureModeBlock:(_Bool)arg1;
- (void)setPureMode:(_Bool)arg1;
- (void)onAwemeToNextVideoUnderReportWithObjectID:(NSString *)arg1;
- (void)onAwemeDeleted:(NSString *)arg1 isLiveFinish:(_Bool)arg2 isDislike:(_Bool)arg3 isLiveEnded:(_Bool)arg4;
- (void)onAwemeDeleted:(NSString *)arg1 isDislike:(_Bool)arg2 silentlyDelete:(_Bool)arg3;
- (void)onAwemeDeleted:(NSString *)arg1 isLiveFinish:(_Bool)arg2 isDislike:(_Bool)arg3;
- (void)onAwemeDeleted:(NSString *)arg1 isDislike:(_Bool)arg2;
- (void)onAwemeMarkDislikeCanWithdraw:(NSString *)arg1;
- (void)holdStopPlayer;
- (void)seekPlayTimeWithItemID:(NSString *)arg1;
- (void)cancelRefresh;
- (void)reloadForceRequest;
@end

