//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEFormatXPlayQueueConfig, NSDictionary, NSError, NSString;
@protocol AWEFormatXPlayInterface;

@protocol AWEFormatXPlayItemDelegate <NSObject>
- (void)didFinishQueueInfo:(AWEFormatXPlayQueueConfig *)arg1;
- (void)didUpdateQueueInfo:(AWEFormatXPlayQueueConfig *)arg1;
- (_Bool)canJoinQueue:(AWEFormatXPlayQueueConfig *)arg1;
- (void)needQueue;
- (void)didReceivePodMiddlewareMessage:(NSDictionary *)arg1;
- (void)didReceiveRTCCustomMessageWithString:(NSString *)arg1;
- (void)itemLoadFailed:(NSDictionary *)arg1 error:(NSError *)arg2 logId:(NSString *)arg3;
- (void)itemLoadSuccess:(NSString *)arg1;
- (void)playItem:(id <AWEFormatXPlayInterface>)arg1 playStatusDidUpdated:(long long)arg2 info:(NSDictionary *)arg3;
- (void)playItem:(id <AWEFormatXPlayInterface>)arg1 preloadDidSucceed:(NSDictionary *)arg2;
- (void)playItem:(id <AWEFormatXPlayInterface>)arg1 preloadDidFailed:(NSDictionary *)arg2;
@end

