//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWEAwemeModel;

@protocol AWEFormatLiveFeedViewControllerProtocol
- (void)reset;
- (void)pause;
- (void)vcPrepareForDisplay;
- (void)vcEndDisplay;
- (void)play;
- (void)preloadWithModel:(AWEAwemeModel *)arg1;
- (void)updateModelWithModel:(AWEAwemeModel *)arg1;
- (void)vcWillDisplay;
@end

