//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWEGrowingTextView, NSArray, NSString, NSTextAttachment;
@protocol UITextDragRequest;

@protocol AWEGrowingTextViewDelegate

@optional
- (NSArray *)growingTextView:(AWEGrowingTextView *)arg1 itemsForDrag:(id <UITextDragRequest>)arg2;
- (_Bool)growingTextView:(AWEGrowingTextView *)arg1 shouldInteractWithTextAttachment:(NSTextAttachment *)arg2 inRange:(struct _NSRange)arg3 interaction:(long long)arg4;
- (_Bool)growingTextViewShouldReturn:(AWEGrowingTextView *)arg1;
- (void)growingTextViewDidChangeSelection:(AWEGrowingTextView *)arg1;
- (void)growingTextView:(AWEGrowingTextView *)arg1 didChangeHeight:(float)arg2;
- (void)growingTextView:(AWEGrowingTextView *)arg1 willChangeHeight:(float)arg2;
- (void)growingTextViewDidChange:(AWEGrowingTextView *)arg1;
- (_Bool)growingTextView:(AWEGrowingTextView *)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(NSString *)arg3;
- (void)growingTextViewDidEndEditing:(AWEGrowingTextView *)arg1;
- (void)growingTextViewDidBeginEditing:(AWEGrowingTextView *)arg1;
- (_Bool)growingTextViewShouldEndEditing:(AWEGrowingTextView *)arg1;
- (_Bool)growingTextViewShouldBeginEditing:(AWEGrowingTextView *)arg1;
@end

