//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, UIPanGestureRecognizer, UIView;

@protocol AWEHangoutTopTabContainerProtocol <NSObject>

@optional
- (void)channelTopTabDidSelect;
- (void)preparePlaceHolder;
- (void)pulldownRefreshGestureRecognizerEnd:(UIPanGestureRecognizer *)arg1;
- (void)pulldownRefreshGestureRecognizerBegin:(UIPanGestureRecognizer *)arg1;
- (void)didLandingWithParams:(NSDictionary *)arg1;
- (_Bool)canLandingWithParams:(NSDictionary *)arg1;
- (void)didLeaveWithParams:(NSDictionary *)arg1;
- (void)didEnterWithParams:(NSDictionary *)arg1;
- (UIView *)navBarSearchIconView;
- (void)holdChannelController:(id)arg1;
@end

