//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSObject;
@protocol AWEHPListKitItemControllerContext;

@protocol AWEHPListKitItemControllerProtocol <NSObject>
@property(readonly, nonatomic) NSObject<AWEHPListKitItemControllerContext> *hpListKitItemContext;
- (void)reloadWithContext:(NSObject<AWEHPListKitItemControllerContext> *)arg1 extraData:(NSDictionary *)arg2;
- (_Bool)canReloadWithContext:(NSObject<AWEHPListKitItemControllerContext> *)arg1 extraData:(NSDictionary *)arg2;
- (id)initWithContext:(NSObject<AWEHPListKitItemControllerContext> *)arg1 extraData:(NSDictionary *)arg2;

@optional
- (double)cellViewHeight;
- (_Bool)needLoadHPController;
- (void)hpListKitViewDidDisappear;
- (void)hpListKitViewWillDisappear;
- (void)hpListKitViewDidAppear;
- (void)hpListKitViewWillAppear;
@end

