//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEIMSelectableContextProtocol;

@protocol AWEIMSelectableBasicViewModelProtocol <NSObject>
@property(nonatomic) __weak id <AWEIMSelectableContextProtocol> selectableContext;

@optional
- (void)viewControllerDidDismiss;
- (void)themeReload;
- (void)viewDidLoad;
@end

