//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMShareContactListConfig, AWEIMShareContactListTrackInfo, NSArray, UIScrollView, UIView;
@protocol AWEIMShareModelProtocol;

@protocol AWEIMShareContactListProtocol <NSObject>
- (_Bool)isInFirstScreenForIndex:(long long)arg1;
- (void)openMorePanelWithPosition:(unsigned long long)arg1;
- (void)openMorePanel;
- (void)handleTapOutsideOfPanel;
- (void)updateAdditionTextPreviewImage;
- (void)updateSelectState:(_Bool)arg1 withShareModel:(id <AWEIMShareModelProtocol>)arg2;
- (NSArray *)interactingGestures;
- (double)height;
- (UIScrollView *)verticalScrollView;
- (UIView *)listView;
@property(nonatomic, readonly) AWEIMShareContactListTrackInfo *trackInfo;
@property(nonatomic, readonly) unsigned long long state;
@property(nonatomic, readonly) AWEIMShareContactListConfig *config;
@end

