//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMShareAdditionTextViewConfig, AWEIMShareAdditionTextViewTrackInfo, AWEShareEmoticonModel, NSArray, NSString;
@protocol AWEIMShareAdditionTextViewDelegate, AWEIMShareAdditionTextViewUIDelegate;

@protocol AWEIMShareAdditionTextViewProtocol <NSObject>
- (_Bool)canShowEmoticonBtn;
- (void)setEnterFrom:(NSString *)arg1;
- (AWEShareEmoticonModel *)currentSelectedEmoticon;
- (double)minHeight;
- (void)updateWithConfig:(AWEIMShareAdditionTextViewConfig *)arg1;
- (void)updatePreviewImageWithHandler:(void (^)(UIImageView *))arg1;
- (void)updateButtonLayout;
- (void)updateButtons:(NSArray *)arg1;
- (void)endEditing;
- (void)addDelegate:(id <AWEIMShareAdditionTextViewDelegate>)arg1;
@property(nonatomic) __weak id <AWEIMShareAdditionTextViewUIDelegate> uiDelegate;
@property(nonatomic, readonly) NSArray *ignoreDismissArea;
@property(nonatomic, readonly) NSArray *conflictGestures;
@property(nonatomic, readonly) AWEIMShareAdditionTextViewTrackInfo *trackInfo;
@property(nonatomic, readonly) unsigned long long currentInputMode;
@property(nonatomic, copy) NSString *currentText;
@end

