//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AWEIMSelectableContextProtocol <NSObject>
- (void)dismiss;
- (void)updatePageStatus:(long long)arg1;
@property(nonatomic) _Bool canShowInnerPush;
@property(nonatomic, copy) NSString *toastText;
@property(nonatomic, readonly) long long pageStatus;
@end

