//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEImageTextCellShrinkComponentProtocol <NSObject>
- (void)updateShrinkState:(_Bool)arg1 insets:(struct UIEdgeInsets)arg2 animated:(_Bool)arg3 animationDuration:(double)arg4;
- (struct AWEImageTextCellShrinkState)getShrinkState;
@end

