//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMMessage, NSArray;
@protocol AWEIMMessageListComponentCenter, AWEIMMsgRefreshMessageProtocol;

@protocol AWEIMMsgRefreshHandlerProtocol <NSObject>
+ (_Bool)supportRefresh;
+ (long long)getRefreshHandlerType;
@property(nonatomic) __weak id <AWEIMMessageListComponentCenter> componentCenter;
@property(nonatomic) unsigned long long requestInterval;
- (void)refrshResourceStateFor:(NSArray *)arg1 forViewModels:(NSArray *)arg2 strategy:(unsigned long long)arg3;
- (_Bool)supportRefreshMessage:(AWEIMMessage *)arg1;
- (_Bool)supportRefreshStrategy:(unsigned long long)arg1;
- (id)new;
- (id)init;
- (id)initWithComponentCenter:(id <AWEIMMessageListComponentCenter>)arg1;

@optional
- (_Bool)isRequestIntervalNotReached:(id <AWEIMMsgRefreshMessageProtocol>)arg1;
@end

