//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary, UIGestureRecognizer, UITableViewCell, UIView;

@protocol AWEIMAwemeMediaDisplayControllerProtocol <NSObject>
- (UIView *)transitionEndView;
- (_Bool)transitionEndViewAvailable;
- (void)play;
- (void)cellDidEndDisplay:(UITableViewCell *)arg1;
@property(nonatomic, copy) CDUnknownBlockType innerScrollViewDidSingleTap;
@property(nonatomic, retain) AWEAwemeModel *awemeModel;
@property(nonatomic, copy) CDUnknownBlockType innerScrollViewEndDecelerating;
@property(nonatomic, copy) CDUnknownBlockType pureModeBlock;

@optional
- (_Bool)longPressModuleViewEnable;
- (void)showLongPressPanelWithExtraParams:(NSDictionary *)arg1;
- (_Bool)shouldShowDownloadBtnOnNavibar;
- (void)onPressDownLoad;
- (_Bool)tableviewGestureRecognizer:(UIGestureRecognizer *)arg1 shouldRecognizeSimultaneouslyIfNeeded:(UIGestureRecognizer *)arg2;
- (_Bool)tableviewGestureRecognizerShouldBegin:(UIGestureRecognizer *)arg1;
@end

