//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEIMSelectableBasicViewModelProtocol-Protocol.h>

@class NSString;

@protocol AWEIMSelectablePageViewModelProtocol <AWEIMSelectableBasicViewModelProtocol>
@property(nonatomic, copy) NSString *failButtonText;
@property(nonatomic, copy) NSString *failDescriptionText;
@property(nonatomic, copy) NSString *failTitleText;
@property(nonatomic, copy) NSString *emptyTitleText;

@optional
- (void)emptyPagePrimaryButtonTapped;
- (struct UIEdgeInsets)emptyPageEdgeInsets;
@end

