//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEImageAlbumImageModel;

@protocol AWEImageTextRefinedLayoutComponentProtocol <NSObject>
- (void)updateAlbumContentModeLayout;
- (void)updateCurrentImageContentViewLayout;
- (double)getImageContentTopInset;
- (struct CGRect)getTemporaryImageViewRectWithMinWHRatio;
- (void)clearImageContentViewTopInset;
- (void)updateImageContentViewTopInsetWithLeftInteractionMinY:(double)arg1 authorElementMinY:(double)arg2;
- (unsigned long long)getRefinedImageContentMode:(AWEImageAlbumImageModel *)arg1;
- (void)setImageContentInsets:(struct UIEdgeInsets)arg1 animated:(_Bool)arg2 duration:(double)arg3;
- (struct UIEdgeInsets)getImageContentInsets;
@property(nonatomic, readonly) _Bool enableRefinedImageLayout;
@end

