//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMMessage, AWEShareContext, NSArray, NSDictionary, NSString;
@protocol AWEIMShareModelProtocol;

@protocol AWEIMIncentieShareService_Data <NSObject>
- (NSString *)incentiveShareDebugInfo;
- (_Bool)feedShareElementFeatureEnable;
- (NSArray * (^)(NSArray *, AWEIMFetchShareListDatasource *))shareSourceDecorator;
- (void)receivedLocalShareResultWithContainer:(NSArray *)arg1 shareResult:(NSDictionary *)arg2;
- (NSDictionary *)incentiveAdditionSyncedExtWithMessage:(AWEIMMessage *)arg1;
- (_Bool)bindSyncedExtToMessageIfNeedWithContext:(AWEShareContext *)arg1 shareModel:(id <AWEIMShareModelProtocol>)arg2 message:(AWEIMMessage *)arg3;
- (void)handleReceiveLaunchData:(NSDictionary *)arg1;
@end

