//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPlayerDidPlayBackActionContext;
@protocol IESVideoPlayerProtocol;

@protocol AWEIncentivePlayerMessage <NSObject>
- (void)onPlayer:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2 context:(AWEPlayerDidPlayBackActionContext *)arg3;
@end

