//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMConversationInfoModel;

@protocol AWEIMShareContactListViewControllerDelegate <NSObject>

@optional
- (void)selectGroupSessionCompleteWithNothing;
- (void)groupSelected:(AWEIMConversationInfoModel *)arg1;
@end

