//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEIMVmojiManager;

@protocol AWEIMVmojiManagerDelegate <NSObject>
- (void)vmojiManagerDidUpdateVirtualAvatar:(id <AWEIMVmojiManager>)arg1;
@end

