//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, UIView;
@protocol AWEIMShareAdditionTextViewProtocol, AWEIMShareContactListProtocol, AWEIMShareModelProtocol;

@protocol AWEIMShareContactListDelegate <NSObject>
- (void)shareContactList:(id <AWEIMShareContactListProtocol>)arg1 hideContainerListWithCompletion:(void (^)(void))arg2 atScene:(unsigned long long)arg3;

@optional
- (void)shareContactList:(id <AWEIMShareContactListProtocol>)arg1 additionTextViewDismissed:(UIView<AWEIMShareAdditionTextViewProtocol> *)arg2;
- (UIView<AWEIMShareAdditionTextViewProtocol> *)createAdditionTextAndAppendToViewHierarchyWithShareContactList:(id <AWEIMShareContactListProtocol>)arg1;
- (NSDictionary *)trackCommonParamsWithShareContactList:(id <AWEIMShareContactListProtocol>)arg1;
- (void)shareContactList:(id <AWEIMShareContactListProtocol>)arg1 didSelectRecentShareWithShareModels:(NSArray *)arg2 atIndex:(long long)arg3;
- (_Bool)shareContactList:(id <AWEIMShareContactListProtocol>)arg1 didSelectWithShareModel:(id <AWEIMShareModelProtocol>)arg2 atIndex:(long long)arg3 currentSelectState:(_Bool)arg4;
- (void)shareContactList:(id <AWEIMShareContactListProtocol>)arg1 stateDidChangeFromState:(unsigned long long)arg2 toState:(unsigned long long)arg3;
- (void)updateUIWithShareContactList:(id <AWEIMShareContactListProtocol>)arg1;
@end

