//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UICollectionViewCell;

@protocol AWEImageTextSectionControllerProtocol <NSObject>
- (UICollectionViewCell *)currentCell;
@property(nonatomic, readonly) _Bool enableBreakUpTask;
@end

