//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEIMSelectableBasicViewModelProtocol-Protocol.h>

@protocol AWEIMSelectableCommonViewModelProtocol <AWEIMSelectableBasicViewModelProtocol>
- (struct CGSize)preferredContentSize;
@end

