//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEIMIncentiveShareSnackBarReflowConfig, AWEShareContext, NSArray, NSString, UIView;
@protocol AWEIMShareModelProtocol;

@protocol AWEIMIncentiveShareService_SharePanel <NSObject>
- (void)resetFeedElementRedPacketWithWholeView:(UIView *)arg1 imageView:(UIView *)arg2 labelView:(UIView *)arg3 awemeModel:(AWEAwemeModel *)arg4;
- (void)playFeedElementRedPacketAppearAnimateWithWholeView:(UIView *)arg1 imageView:(UIView *)arg2 labelView:(UIView *)arg3 awemeModel:(AWEAwemeModel *)arg4;
- (void)playRedPacketAnimateIfNeededWithView:(UIView *)arg1;
- (AWEIMIncentiveShareSnackBarReflowConfig *)snackBarContextWithShareList:(NSArray *)arg1 shareContext:(AWEShareContext *)arg2;
- (NSString *)sharePanelSubtitleWithModel:(id <AWEIMShareModelProtocol>)arg1 context:(AWEShareContext *)arg2;
- (_Bool)shouldShowSharePanelRedPacketWithModel:(id <AWEIMShareModelProtocol>)arg1;
- (NSArray *)batchGetIncentiveShareListWithModelList:(NSArray *)arg1;
- (_Bool)enableIncentiveShareWithContext:(AWEShareContext *)arg1;
@end

