//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMMessage, NSString;

@protocol AWEIMVoipFinishMessage <NSObject>
- (void)handleVoipFinishMessage:(AWEIMMessage *)arg1 withConversationID:(NSString *)arg2 timestamp:(double)arg3;
@end

