//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEImageTextPinchZoomComponentProtocol <NSObject>
- (void)zoomCurrentImageToRatioRect:(struct CGRect)arg1 scale:(double)arg2 animated:(_Bool)arg3;
- (void)trackPinchZoomWithZoomType:(long long)arg1;
- (void)setCurrentImageZoomWrapperWithInfo:(id)arg1 animated:(_Bool)arg2 completion:(void (^)(void))arg3;
- (id)getCurrentImageZoomInfoWrapper;
@end

