//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEIMSelectableBasicViewModelProtocol-Protocol.h>

@class NSAttributedString, NSString;

@protocol AWEIMSelectableTitleViewModelProtocol <AWEIMSelectableBasicViewModelProtocol>
@property(nonatomic, copy) NSAttributedString *subtitleAttributedText;
@property(nonatomic, copy) NSString *subtitleText;
@property(nonatomic, copy) NSAttributedString *titleAttributedText;
@property(nonatomic, copy) NSString *titleText;
@property(nonatomic) double titleBarHeight;

@optional
- (void)didClickSubtitleLabel;
- (void)didClickTitleLabel;
@end

