//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEBaseListSectionController, UICollectionViewCell, UIView;

@protocol AWEImageTextLifeCycleProtocol <NSObject>

@optional
- (void)zoomScrollViewDidEndZooming;
- (void)zoomScrollViewWillBeginZooming;
- (void)updateInnerSlidableIndex:(long long)arg1 newIndex:(long long)arg2;
- (void)didSetupPageContext;
- (void)sectionControllerDidEndDisplaying:(AWEBaseListSectionController *)arg1;
- (void)configOverlayView:(UIView *)arg1;
- (void)viewControllerWillDisappear:(_Bool)arg1 isBeingDismissed:(_Bool)arg2 isMovingFromParentViewController:(_Bool)arg3;
- (void)viewControllerDidAppear:(_Bool)arg1;
- (void)sectionWillDisplayCell:(UICollectionViewCell *)arg1 index:(long long)arg2 model:(id)arg3;
- (void)didBindSectionViewModel;
- (void)configCell:(UICollectionViewCell *)arg1 index:(long long)arg2 model:(id)arg3;
@end

