//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEIMIncentieShareService_Data-Protocol.h>
#import <AwemeCore/AWEIMIncentiveShareService_SharePanel-Protocol.h>
#import <AwemeCore/HTSService-Protocol.h>

@protocol AWEIMIncentiveShareService <HTSService, AWEIMIncentiveShareService_SharePanel, AWEIMIncentieShareService_Data>
@end

