//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol BDMultiContentVideoPlayerProtocol;

@protocol AWEImageTextVideoControllerDelegate <NSObject>

@optional
- (void)pauseByClick:(_Bool)arg1;
- (void)playByClick:(_Bool)arg1;
- (void)prepareForPlayingIfNeeded;
- (void)createdVideoController:(id <BDMultiContentVideoPlayerProtocol>)arg1;
@end

