//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;
@protocol AWEInteractionElementPopoverContextProtocol;

@protocol AWEInteractionElementPopoverProtocol <NSObject>
- (void)remove;
- (void)showWithContext:(id <AWEInteractionElementPopoverContextProtocol>)arg1 target:(UIView *)arg2 alignView:(UIView *)arg3 interactionContainer:(UIView *)arg4 didGetFocus:(void (^)(void))arg5 didLoseFocus:(void (^)(void))arg6 didDismiss:(void (^)(void))arg7;
@end

