//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEIMSelectableBasicViewModelProtocol-Protocol.h>

@class NSArray, NSIndexPath, NSString;

@protocol AWEIMSelectableListViewModelProtocol <AWEIMSelectableBasicViewModelProtocol>
- (void)didClickConfirmButton;
@property(nonatomic, copy) NSString *selectLimitToastText;
@property(nonatomic) long long selectLimit;
@property(nonatomic, copy) NSString *confirmText;
@property(nonatomic, copy) NSArray *userSelectedViewModels;
@property(nonatomic, copy) NSArray *sectionViewModels;

@optional
- (void)didSelectItemAtIndexPath:(NSIndexPath *)arg1;
- (void)lodaMoreData;
@end

