//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSDictionary, UIView;
@protocol InteractionElementPopoverCellCustomContentProtocol;

@protocol AWEInteractionElementPopoverDataProtocol <NSObject>
- (void)loadDataIfNeeded:(void (^)(void))arg1 releaseBlock:(void (^)(void))arg2;
- (void)configContentView:(UIView *)arg1 atIndex:(long long)arg2;
- (UIView *)elementContentView;
- (long long)dataCount;
@property(nonatomic, copy) NSDictionary *contextDict;
@property(nonatomic, retain) AWEAwemeModel *model;

@optional
- (void)eventOccurAtIndex:(long long)arg1 target:(UIView *)arg2 sourceView:(UIView *)arg3 containerView:(UIView *)arg4 eventType:(unsigned long long)arg5 completion:(void (^)(void))arg6;
- (struct CGSize)dataItemSize;
- (double)dataItemSpace;
- (UIView<InteractionElementPopoverCellCustomContentProtocol> *)elementCustomContentView;
- (void)configContentCustomView:(UIView<InteractionElementPopoverCellCustomContentProtocol> *)arg1 atIndex:(long long)arg2;
@end

