//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIView;
@protocol AWEIMEmoticonModelProtocol, AWEIMEmoticonThemeModelProtocol;

@protocol AWEIMShareInputEmoticonToolBarViewDelegate <NSObject>

@optional
- (void)didSelectEmoticon:(id <AWEIMEmoticonModelProtocol>)arg1 belongToTheme:(id <AWEIMEmoticonThemeModelProtocol>)arg2 selectedView:(UIView *)arg3;
- (void)trackEmoticonWithEmoticonString:(NSString *)arg1 sessionType:(long long)arg2;
- (void)didClickedEmoticonControlButtonToStatus:(unsigned long long)arg1;
- (_Bool)canInsertEmoticonWithEmoticonString:(NSString *)arg1;
- (void)exceedingMaxLengthLimit;
- (long long)maxTextLength;
@end

