//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEAwemeModel, NSArray, NSDictionary, NSString, UIView;
@protocol AWEFollowShootChoosePopupDelegate, AWETopicShootButtonProtocol;

@protocol AWEKnowledgeModuleService <HTSService>
- (NSArray *)getTopicUserBehaviorRecordPublishContentSourceList;
- (NSArray *)getTopicUserBehaviorRecordRecentVideoPlayItemIdList;
- (UIView<AWETopicShootButtonProtocol> *)createTopicShootButtonWithStyleName:(NSString *)arg1;
- (void)onFinishCommentInputViewWillShowWithModel:(AWEAwemeModel *)arg1;
- (NSArray *)processEmoticonList:(NSArray *)arg1 model:(AWEAwemeModel *)arg2;
- (NSString *)ugcTopicSchemaMergeMaterialInfo:(NSString *)arg1 awemeModel:(AWEAwemeModel *)arg2;
- (NSString *)getTemplateFeatureList;
- (void)pitayaDataVerifyWith:(NSString *)arg1 params:(NSDictionary *)arg2;
- (_Bool)pitayaDataVerifyEnable;
- (_Bool)isFollowShootChoosePopupSchema:(NSString *)arg1;
- (void)setCurrentFollowShootChoosePopupDelegate:(id <AWEFollowShootChoosePopupDelegate>)arg1;
- (_Bool)isFollowShootCameraSchema:(NSString *)arg1;
- (Class)trackingManager;
@end

