//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AWEKnowledgeSceneProvider <NSObject>
- (void)checkPlayStateForSyncStateFromScene:(NSString *)arg1 toScene:(NSString *)arg2;
- (NSDictionary *)infoProviders;
@end

