//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEKnowledgeStateCardToken;
@protocol AWEKnowledgeSceneProvider;

@protocol AWEKnowledgePlayResultControlProtocol <NSObject>
- (id <AWEKnowledgeSceneProvider>)sceneProvider;
- (void)setPlayMode:(unsigned long long)arg1;
- (void)setUserScrolled:(_Bool)arg1;
- (AWEKnowledgeStateCardToken *)getCardToken;
- (void)pauseByResultHandlerWithAnimation:(_Bool)arg1;
- (void)playByResultHandlerWithAnimation:(_Bool)arg1;
- (void)setPlayControlByResultHandler:(_Bool)arg1;
@end

