//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWELeftSideBarBussinessTrackInfo;

@protocol AWELeftSideBarCommonProtocol <NSObject>

@optional
- (AWELeftSideBarBussinessTrackInfo *)bussinessTrackInfo;
- (void)leftSideBarPresenterOnCreate;
- (_Bool)needLoadPresenter;
- (void)onLeftSideBarClose;
- (void)onLeftSideBarOpen;
- (void)onLeftSideBarWillOpen;
@end

