//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel;

@protocol AWELandscapeCellManagerProtocol <NSObject>
- (Class)cellClassForModel:(AWEAwemeModel *)arg1;
- (void)registerCellClass:(Class)arg1 forType:(unsigned long long)arg2;
@end

