//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AWELeftSideBarEntranceViewClickProtocol <NSObject>

@optional
- (void)leftSideBarEntranceViewClickWithAmbienceIdentification:(NSString *)arg1;
- (_Bool)isInterceptClickWithAmbienceIdentification:(NSString *)arg1;
@end

