//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSCoding-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol AWELiteTimerTaskProtocol <NSObject, NSCoding>
- (void)didTaskStatusChange:(long long)arg1;
- (void)didTaskProgressUpdateWithRule:(NSString *)arg1;
- (double)totalTaskTime;
- (NSArray *)rules;
- (NSString *)taskID;
@property(nonatomic) double progress;

@optional
- (void)taskDidWaitedToCounting;
- (void)taskDidStartedCounting;
- (void)taskDidStoppedCounting;
- (_Bool)checkExtraCondition:(NSString *)arg1;
- (void)hasReachedLimit:(NSString *)arg1;
- (_Bool)needLocalStorage;
- (double)timeInterval;
@end

