//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWELivePreStreamContext, AWELivePreStreamInnerRoomDisplayManager, AWELiveQuitRoomModel, HTSLivePreviewPromotionSyncData, NSDictionary;

@protocol AWELivePreStreamInnerRoomDisplayConfigProtocol <NSObject>
- (id)initWithModel:(AWEAwemeModel *)arg1 displayManager:(AWELivePreStreamInnerRoomDisplayManager *)arg2 context:(AWELivePreStreamContext *)arg3;

@optional
- (NSDictionary *)enterClickRoomParams;
- (NSDictionary *)enterFirstRoomParams;
- (NSDictionary *)enterRoomBussinessParams;
- (NSDictionary *)enterRoomBuriedParams;
- (NSDictionary *)enterRoomParams;
- (void)viewController_viewWillAppear;
- (void)viewController_viewDidDisAppear;
- (void)application_WillResignActive;
- (void)application_willEnterForeground;
- (void)onUserQuitLiveRoom:(AWELiveQuitRoomModel *)arg1;
- (void)onUserEnterLiveRoom;
- (void)handleMessage:(HTSLivePreviewPromotionSyncData *)arg1 actionBlock:(void (^)(long long, unsigned long long, id))arg2;
- (void)reset;
- (void)startCountDownTimerIfNeeded:(void (^)(long long, unsigned long long, id))arg1;
@end

