//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString, UIView;
@protocol AWELeftSideBarItemContext;

@protocol AWELeftSideBarCellProtocol <NSObject>
- (void)leftSideBarPresenterOnReloadWithContext:(id <AWELeftSideBarItemContext>)arg1 extraData:(NSDictionary *)arg2;
- (void)leftSideBarThemeDidChange:(long long)arg1;
- (double)cellViewHeight;
- (UIView *)onCreateCellView;

@optional
- (UIView *)contentViewWithSubBusinessID:(NSString *)arg1;
- (void)leftSideBarViewDynamicModuleForceRequestDataFailed;
- (void)leftSideBarViewDynamicModuleForceRequestDataComplete:(NSDictionary *)arg1;
- (void)leftSideBarViewDynamicModuleRequestDataFailed;
- (void)leftSideBarViewDynamicModuleRequestDataComplete:(NSDictionary *)arg1 isCacheData:(_Bool)arg2;
- (void)leftSideBarCellClick;
- (void)showReloadAnimation;
- (void)leftSideBarViewDidDisAppear;
- (void)leftSideBarViewWillDisAppear;
- (void)leftSideBarViewDidAppear;
- (void)leftSideBarViewWillAppear;
- (double)cellViewWidth;
@end

