//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEBaseListSectionController, NSArray;

@protocol AWEListSectionControllerDelegate <NSObject>

@optional
- (void)sectionControllerDidUpdateModelsAfterMovement:(AWEBaseListSectionController *)arg1;
- (void)sectionControllerDidDelayUpdateModelsWhenMoving:(AWEBaseListSectionController *)arg1;
- (void)sectionController:(AWEBaseListSectionController *)arg1 didMoveModel:(id)arg2 fromIndex:(long long)arg3 toIndex:(long long)arg4 finalModelsArray:(NSArray *)arg5;
- (void)sectionControllerDidExitWorkingRange:(AWEBaseListSectionController *)arg1;
- (void)sectionControllerWillEnterWorkingRange:(AWEBaseListSectionController *)arg1;
- (void)sectionControllerDidEndDisplaying:(AWEBaseListSectionController *)arg1;
- (void)sectionControllerWillDisplay:(AWEBaseListSectionController *)arg1;
@end

