//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol AWELiteUGSPTimeMessage
- (void)spTimeDidChanged:(unsigned long long)arg1 byMode:(unsigned long long)arg2;
@end

