//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class ACCModernTextModeStyleModel, AWEVideoPublishViewModel, NSString, UIView, UIViewController;
@protocol ACCModernTextModeStickerEditDelegate, ACCModernTextModeStickerProtocol, ACCTextModeTextEditInputDelegate, UIViewControllerTransitioningDelegate;

@protocol AWEModernTextSwiftProtocol <HTSService>
- (void)showModernTextEditViewWithInputView:(UIView<ACCModernTextModeStickerProtocol> *)arg1 model:(ACCModernTextModeStyleModel *)arg2 delegate:(id <ACCModernTextModeStickerEditDelegate>)arg3;
- (UIViewController *)presentModernTextEditViewControllerWithPublishModel:(AWEVideoPublishViewModel *)arg1 type:(unsigned long long)arg2 delegate:(id <ACCTextModeTextEditInputDelegate>)arg3 placeholderText:(NSString *)arg4 customTransitionDelegate:(id <UIViewControllerTransitioningDelegate>)arg5;
@end

