//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWETabListHeaderViewControllerProtocol-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class AWEMusicDetailResponse, NSArray, NSError, Protocol;

@protocol AWEMusicDetailHeaderViewControllerProtocol <NSObject, AWETabListHeaderViewControllerProtocol>
- (void)setupMusicDetailFailType:(long long)arg1;
- (void)onRelatedDataEndWithMusicList:(NSArray *)arg1;
- (void)onFetchDataEndWithSuccess:(_Bool)arg1 response:(AWEMusicDetailResponse *)arg2 error:(NSError *)arg3;
- (id)regionByProtocol:(Protocol *)arg1;
@end

