//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEMediaExporterConfig;

@protocol AWEMediaExporterServiceContextProtocol <HTSService>
- (void)getExportVideoPath:(AWEMediaExporterConfig *)arg1 completion:(void (^)(NSURL *, NSError *))arg2;
@end

