//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, NSError, NSString, UIView, UIViewController;
@protocol AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol;

@protocol AWEMusicCardCell <NSObject>
- (void)updateCardVC:(_Bool)arg1;
- (UIView *)pinchTargetView;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 playbackFailedForURL:(NSString *)arg2 error:(NSError *)arg3;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 playbackFailedWithError:(NSError *)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangeStallState:(long long)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackToAction:(long long)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 updatePlayTime:(double)arg2 canPlayTime:(double)arg3 totalTime:(double)arg4 playbackRate:(double)arg5;
- (_Bool)shouldResponseToTap:(struct CGPoint)arg1 from:(UIView *)arg2;
- (void)cardDidEndDisplay;
- (void)cardWillDisplay;
- (void)reset;
- (void)stop;
- (void)pause;
- (void)play;
- (void)configWithModel:(AWEAwemeModel *)arg1 isPureMode:(_Bool)arg2 parentVC:(UIViewController *)arg3;
@property(nonatomic, copy) NSString *referString;
@end

