//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIViewController;

@protocol AWEMicroAppLifeCycleDelegate <NSObject>

@optional
- (void)microAppWorkBeforeCloseWithAppID:(NSString *)arg1 containerViewController:(UIViewController *)arg2;
- (void)microAppViewDidLoadWithAppID:(NSString *)arg1 containerViewController:(UIViewController *)arg2;
- (void)appDidFinishWarmBoot:(NSString *)arg1;
- (void)appDidFinishRender:(NSString *)arg1;
- (void)appDidRenderFirstFrame:(NSString *)arg1;
@end

