//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEMusicDetailHeaderMusicRegionOCDelegate, AWEMusicDetailTrackInstanceProtocol;

@protocol AWEMusicDetailHeaderMusicRegionOCProtocol <NSObject>
- (_Bool)isMusicPlaying;
- (void)autoPlayMusicIfNeeded;
- (void)noteCurrentPlayTime;
- (void)headerHandleMusicEntryPlanIfNeeded;
- (void)hideCoverPlayIconAndText:(_Bool)arg1;
- (void)prepareTrackInstance:(id <AWEMusicDetailTrackInstanceProtocol>)arg1;
@property(nonatomic) __weak id <AWEMusicDetailHeaderMusicRegionOCDelegate> ocDelegate;
@end

