//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol AWEMusicCardServiceDelegate <NSObject>
- (void)onCardInfoUpdate:(NSDictionary *)arg1 awemeId:(NSString *)arg2;
@end

