//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEAwemeModel, NSDictionary, NSObject, NSString;
@protocol AWEMusicCardServiceDelegate;

@protocol AWEMusicCardService <HTSService>
- (Class)musicCardCellClass;
- (NSString *)musicCardUrl:(AWEAwemeModel *)arg1;
- (NSDictionary *)queryCardInfoWithItemId:(NSString *)arg1;
- (NSString *)queryLyricsWithItemId:(NSString *)arg1;
- (void)preloadModel:(AWEAwemeModel *)arg1;
- (void)prefetchCardInfoWithItemId:(NSString *)arg1;
- (void)removeCardInfoObserver:(NSObject<AWEMusicCardServiceDelegate> *)arg1;
- (void)addCardInfoObserver:(NSObject<AWEMusicCardServiceDelegate> *)arg1;
@end

