//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEMusicDetailMusicModel, UIView;

@protocol AWEMusicDetailMusicCardViewDelegate <NSObject>
- (void)headerMusicRegionCollectMusicWithSender:(UIView *)arg1 musicModel:(AWEMusicDetailMusicModel *)arg2;
@end

