//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;
@protocol AWEAdMannorCommentGuideView;

@protocol AWEMannorCommentGuideDelegate <NSObject>
- (void)closeAdMannorCommentGuide:(UIView<AWEAdMannorCommentGuideView> *)arg1;
@end

