//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWEButtonUnitModel, AWECommonButtonInfoModel, NSDictionary, UIView;
@protocol AWEPlayInteractionBottomButtonComponentProtocol, AWEPlayInteractionContextProtocol;

@protocol AWEPlayInteractionBottomButtonComponentViewModelProtocol
+ (_Bool)shouldShowButtonForModel:(AWECommonButtonInfoModel *)arg1 context:(id <AWEPlayInteractionContextProtocol>)arg2;
- (void)didClickView:(UIView *)arg1 atPosition:(long long)arg2 withModel:(AWEButtonUnitModel *)arg3;
- (id)initWithInfoModel:(AWECommonButtonInfoModel *)arg1 context:(id <AWEPlayInteractionContextProtocol>)arg2 component:(id <AWEPlayInteractionBottomButtonComponentProtocol>)arg3;
- (long long)activateType;

@optional
- (_Bool)shouldShowTemplateButtonRepeatedly;
- (NSDictionary *)bizParamsForClickEventTrack;
- (NSDictionary *)bizParamsForShowEventTrack;
- (void)didShowViewByTriggerDelay:(_Bool)arg1;
- (_Bool)canRespondToTriggerType:(long long)arg1;
@end

