//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView, UIViewController;

@protocol AWEPadFullPageFeedContainerProtocol <NSObject>
- (void)didClickBackButton;
- (void)setupAlbumPreviewView;
- (UIView *)albumPreviewView;
- (void)reloadForRotate:(_Bool)arg1 richContentWidth:(double)arg2;
- (UIView *)commentBar;
- (void)giveBackRichContentView:(UIView *)arg1;
- (UIView *)richContentViewForRotate;
- (UIViewController *)feedContainerViewController;
- (UIViewController *)feedListVC;
@end

