//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIViewController;
@protocol UIViewControllerTransitionCoordinator;

@protocol AWEPadUIAdaptionViewTransitionObserver <NSObject>

@optional
- (void)awe_viewController:(UIViewController *)arg1 willTransitionToSize:(struct CGSize)arg2 transitionCoordinator:(id <UIViewControllerTransitionCoordinator>)arg3;
@end

