//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol;

@protocol AWEPlayVideoStrategyDelegate <NSObject>

@optional
- (_Bool)shouldUseTTPlayerForXiGuaVideo;
- (_Bool)shouldAddPlayerPeriodicTimerForPlayer:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (_Bool)shouldReponseToVideoRecallInPlayer:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
@end

