//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEPadUIAdaptionAutorotateProtocol <NSObject>

@optional
- (unsigned long long)awe_supportedInterfaceOrientations;
- (_Bool)awe_shouldAutorotate;
@end

