//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEPlayVideoInteractionDelegate-Protocol.h>
#import <AwemeCore/AWEPlayVideoOptimizeDelegate-Protocol.h>
#import <AwemeCore/AWEPlayVideoStrategyDelegate-Protocol.h>

@class NSDictionary, NSError, NSString, UIViewController;
@protocol AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol, IESVideoPlayerProtocol;

@protocol AWEPlayVideoDelegate <AWEPlayVideoOptimizeDelegate, AWEPlayVideoStrategyDelegate, AWEPlayVideoInteractionDelegate>

@optional
- (void)playerVideoVCDidReadyForDisplay:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 subtitleInfoCallBack:(NSDictionary *)arg2;
- (_Bool)shouldPlayerShowAudioInterruptionToast:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (_Bool)shouldPlayerHideTopGradientView:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (_Bool)forceDisableVideoViewUp;
- (_Bool)shouldPreventPlayerPlay:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 maskInfoCallBackWithSVG:(NSString *)arg2 pts:(unsigned long long)arg3;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didUpdateVRHeadPoseWithYaw:(double)arg2 pitch:(double)arg3 roll:(double)arg4;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didStartPlayPreventedWithReason:(NSString *)arg2;
- (void)awePlayer:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 playbackFailedForURL:(NSString *)arg2 error:(NSError *)arg3;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 playbackFailedWithError:(NSError *)arg2;
- (double)customTimerPeriodic:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)videoResourceDidRecallInPlayer:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangeStallState:(long long)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didChangePlaybackToAction:(long long)arg2;
- (void)playerDidStopped:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 bufferingUpdate:(double)arg2;
- (void)playerWillStartNextLoopFinished:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)playerWillStartNextLoop:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (void)playerVideoController:(UIViewController<AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg1 didRecreatePlayerController:(id <IESVideoPlayerProtocol>)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 downloadProgressWithKey:(NSString *)arg2 videoId:(NSString *)arg3 cacheSize:(long long)arg4 mediaSize:(long long)arg5;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 didUpdateFromPlayViewController:(UIViewController<AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol> *)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 updateTotalPlayDuration:(double)arg2;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 updatePlayProgressWithTime:(double)arg2 totalDuration:(double)arg3;
- (void)player:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1 updatePlayTime:(double)arg2 canPlayTime:(double)arg3 totalTime:(double)arg4;
@end

