//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEProfileExtensionAreaCommonParamModel, AWEUserModel, NSDictionary, NSString;
@protocol AWEProfileExtensionAreaCardControllerProtocol, AWEProfileExtensionAreaCardViewProtocol, AWEProfileExtensionAreaContainerProtocol, AWEProfileExtensionAreaPopoverConfigProtocol, AWEProfileExtensionAreaReminderIconConfigProtocol, AWEProfileExtensionAreaRichContentConfigProtocol;

@protocol AWEProfileExtensionAreaCardControllerProtocol <NSObject>

@optional
+ (_Bool)shouldShowCardWithUserModel:(AWEUserModel *)arg1;
+ (id <AWEProfileExtensionAreaCardControllerProtocol>)cardControllerWithCommonParam:(AWEProfileExtensionAreaCommonParamModel *)arg1;
- (void)configRichContentConfig:(id <AWEProfileExtensionAreaRichContentConfigProtocol>)arg1 withCardOffset:(double)arg2 isScrollable:(_Bool)arg3;
- (void)configReminderIconConfigModel:(id <AWEProfileExtensionAreaReminderIconConfigProtocol>)arg1;
- (_Bool)needToShowDynamicIcon;
- (void)configPopoverConfigModel:(id <AWEProfileExtensionAreaPopoverConfigProtocol>)arg1;
- (_Bool)needToShowPopover;
- (_Bool)isForcedToShowAfterHomePageRefresh;
- (NSDictionary *)trackerExtraParamsWithEventName:(NSString *)arg1;
- (_Bool)isEqualController:(id)arg1;
- (void)cardDidDisappear;
- (void)cardWillDisappear;
- (void)cardDidAppear;
- (void)cardWillAppear;
- (void)cardDidClicked;
- (void)cardNewlyAddedAfterAppInstall;
- (void)configDelegate:(id <AWEProfileExtensionAreaContainerProtocol>)arg1;
- (void)passCardView:(id <AWEProfileExtensionAreaCardViewProtocol>)arg1;
- (_Bool)shouldShowCard;
@end

