//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPadNumKeyboard, NSString;

@protocol AWEPadNumKeyboardDelegate <NSObject>
- (void)p_buttonDidClickedWithKeyboard:(AWEPadNumKeyboard *)arg1 isDelete:(_Bool)arg2 content:(NSString *)arg3;
- (void)p_orientationDidChangeWithKeyboard:(AWEPadNumKeyboard *)arg1;
- (void)p_orientationWillChangeWithKeyboard:(AWEPadNumKeyboard *)arg1;
@end

