//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSError, UIView;
@protocol AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol;

@protocol AWEPlayVideoInteractionDelegate <NSObject>

@optional
- (void)coverImageUpdateSuccess:(_Bool)arg1 loadingTime:(double)arg2 error:(NSError *)arg3;
- (UIView *)interactionViewForPlayer:(id <AWEAwemePlayVideoProtocol><AWEAwemePlayVideoTrackProtocol>)arg1;
- (double)interactionInfoAreaHeight;
- (void)stopLoadingAniamtion;
- (void)showLoadingAnimation;
@end

