//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPublishBaseTask, NSDictionary, NSError;
@protocol AWEPublishStageProtocol;

@protocol AWEPublishTaskMessage <NSObject>

@optional
- (void)task:(AWEPublishBaseTask *)arg1 cancelWithResult:(_Bool)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 didResumeAtStage:(id <AWEPublishStageProtocol>)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 didPendingAtStage:(id <AWEPublishStageProtocol>)arg2 error:(NSError *)arg3;
- (void)task:(AWEPublishBaseTask *)arg1 didRemoveWithResult:(long long)arg2 error:(NSError *)arg3 info:(NSDictionary *)arg4;
- (void)replaceMusicPublishProgressWithTask:(AWEPublishBaseTask *)arg1 taskStatus:(long long)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 progressDidChangeWithInfo:(NSDictionary *)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 needResetWithInfo:(NSDictionary *)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 didWholeEndWithResult:(long long)arg2 error:(NSError *)arg3;
- (void)task:(AWEPublishBaseTask *)arg1 didEndWithResult:(long long)arg2 error:(NSError *)arg3;
- (void)task:(AWEPublishBaseTask *)arg1 didCreateAweme:(_Bool)arg2 error:(NSError *)arg3;
- (void)task:(AWEPublishBaseTask *)arg1 productDidExportWithInfo:(NSDictionary *)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 didBeginWithInfo:(NSDictionary *)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 didAppendWithInfo:(NSDictionary *)arg2;
- (void)task:(AWEPublishBaseTask *)arg1 willAppendWithInfo:(NSDictionary *)arg2;
@end

