//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESVideoPlayerProtocol;

@protocol AWEPlayVideoMessage <NSObject>

@optional
- (void)player:(id <IESVideoPlayerProtocol>)arg1 beInsertedSuccessWithPlaybackAction:(long long)arg2;
- (void)playerDidReadyForDisplay:(id <IESVideoPlayerProtocol>)arg1;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2;
@end

