//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEPhotosPreviewViewController;

@protocol AWEPhotosPreviewViewControllerDelegate <NSObject>
- (void)userDidPerformOperationOnPhotosPreviewViewController:(AWEPhotosPreviewViewController *)arg1;

@optional
- (void)photosPreviewViewControllerWillDisappear:(AWEPhotosPreviewViewController *)arg1;
- (void)photosPreviewViewControllerDidAppear:(AWEPhotosPreviewViewController *)arg1;
- (void)photosPreviewViewController:(AWEPhotosPreviewViewController *)arg1 didDisappearWithStayTime:(long long)arg2;
@end

