//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIView;

@protocol AWEPhotosPreviewFadeOutTransitionContextProvider

@optional
- (long long)fadeOutTransitionItemOffset;
- (_Bool)fadeOutTransitionWantsBlackMaskView;
- (unsigned long long)fadeOutTransitionAllowedTriggerDirection;
- (UIView *)fadeOutTransitionEndView;
@end

