//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWERelatedRecommendPanelManagerProtocol <NSObject>
- (void)dismissPanelIfNeeded;
- (double)originShrinkVideoHeight;
- (void)tryPreloadRelatedVideosWithPreloadType:(unsigned long long)arg1;
- (void)showRelatedRecommendPanel;
- (_Bool)isPanelShowing;
@property(nonatomic) _Bool videoIsPlayWhenEnterPage;
@end

