//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol AWERouterViewControllerProtocol <NSObject>
- (_Bool)configWithRouterParamDict:(NSDictionary *)arg1;
@end

