//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWERLComponentContainer;

@protocol AWERLComponentContainerDelegate <NSObject>
- (void)componentContainer:(AWERLComponentContainer *)arg1 changeBoundsToSize:(struct CGSize)arg2;

@optional
- (void)debug_onUserMultiTapped:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerDidUpdate:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerWillUpdate:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerDidRender:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerWillRender:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainer:(AWERLComponentContainer *)arg1 didLayout:(struct CGSize)arg2;
- (void)debug_componentContainer:(AWERLComponentContainer *)arg1 willLayout:(struct CGSize)arg2;
- (void)debug_componentContainerDidBuildVirtualViews:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerWillBuildVirtualViews:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerDidBuildComponents:(AWERLComponentContainer *)arg1;
- (void)debug_componentContainerWillBuildComponents:(AWERLComponentContainer *)arg1;
@end

