//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEDCFeedPageContext, NSDictionary, NSString, UIScrollView, UIViewController;
@protocol AWEDCFeedListViewControllerProtocol;

@protocol AWERelatedRecommendViewControllerDelegate <NSObject>

@optional
- (double)sheetMinimumContentHeight;
- (double)sheetMaximimContentHeight;
- (double)topViewHeight;
- (_Bool)topViewShow;
- (_Bool)shouldShowNoMoreButton;
- (void)dcFeedDidBeginReloadTheme;
- (struct CGRect)relatedRecommendCollectionViewFrameWithBounds:(struct CGRect)arg1;
- (_Bool)dcFeedClientShouldShowDislikeVC;
- (NSDictionary *)dcFeedClientClickTrackParamsWithModel:(AWEAwemeModel *)arg1;
- (NSDictionary *)dcFeedClientShowTrackParamsWithModel:(AWEAwemeModel *)arg1;
- (NSDictionary *)dcFeedCustomTrackParamsWithModel:(AWEAwemeModel *)arg1 eventName:(NSString *)arg2;
- (Class)dcFeedCustomCellWithModel:(AWEAwemeModel *)arg1 context:(AWEDCFeedPageContext *)arg2;
- (_Bool)dcFeedShouldDisableCellClick;
- (_Bool)dcFeed:(UIViewController<AWEDCFeedListViewControllerProtocol> *)arg1 handleRouterEventWithEventType:(unsigned long long)arg2 awemeModel:(AWEAwemeModel *)arg3;
- (_Bool)isMentionDataPreloading;
- (_Bool)panedIsExpanded;
- (_Bool)panelIsShowing;
- (void)updateFetchStateWithSuccess:(_Bool)arg1;
- (double)sheetOriginHeight;
- (_Bool)bottomInteractionViewIsShow;
- (void)scrollViewScroll:(UIScrollView *)arg1 isScrollViewDidScrollCallback:(_Bool)arg2;
- (void)updateCloseType:(long long)arg1;
- (void)backToPanel;
- (void)enterInner;
- (void)back;
@end

