//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWEPageContext, NSArray, UIView, UIViewController;
@protocol AWEPlayInteractionContextProtocol, AWEPlayInteractionViewControllerProtocol, AWERelatedRecommendTopElementDataModel, AWERelatedRecommendTopElementDelegate;

@protocol AWERelatedRecommendTopElement <NSObject>
+ (id)createWithContext:(AWEPageContext<AWEPlayInteractionContextProtocol> *)arg1 container:(UIViewController<AWEPlayInteractionViewControllerProtocol> *)arg2 currentModel:(AWEAwemeModel *)arg3;
+ (long long)type;
@property(nonatomic) long long state;
@property(nonatomic) __weak id <AWERelatedRecommendTopElementDelegate> delegate;
@property(readonly, nonatomic) double bottomSpacing;
@property(readonly, nonatomic) id <AWERelatedRecommendTopElementDataModel> dataModel;
@property(readonly, nonatomic) double height;
@property(readonly, nonatomic) UIView *skeletonView;
@property(readonly, nonatomic) UIView *contentView;
- (NSArray *)horizontalGestureRecognizers;
- (_Bool)validate;
- (void)updateUI;
- (void)updateWithNewState:(long long)arg1;
- (id)initWithDataModel:(id <AWERelatedRecommendTopElementDataModel>)arg1;
@end

