//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIViewController;
@protocol AWEDCFeedListViewControllerProtocol, AWERelatedRecommendViewControllerDelegate;

@protocol AWERelatedRecommendViewControllerProtocol <NSObject>
- (void)trackExitDCWithCloseMethod:(NSString *)arg1;
- (void)trackEnterDC;
@property(nonatomic) unsigned long long entrancePageType;
@property(nonatomic) __weak id <AWERelatedRecommendViewControllerDelegate> delegate;
@property(nonatomic) _Bool shouldEnableCustomFetchData;
@property(nonatomic, copy) NSString *customEnterMethod;
@property(nonatomic, copy) NSString *customReferString;
@property(nonatomic) _Bool disableContentTopInset;
@property(nonatomic, retain) UIViewController<AWEDCFeedListViewControllerProtocol> *dcViewController;
@property(nonatomic) _Bool shouldHoldTopAreaView;
@end

