//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWERLVirtualView, NSArray;

@protocol AWERLComponentUIOverride <NSObject>
- (AWERLVirtualView *)buildVirtualView:(NSArray *)arg1;
@end

