//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEStoryDetailTransitionProvider-Protocol.h>

@protocol AWEStoryDetailTransitionOuterProvider <AWEStoryDetailTransitionProvider>

@optional
- (_Bool)shouldMute;
@end

