//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel;

@protocol AWEShareSelectDelegate <NSObject>
- (unsigned long long)selectedIndexAwemeModel:(AWEAwemeModel *)arg1;
- (_Bool)canSelectedAwemeModel:(AWEAwemeModel *)arg1;
- (_Bool)selectedAwemeModel:(AWEAwemeModel *)arg1;
- (void)didSelectedAwemeModel:(AWEAwemeModel *)arg1;
@end

