//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class ACCAIGCVideoReferenceFrameCheckModel, NSDictionary, UIImage;

@protocol AWEStudioRecordBachProcessProtocol <NSObject>
- (ACCAIGCVideoReferenceFrameCheckModel *)startBachWith:(UIImage *)arg1 initParams:(NSDictionary *)arg2;
- (_Bool)process:(UIImage *)arg1;
@end

