//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSNumber, NSString;

@protocol AWEShareLiveRoomModelProtocol <NSObject>
- (NSDictionary *)awes_ieslive_toJson;
- (NSString *)awes_ownerAvatarURLString;
- (NSString *)awes_ownerSignature;
- (NSString *)awes_ownerDisplayID;
- (NSString *)awes_ownerNickname;

@optional
- (NSString *)anchorShareText;
- (NSString *)userShareText;
- (NSString *)requestId;
- (NSNumber *)roomID;
@end

