//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/AWEStory25Onboarding-Protocol.h>
#import <AwemeCore/AWEStory25ServiceCameraConfig-Protocol.h>
#import <AwemeCore/AWEStory25ServiceShotEntrance-Protocol.h>
#import <AwemeCore/HTSService-Protocol.h>

@class AWEAwemeModel, AWEPublishBaseTask, NSNumber, NSString, UIViewController;
@protocol AWERouterViewControllerProtocol;

@protocol AWEStory25Service <HTSService, AWEStory25ServiceShotEntrance, AWEStory25ServiceCameraConfig, AWEStory25Onboarding>
- (NSString *)convertToStory25DetailFrom:(NSString *)arg1 isInnerPush:(_Bool)arg2;
- (_Bool)isSkylightStory25BubbleEnabled;
- (UIViewController<AWERouterViewControllerProtocol> *)story25FeedViewController;
- (void)trackFolderExitWithAweme:(AWEAwemeModel *)arg1 enterFrom:(NSString *)arg2 previousPage:(NSString *)arg3 previousMethod:(NSString *)arg4 circleType:(NSString *)arg5 vv:(NSNumber *)arg6 duration:(NSNumber *)arg7;
- (void)trackFolderShowWithAweme:(AWEAwemeModel *)arg1 enterFrom:(NSString *)arg2 previousPage:(NSString *)arg3 previousMethod:(NSString *)arg4 circleType:(NSString *)arg5;
- (NSString *)story25FeedReferString;
- (AWEAwemeModel *)mergeWithDraftOutSideAweme:(AWEAwemeModel *)arg1 realOutsideAweme:(AWEAwemeModel *)arg2;
- (AWEAwemeModel *)generateAggregatedAwemeUsingTask:(AWEPublishBaseTask *)arg1;
- (_Bool)shouldUseStory25Handler;
- (_Bool)shouldUseStory25Feed;
- (_Bool)shouldUseImageMusicInfoWith:(AWEAwemeModel *)arg1;
- (void)recordFamiliarStatusForAweme:(AWEAwemeModel *)arg1 enterFrom:(NSString *)arg2;
- (_Bool)shouldUseImageDownloadVideoWith:(AWEAwemeModel *)arg1;
- (_Bool)isStory25WithTask:(AWEPublishBaseTask *)arg1;
- (_Bool)isStory25With:(AWEAwemeModel *)arg1;
- (_Bool)isStory25Enabled;
@end

