//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel;

@protocol AWEStoryContainerViewControllerDelegate <NSObject>
- (_Bool)currentVCIsActive;

@optional
- (void)storyContainerViewControllerDidChangePlayingModel:(AWEAwemeModel *)arg1 externalModel:(AWEAwemeModel *)arg2;
@end

