//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEAIGCResourceUploadInput, NSArray, NSString;

@protocol AWEStudioAIGCUploadResourcesTaskServiceProtocol <HTSService>
- (void)cancelUploadTasksWithTaskIds:(NSArray *)arg1;
- (NSString *)startUploadResourceWithInput:(AWEAIGCResourceUploadInput *)arg1 progress:(void (^)(NSString *, double))arg2 completion:(void (^)(AWEAIGCUploadResourcesResult *, NSDictionary *, NSError *))arg3;
@end

