//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSString;

@protocol AWEStudioUIViewControllerHelperProtocol
@property(nonatomic) _Bool aweDisableFullscreenPopTransition;
@property(retain, nonatomic) NSDictionary *awe_trackAttributes;
@property(retain, nonatomic) NSString *awe_staytimeLabel;
@property(nonatomic) _Bool btd_prefersNavigationBarHidden;
@end

