//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEStory25ServiceShotEntrance <NSObject>
- (_Bool)shouldProfileAvatarShowPlusIcon;
- (_Bool)shouldSkylightUseStoryCamera;
- (_Bool)isWidgetForceLandingCameraEnable;
- (_Bool)shouldShowForwardInputPanelGuide;
- (_Bool)shouldRemoveStory24FeedShotEntrance;
- (_Bool)isIMMessageTabEntranceEnable;
- (_Bool)isIMMessageCFInviteEntranceEnable;
- (_Bool)isFamiliarTabShotEntranceEnable;
@end

