//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEStudioAIEnhanceAIPResult, AWEStudioAIEnhanceSecondaryPageInput, NSArray, NSString, UIViewController;
@protocol AWEStudioAIEnhanceAIPRequestHandlerProtocol, AWEStudioAIEnhanceSecondaryPageProtocol;

@protocol AWEStudioAIEnhanceServiceProtocol <HTSService>
- (UIViewController<AWEStudioAIEnhanceSecondaryPageProtocol> *)fetchAIEnhanceSecondaryPage:(AWEStudioAIEnhanceSecondaryPageInput *)arg1 completion:(void (^)(_Bool, UIViewController<AWEStudioAIEnhanceSecondaryPageProtocol> *))arg2;
- (void)cleanAIPCache;
- (AWEStudioAIEnhanceAIPResult *)fetchAIPCacheResult:(NSString *)arg1 stepName:(NSString *)arg2 algoReqJSONStr:(NSString *)arg3 inputImagesIdentifier:(NSString *)arg4;
- (id <AWEStudioAIEnhanceAIPRequestHandlerProtocol>)requestEnhanceAIP:(NSArray *)arg1 creationID:(NSString *)arg2 bizType:(NSString *)arg3 stepName:(NSString *)arg4 algoReqJSONStr:(NSString *)arg5 inputImagesIdentifier:(NSString *)arg6 uploadUseBinary:(_Bool)arg7 uploadBytesLimit:(long long)arg8 downloadUseBinary:(_Bool)arg9 progressCallback:(void (^)(NSString *, double))arg10 completion:(void (^)(AWEStudioAIEnhanceAIPResult *, _Bool, NSDictionary *, NSError *))arg11;
@end

