//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AWEStory25ServiceCameraConfig <NSObject>
- (NSString *)storyCameraSchemaWithShootWay:(NSString *)arg1 enterFrom:(NSString *)arg2;
- (void)enterStory25SocialCameraWithShootWay:(NSString *)arg1 enterFrom:(NSString *)arg2;
@end

