//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, UIGestureRecognizer;

@protocol AWEStoryProgressContainerViewDelegate <NSObject>

@optional
- (_Bool)progressContainerShouldBeginGestureRecognizer:(UIGestureRecognizer *)arg1;
- (NSArray *)accessibilityLabels;
- (void)progressContainerViewTouchEnded;
- (void)progressContainerViewValueChangedWithOffsetX:(double)arg1;
- (void)progressContainerViewTouchBegan;
- (void)scrollToIndex:(long long)arg1;
- (void)swipeToNextStory;
- (void)swipeToLastStory;
@end

