//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWERecordBachProcessorConfig, NSObject;
@protocol AWEStudioRecordBachProcessProtocol;

@protocol AWEStudioBusinessBachServiceContextProtocol <HTSService>
- (NSObject<AWEStudioRecordBachProcessProtocol> *)getRecordBachProcess:(AWERecordBachProcessorConfig *)arg1;
@end

