//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol AWEStory25Onboarding <NSObject>
- (void)addAvatarLongPressGuideIfNeededWithHostView:(UIView *)arg1;
- (Class)profileAvatarLongPressAlertClass;
- (Class)feedAppearEventClass;
- (Class)onboardingAlertClass;
@end

