//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class UIViewController;
@protocol AWEAwemeBizPlayVideoProtocol;

@protocol AWEStoryDetailTransitionProvider
- (id)storyDetailTransitionContext;

@optional
- (unsigned long long)zoomTransitionAllowedTriggerDirection;
- (void)storyDetailTransitionDidFinishFromPlayer:(UIViewController<AWEAwemeBizPlayVideoProtocol> *)arg1 toPlayer:(UIViewController<AWEAwemeBizPlayVideoProtocol> *)arg2;
- (void)storyDetailTransitionWillBeginFromPlayer:(UIViewController<AWEAwemeBizPlayVideoProtocol> *)arg1 toPlayer:(UIViewController<AWEAwemeBizPlayVideoProtocol> *)arg2;
@end

