//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSService-Protocol.h>

@class AWEStudioAIGCTaskTransformInput;

@protocol AWEStudioAIGCAIProcessTaskServiceProtocol <HTSService>
- (void)transformToAsyncTask:(AWEStudioAIGCTaskTransformInput *)arg1 completion:(void (^)(AWEStudioAIGCTaskTransformOutput *))arg2;
@end

