//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;
@protocol AWETextInput;

@protocol AWETextInputControllerDelegate <NSObject>

@optional
- (double)textInputCurrentAwemeDuration:(id <AWETextInput>)arg1;
- (_Bool)textInputShouldMatchTimeExtra:(id <AWETextInput>)arg1;
- (void)textInputDidInsertMusic:(id <AWETextInput>)arg1;
- (NSDictionary *)textInputRemotePlayRoomParams;
- (void)textInputDidClearInputData:(id <AWETextInput>)arg1;
- (void)textInputDidDeleteCommentChain:(id <AWETextInput>)arg1;
- (void)textInputDidDeleteDuetChain:(id <AWETextInput>)arg1;
- (void)textInputDismissCompletion;
- (void)textInput:(id <AWETextInput>)arg1 didReplaceTextInRange:(struct _NSRange)arg2 withText:(NSString *)arg3;
- (void)textInput:(id <AWETextInput>)arg1 didDeleteTextInRange:(struct _NSRange)arg2;
- (_Bool)textInput:(id <AWETextInput>)arg1 shouldDeleteTextInRange:(struct _NSRange)arg2;
- (void)textInputDidNeedClosingSuggestion:(id <AWETextInput>)arg1;
- (void)textInput:(id <AWETextInput>)arg1 didRequestSuggestion:(NSArray *)arg2 hitBlockList:(_Bool)arg3;
- (_Bool)textInputNoNeedSuggestionWhenOnlyHash:(NSString *)arg1;
- (void)textInputDidStartLoadingSuggestions:(id <AWETextInput>)arg1;
- (void)textInputDidDeleteUser:(id <AWETextInput>)arg1;
- (void)textInputDidAddUser:(id <AWETextInput>)arg1;
- (void)textInputValueChanged:(id <AWETextInput>)arg1;
- (void)textInputDidExceedMaxUserCount:(id <AWETextInput>)arg1;
- (void)textInputDidExceedMaxLength:(id <AWETextInput>)arg1;
@end

