//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWESearchHotSpotConfigModel, NSDictionary, UIView;
@protocol AWETopicShootButtonDelegate;

@protocol AWETopicShootButtonProtocol <NSObject>
- (void)executeAutoLayoutWithContainerView:(UIView *)arg1;
- (void)executeManualLayoutWithContainerSize:(struct CGSize)arg1;
- (void)configWithModel:(AWESearchHotSpotConfigModel *)arg1 delegate:(id <AWETopicShootButtonDelegate>)arg2 logExtraDict:(NSDictionary *)arg3;
@end

