//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWETextTemplateDownloadManager, IESEffectModel, NSError, NSString;

@protocol AWETextTemplateDownloadObserverProtocol <NSObject>

@optional
- (void)stickerDownloadManager:(AWETextTemplateDownloadManager *)arg1 needUpdateCellDownloadedSticker:(IESEffectModel *)arg2;
- (void)stickerDownloadManager:(AWETextTemplateDownloadManager *)arg1 didFailDownloadSticker:(IESEffectModel *)arg2 withError:(NSError *)arg3;
- (void)stickerDownloadManager:(AWETextTemplateDownloadManager *)arg1 didFinishDownloadSticker:(IESEffectModel *)arg2 extraParams:(NSString *)arg3;
- (void)stickerDownloadManager:(AWETextTemplateDownloadManager *)arg1 sticker:(IESEffectModel *)arg2 downloadProgressChange:(double)arg3;
- (void)stickerDownloadManager:(AWETextTemplateDownloadManager *)arg1 didBeginDownloadSticker:(IESEffectModel *)arg2;
@end

