//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIScrollView;

@protocol AWETabListItemViewControllerProtocol <NSObject>
- (UIScrollView *)tabContentScrollView;

@optional
- (_Bool)tabListEnableTabItemRefreshHeader;
- (_Bool)tabListDefaultHideSegmentedControl;
- (_Bool)tabListDisableTabItemStickSegmentedControl;
- (_Bool)tabListEnableTabItemScrollViewBounce;
- (void)tabListDidEndScrolling;
- (void)tabListItemDidDeselect;
- (void)tabListItemDidSelect:(_Bool)arg1;
- (id)segmentedControlItemConfigForTabList:(id)arg1;
- (void)configWithTabItemModel:(id)arg1;
@end

