//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol AWEUGSceneDesktopChannelGuideEvadeProtocol <NSObject>
- (NSString *)sceneType;
- (_Bool)shouldDesktopChannelGuideEvadeWithScene:(NSString *)arg1 enterFrom:(NSString *)arg2;

@optional
- (NSString *)tabID;
- (NSString *)position;
- (NSString *)enterFrom;
@end

