//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEUGDesktopChannelGuideUIConfigModel, AWEUGDesktopPitayaMessageModel, NSDictionary, NSError, NSString;

@protocol AWEUGDesktopChannelGuideMessage <NSObject>

@optional
- (void)desktopChannelGuideClickWithScene:(NSString *)arg1 enterFrom:(NSString *)arg2 guideType:(NSString *)arg3 clickTarget:(NSString *)arg4;
- (void)desktopChannelGuideShowFailedWithScene:(NSString *)arg1 enterFrom:(NSString *)arg2 guideType:(NSString *)arg3 error:(NSError *)arg4 extraParams:(NSDictionary *)arg5;
- (void)desktopChannelGuideAlreadyShowWithScene:(NSString *)arg1 enterFrom:(NSString *)arg2 guideType:(NSString *)arg3 extraParams:(NSDictionary *)arg4 config:(AWEUGDesktopChannelGuideUIConfigModel *)arg5;
- (void)showAlineCardDesktopChannelGuideWithModel:(AWEUGDesktopPitayaMessageModel *)arg1 extraParams:(NSDictionary *)arg2;
- (void)showDesktopChannelGuide:(NSString *)arg1 config:(AWEUGDesktopChannelGuideUIConfigModel *)arg2 guideType:(NSString *)arg3;
@end

