//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEUserModel, AWEUserRelationContext, AWEUserRelationResponse, NSDictionary, NSError, NSNumber, NSString;

@protocol AWEUserMessage <NSObject>

@optional
- (void)didCancelSpecialFollowWithUser:(AWEUserModel *)arg1 error:(NSError *)arg2;
- (void)didSpecialFollowWithUser:(AWEUserModel *)arg1 error:(NSError *)arg2;
- (void)didReceiveUnfollowUserResponse:(AWEUserRelationResponse *)arg1 context:(AWEUserRelationContext *)arg2 error:(NSError *)arg3;
- (void)willSendUnfollowUserRequestWithContext:(AWEUserRelationContext *)arg1;
- (void)didReceiveFollowUserResponse:(AWEUserRelationResponse *)arg1 context:(AWEUserRelationContext *)arg2 error:(NSError *)arg3;
- (void)followStatusChangeForUser:(AWEUserModel *)arg1 status:(long long)arg2 error:(NSError *)arg3;
- (void)didFinishRemoveFansWithUser:(NSString *)arg1;
- (void)didFinishSetRemarkWithUser:(AWEUserModel *)arg1;
- (void)didFinishTurnOffPostNotification:(NSString *)arg1;
- (void)didFinishTurnOnPostNotification:(NSString *)arg1;
- (void)updateFollowRequestCount:(NSNumber *)arg1;
- (void)didFinishCloseFriendsWithUser:(NSString *)arg1 status:(long long)arg2;
- (void)willFinishCloseFriendsWithUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishTapTAIsFriendWithUser:(NSString *)arg1 isFriend:(_Bool)arg2;
- (void)didFinishShowOneDayWithUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishHideOneDayWithUser:(NSString *)arg1 status:(long long)arg2;
- (void)didChangePrivateRelationWithUser:(NSString *)arg1 relationType:(long long)arg2 relationValue:(long long)arg3;
- (void)didFinishUnHidePostFromHer:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishHidePostFromHer:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishShowMyPostToUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishRejectUserFollowRequestWithNoticeID:(NSNumber *)arg1 user:(NSString *)arg2;
- (void)didFinishApproveUserFollowRequest:(NSString *)arg1 error:(NSError *)arg2;
- (void)didFinishHideMyPostFromUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishUnBlockUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishBlockUser:(NSString *)arg1 status:(long long)arg2 followStatus:(long long)arg3 followerStatus:(long long)arg4;
- (void)didFinishBlockUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishUnTopFollowingUser:(NSString *)arg1 status:(long long)arg2;
- (void)didFinishTopFollowingUser:(NSString *)arg1 status:(long long)arg2;
- (void)didStartUnFollowUserOnProfileMenu:(AWEUserModel *)arg1 enterMethod:(unsigned long long)arg2 needConfirm:(_Bool)arg3;
- (void)didFinishFollow:(AWEUserRelationContext *)arg1 error:(NSError *)arg2;
- (void)didFinishUnFollowUser:(AWEUserModel *)arg1 status:(long long)arg2 error:(NSError *)arg3;
- (void)didFinishFollowUser:(AWEUserModel *)arg1 status:(long long)arg2 error:(NSError *)arg3;
- (void)didChangeUserSchoolName;
- (void)didFinishPassportQueryButFailAweme;
- (void)didFinishPushUpdateUser:(NSString *)arg1;
- (void)didFinishEditProfileFromNewUser:(NSString *)arg1;
- (void)didUpdateUserOnLaunch;
- (void)didFinishSetPassword;
- (void)didFinishBindPhone;
- (void)didFinishUpdateCurrentFullUserForReason:(unsigned long long)arg1;
- (void)didFinishUpdateAwemeUserWithtintTags:(NSDictionary *)arg1;
- (void)didFinishUpdateAwemeUser;
- (void)extraChangeExpectAccountNumberValueBy:(long long)arg1;
- (void)willSwitchAccountWithUserID:(NSString *)arg1;
- (void)didDeleteAccountWithUserID:(NSString *)arg1;
- (void)didSwitchAccountRequestProfileError;
- (void)didSwitchAccountFailed;
- (void)willStartSwitchAccountWithUser:(AWEUserModel *)arg1;
- (void)userChangedFrom:(NSString *)arg1 to:(NSString *)arg2;
- (void)didFinishLogoutWithUid:(NSString *)arg1;
- (void)willLogoutWithUserID:(NSString *)arg1;
- (void)didLoginFailed;
- (void)didCancelLogin;
- (void)didFinishLogin;
- (void)didFinishLoginWithUid:(NSString *)arg1;
- (void)willStartLogin;
@end

