//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIViewController;
@protocol AWEFeedTableViewControllerProtocol, AWEXTabBaseChannelControllerProtocol;

@protocol AWEXTabChildViewControllerProtocol <NSObject>
@property(nonatomic, readonly) NSString *referString;
@property(nonatomic) __weak id <AWEXTabBaseChannelControllerProtocol> channelController;

@optional
- (void)didTopTabBarShowChanged:(_Bool)arg1;
- (_Bool)isSkyLightViewShowing;
- (UIViewController<AWEFeedTableViewControllerProtocol> *)xtabFeedTableViewController;
- (_Bool)isVideoRelatedPanelShowing;
- (_Bool)isAITextPanelShowing;
- (_Bool)isCommentPanelShowing;
- (void)updatePreviousPage:(NSString *)arg1;
- (void)play;
@end

