//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEYAPTransportCitySceneModel, AWEYAPTransportContext, UIViewController;
@protocol AWEYAPTransportDelegate, AWEYAPTransportViewControllerProtocol;

@protocol AWEYAPTransportHandlerProtocol <NSObject>
+ (UIViewController<AWEYAPTransportViewControllerProtocol> *)createContainer:(AWEYAPTransportCitySceneModel *)arg1 context:(AWEYAPTransportContext *)arg2 delegate:(id <AWEYAPTransportDelegate>)arg3;
@end

