//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol AWEYAPChannelGuideViewProtocol <NSObject>
- (void)closeWithAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
@end

