//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEYAPTransportCitySceneModel, NSString;

@protocol AWEYAPTransportViewControllerProtocol <NSObject>
- (void)didFinishLoginWithUid:(NSString *)arg1;
- (void)didFinishLogin;
- (void)showActivateRetainGuide;
- (_Bool)hasActivateRetainGuide;
- (_Bool)needHighLightScreenBrightness;
- (void)updateContainer:(AWEYAPTransportCitySceneModel *)arg1;
@end

