//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class AWETransitionContext, UIColor, UIView, UIViewController;

@protocol AWEZoomTransitionInnerContextProvider

@optional
- (void)transitionDidCompleteAnimation:(_Bool)arg1;
- (void)transitionDidSubmitAnimation;
- (void)viewControllerDidPopDoneTransition:(AWETransitionContext *)arg1;
- (void)willStartAnimationWithToCP:(UIViewController *)arg1 withFromCP:(UIViewController *)arg2;
- (void)zoomTransitionShrinkFinish:(AWETransitionContext *)arg1;
- (_Bool)zoomTransitionShouldAnimateWithTransform;
- (_Bool)zoomTransitionForbidShowToVCSnapshot;
- (double)tabbarAnimationDuration;
- (double)animationDuration;
- (_Bool)zoomTransitionWantsRemoveSpringAnimation;
- (long long)zoomTransitionItemOffset;
- (void)zoomTransitionWillStartForView:(UIView *)arg1;
- (_Bool)zoomTransitionWantsTabBarAlphaAnimation;
- (_Bool)zoomTransitionWantsViewMigration;
- (UIColor *)zoomTransitionMaskViewColor;
- (_Bool)zoomTransitionWantsBlackMaskView;
- (unsigned long long)zoomTransitionAllowedTriggerDirection;
- (UIView *)zoomTransitionEndView;
- (UIView *)targetHolderView;
- (_Bool)needShowliveSnapView;
- (id)liveTransitionContext;
@end

