//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSBundle, NSString;

@protocol BCAABundleListener <NSObject>

@optional
- (void)bundleIsLoadedByInstanceService:(NSBundle *)arg1 fromBundle:(NSString *)arg2 serviceName:(NSString *)arg3 methodName:(NSString *)arg4;
- (void)preLoadBundleDidEntered:(NSString *)arg1 fromBundle:(NSString *)arg2 enterTag:(NSString *)arg3;
- (void)bundleDidActived:(NSBundle *)arg1 machoHeader:(struct mach_header_64 *)arg2 fromBundle:(NSString *)arg3 enterTag:(NSString *)arg4 cost:(double)arg5;
- (void)bundleDidLoaded:(NSString *)arg1 machoHeader:(struct mach_header_64 *)arg2 fromBundle:(NSString *)arg3 enterTag:(NSString *)arg4 cost:(double)arg5;
- (void)bundleLoadFailed:(NSString *)arg1 fromBundle:(NSBundle *)arg2 enterTag:(NSString *)arg3 error:(NSString *)arg4;
- (void)bundleWillBeLoaded:(NSString *)arg1 fromBundle:(NSString *)arg2 enterTag:(NSString *)arg3;
@end

