//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAABundleService-Protocol.h>

@protocol BCAAInstanceService <BCAABundleService>

@optional
- (_Bool)isWeakBCAAInstance;
@end

