//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol BDHMXPerfTimingProviderProtocol <NSObject>
- (void)fetchAggregationPerfTiming:(unsigned long long)arg1 waitCompleteData:(unsigned long long)arg2 completion:(void (^)(NSDictionary *))arg3;
@end

