//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDImageXUploaderClient, BDUploadImageXInfo, NSError, NSString;

@protocol BDImageXUploadClientDelegate <NSObject>
- (void)imageXUploadDidFinish:(BDImageXUploaderClient *)arg1;
- (void)imageXUpload:(BDImageXUploaderClient *)arg1 fileIndex:(long long)arg2 progressDidUpdate:(long long)arg3;
- (void)imageXUpload:(BDImageXUploaderClient *)arg1 fileIndex:(long long)arg2 singleImage:(BDUploadImageXInfo *)arg3 error:(NSError *)arg4;

@optional
- (void)imageXUpoadDidFinishTos:(BDImageXUploaderClient *)arg1;
- (NSString *)imageXUploadGetMediaDataString:(BDImageXUploaderClient *)arg1;
- (void)imageXUpload:(BDImageXUploaderClient *)arg1 updateStage:(long long)arg2 timestamp:(double)arg3;
- (void)imageXUpload:(BDImageXUploaderClient *)arg1 onLogInfo:(NSString *)arg2;
- (long long)imageXUploadGetNetState:(BDImageXUploaderClient *)arg1;
@end

