//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDKAnnotationView, BDKMapView, CLLocationManager, MKAnnotationView, MKOverlayRenderer, NSArray, NSError, UIView;
@protocol BDKAnnotationViewProtocol, MKAnnotation, MKOverlay;

@protocol BDKMapViewDelegate <NSObject>

@optional
- (void)mapView:(BDKMapView *)arg1 didLongPressedAtCoordinate:(struct CLLocationCoordinate2D)arg2 touchPoint:(struct CGPoint)arg3;
- (void)mapView:(BDKMapView *)arg1 didSingleTappedAtCoordinate:(struct CLLocationCoordinate2D)arg2 touchPoint:(struct CGPoint)arg3;
- (void)mapView:(BDKMapView *)arg1 didTouchPois:(NSArray *)arg2;
- (void)mapView:(BDKMapView *)arg1 didAnnotationViewTapped:(UIView<BDKAnnotationViewProtocol> *)arg2;
- (void)mapView:(BDKMapView *)arg1 didAnnotationViewCalloutTapped:(BDKAnnotationView *)arg2;
- (void)mapView:(BDKMapView *)arg1 didAddOverlayRenderers:(NSArray *)arg2;
- (MKOverlayRenderer *)mapView:(BDKMapView *)arg1 rendererForMKOverlay:(id <MKOverlay>)arg2;
- (id)mapView:(BDKMapView *)arg1 rendererForMAOverlay:(id)arg2;
- (void)mapView:(BDKMapView *)arg1 didFailToLocateUserWithError:(NSError *)arg2;
- (void)mapViewRequireLocationAuth:(CLLocationManager *)arg1;
- (void)mapViewDidStopLocatingUser:(BDKMapView *)arg1;
- (void)mapViewWillStartLocatingUser:(BDKMapView *)arg1;
- (void)mapView:(BDKMapView *)arg1 didDeselectAnnotationView:(UIView *)arg2;
- (void)mapView:(BDKMapView *)arg1 didSelectAnnotationView:(UIView *)arg2;
- (void)mapView:(BDKMapView *)arg1 didAddAnnotationViews:(NSArray *)arg2;
- (BDKAnnotationView *)mapView:(BDKMapView *)arg1 viewForAnnotation:(id)arg2;
- (MKAnnotationView *)mapView:(BDKMapView *)arg1 viewForMKAnnotation:(id <MKAnnotation>)arg2;
- (UIView<BDKAnnotationViewProtocol> *)mapView:(BDKMapView *)arg1 viewForMAAnnotation:(id)arg2;
- (void)mapViewDidFinishRenderingMap:(BDKMapView *)arg1 fullyRendered:(_Bool)arg2;
- (void)mapInitComplete:(BDKMapView *)arg1;
- (void)mapView:(BDKMapView *)arg1 didFailLoadTerrainWithError:(NSError *)arg2;
- (void)mapViewDidFailLoadingMap:(BDKMapView *)arg1 withError:(NSError *)arg2;
- (void)mapViewDidFinishLoadingMap:(BDKMapView *)arg1;
- (void)mapViewWillStartLoadingMap:(BDKMapView *)arg1;
- (void)mapView:(BDKMapView *)arg1 mapDidZoomByUser:(_Bool)arg2;
- (void)mapView:(BDKMapView *)arg1 mapWillZoomByUser:(_Bool)arg2;
- (void)mapView:(BDKMapView *)arg1 mapDidMoveByUser:(_Bool)arg2;
- (void)mapView:(BDKMapView *)arg1 mapWillMoveByUser:(_Bool)arg2;
- (void)mapViewDidChangeVisibleRegion:(BDKMapView *)arg1;
- (void)mapView:(BDKMapView *)arg1 regionDidChangeAnimated:(_Bool)arg2 wasUserAction:(_Bool)arg3;
- (void)mapView:(BDKMapView *)arg1 regionWillChangeAnimated:(_Bool)arg2 wasUserAction:(_Bool)arg3;
- (void)mapView:(BDKMapView *)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)mapView:(BDKMapView *)arg1 regionWillChangeAnimated:(_Bool)arg2;
@end

