//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDVideoUploadInfo, BDVideoUploaderClient, NSError, NSString;

@protocol BDVideoUploadClientDelegate <NSObject>
- (void)videoUpload:(BDVideoUploaderClient *)arg1 progressDidUpdate:(long long)arg2;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 didFinish:(BDVideoUploadInfo *)arg2 error:(NSError *)arg3;

@optional
- (void)videoUpload:(BDVideoUploaderClient *)arg1 fileIndex:(long long)arg2 videoInfo:(BDVideoUploadInfo *)arg3 error:(NSError *)arg4 log:(NSString *)arg5;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 fileIndex:(long long)arg2 progressDidUpdate:(long long)arg3 identifier:(NSString *)arg4;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 progressDidUpdate:(long long)arg2 identifier:(NSString *)arg3;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 didFinish:(BDVideoUploadInfo *)arg2 failNum:(long long)arg3;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 updateVideoStage:(long long)arg2 timestamp:(double)arg3;
- (void)videoUpload:(BDVideoUploaderClient *)arg1 onLogInfo:(NSString *)arg2;
- (NSString *)videoUploadGetMetaString:(BDVideoUploaderClient *)arg1;
- (long long)videoUploadGetNetState:(BDVideoUploaderClient *)arg1;
- (void)videoUploadDiskResumeFailed:(BDVideoUploaderClient *)arg1;
@end

