//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDVoiceOverNodeDescriptor, BDVoiceOverRuleItemModel, NSArray, NSString;

@protocol BDVoiceOverNodeProtocol <NSObject>
- (void)awe_bindRule:(BDVoiceOverRuleItemModel *)arg1;
- (NSString *)awe_accessibilityLabelWithItemModel:(BDVoiceOverRuleItemModel *)arg1;
- (NSArray *)awe_findNodesWithDescriptor:(BDVoiceOverNodeDescriptor *)arg1;
@end

