//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol BDWebSecureLinkContextProtocol <NSObject>
- (NSString *)bdw_getSeclinkPluginScene;
- (_Bool)bdw_isSeclinkInstalled;
- (void)bdw_clearSecLinkContext;
@end

