//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class LynxTemplateBundle, NSDictionary, NSError, NSMutableURLRequest, NSNumber, NSString, NSURLRequest, NSURLResponse;
@protocol AnnieXContainerBaseProtocol, BDXKitViewProtocol, BDXPoolProtocol, BDXResourceProtocol;

@protocol BDXContainerLifecycleProtocol <NSObject>

@optional
- (void)containerUpFullScreen:(id <AnnieXContainerBaseProtocol>)arg1 updateHalfScreenButtonsTopOffsetWithContainerOnTop:(_Bool)arg2;
- (void)containerUpFullScreen:(id <AnnieXContainerBaseProtocol>)arg1 backButtonAlpha:(double)arg2;
- (void)containerUpFullScreen:(id <AnnieXContainerBaseProtocol>)arg1 halfScreenCloseButtonAlpha:(double)arg2;
- (void)containerOnBlockBackGesture:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerPopupWillClose:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerPopupStatusChange:(id <AnnieXContainerBaseProtocol>)arg1 status:(long long)arg2;
- (void)containerTapOnPopupMask:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerOnMemoryWarning:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerOnTakeScreenShot:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerOnAppResignActive:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerOnAppBecomeActive:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 onTemplateBundleReady:(LynxTemplateBundle *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 onKeyBoardChange:(NSDictionary *)arg2 eventType:(unsigned long long)arg3;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 onUpdateLynxInfo:(NSDictionary *)arg2 bulletInfo:(NSDictionary *)arg3;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 onSetupLynxInfo:(NSDictionary *)arg2 bulletInfo:(NSDictionary *)arg3;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didFallBackWithURL:(NSString *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didRecycleIntoPool:(id <BDXPoolProtocol>)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didReuseFromPool:(id <BDXPoolProtocol>)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didFetchFromPool:(id <BDXPoolProtocol>)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didReceivePerformanceFirstLoad:(NSDictionary *)arg2 bulletPerfDict:(NSDictionary *)arg3;
- (void)containerDidConstructJSRuntime:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidPageUpdate:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didEndAnimationWithDuration:(double)arg2 startFrame:(struct CGRect)arg3 finalFrame:(struct CGRect)arg4;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didStartAnimationWithDuration:(double)arg2 startFrame:(struct CGRect)arg3 finalFrame:(struct CGRect)arg4;
- (void)containerWillDisappear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidClose:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidNavigatedStateChanged:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 updateTitle:(NSString *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didReceivePerformance:(NSDictionary *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didRecieveError:(NSError *)arg2;
- (void)containerDidUpdate:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didLoadFailedWithUrl:(NSString *)arg2 error:(NSError *)arg3;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didFinishLoadWithURL:(NSString *)arg2;
- (void)containerDidCommitNavigation:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidFirstScreen:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didFetchedResource:(id <BDXResourceProtocol>)arg2 error:(NSError *)arg3;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didStartFetchResourceWithURL:(NSString *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didWebConstructURLRequest:(NSMutableURLRequest *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didStartLoadingFailedWithUrl:(NSString *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 decidePolicyForNavigationResponse:(NSURLResponse *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didStartLoadingSuccessWithUrl:(NSString *)arg2;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 request:(NSURLRequest *)arg2 decidePolicyForNavigationWithDecisionHandler:(void (^)(long long))arg3;
- (void)containerDidStartLoading:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerWillStartLoading:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerWillConstructKitView:(id <AnnieXContainerBaseProtocol>)arg1 source:(long long)arg2;
- (void)containerOnTasmFinishByNative:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)container:(id <AnnieXContainerBaseProtocol>)arg1 didChangeIntrinsicContentSize:(struct CGSize)arg2;
- (_Bool)container:(id <AnnieXContainerBaseProtocol>)arg1 shouldStartLoadWithRequest:(NSURLRequest *)arg2 navigationType:(NSNumber *)arg3;
- (void)containerVCViewDidDisAppear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerVCViewDidAppear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerViewControllerViewDidDisAppear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerViewControllerViewDidAppear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerViewControllerViewDidLoad:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerOnHide:(id <AnnieXContainerBaseProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerOnShow:(id <AnnieXContainerBaseProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerDidPageReady:(id <AnnieXContainerBaseProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerWillDestory:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerWillClose:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)kitViewWillCreate:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidCreated:(id <AnnieXContainerBaseProtocol>)arg1 view:(id <BDXKitViewProtocol>)arg2;
- (void)containerWillCreated:(id <AnnieXContainerBaseProtocol>)arg1 view:(id <BDXKitViewProtocol>)arg2;
- (void)lynxViewDidProcessRender:(id <AnnieXContainerBaseProtocol>)arg1;
@end

