//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDXLynxMapContainerView, NSSet, UIEvent;

@protocol BDXLynxMapContainerViewDelegate <NSObject>

@optional
- (void)mapContainerView:(BDXLynxMapContainerView *)arg1 touchesCancelled:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mapContainerView:(BDXLynxMapContainerView *)arg1 touchesEnded:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mapContainerView:(BDXLynxMapContainerView *)arg1 touchesMoved:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mapContainerView:(BDXLynxMapContainerView *)arg1 touchesBegan:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)mapContainerView:(BDXLynxMapContainerView *)arg1 didTapCoordinateInMap:(struct CLLocationCoordinate2D)arg2 point:(struct CGPoint)arg3;
@end

