//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDXLynxMapAnimateModel, BDXLynxMapAnnotationModel, BDXLynxMapPolygonModel, BDXLynxMapVisibleRectModel, LynxUIContext, NSArray, NSDictionary, NSString, UIView;
@protocol BDXLynxMapViewDelegate;

@protocol BDXLynxMapAdapterProtocol <NSObject>
@property(nonatomic) double collisionPercent;
@property(nonatomic) _Bool enableAnnotationContentCollision;
@property(nonatomic) _Bool showsTraffic;
@property(nonatomic) _Bool showsBuildings;
@property(nonatomic) _Bool showsPointsOfInterest;
@property(nonatomic) _Bool disableDoubleClickOnMap;
@property(nonatomic) _Bool pitchEnabled;
@property(nonatomic) _Bool rotateEnabled;
@property(nonatomic) _Bool scrollEnabled;
@property(nonatomic) _Bool zoomEnabled;
@property(retain, nonatomic) BDXLynxMapAnnotationModel *userLocationData;
@property(nonatomic) _Bool needsUserLocationHeading;
@property(copy, nonatomic) BDXLynxMapVisibleRectModel *visibleRectData;
@property(nonatomic) double maxZoomLevel;
@property(nonatomic) double minZoomLevel;
@property(nonatomic) double zoomLevel;
@property(nonatomic) double rotationDegree;
@property(nonatomic) struct CLLocationCoordinate2D centerCoordinate;
@property(nonatomic) _Bool shouldSelectAnnotationCallback;
@property(nonatomic) _Bool shouldViewDrawCallback;
@property(nonatomic) _Bool shouldZoomCallback;
@property(copy, nonatomic) NSArray *tileHeatData;
@property(copy, nonatomic) NSArray *multiPointData;
@property(copy, nonatomic) NSArray *annotationData;
@property(copy, nonatomic) NSArray *lineData;
@property(copy, nonatomic) NSArray *areaHeatData;
@property(copy, nonatomic) NSArray *polygonData;
@property(copy, nonatomic) NSArray *circleData;
@property(copy, nonatomic) NSArray *districtData;
@property(nonatomic) __weak id <BDXLynxMapViewDelegate> delegate;
@property(nonatomic) unsigned long long mapType;
@property(nonatomic) long long sign;
@property(nonatomic) __weak LynxUIContext *context;
- (void)getMapScreenShotInRect:(struct CGRect)arg1 timeoutInterval:(double)arg2 completionBlock:(void (^)(UIImage *, long long))arg3;
- (void)stopEditPolygonWithIdentifier:(NSString *)arg1;
- (void)startEditPolygonWithIdentifier:(NSString *)arg1;
- (void)startAnnotationAnimation:(BDXLynxMapAnimateModel *)arg1;
- (BDXLynxMapPolygonModel *)getPolygonPointsWithIdentifier:(NSString *)arg1;
- (void)updatePolygons:(NSArray *)arg1 withType:(unsigned long long)arg2;
- (void)updateCircles:(NSArray *)arg1 withType:(unsigned long long)arg2;
- (void)updateLines:(NSArray *)arg1 params:(NSArray *)arg2 withType:(unsigned long long)arg3;
- (void)updateAnnotations:(NSArray *)arg1 withType:(unsigned long long)arg2;
- (void)deselectAnnotationWithIdentifier:(NSString *)arg1;
- (void)selectAnnotationWithIdentifier:(NSString *)arg1;
- (void)setCustomMapStyle:(NSString *)arg1;
- (struct CGPoint)convertCoordinateOnMapView:(struct CLLocationCoordinate2D)arg1;
- (struct CLLocationCoordinate2D *)visibleRectVertexCoordinatesWithEdgePadding:(struct UIEdgeInsets)arg1;
- (struct CLLocationCoordinate2D *)visibleRectVertexCoordinates;
- (void)setVisibleRectData:(BDXLynxMapVisibleRectModel *)arg1 animated:(_Bool)arg2 duration:(long long)arg3;
- (void)setVisibleRectData:(BDXLynxMapVisibleRectModel *)arg1 animated:(_Bool)arg2;
- (void)setCenterCoordinate:(struct CLLocationCoordinate2D)arg1 zoomLevel:(double)arg2 padding:(struct UIEdgeInsets)arg3 animated:(_Bool)arg4 duration:(long long)arg5;
- (void)setCenterCoordinate:(struct CLLocationCoordinate2D)arg1 zoomLevel:(double)arg2 padding:(struct UIEdgeInsets)arg3 animated:(_Bool)arg4;
- (void)setLimitRegionNorthEast:(struct CLLocationCoordinate2D)arg1 southWest:(struct CLLocationCoordinate2D)arg2;
- (void)setZoomLevel:(double)arg1 animated:(_Bool)arg2 duration:(long long)arg3;
- (void)setZoomLevel:(double)arg1 animated:(_Bool)arg2;
- (void)setCenterCoordinate:(struct CLLocationCoordinate2D)arg1 animated:(_Bool)arg2 duration:(long long)arg3;
- (void)setCenterCoordinate:(struct CLLocationCoordinate2D)arg1 animated:(_Bool)arg2;
- (struct CLLocationCoordinate2D)getMapViewCenterCoordinate;
- (void)setRotationDegree:(double)arg1 animated:(_Bool)arg2 duration:(long long)arg3;
- (_Bool)isSupportSetRotationDegree;
- (unsigned long long)getMapRenderSDK;
- (void)layoutDidFinished;
- (UIView *)createViewWithMapSDKType:(unsigned long long)arg1 bizName:(NSString *)arg2 extraParams:(NSDictionary *)arg3;
- (UIView *)createView;
@end

