//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class BTMPage, NSMutableArray;

@protocol BTMPageManagerType
@property(readonly, nonatomic) NSMutableArray *btm_childPages;
@property(retain, nonatomic) BTMPage *btm_pageItem;
- (void)btm_lazyCreatePageItem;
@end

