//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class ByteRTCLocalStreamStats, ByteRTCNetworkQualityStats, ByteRTCRemoteStreamStats, ByteRTCRoom, ByteRTCRoomEventInfo, ByteRTCRoomStats, ByteRTCUserInfo, NSArray, NSData, NSString;
@protocol ByteRTCStream;

@protocol ByteRTCRoomDelegate <NSObject>

@optional
- (void)rtcRoom:(ByteRTCRoom *)arg1 onControlMessageSendResult:(long long)arg2 error:(long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onSubtitleMessageReceived:(NSArray *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onSubtitleStateChanged:(long long)arg2 errorCode:(long long)arg3 errorMessage:(NSString *)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onNetworkQuality:(ByteRTCNetworkQualityStats *)arg2 remoteQualities:(NSArray *)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onForwardStreamEvent:(NSArray *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onForwardStreamStateChanged:(NSArray *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onAudioStreamBanned:(NSString *)arg2 isBanned:(_Bool)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onVideoStreamBanned:(NSString *)arg2 isBanned:(_Bool)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserVisibilityChanged:(_Bool)arg2 errorCode:(long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomExtraInfoUpdate:(NSString *)arg2 value:(NSString *)arg3 lastUpdateUserId:(NSString *)arg4 lastUpdateTimeMs:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onSetRoomExtraInfoResult:(long long)arg2 result:(long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomMessageSendResult:(long long)arg2 error:(long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserMessageSendResult:(long long)arg2 error:(long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserBinaryMessageReceived:(long long)arg2 uid:(NSString *)arg3 message:(NSData *)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserMessageReceived:(long long)arg2 uid:(NSString *)arg3 message:(NSString *)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomBinaryMessageReceived:(long long)arg2 uid:(NSString *)arg3 message:(NSData *)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomMessageReceived:(long long)arg2 uid:(NSString *)arg3 message:(NSString *)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserBinaryMessageReceived:(NSString *)arg2 message:(NSData *)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserMessageReceived:(NSString *)arg2 message:(NSString *)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomBinaryMessageReceived:(NSString *)arg2 message:(NSData *)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomMessageReceived:(NSString *)arg2 message:(NSString *)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserPublishScreenAudio:(NSString *)arg2 uid:(NSString *)arg3 isPublish:(_Bool)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserPublishScreenVideo:(NSString *)arg2 uid:(NSString *)arg3 isPublish:(_Bool)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserPublishStreamAudio:(NSString *)arg2 uid:(NSString *)arg3 isPublish:(_Bool)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserPublishStreamVideo:(NSString *)arg2 uid:(NSString *)arg3 isPublish:(_Bool)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onAVSyncEvent:(NSString *)arg2 userId:(NSString *)arg3 eventCode:(long long)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onStreamPublishSuccess:(NSString *)arg2 isScreen:(_Bool)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onStreamRemove:(NSString *)arg2 stream:(id <ByteRTCStream>)arg3 reason:(long long)arg4;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onStreamAdd:(id <ByteRTCStream>)arg2;
- (void)onSubscribePrivilegeTokenWillExpire:(ByteRTCRoom *)arg1;
- (void)onPublishPrivilegeTokenWillExpire:(ByteRTCRoom *)arg1;
- (void)onTokenWillExpire:(ByteRTCRoom *)arg1;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserLeave:(NSString *)arg2 reason:(unsigned long long)arg3;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onUserJoined:(ByteRTCUserInfo *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRemoteStreamStats:(ByteRTCRemoteStreamStats *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onLocalStreamStats:(ByteRTCLocalStreamStats *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomEvent:(NSString *)arg2 uid:(NSString *)arg3 state:(long long)arg4 info:(ByteRTCRoomEventInfo *)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomStats:(ByteRTCRoomStats *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onScreenAudioSubscribeStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onScreenVideoSubscribeStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onAudioSubscribeStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onVideoSubscribeStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onScreenAudioPublishStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onScreenVideoPublishStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onAudioPublishStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onVideoPublishStateChanged:(NSString *)arg2 userId:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onAVSyncStateChange:(long long)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomWarning:(long long)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onLeaveRoom:(ByteRTCRoomStats *)arg2;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onStreamStateChanged:(NSString *)arg2 withUid:(NSString *)arg3 state:(long long)arg4 extraInfo:(NSString *)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomStateChanged:(NSString *)arg2 withUid:(NSString *)arg3 state:(long long)arg4 extraInfo:(NSString *)arg5;
- (void)rtcRoom:(ByteRTCRoom *)arg1 onRoomStateChangedWithReason:(NSString *)arg2 withUid:(NSString *)arg3 state:(long long)arg4 reason:(long long)arg5;
@end

