//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol CAKStatusBarEvilController <NSObject>

@optional
- (long long)cak_statusBarStyle;
- (_Bool)cak_statusBarHidden;
@end

