//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class LiveStreamSession;

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct ABRManager;

struct AFDAlbumImageZoomInfo {
    double _field1;
    struct CGPoint _field2;
};

struct AWEDCFeedListRequestInfo {
    unsigned long long _field1;
    union {
        unsigned long long _field1;
        unsigned long long _field2;
    } _field2;
};

struct AWEImageTextCellShrinkState {
    _Bool _field1;
    struct UIEdgeInsets _field2;
};

struct AudioBuffer {
    unsigned int _field1;
    unsigned int _field2;
    void *_field3;
};

struct AudioBufferList {
    unsigned int _field1;
    struct AudioBuffer _field2[1];
};

struct AudioDecoderFactoryInterface;

struct AudioSinkInterface {
    CDUnknownFunctionPointerType *_field1;
};

struct AudioStreamBasicDescription {
    double _field1;
    unsigned int _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
};

struct AudioTrackInterface;

struct AutoRefCounter<livecore::VeLivePusher> {
    struct VeLivePusher *ptr_;
};

struct BandwidthCoordinator;

struct BmfSITICalculator;

struct CATransform3D {
    double m11;
    double m12;
    double m13;
    double m14;
    double m21;
    double m22;
    double m23;
    double m24;
    double m31;
    double m32;
    double m33;
    double m34;
    double m41;
    double m42;
    double m43;
    double m44;
};

struct CGAffineTransform {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
    double _field5;
    double _field6;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CGVector {
    double _field1;
    double _field2;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct DecodeImageBuffer;

struct DitoStyleCornerRadius {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
};

struct EngineAudioWrapper {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    void *_field5;
};

struct EngineVideoWrapper {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    void *_field3;
};

struct GPBExtensionRange {
    unsigned int _field1;
    unsigned int _field2;
};

struct GPBMessage_Storage {
    unsigned int _field1[0];
};

struct HTSGPUMatrix3x3 {
    struct HTSGPUVector3 _field1;
    struct HTSGPUVector3 _field2;
    struct HTSGPUVector3 _field3;
};

struct HTSGPUMatrix4x4 {
    struct HTSGPUVector4 _field1;
    struct HTSGPUVector4 _field2;
    struct HTSGPUVector4 _field3;
    struct HTSGPUVector4 _field4;
};

struct HTSGPUVector3 {
    float _field1;
    float _field2;
    float _field3;
};

struct HTSGPUVector4 {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct IESHorizentalEdge {
    double _field1;
    double _field2;
};

struct IESIndensityParam_t {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
    float _field17;
    float _field18;
    float _field19;
    float _field20;
    float _field21;
    float _field22;
    float _field23;
    float _field24;
    float _field25;
    float _field26;
    float _field27;
    float _field28;
    float _field29;
    float _field30;
    float _field31;
    float _field32;
    float _field33;
};

struct IESSrtDdata {
    struct IESSrtLine *_field1;
    int _field2;
};

struct IESSrtLine;

struct IESVerticalEdge {
    double _field1;
    double _field2;
};

struct IOSPlatformAudioDecodedCallback;

struct IOSPlatformObserverServer;

struct LSAudioBGMProcessor {
    CDUnknownFunctionPointerType *_field1;
    long long _field2;
    _Bool _field3;
    id _field4;
    id _field5;
    unsigned long long _field6;
    id _field7;
    id _field8;
    struct mutex _field9;
    _Bool _field10;
};

struct LSBundle {
    struct map<std::string, void *, std::less<std::string>, std::allocator<std::pair<const std::string, void *>>> m_mapBundle;
};

struct LSLiveEffectImage {
    char *_field1;
    int _field2;
    int _field3;
    int _field4;
    int _field5;
    unsigned long long _field6;
    void *_field7;
};

struct LSLiveIntensityParam_t {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
    float _field7;
    float _field8;
    float _field9;
    float _field10;
    float _field11;
    float _field12;
    float _field13;
    float _field14;
    float _field15;
    float _field16;
    float _field17;
    float _field18;
    float _field19;
    float _field20;
    float _field21;
    float _field22;
    float _field23;
    float _field24;
    float _field25;
    float _field26;
    float _field27;
    float _field28;
    float _field29;
    float _field30;
    float _field31;
    float _field32;
    float _field33;
};

struct LSSITICalculatorObserver {
    CDUnknownFunctionPointerType *_vptr$SITICalculatorObserver;
    LiveStreamSession *session_;
};

struct LiveSeiObserver;

struct LiveVideoColorHist;

struct LiveVideoVQScore;

struct MAMapPoint {
    double _field1;
    double _field2;
};

struct MAMapRect {
    struct MAMapPoint _field1;
    struct MAMapSize _field2;
};

struct MAMapSize {
    double _field1;
    double _field2;
};

struct MediaEncodeStreamInterface;

struct MediaEngineFactoryInterface;

struct ObjcAudioTrackSource;

struct ObjcVideoTrackSource;

struct PushStreamStallRecorder;

struct RTMPTransportInterface;

struct RxDirectionalEdgeInsets {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
};

struct SITICalculator {
    CDUnknownFunctionPointerType *_vptr$ObserverInterface;
    struct SITICalculatorObserver *observer_;
    struct scoped_refptr<avframework::SITIHelperInterface> siti_;
    int curCplxCategory_;
};

struct SITICalculatorObserver;

struct SITIHelperInterface;

struct TGFrame {
    char *_field1;
    long long _field2;
    int _field3;
    int _field4;
    int _field5;
    int _field6;
    basic_string_05660eb3 _field7;
    int _field8;
    int _field9;
    _Bool _field10;
    int *_field11;
};

struct TVLAudioWrapper {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
    CDUnknownFunctionPointerType _field4;
    void *_field5;
    void *_field6;
};

struct TVLVideoWrapper {
    CDUnknownFunctionPointerType _field1;
    CDUnknownFunctionPointerType _field2;
    void *_field3;
};

struct TransOffset {
    struct CGPoint _field1;
    struct CGPoint _field2;
    struct CGPoint _field3;
    struct CGPoint _field4;
};

struct TransportSendStallStatics {
    long long _totalReConnectCostTime;
    long long _totalReConnectCount;
    long long _totalSendVideoStallTime;
    long long _totalSendAudioStallTime;
    long long _totalSendVideoStallCount;
    long long _totalSendAudioStallCount;
    long long _totalPtsVideoStallTime;
    long long _totalPtsAudioStallTime;
    long long _totalPtsVideoStallCount;
    long long _totalPtsAudioStallCount;
};

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct UIOffset {
    double _field1;
    double _field2;
};

struct UIPropertyValue {
    CDUnknownFunctionPointerType *_field1;
    int _field2;
};

struct VeLivePusher;

struct VideoEncoderFactoryInterface;

struct VideoInfoStatisticManager;

struct VideoTrackInterface;

struct _DanceUIUIKitBaselineOffset {
    double _field1;
    double _field2;
};

struct _LynxBorderUnitValue {
    double _field1;
    long long _field2;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _VETouchInfo {
    unsigned int _field1;
    struct CGPoint _field2;
    float _field3;
    float _field4;
    int _field5;
    long long _field6;
};

struct _opaque_pthread_mutex_t {
    long long __sig;
    char __opaque[56];
};

struct _opaque_pthread_rwlock_t {
    long long __sig;
    char __opaque[192];
};

struct atomic<bool> {
    struct __cxx_atomic_impl<bool, std::__cxx_atomic_base_impl<bool>> {
        _Atomic _Bool __a_value;
    } __a_;
};

struct basic_string<char, std::char_traits<char>, std::allocator<char>> {
    struct __compressed_pair<std::basic_string<char>::__rep, std::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
};

struct bef_cloud_rendering_extended_output_data {
    _Bool _field1;
    double _field2;
    unsigned int _field3;
};

struct con_string_ {
    unsigned short _field1;
    unsigned char _field2[0];
};

struct contour_extra_ {
    unsigned char _field1;
    unsigned short _field2;
    unsigned char _field3[0];
};

struct contour_info_st {
    unsigned char _field1;
    unsigned short _field2;
    unsigned short _field3;
    struct con_string_ _field4;
    struct contour_extra_ _field5;
    unsigned char _field6;
    struct contour_item_ _field7[0];
};

struct contour_item_ {
    unsigned short _field1;
    struct point_ _field2[0];
};

struct hmd_opaque_backtrace_helper {
    unsigned char _field1[152];
};

struct hmdbt_backtrace {
    struct hmdbt_frame *_field1;
    unsigned long long _field2;
    char *_field3;
    unsigned long long _field4;
    unsigned int _field5;
    float _field6;
    int _field7;
    int _field8;
    int _field9;
};

struct hmdbt_frame;

struct mach_header_64 {
    unsigned int _field1;
    int _field2;
    int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
};

struct map<std::string, void *, std::less<std::string>, std::allocator<std::pair<const std::string, void *>>> {
    struct __tree<std::__value_type<std::string, void *>, std::__map_value_compare<std::string, std::__value_type<std::string, void *>, std::less<std::string>, true>, std::allocator<std::__value_type<std::string, void *>>> {
        void *__begin_node_;
        struct __compressed_pair<std::__tree_end_node<std::__tree_node_base<void *>*>, std::allocator<std::__tree_node<std::__value_type<std::string, void *>, void *>>> {
            struct __tree_end_node<std::__tree_node_base<void *>*> {
                void *__left_;
            } __value_;
        } __pair1_;
        struct __compressed_pair<unsigned long, std::__map_value_compare<std::string, std::__value_type<std::string, void *>, std::less<std::string>, true>> {
            unsigned long long __value_;
        } __pair3_;
    } __tree_;
};

struct mutex {
    struct _opaque_pthread_mutex_t __m_;
};

struct point_ {
    unsigned short _field1;
    unsigned short _field2;
};

struct scoped_refptr<avframework::ABRManager> {
    struct ABRManager *ptr_;
};

struct scoped_refptr<avframework::AudioTrackInterface> {
    struct AudioTrackInterface *ptr_;
};

struct scoped_refptr<avframework::BandwidthCoordinator> {
    struct BandwidthCoordinator *ptr_;
};

struct scoped_refptr<avframework::EstimateInterface<int>> {
    void *ptr_;
};

struct scoped_refptr<avframework::LiveVideoColorHist> {
    struct LiveVideoColorHist *ptr_;
};

struct scoped_refptr<avframework::LiveVideoVQScore> {
    struct LiveVideoVQScore *ptr_;
};

struct scoped_refptr<avframework::MediaEngineFactoryInterface> {
    struct MediaEngineFactoryInterface *ptr_;
};

struct scoped_refptr<avframework::ObjcAudioTrackSource> {
    struct ObjcAudioTrackSource *ptr_;
};

struct scoped_refptr<avframework::ObjcVideoTrackSource> {
    struct ObjcVideoTrackSource *ptr_;
};

struct scoped_refptr<avframework::PushStreamStallRecorder> {
    struct PushStreamStallRecorder *ptr_;
};

struct scoped_refptr<avframework::RTMPTransportInterface> {
    struct RTMPTransportInterface *ptr_;
};

struct scoped_refptr<avframework::SITIHelperInterface> {
    struct SITIHelperInterface *ptr_;
};

struct scoped_refptr<avframework::VideoTrackInterface> {
    struct VideoTrackInterface *ptr_;
};

struct shared_ptr<ILASDK::DecodeImageBuffer> {
    struct DecodeImageBuffer *_field1;
    struct __shared_weak_count *_field2;
};

struct unique_ptr<avframework::AudioDecoderFactoryInterface, std::default_delete<avframework::AudioDecoderFactoryInterface>> {
    struct __compressed_pair<avframework::AudioDecoderFactoryInterface *, std::default_delete<avframework::AudioDecoderFactoryInterface>> {
        struct AudioDecoderFactoryInterface *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::BmfSITICalculator, std::default_delete<avframework::BmfSITICalculator>> {
    struct __compressed_pair<avframework::BmfSITICalculator *, std::default_delete<avframework::BmfSITICalculator>> {
        struct BmfSITICalculator *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::IOSPlatformAudioDecodedCallback, std::default_delete<avframework::IOSPlatformAudioDecodedCallback>> {
    struct __compressed_pair<avframework::IOSPlatformAudioDecodedCallback *, std::default_delete<avframework::IOSPlatformAudioDecodedCallback>> {
        struct IOSPlatformAudioDecodedCallback *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::IOSPlatformObserverServer, std::default_delete<avframework::IOSPlatformObserverServer>> {
    struct __compressed_pair<avframework::IOSPlatformObserverServer *, std::default_delete<avframework::IOSPlatformObserverServer>> {
        struct IOSPlatformObserverServer *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::LiveSeiObserver, std::default_delete<avframework::LiveSeiObserver>> {
    struct __compressed_pair<avframework::LiveSeiObserver *, std::default_delete<avframework::LiveSeiObserver>> {
        struct LiveSeiObserver *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::MediaEngineInterface::MediaEncodeStreamInterface, std::default_delete<avframework::MediaEngineInterface::MediaEncodeStreamInterface>> {
    struct __compressed_pair<avframework::MediaEngineInterface::MediaEncodeStreamInterface *, std::default_delete<avframework::MediaEngineInterface::MediaEncodeStreamInterface>> {
        struct MediaEncodeStreamInterface *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::VideoEncoderFactoryInterface, std::default_delete<avframework::VideoEncoderFactoryInterface>> {
    struct __compressed_pair<avframework::VideoEncoderFactoryInterface *, std::default_delete<avframework::VideoEncoderFactoryInterface>> {
        struct VideoEncoderFactoryInterface *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::VideoInfoStatisticManager, std::default_delete<avframework::VideoInfoStatisticManager>> {
    struct __compressed_pair<avframework::VideoInfoStatisticManager *, std::default_delete<avframework::VideoInfoStatisticManager>> {
        struct VideoInfoStatisticManager *__value_;
    } __ptr_;
};

struct unique_ptr<avframework::VideoSinkInterface<avframework::VideoFrame>, std::default_delete<avframework::VideoSinkInterface<avframework::VideoFrame>>> {
    struct __compressed_pair<avframework::VideoSinkInterface<avframework::VideoFrame>*, std::default_delete<avframework::VideoSinkInterface<avframework::VideoFrame>>> {
        void *__value_;
    } __ptr_;
};

struct vImage_Buffer {
    void *_field1;
    unsigned long long _field2;
    unsigned long long _field3;
    unsigned long long _field4;
};

#pragma mark Typedef'd Structures

typedef struct {
    double _field1;
    double _field2;
    double _field3;
    double _field4;
} CDStruct_d2b197d1;

typedef struct {
    double _field1;
    double _field2;
} CDStruct_c3b9c2ee;

typedef struct {
    float _field1;
    float _field2;
    float _field3;
    _Bool _field4;
    float _field5;
    float _field6;
} CDStruct_7495972c;

typedef struct {
    long long value;
    int timescale;
    unsigned int flags;
    long long epoch;
} CDStruct_1b6d18a9;

typedef struct {
    long long _field1;
    long long _field2;
} CDStruct_912cb5d2;

typedef struct {
    CDStruct_1b6d18a9 _field1;
    CDStruct_1b6d18a9 _field2;
} CDStruct_5c5366e1;

typedef struct {
    struct CLLocationCoordinate2D _field1;
    CDStruct_c3b9c2ee _field2;
} CDStruct_26e8d939;

// Template types
typedef struct basic_string<char, std::char_traits<char>, std::allocator<char>> {
    struct __compressed_pair<std::basic_string<char>::__rep, std::allocator<char>> {
        struct __rep {
            union {
                struct __long {
                    char *_field1;
                    unsigned long long _field2;
                    unsigned long long _field3;
                } _field1;
                struct __short {
                    char _field1[23];
                    struct {
                        unsigned char _field1;
                    } _field2;
                } _field2;
                struct __raw {
                    unsigned long long _field1[3];
                } _field3;
            } _field1;
        } _field1;
    } _field1;
} basic_string_05660eb3;

typedef struct shared_ptr<ILASDK::DecodeImageBuffer> {
    struct DecodeImageBuffer *_field1;
    struct __shared_weak_count *_field2;
} shared_ptr_e6d331a6;

#pragma mark Typedef'd Unions

typedef union {
    _Bool _field1;
    int _field2;
    long long _field3;
    unsigned int _field4;
    unsigned long long _field5;
    float _field6;
    double _field7;
    id _field8;
    id _field9;
    id _field10;
    int _field11;
} CDUnion_cf1021d0;

