//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSIndexSet;

@protocol CKAMediaSequenceDiffProtocol
- (void)iterateMoves:(void (^)(long long, long long))arg1;
@property(nonatomic, readonly) NSIndexSet *changedIndexes;
@property(nonatomic, readonly) NSIndexSet *insertedIndexes;
@property(nonatomic, readonly) NSIndexSet *removedIndexes;
@end

