//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol CKASequenceProtocol
- (id)objectAtIndex:(long long)arg1;
@property(nonatomic, readonly) long long count;
@end

