//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class DUXActionSheet;

@protocol DUXActionSheetDelegate <NSObject>

@optional
- (void)didActionSheetDismiss:(DUXActionSheet *)arg1;
- (void)willActionSheetDismiss:(DUXActionSheet *)arg1;
- (void)actionSheetDidClickMaskArea:(DUXActionSheet *)arg1;
- (void)actionSheetDidClickCancelButton:(DUXActionSheet *)arg1;
- (void)actionSheet:(DUXActionSheet *)arg1 didClickButtonAtIndex:(long long)arg2;
@end

