//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class DUXAlertDialog;

@protocol DUXAlertDialogDelegate <NSObject>

@optional
- (void)alertDialogDealloc:(DUXAlertDialog *)arg1;
- (void)alertDialogWidthWillChanged:(double)arg1 dialog:(DUXAlertDialog *)arg2;
- (void)alertDialogDidDismiss:(DUXAlertDialog *)arg1;
- (void)alertDialogWillDismiss:(DUXAlertDialog *)arg1;
- (void)alertDialogDidClickMaskArea:(DUXAlertDialog *)arg1;
@end

