//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class DUXDialogUIConfigModel, UIView;

@protocol DUXAlertDialogBodyView <NSObject>
- (UIView *)duxAlertDialog_view;

@optional
- (UIView *)duxAlertDialog_viewWithConfig:(DUXDialogUIConfigModel *)arg1;
@end

