//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSAttributedString;

@protocol DUXBasicSheetProtocol <NSObject>

@optional
- (NSArray *)dux_sheetShouldRecognizeAsynchronousScrollViewArray;
- (NSAttributedString *)dux_titleForColoseButton;
@end

