//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol DUXGridBreakPointResponder <NSObject>

@optional
- (void)duxGrid_superViewDidChangeBreakPointFrom:(CDStruct_912cb5d2)arg1 toBreakPoint:(CDStruct_912cb5d2)arg2;
- (void)duxGrid_viewSizeDidChangeToBreakPoint:(CDStruct_912cb5d2)arg1;
- (void)duxGrid_viewDidChangeBreakPointFrom:(CDStruct_912cb5d2)arg1 toBreakPoint:(CDStruct_912cb5d2)arg2;
@end

