//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;

@protocol DUXInfoPanelContent <NSObject>
- (UIView *)duxInfoPanel_view;

@optional
- (UIView *)duxInfoPanel_view:(unsigned long long)arg1 maxScale:(double)arg2;
- (UIView *)duxInfoPanel_view:(unsigned long long)arg1;
@end

