//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/DUXToastDelegate-Protocol.h>

@class DUXLoadingToast;

@protocol DUXLoadingToastDelegate <DUXToastDelegate>

@optional
- (void)DUXLoadingToastDidClosed:(DUXLoadingToast *)arg1;
- (void)DUXLoadingToastDidStopAnimating:(DUXLoadingToast *)arg1;
- (void)DUXLoadingToastDidStartAnimating:(DUXLoadingToast *)arg1;
@end

