//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class DUXToast;

@protocol DUXToastDelegate <NSObject>

@optional
- (void)DUXToastWillRemoved:(DUXToast *)arg1;
- (void)DUXToastWillHidden:(DUXToast *)arg1;
- (void)DUXToastDidShow:(DUXToast *)arg1;
@end

