//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class FlowVideoPlayer;

@protocol FlowVideoPlayerDelegate <NSObject>
- (void)videoPlayer:(FlowVideoPlayer *)arg1 loadStateDidChange:(long long)arg2;
- (void)videoPlayer:(FlowVideoPlayer *)arg1 playbackStateDidChange:(long long)arg2;
@end

