//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol FPCreationModelPublicContext
- (id)fp_getRepoServiceWithAPI:(id)arg1;
- (id)fp_getReaderWithProtocol:(id)arg1;
@end

