//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSData, NSString;

@protocol GACAppAttestService <NSObject>
@property(readonly, getter=isSupported) _Bool supported;
- (void)generateAssertion:(NSString *)arg1 clientDataHash:(NSData *)arg2 completionHandler:(void (^)(NSData *, NSError *))arg3;
- (void)attestKey:(NSString *)arg1 clientDataHash:(NSData *)arg2 completionHandler:(void (^)(NSData *, NSError *))arg3;
- (void)generateKeyWithCompletionHandler:(void (^)(NSString *, NSError *))arg1;
@end

