//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HMDCleanupConfig, HMDModuleConfig, Heimdallr, NSMutableDictionary, NSString;

@protocol HeimdallrModule <NSObject>
@property(readonly, nonatomic) NSMutableDictionary *manualControlIdentifiersAlreadyUsed;
@property(readonly) _Bool hasExecutedTaskIndependentOfStart;
@property(readonly) _Bool isRunning;
@property(readonly) HMDModuleConfig *config;
@property(readonly, nonatomic) __weak Heimdallr *heimdallr;
- (void)updateConfig:(HMDModuleConfig *)arg1;
- (void)cleanupWithConfig:(HMDCleanupConfig *)arg1;
- (Class)storeClass;
- (void)runTaskIndependentOfStart;
- (void)stop;
- (void)start;
- (void)setupWithHeimdallr:(Heimdallr *)arg1;
- (NSString *)moduleName;

@optional
- (_Bool)exceptionDataSource;
- (_Bool)performanceDataSource;
- (void)prepareForDefaultStart;
- (_Bool)needSyncStart;
@end

