//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol HMDAttributes <NSObject>
+ (NSDictionary *)hmd_attributeMapDictionary;
@end

