//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;
@protocol HMDExcludeModule;

@protocol HMDExcludeModule <NSObject>
+ (id <HMDExcludeModule>)excludedModule;
@property(readonly, getter=isDetected) _Bool detected;
@property(readonly, getter=isFinishDetection) _Bool finishDetection;
- (NSString *)finishDetectionNotification;
@end

