//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSData;

@protocol HMDJSONObjectProtocol <NSObject>
- (NSData *)hmd_jsonDataWithOptions:(unsigned long long)arg1 error:(id *)arg2;
- (_Bool)hmd_isValidJSONObject;
@end

