//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol HMDURLHostProvider <NSObject>
- (_Bool)shouldEncrypt;

@optional
- (NSArray *)URLHostProviderDefaultHosts:(NSString *)arg1;
- (NSArray *)URLHostProviderInjectedHosts:(NSString *)arg1;
- (NSArray *)URLHostProviderConfigHosts:(NSString *)arg1;
@end

