//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HMDUITrackableContext;

@protocol HMDUITrackable <NSObject>
@property(readonly, nonatomic) HMDUITrackableContext *hmd_trackContext;
@end

