//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol HTSLiveNetworkStatusActions <NSObject>

@optional
- (void)checkNetworkForEnterWithCertainBlock:(void (^)(void))arg1;
- (void)changeToNetworkUnreachable;
- (void)changeToWifiNetwork;
- (void)changeToCellularNetwork;
- (void)onNetworkStatusChange:(long long)arg1;
@end

