//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol HTSLiveModelTrackProtocol <NSObject>
@property(retain, nonatomic, setter=setlogpb:) NSString *logpb;
@property(retain, nonatomic, setter=setrequestId:) NSString *requestId;
@end

