//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/HTSServiceUnavailable-Protocol.h>

@protocol HTSService <HTSServiceUnavailable>

@optional
+ (int)serviceScopeType;
- (void)onServiceInitInMainThread;
- (void)onServiceClearData;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceTerminate;
- (void)onServiceEnterForeground;
- (void)onServiceEnterBackground;
- (void)onServiceInit;
@end

