//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSError, NSNumber, NSString, NSURLRequest;
@protocol AnnieXContainerBaseProtocol, BDXContainerProtocol, BDXKitViewProtocol, BDXResourceProtocol, HunterContainerProtocol;

@protocol HunterContainerLifeCycleProtocol <NSObject>

@optional
- (void)container:(id <HunterContainerProtocol>)arg1 onUpdateLynxInfo:(NSDictionary *)arg2 bulletInfo:(NSDictionary *)arg3;
- (void)container:(id <HunterContainerProtocol>)arg1 onSetupLynxInfo:(NSDictionary *)arg2 bulletInfo:(NSDictionary *)arg3;
- (void)container:(id <HunterContainerProtocol>)arg1 didFallBackWithURL:(NSString *)arg2;
- (void)container:(id <HunterContainerProtocol>)arg1 didReceivePerformanceFirstLoad:(NSDictionary *)arg2 bulletPerfDict:(NSDictionary *)arg3;
- (void)containerDidConstructJSRuntime:(id <HunterContainerProtocol>)arg1;
- (void)containerDidPageUpdate:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 didEndAnimationWithDuration:(double)arg2 startFrame:(struct CGRect)arg3 finalFrame:(struct CGRect)arg4;
- (void)container:(id <HunterContainerProtocol>)arg1 didStartAnimationWithDuration:(double)arg2 startFrame:(struct CGRect)arg3 finalFrame:(struct CGRect)arg4;
- (void)containerDidClose:(id <HunterContainerProtocol>)arg1;
- (void)containerDidNavigatedStateChanged:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 updateTitle:(NSString *)arg2;
- (void)container:(id <HunterContainerProtocol>)arg1 didReceivePerformance:(NSDictionary *)arg2;
- (void)container:(id <HunterContainerProtocol>)arg1 didRecieveError:(NSError *)arg2;
- (void)containerDidUpdate:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 didLoadFailedWithUrl:(NSString *)arg2 error:(NSError *)arg3;
- (void)containerDidReuse:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 didFinishLoadWithURL:(NSString *)arg2;
- (void)containerDidFirstScreen:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 didFetchedResource:(id <BDXResourceProtocol>)arg2 error:(NSError *)arg3;
- (void)container:(id <HunterContainerProtocol>)arg1 didStartFetchResourceWithURL:(NSString *)arg2;
- (void)container:(id <HunterContainerProtocol>)arg1 didStartLoadingFailedWithUrl:(NSString *)arg2;
- (void)container:(id <HunterContainerProtocol>)arg1 didStartLoadingSuccessWithUrl:(NSString *)arg2;
- (void)containerDidStartLoading:(id <HunterContainerProtocol>)arg1;
- (void)containerWillStartLoading:(id <HunterContainerProtocol>)arg1;
- (void)containerOnTasmFinishByNative:(id <HunterContainerProtocol>)arg1;
- (void)container:(id <HunterContainerProtocol>)arg1 didChangeIntrinsicContentSize:(struct CGSize)arg2;
- (_Bool)container:(id <HunterContainerProtocol>)arg1 shouldStartLoadWithRequest:(NSURLRequest *)arg2 navigationType:(NSNumber *)arg3;
- (void)containerVCViewDidDisAppear:(id <BDXContainerProtocol>)arg1;
- (void)containerVCViewDidAppear:(id <HunterContainerProtocol>)arg1;
- (void)containerViewControllerViewDidDisAppear:(id <HunterContainerProtocol>)arg1;
- (void)containerOnHide:(id <HunterContainerProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerOnShow:(id <HunterContainerProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerViewControllerViewDidAppear:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerViewControllerViewDidLoad:(id <AnnieXContainerBaseProtocol>)arg1;
- (void)containerDidPageReady:(id <HunterContainerProtocol>)arg1 sourceParam:(NSDictionary *)arg2;
- (void)containerWillDestory:(id <HunterContainerProtocol>)arg1;
- (void)containerWillClose:(id <HunterContainerProtocol>)arg1;
- (void)kitViewWillCreate:(id <HunterContainerProtocol>)arg1;
- (void)containerDidCreated:(id <HunterContainerProtocol>)arg1 view:(id <BDXKitViewProtocol>)arg2;
- (void)containerWillCreated:(id <HunterContainerProtocol>)arg1 view:(id <BDXKitViewProtocol>)arg2;
- (void)lynxViewDidProcessRender:(id <HunterContainerProtocol>)arg1;
@end

