//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSError;
@protocol HunterLynxBackgroundRuntimeProtocol;

@protocol HunterLynxBackgroundRuntimeLifecycleProtocol <NSObject>

@optional
- (void)runtime:(id <HunterLynxBackgroundRuntimeProtocol>)arg1 OnReady:(NSDictionary *)arg2;
- (void)runtime:(id <HunterLynxBackgroundRuntimeProtocol>)arg1 didRecieveError:(NSError *)arg2;
@end

