//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSAttributedString, NSString, UIImage;

@protocol IESECSlidingTabConvertible <NSObject>
- (NSAttributedString *)iesec_tabSelectedAttributedTitle;
- (NSAttributedString *)iesec_tabAttributedTitle;
- (UIImage *)iesec_tabSelectedImage;
- (UIImage *)iesec_tabImage;
- (struct CGSize)iesec_selectedIconSize;
- (struct CGSize)iesec_iconSize;
- (NSString *)iesec_unSelectedColor;
- (NSString *)iesec_selectedColor;
- (NSString *)iesec_tabSelectedAccessibilityLabel;
- (NSString *)iesec_tabSelectedTitle;
- (NSString *)iesec_tabTitle;

@optional
- (unsigned long long)badgeImagePosition;
- (NSAttributedString *)badgeLabelAttributedText;
- (NSArray *)badgeImageURLArray;
- (_Bool)showRedDot;
@end

