//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESECAttributedContentManager;

@protocol IESECAttributedContentItemUpdateProtocol <NSObject>
- (void)iesec_attributedContentManagerDidUpdate:(IESECAttributedContentManager *)arg1;
@end

