//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESGurdDownloadPackageInfo, NSDictionary, NSError, NSString;

@protocol IESGurdEventDelegate <NSObject>

@optional
- (void)gurdDidSyncResourceWithAccessKey:(NSString *)arg1 succeed:(_Bool)arg2 statusDict:(NSDictionary *)arg3;
- (void)gurdDidAccessCachePackageWithAccessKey:(NSString *)arg1 channel:(NSString *)arg2 path:(NSString *)arg3;
- (void)gurdDidAccessInternalPackageWithAccessKey:(NSString *)arg1 channel:(NSString *)arg2 path:(NSString *)arg3 dataAccessPolicy:(long long)arg4;
- (void)gurdDidCleanCachePackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2;
- (void)gurdDidFinishApplyingPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 succeed:(_Bool)arg3 error:(NSError *)arg4;
- (void)gurdDidFinishDownloadingPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 packageInfo:(IESGurdDownloadPackageInfo *)arg3;
- (void)gurdWillDownloadPackageForAccessKey:(NSString *)arg1 channel:(NSString *)arg2 isPatch:(_Bool)arg3;
- (void)gurdDidRequestConfigForAccessKey:(NSString *)arg1 configsDictionary:(NSDictionary *)arg2;
@end

