//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol IESIMChatListBizCellInfoProtocol <NSObject>
- (NSString *)businessID;

@optional
- (_Bool)shouldStickOnTopByDefault;
- (void)stickOnTopStateDidChange:(_Bool)arg1 reason:(unsigned long long)arg2;
- (_Bool)enableCustomUpdateCellInfo;
- (NSArray *)sessionIDList;
@end

