//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class AWEIMBotSkill, NSDictionary;
@protocol IESIMConversationProtocol;

@protocol IESIMGroupAssistantSkillService <BCAAInstanceService>
- (void)updateGrowthPlan:(_Bool)arg1 completion:(void (^)(NSError *))arg2;
- (void)updateChatSkillStateForType:(unsigned long long)arg1 state:(_Bool)arg2 con:(id <IESIMConversationProtocol>)arg3 completion:(void (^)(NSError *))arg4;
- (void)editStateForType:(unsigned long long)arg1 con:(id <IESIMConversationProtocol>)arg2 extraParams:(NSDictionary *)arg3 display:(void (^)(NSError *))arg4 update:(void (^)(_Bool))arg5;
- (_Bool)canEditForType:(unsigned long long)arg1 con:(id <IESIMConversationProtocol>)arg2;
- (_Bool)stateForType:(unsigned long long)arg1 con:(id <IESIMConversationProtocol>)arg2;
- (_Bool)isEnabledForSkill:(AWEIMBotSkill *)arg1 con:(id <IESIMConversationProtocol>)arg2;
- (unsigned long long)dimensionForType:(unsigned long long)arg1;
@end

