//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIView;
@protocol IESIMToastProtocol;

@protocol IESIMToastDelegate <NSObject>

@optional
- (void)toastWillRemoved:(UIView<IESIMToastProtocol> *)arg1;
- (void)toastWillHidden:(UIView<IESIMToastProtocol> *)arg1;
- (void)toastDidShow:(UIView<IESIMToastProtocol> *)arg1;
@end

