//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESIMSendMessageResponse;

@protocol IESIMMessageSenderDelegate <NSObject>
- (void)iesim_didReceiveAsyncSendMessageResponse:(IESIMSendMessageResponse *)arg1;
- (void)iesim_didReceiveSendMessageResponse:(IESIMSendMessageResponse *)arg1;
@end

