//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@protocol IESIMConversationProtocol;

@protocol IESIMGroupPushCoordinatorProtocol <BCAAInstanceService>
- (void)didShowLastestMessagePushWithConversation:(id <IESIMConversationProtocol>)arg1;
- (_Bool)enableShowLastestMessagePushWithConversation:(id <IESIMConversationProtocol>)arg1;
@end

