//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@protocol IESIMConversationProtocol;

@protocol IESIMGroupMuteUtil <BCAAInstanceService>
- (void)checkIsEnableSwitchToUnmuteForConversation:(id <IESIMConversationProtocol>)arg1 completion:(void (^)(_Bool))arg2;
- (void)setFold:(_Bool)arg1 forConversation:(id <IESIMConversationProtocol>)arg2 completion:(void (^)(id <IESIMConversationOperationResponse>, NSError *))arg3;
- (void)setMuteMasks:(long long)arg1 forConversation:(id <IESIMConversationProtocol>)arg2 completion:(void (^)(id <IESIMConversationOperationResponse>, NSError *))arg3;
- (_Bool)isFoldWithConversation:(id <IESIMConversationProtocol>)arg1;
- (long long)muteSettingsMaskOfConversation:(id <IESIMConversationProtocol>)arg1;
@end

