//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESIMTickleAnimationContext;

@protocol IESIMTickleAnimationMessage <NSObject>

@optional
- (void)endPlayTickleAnimationWithContext:(id <IESIMTickleAnimationContext>)arg1;
- (void)willPlayTickleAnimationWithContext:(id <IESIMTickleAnimationContext>)arg1;
@end

