//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESIMContactPickerController;

@protocol IESIMContactPickerControllerDelegate <NSObject>

@optional
- (void)halfScreenContainerVCDidTapContainerToDismissController:(IESIMContactPickerController *)arg1;
- (void)halfScreenContainerVCWillDragToDismissController:(IESIMContactPickerController *)arg1;
- (void)contactPickerControllerDidDismissViewController:(IESIMContactPickerController *)arg1;
- (void)contactPickerControllerWillDismissViewController:(IESIMContactPickerController *)arg1;
- (void)contactPickerControllerDidShowViewController:(IESIMContactPickerController *)arg1;
- (void)contactPickerControllerWillShowViewController:(IESIMContactPickerController *)arg1;
@end

