//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class NSDictionary, NSString;

@protocol IESIMHunterJSRuntimeService <BCAAInstanceService>
- (NSDictionary *)userInfoData;
- (void)sendJSEvent:(NSString *)arg1 withParams:(NSDictionary *)arg2;
- (void)startJSRuntime;
@end

