//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class UIViewController;
@protocol IESIMContentSheetVCProtocol;

@protocol IESIMConversationB2CSMSService <BCAAInstanceService>
- (void)setSheetContainer:(UIViewController<IESIMContentSheetVCProtocol> *)arg1;
- (_Bool)currentStateIsVerify;
- (double)getHighContainerSheetHeight;
- (double)getContainerSheetHeight;
@end

