//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMMessage, AWEIMRefreshImageView;

@protocol IESIMMediaCoverDisplayProtocol <NSObject>
- (struct CGSize)mediaSize;
- (AWEIMMessage *)mediaMessage;
- (AWEIMRefreshImageView *)mediaImageView;
@end

