//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class NSDictionary, NSSet, NSString, UIImage;
@protocol IESIMConversationProtocol;

@protocol IESIMGroupInfoUtil <BCAAInstanceService>
- (NSString *)groupNumberForCon:(id <IESIMConversationProtocol>)arg1;
- (void)uploadAvatar:(UIImage *)arg1 completion:(void (^)(NSString *, UIImage *, NSError *))arg2;
- (void)setIcon:(NSString *)arg1 ext:(NSDictionary *)arg2 ofConversation:(id <IESIMConversationProtocol>)arg3 completion:(void (^)(id <IESIMConversationOperationResponse>, NSError *))arg4;
- (NSString *)avatarUrlForCon:(id <IESIMConversationProtocol>)arg1;
- (_Bool)isAvatarChangedForCon:(id <IESIMConversationProtocol>)arg1;
- (_Bool)isNameChangedForCon:(id <IESIMConversationProtocol>)arg1;
- (void)hasGroupsWithCheckBlock:(_Bool (^)(id <IESIMConversationProtocol>))arg1 maxCount:(unsigned long long)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)hasGroupsWithCategories:(NSSet *)arg1 maxCount:(unsigned long long)arg2 completion:(void (^)(_Bool, NSError *))arg3;
@end

