//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol IESIMUserServiceMessage <NSObject>

@optional
- (void)didFinishUpdateCurrentFullUserForReason:(unsigned long long)arg1;
- (void)didFinishUpdateAwemeUser;
- (void)didFinishLogoutWithUid:(NSString *)arg1;
- (void)didFinishLoginWithUid:(NSString *)arg1;
- (void)didFinishLogin;
@end

