//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESIMConversationProtocol, IESIMFriendsAlbumInflowListDataControllerInterface;

@protocol IESIMFriendsAlbumInflowListDataControllerDelegate <NSObject>
- (void)loadMoreWithListDataController:(id <IESIMFriendsAlbumInflowListDataControllerInterface>)arg1 complention:(void (^)(_Bool, NSArray *, NSError *))arg2;
- (id <IESIMConversationProtocol>)conForListDataController:(id <IESIMFriendsAlbumInflowListDataControllerInterface>)arg1;
@end

