//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIViewController;
@protocol IESIMSheetBaseVCProtocol;

@protocol IESIMSheetVCDelegate <NSObject>

@optional
- (void)sheetDealloc:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheet:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1 didChangeFrame:(struct CGRect)arg2 withUserInteraction:(_Bool)arg3;
- (void)sheetDidClickReturnButton:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheetDidDragToDismiss:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheetDidDismiss:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheetWillDismiss:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheetDidClickMaskArea:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (void)sheetDidClickCloseButton:(UIViewController<IESIMSheetBaseVCProtocol> *)arg1;
- (_Bool)sheetWillStayAfterClickMaskArea;
- (_Bool)sheetWillStayAfterClickCloseButton;
@end

