//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMCodeGenFriendsAlbumMediaInfoModel, NSString;
@protocol IESIMFriendsAlbumCacheModelProtocol;

@protocol IESIMFriendsAlbumActionMessage <NSObject>

@optional
- (void)updateAssetActionWithCid:(NSString *)arg1 assetId:(NSString *)arg2 assetModel:(AWEIMCodeGenFriendsAlbumMediaInfoModel *)arg3 cacheModel:(id <IESIMFriendsAlbumCacheModelProtocol>)arg4;
@end

