//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UICollectionViewCell;
@protocol IESIMB2CPickerListItemViewModelProtocol;

@protocol IESIMB2CPickerListCollectionViewCellDelegate <NSObject>
- (void)didClickCell:(UICollectionViewCell *)arg1 itemModel:(id <IESIMB2CPickerListItemViewModelProtocol>)arg2 completion:(void (^)(_Bool))arg3;
@end

