//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol AWEIMMessageListComponentCenter, AWEIMMsgRefreshHandlerProtocol, IESIMFriendsAlbumCacheModelProtocol;

@protocol IESIMFriendsAlbumCacheServiceInterface <NSObject>
- (void)removePreloadAssetsModelsForCid:(NSString *)arg1;
- (void)updatePreloadAssetsModelsForCid:(NSString *)arg1 assetsModels:(NSArray *)arg2;
- (NSArray *)preloadAssetsModelsForCid:(NSString *)arg1;
- (long long)friendsAlbumPreloadCounts;
- (id <AWEIMMsgRefreshHandlerProtocol>)refreshHandlerWithComponentCenter:(id <AWEIMMessageListComponentCenter>)arg1;
- (_Bool)supportRefreshWithComponentCenter:(id <AWEIMMessageListComponentCenter>)arg1;
- (id <IESIMFriendsAlbumCacheModelProtocol>)cacheModelForIdentifier:(NSString *)arg1;
- (void)storeCacheModel:(id <IESIMFriendsAlbumCacheModelProtocol>)arg1;
- (id <IESIMFriendsAlbumCacheModelProtocol>)makeCacheModel;
@end

