//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMMessage, AWEIMMessageConversation, AWEIMMessageViewModel, AWEIMNoticeMessage, AWEIMUser, NSDictionary, UIView;
@protocol IESIMConversationProtocol;

@protocol IESIMTickleService <NSObject>
- (void)cancelTickleAnimationForMessageViewModel:(AWEIMMessageViewModel *)arg1;
- (void)cancelAllTickleAnimation;
- (void)setReadedMaxTickleGlobalIndex:(long long)arg1 con:(id <IESIMConversationProtocol>)arg2 completion:(void (^)(NSError *))arg3;
- (long long)readedMaxTickleGlobalIndexForCon:(id <IESIMConversationProtocol>)arg1;
- (void)playTickleElfWidgetView:(UIView *)arg1 triggerMessage:(AWEIMNoticeMessage *)arg2 completion:(void (^)(NSString *, NSError *))arg3;
- (void)playTickleAvatarView:(UIView *)arg1 targetMessageViewModel:(AWEIMMessageViewModel *)arg2 triggerMessageViewModel:(AWEIMMessageViewModel *)arg3 completion:(void (^)(NSString *, NSError *))arg4;
- (void)tickleElfWidgetView:(UIView *)arg1 conversation:(AWEIMMessageConversation *)arg2 elfUser:(AWEIMUser *)arg3 memory:(NSDictionary *)arg4 completion:(void (^)(NSError *))arg5;
- (void)tickleAvatarView:(UIView *)arg1 messageViewModel:(AWEIMMessageViewModel *)arg2 memory:(NSDictionary *)arg3 completion:(void (^)(NSError *))arg4;
- (_Bool)enableTickleForConversation:(AWEIMMessageConversation *)arg1 fromUser:(AWEIMUser *)arg2 message:(AWEIMMessage *)arg3;
- (_Bool)enableTickleForConversation:(AWEIMMessageConversation *)arg1;
- (_Bool)isTickleFromMe:(AWEIMNoticeMessage *)arg1;
- (_Bool)isBeTickledMessage:(AWEIMNoticeMessage *)arg1;
- (_Bool)ticklePassiveState;
- (_Bool)tickleActiveState;
@end

