//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESIMChatSettingsItemModel, NSArray, NSNumber;
@protocol IESIMConversationProtocol;

@protocol IESIMGroupSettingsDataControllerProtocol <NSObject>
- (void)asyncSingleSettingsSectionsForCon:(id <IESIMConversationProtocol>)arg1 completion:(void (^)(NSArray *))arg2;
- (void)asyncGroupManagementSectionsForCon:(id <IESIMConversationProtocol>)arg1 completion:(void (^)(NSArray *))arg2;
- (NSArray *)groupManagementSectionsForCon:(id <IESIMConversationProtocol>)arg1;
- (void)asyncGetGroupSettingsSectionsForCon:(id <IESIMConversationProtocol>)arg1 completion:(void (^)(NSArray *))arg2;
- (NSArray *)groupSettingsSectionsForCon:(id <IESIMConversationProtocol>)arg1;
- (void)asyncGetGroupSettingsItemForCon:(id <IESIMConversationProtocol>)arg1 type:(long long)arg2 completion:(void (^)(IESIMChatSettingsItemModel *))arg3;
- (_Bool)isSupportFeatureWithType:(long long)arg1 forConversation:(id <IESIMConversationProtocol>)arg2;
- (IESIMChatSettingsItemModel *)groupSettingsItemWithType:(long long)arg1 forGroupType:(NSNumber *)arg2;
- (IESIMChatSettingsItemModel *)groupSettingsItemForCon:(id <IESIMConversationProtocol>)arg1 type:(long long)arg2;
- (void)asyncGetGroupSettingsItemPermissionForCon:(id <IESIMConversationProtocol>)arg1 type:(long long)arg2 completion:(void (^)(long long))arg3;
- (long long)groupSettingsItemPermissionForCon:(id <IESIMConversationProtocol>)arg1 type:(long long)arg2;
- (id)init;
@end

