//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class AWEIMCodeGenFileInfoModel, AWEIMCodeGenFriendsAlbumMediaInfoModel, AWEIMMessage, NSDictionary, NSString;
@protocol AWEIMMessageProtocol, IESIMConversationProtocol;

@protocol IESIMGroupCollectServiceInterface <BCAAInstanceService>
- (_Bool)isSupportPreviewMediaNewStyleWithMessage:(id <AWEIMMessageProtocol>)arg1;
- (long long)groupPreviewMediaStyleWithCon:(id <IESIMConversationProtocol>)arg1;
- (void)removeCollectWithCid:(NSString *)arg1 mediaId:(NSString *)arg2 fileId:(NSString *)arg3 extraParams:(NSDictionary *)arg4 completion:(void (^)(AWEBaseResponseModel *, NSError *))arg5;
- (void)addCollectWithCid:(NSString *)arg1 serverMessageId:(long long)arg2 extraParams:(NSDictionary *)arg3 completion:(void (^)(AWEBaseResponseModel *, NSError *))arg4;
- (NSString *)groupCollectMessageExtMediaIDKey;
- (NSString *)groupCollectMessageExtStateKey;
- (long long)groupCollectStateForMessage:(id <AWEIMMessageProtocol>)arg1;
- (_Bool)hasRemovePermissionForCon:(id <IESIMConversationProtocol>)arg1 message:(id <AWEIMMessageProtocol>)arg2 assetModel:(AWEIMCodeGenFriendsAlbumMediaInfoModel *)arg3 fileModel:(AWEIMCodeGenFileInfoModel *)arg4;
- (_Bool)hasEntrancePermissionForCon:(id <IESIMConversationProtocol>)arg1;
- (_Bool)isSupportGroupCollectWithCon:(id <IESIMConversationProtocol>)arg1;
- (_Bool)isSupportGroupCollectWithMessage:(AWEIMMessage *)arg1;
- (_Bool)enableGroupCollect;
@end

