//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UITableViewCell;

@protocol IESIMGroupJoinEntryLimitCellDelegate <NSObject>
- (void)jumpWithSchema:(UITableViewCell *)arg1 schema:(NSString *)arg2 needDismiss:(_Bool)arg3;
- (void)didTapCellJoinMemberBtn:(UITableViewCell *)arg1 schema:(NSString *)arg2;
- (void)didTapCellFollowBtn:(UITableViewCell *)arg1;
@end

