//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class NSDictionary, NSString;

@protocol IESIMGroupOpenCapabilityRouterService <BCAAInstanceService>
- (void)trackGroupOpenCapabilityInvokeEvent:(NSString *)arg1 invokeChannel:(long long)arg2 bizLine:(long long)arg3 bizScene:(NSString *)arg4 result:(long long)arg5 ext:(NSString *)arg6;
- (NSDictionary *)migrationCoverWithRouterParams:(NSDictionary *)arg1;
- (_Bool)canOpenViewControllerWithParams:(NSDictionary *)arg1;
- (void)openViewControllerWithRouterParams:(NSDictionary *)arg1 completion:(void (^)(long long))arg2;
@end

