//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class UIColor, UIControl, UIImage, UIView, UIViewController;
@protocol IESIMCustomModalTransitionContext;

@protocol IESIMCustomModalTransitionVCProtocol <NSObject>
@property(nonatomic) __weak id <IESIMCustomModalTransitionContext> transitionContext;

@optional
- (void)viewControllerDidDismissByAction:(long long)arg1;
- (void)viewControllerWillDismissByAction:(long long)arg1;
- (_Bool)customActionHandlerForAction:(long long)arg1;
- (double)customCornerRadius;
- (UIViewController *)childForPreferredContentSize;
- (UIColor *)transitionViewBackgroundColor;
- (_Bool)referredContentWidthBelongToAutoLayout;
- (_Bool)disablePreferredContentSizeBelongToAutoLayout;
- (UIColor *)pullIndicatorRegionBackgroundColor;
- (UIColor *)pullIndicatorViewBackgroundColor;
- (_Bool)disablePullIndicatorView;
- (_Bool)enablePullDismissGestureForPresentation;
- (void)layoutCloseButtonForPresentation:(UIView *)arg1;
- (UIControl *)closeButtonForPresentation;
- (UIImage *)closeButtonImageForPresentation;
- (_Bool)enableCloseButtonForPresentation;
- (_Bool)shouldBypassPresentationHook;
- (_Bool)disableDismissTapGestureForPresentation;
- (_Bool)transitionPresentedViewFullScreenEnable;
@end

