//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol IESIMContactPickerIdentifier <NSObject>
@property(readonly, copy, nonatomic) NSString *contactPicker_identifier;
@end

