//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class AWEIMUser, NSArray, NSDictionary, NSString;
@protocol IESIMConversationProtocol;

@protocol IESIMGroupAssistantDynamicService <BCAAInstanceService>
- (void)cacheBotInfoForCon:(id <IESIMConversationProtocol>)arg1 botInfo:(NSArray *)arg2;
- (NSArray *)cachedBotInfoForCon:(id <IESIMConversationProtocol>)arg1;
- (void)showGuidePanelWithCon:(id <IESIMConversationProtocol>)arg1 extraParams:(NSDictionary *)arg2 completion:(void (^)(NSError *))arg3;
- (void)showGroupAssistantSettingsWithCon:(id <IESIMConversationProtocol>)arg1 groupAssistantSecUid:(NSString *)arg2 groupAssistantUser:(AWEIMUser *)arg3 extraParams:(NSDictionary *)arg4 completion:(void (^)(NSError *))arg5;
- (void)showGroupAssistantProfileWithUid:(NSString *)arg1 secUid:(NSString *)arg2 cid:(NSString *)arg3 extraParams:(NSDictionary *)arg4 completion:(void (^)(NSError *))arg5;
- (_Bool)enableDynamicWithScene:(long long)arg1;
@end

