//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class AWEIMCodeGenPublicGroupCreateInfoModel, IESIMGroupOpenCapabilityModel, NSDictionary, NSObject, NSString, UIViewController;
@protocol IESIMCreateOpenGroupPageContextProtocol;

@protocol IESIMCreateOpenGroupService <BCAAInstanceService>
- (void)tryTransferToCreatePublicGroupPickerWithModel:(IESIMGroupOpenCapabilityModel *)arg1 completion:(void (^)(_Bool, NSDictionary *))arg2;
- (_Bool)enableTransferToCreatePublicGroupPickerWithModel:(IESIMGroupOpenCapabilityModel *)arg1;
- (void)checkIsEnableToCreateOpenGroupWithGroupType:(long long)arg1 checkSource:(long long)arg2 completion:(void (^)(_Bool, AWEIMCodeGenPublicGroupCreateInfoModel *, NSDictionary *))arg3;
- (_Bool)createOpenGroupV2IfNeed;
- (void)configurationPageContext:(id <IESIMCreateOpenGroupPageContextProtocol>)arg1 params:(NSDictionary *)arg2;
- (void)showCreateOpenGroupRuleViewControllerWithRuleInfo:(AWEIMCodeGenPublicGroupCreateInfoModel *)arg1;
- (void)transferToCreateOpenGroupPageWithEnterFrom:(NSString *)arg1 groupType:(long long)arg2 checkSource:(long long)arg3 pageContextConfiguration:(void (^)(id <IESIMCreateOpenGroupPageContextProtocol>))arg4 transferCompletion:(void (^)(_Bool))arg5;
- (_Bool)showCreateOpenGroupRuleBlockDialogWithTitle:(NSString *)arg1 subtitle:(NSString *)arg2 ruleInfo:(AWEIMCodeGenPublicGroupCreateInfoModel *)arg3;
- (void)fetchCreateOpenGroupDataWithGroupType:(long long)arg1 actionCheckSource:(long long)arg2 completion:(void (^)(AWEIMCodeGenGroupActionCheckResponseModel *, NSError *))arg3;
- (NSObject *)prefetchCreateOpenGroupPageDataWithGroupType:(long long)arg1 actionCheckSource:(long long)arg2;
- (id <IESIMCreateOpenGroupPageContextProtocol>)makeCreateOpenGroupPageContextWithBizLine:(long long)arg1 bizScene:(NSString *)arg2 invokeChannel:(long long)arg3 enterFrom:(NSString *)arg4;
- (id <IESIMCreateOpenGroupPageContextProtocol>)makeCreateOpenGroupPageContextWithEnterFrom:(NSString *)arg1;
- (UIViewController *)makeCreateOpenGroupViewControllerWithModel:(IESIMGroupOpenCapabilityModel *)arg1 ruleInfo:(AWEIMCodeGenPublicGroupCreateInfoModel *)arg2;
- (UIViewController *)makeCreateOpenGroupViewControllerWithContext:(id <IESIMCreateOpenGroupPageContextProtocol>)arg1;
- (Class)createOpenGroupViewControllerClass;
@end

