//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class IESIMGroupOpenCapabilityModel;

@protocol IESIMGroupOpenCapabilityNativeService <BCAAInstanceService>
- (_Bool)canOpenViewControllerWithModel:(IESIMGroupOpenCapabilityModel *)arg1;
- (void)openViewControllerWithModel:(IESIMGroupOpenCapabilityModel *)arg1 invokeChannel:(long long)arg2 completion:(void (^)(long long))arg3;
@end

