//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESIMGroupOpenCapabilityModel;

@protocol IESIMGroupOpenCapabilityViewController <NSObject>
- (id)initWithModel:(IESIMGroupOpenCapabilityModel *)arg1;

@optional
- (_Bool)needSmallDragger;
- (_Bool)enableDrag;
- (_Bool)supportFloatMode;
@end

