//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IESIMToastDelegate-Protocol.h>

@class UIView;
@protocol IESIMToastLoadingProtocol;

@protocol IESIMLoadingToastDelegate <IESIMToastDelegate>

@optional
- (void)loadingToastDidClosed:(UIView<IESIMToastLoadingProtocol> *)arg1;
- (void)loadingToastDidStopAnimating:(UIView<IESIMToastLoadingProtocol> *)arg1;
- (void)loadingToastDidStartAnimating:(UIView<IESIMToastLoadingProtocol> *)arg1;
@end

