//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class NSDictionary, NSError;
@protocol IESIMConversationOperationResponse, IESIMConversationProtocol;

@protocol IESIMGroupSettingsBasicItemsServiceProtocol <BCAAInstanceService>
- (NSDictionary *)commonTrackParamsWithConversation:(id <IESIMConversationProtocol>)arg1;
- (void)showErrorToastIfNeededWithResponse:(id <IESIMConversationOperationResponse>)arg1 error:(NSError *)arg2;
@end

