//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEIMCodeGenFriendsAlbumMediaInfoModel, NSArray, NSDictionary, NSString;
@protocol AWEIMMessageProtocol, IESIMConversationProtocol, IESIMMessageProtocol;

@protocol IESIMFriendsAlbumDataControllerInterface <NSObject>
- (NSString *)friendsAlbumMessageExtMediaIDKey;
- (NSString *)friendsAlbumMessageExtStateKey;
- (long long)friendsAlbumStateForIESMessage:(id <IESIMMessageProtocol>)arg1;
- (long long)friendsAlbumStateForMessage:(id <AWEIMMessageProtocol>)arg1;
- (_Bool)isSupportFriendsAlbumMessage:(id <AWEIMMessageProtocol>)arg1;
- (_Bool)isSupportFriendsAlbumCon:(id <IESIMConversationProtocol>)arg1;
- (void)updatePermission:(long long)arg1 con:(id <IESIMConversationProtocol>)arg2 completion:(void (^)(NSError *))arg3;
- (_Bool)hasRemovePermissionForCon:(id <IESIMConversationProtocol>)arg1 iesMessage:(id <IESIMMessageProtocol>)arg2 assetModel:(AWEIMCodeGenFriendsAlbumMediaInfoModel *)arg3;
- (_Bool)hasRemovePermissionForCon:(id <IESIMConversationProtocol>)arg1 message:(id <AWEIMMessageProtocol>)arg2 assetModel:(AWEIMCodeGenFriendsAlbumMediaInfoModel *)arg3;
- (_Bool)hasEntrancePermissionForCon:(id <IESIMConversationProtocol>)arg1;
- (long long)permissionForCon:(id <IESIMConversationProtocol>)arg1;
- (void)fetchAssetWithCid:(NSString *)arg1 mediaIds:(NSArray *)arg2 extraParams:(NSDictionary *)arg3 completion:(void (^)(AWEIMCodeGenFriendsAlbumGetResponseModel *, NSError *))arg4;
- (void)fetchAssetWithCid:(NSString *)arg1 cursor:(long long)arg2 limit:(long long)arg3 extraParams:(NSDictionary *)arg4 completion:(void (^)(AWEIMCodeGenFriendsAlbumGetResponseModel *, NSError *))arg5;
- (void)removeAssetWithCid:(NSString *)arg1 mediaId:(NSString *)arg2 extraParams:(NSDictionary *)arg3 completion:(void (^)(AWEIMCodeGenFriendsAlbumDeleteResponseModel *, NSError *))arg4;
- (void)addAssetWithCid:(NSString *)arg1 sourceInfo:(NSDictionary *)arg2 extraParams:(NSDictionary *)arg3 completion:(void (^)(AWEIMCodeGenFriendsAlbumAddResponseModel *, NSError *))arg4;
@end

