//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/BCAAInstanceService-Protocol.h>

@class AWEIMNoticeMessage, NSDictionary, NSNumber;
@protocol IESIMConversationProtocol, IESIMGroupAssistantGuideServiceDelegate;

@protocol IESIMGroupAssistantGuideService <BCAAInstanceService>
- (void)showGuidePanelWithCon:(id <IESIMConversationProtocol>)arg1 extraParams:(NSDictionary *)arg2 completion:(void (^)(NSError *))arg3;
- (_Bool)enableShowGuidePanelWithCon:(id <IESIMConversationProtocol>)arg1;
- (void)markDidSetGroupAssistantIsOpenIfNeedWithCon:(id <IESIMConversationProtocol>)arg1;
- (void)removeDelegate:(id <IESIMGroupAssistantGuideServiceDelegate>)arg1;
- (void)addDelegate:(id <IESIMGroupAssistantGuideServiceDelegate>)arg1;
- (void)insertNoticeWithWithType:(unsigned long long)arg1 con:(id <IESIMConversationProtocol>)arg2;
- (_Bool)isGroupAssistantGuideNoticeMessage:(AWEIMNoticeMessage *)arg1 inCon:(id <IESIMConversationProtocol>)arg2;
- (_Bool)enableInsertNoticeWithType:(unsigned long long)arg1 lastUnreadCount:(NSNumber *)arg2 con:(id <IESIMConversationProtocol>)arg3;
- (_Bool)enableInsertNoticeFeatureInCon:(id <IESIMConversationProtocol>)arg1;
@end

