//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLiveAutoRotateAction <NSObject>

@optional
- (void)didAutoRotateToOrientation:(long long)arg1 size:(struct CGSize)arg2;
- (void)animationForAutoRotateToOrientation:(long long)arg1 duration:(double)arg2 size:(struct CGSize)arg3;
- (void)willAutoRotateToOrientation:(long long)arg1 size:(struct CGSize)arg2;
@end

