//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLiveVideoPreviewStreamPaidDelegate <NSObject>
- (void)viewStatusDidChange:(long long)arg1;

@optional
- (void)updateCountDownForSecond:(long long)arg1;
- (void)freeTrialFinish;
@end

