//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLLPadUIAdaptionAutorotateProtocol <NSObject>

@optional
- (unsigned long long)iesll_supportedInterfaceOrientations;
- (_Bool)iesll_shouldAutorotate;
@end

