//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLiveDIContext;

@protocol IESLiveDIContextAttacher <NSObject>
+ (id <IESLiveDIContext>)attachingDIContext;
@property(retain, nonatomic) id <IESLiveDIContext> attachingDIContext;

@optional
- (void)didSetAttachingDIContext;
@end

