//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class PushMessageBaseObject;
@protocol IESLCMessageHandlerProtocol;

@protocol IESLCMessageHandlerService <NSObject>

@optional
- (void)ieslc_messageHandler:(id <IESLCMessageHandlerProtocol>)arg1 didReceiveMsg:(PushMessageBaseObject *)arg2 receivedTimestamp:(double)arg3;
- (void)ieslc_messageHandler:(id <IESLCMessageHandlerProtocol>)arg1 didSendMsg:(PushMessageBaseObject *)arg2 success:(_Bool)arg3;
- (void)ieslc_messageHandler:(id <IESLCMessageHandlerProtocol>)arg1 didReceiveMsg:(PushMessageBaseObject *)arg2;
@property(nonatomic) __weak id <IESLCMessageHandlerProtocol> messageHandler;
@end

