//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSNumber;

@protocol IESLiveIMDataSyncDelegate <NSObject>

@optional
- (void)subscribedSyncDataUpdatedWithValue:(id)arg1 oldVersion:(long long)arg2 newVersion:(long long)arg3 forChannel:(NSNumber *)arg4;
- (void)subscribedSyncDataWithValue:(id)arg1 version:(long long)arg2 forChannel:(NSNumber *)arg3;
- (void)subscribedSyncDataUpdatedWithValue:(id)arg1 oldVersion:(long long)arg2 newVersion:(long long)arg3;
- (void)subscribedSyncDataWithValue:(id)arg1 version:(long long)arg2;
@end

