//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray;

@protocol IESLiveRebornGiftPanelInterface <NSObject>
- (void)updateGiftPanelWithRecipients:(NSArray *)arg1 allMic:(_Bool)arg2 recipientChanged:(_Bool)arg3;
@end

