//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLiveChargeFullLoadingViewDelegate <NSObject>
- (void)onChargeFullLoadingViewCloseBtnClick;
@end

