//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HTSLiveRoom, HTSLiveUser;

@protocol IESliveEnterRoomData <NSObject>
- (id)copy;
- (HTSLiveRoom *)roomData;

@optional
- (_Bool)itemIsPseudoLiving;
- (HTSLiveUser *)itemUserInfo;
- (int)itemLiveStatus;
- (void)setRoomData:(HTSLiveRoom *)arg1;
@end

