//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESLiveFrameInfo, IESLiveVideoGiftController, IESLiveVideoGiftMetalConfiguration, IESLiveVideoGiftResourceModel, NSArray, NSError, NSURL, OS_dispatch_queue, UIView;
@protocol IESLiveVideoGiftAudioPlayerProtocol;

@protocol IESLiveVideoGiftControllerDelegate <NSObject>
- (void)didFinishPlayingWithError:(NSError *)arg1;

@optional
- (id <IESLiveVideoGiftAudioPlayerProtocol>)videoGiftController:(IESLiveVideoGiftController *)arg1 externalAudioPlayer:(IESLiveVideoGiftMetalConfiguration *)arg2 resource:(NSURL *)arg3 error:(id *)arg4;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 processAudioFrameWithRawData:(float **)arg2 samples:(int)arg3 timestamp:(long long)arg4;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 prepareAudioWithSampleRate:(double)arg2 channels:(unsigned int)arg3;
- (float)audioPlayVolume;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 isReadyToPlayOnView:(UIView *)arg2;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 didSetMetalViewFrame:(struct CGRect)arg2;
- (_Bool)videoControllerShouldDelayPlayIfAudioResouces:(OS_dispatch_queue *)arg1;
- (void)successParseConfigResourceModel:(IESLiveVideoGiftResourceModel *)arg1;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 sceneError:(NSError *)arg2 scene:(unsigned long long)arg3;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 didFrameCommandBufferCommitted:(IESLiveFrameInfo *)arg2 error:(NSError *)arg3;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 didEndPlayingFrame:(IESLiveFrameInfo *)arg2;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 willPlayFrame:(IESLiveFrameInfo *)arg2;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 didFinishPlayingWithError:(NSError *)arg2;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 playingWithNonFatalError:(NSError *)arg2;
- (void)frameCallBack:(double)arg1;
- (void)videoGiftController:(IESLiveVideoGiftController *)arg1 didTapMasks:(NSArray *)arg2;
@end

