//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HTSLiveUser, NSDictionary, NSNumber, NSString;

@protocol IESLiveRoomCommunityProtocol <NSObject>
@property(copy, nonatomic) NSString *drawOrder;
@property(copy, nonatomic) NSString *clickOrder;
@property(nonatomic) _Bool roomDidStop;
@property(retain, nonatomic) NSString *tagSource;
@property(retain, nonatomic) NSString *tagID;
@property(nonatomic) _Bool challengeUsed;
@property(nonatomic) _Bool dbUsed;
@property(nonatomic) _Bool selfDefinedUsed;
@property(nonatomic) _Bool operationUsed;
@property(nonatomic) _Bool searchUsed;
@property(nonatomic) _Bool recommendUsed;
@property(nonatomic) _Bool isMediaPreview;
@property(retain, nonatomic) HTSLiveUser *anchorChannelUser;
@property(nonatomic) _Bool isPseudoLiving;
@property(nonatomic) _Bool isEnterFromAppointment;
@property(nonatomic) _Bool declineToSwitchToFullScreen;
@property(retain, nonatomic) NSString *recommendMethod;
@property(retain, nonatomic) NSNumber *onlineCountByIM;
@property(retain, nonatomic, setter=setinsertTaskId:) NSString *insertTaskId;
@property(retain, nonatomic, setter=setroomLiveReason:) NSString *roomLiveReason;
- (long long)tempStateDurationWithShortTouchItemType:(long long)arg1 strategy:(int)arg2;
- (_Bool)channelUserFollow;
- (NSDictionary *)challengeTraceInfo;
- (_Bool)hasUsedTopic;
@end

