//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSNumber, UIView;

@protocol IESLiveFormatGiftAtomicModuleDelegate <NSObject>

@optional
- (void)animationEndPlay:(NSNumber *)arg1 assetId:(long long)arg2;
- (void)animationStartPlay:(NSNumber *)arg1 assetId:(long long)arg2;
- (UIView *)animationContainer;
- (UIView *)popUpContainer;
@end

