//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IESLiveGiftPanelRecipientEventAction-Protocol.h>

@class HTSLiveGiftItem, IESLiveGiveGiftDynamicParams, IESLiveGiveGiftTransaction, NSArray, UIScrollView, UIView;

@protocol IESLiveRefactGiftPanelEventAction <IESLiveGiftPanelRecipientEventAction>

@optional
- (void)gpe_rebornDynamicGiftPanelAddSubview:(UIView *)arg1 originalFrame:(struct CGRect)arg2 originalSuperview:(UIView *)arg3;
- (void)gpe_rebornDynamicGiftPanelEnterSearch:(_Bool)arg1;
- (void)gpe_dynamicGiftPanelLynxLoadFinished;
- (void)gpe_giftListCollectionViewWillDisplay;
- (void)gpe_giftOperationChangeToExpand:(_Bool)arg1 isFromExtraRefresh:(_Bool)arg2;
- (void)gpe_giftTopicExpandStatusDidChangeToExpand:(_Bool)arg1 pageType:(long long)arg2;
- (void)gpe_giftTopicExpandAnimationFinishWithToExpand:(_Bool)arg1 pageType:(long long)arg2;
- (void)gpe_giftTopicExpandStatusWillChangeToExpand:(_Bool)arg1 pageType:(long long)arg2;
- (void)gpe_showBigGiftCountDownView:(long long)arg1 item:(HTSLiveGiftItem *)arg2 transaction:(IESLiveGiveGiftTransaction *)arg3 dynamicParams:(IESLiveGiveGiftDynamicParams *)arg4;
- (void)gpe_giftListSortTypeDidChange:(long long)arg1;
- (void)gpe_giftPageScrollViewDidScroll:(UIScrollView *)arg1;
- (void)gpe_giftListScrollViewDidScroll:(UIScrollView *)arg1 tabIndex:(long long)arg2 layoutDirection:(long long)arg3;
- (void)gpe_giftListScrollViewDidEndDecelerating:(UIScrollView *)arg1 tabIndex:(long long)arg2 layoutDirection:(long long)arg3;
- (void)gpe_giftListScrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)gpe_giftListScrollViewWillBeginDragging:(UIScrollView *)arg1 tabIndex:(long long)arg2 layoutDirection:(long long)arg3;
- (void)gpe_onSelectedWithItem:(HTSLiveGiftItem *)arg1 changed:(_Bool)arg2;
- (void)gpe_updateFirstChargeBanner;
- (void)gpe_didChangeToGiftList:(UIScrollView *)arg1 index:(unsigned long long)arg2 active:(_Bool)arg3;
- (void)gpe_topicCollectionViewDataUpdate;
- (void)gpe_topicCollectionViewDidScrollTo:(long long)arg1;
- (void)gpe_topicIdDidChange:(long long)arg1 needScroll:(_Bool)arg2;
- (void)gpe_changeTopicWithId:(long long)arg1 pageType:(long long)arg2 needScroll:(_Bool)arg3;
- (void)gpe_changeTabBackgroundImageUrlList:(NSArray *)arg1;
- (void)gpe_initTabWithIndex:(unsigned long long)arg1;
- (void)gpe_changeTabWithIndex:(unsigned long long)arg1 active:(_Bool)arg2;
- (void)gpe_sendCurrentSelectedItem;
- (void)gpe_didGiftExtraInfoUpdate:(NSArray *)arg1;
- (void)gpe_didGiftPanelCollectionVMsUpdate;
- (void)gpe_dataSharing_currentSelectedGiftItemChangedFromItem:(HTSLiveGiftItem *)arg1 toItem:(HTSLiveGiftItem *)arg2;
- (void)gpe_dataSharing_currentPageTypeChangedFromType:(long long)arg1 toType:(long long)arg2;
- (void)gpe_dataSharing_currentPageIndexChangedFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)gpe_dataSharing_currentPageIndexWillChangeFromIndex:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
@end

