//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class BDImageView, NSString;

@protocol IESLLInfoPanelInterface <NSObject>
@property(copy, nonatomic) NSString *iesll_detail;
@property(copy, nonatomic) NSString *iesll_title;
@property(nonatomic) long long iesll_imageStyle;
@property(readonly, nonatomic) BDImageView *iesll_imageView;
- (void)addActionButtonWithStyle:(unsigned long long)arg1 sizeStyle:(unsigned long long)arg2 title:(NSString *)arg3 target:(id)arg4 action:(SEL)arg5;
@end

