//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HTSLiveStreamPlayer, IESLiveAudienceContainerContext;
@protocol IESLiveRoomService;

@protocol IESLiveAudiencePluginProtocol <NSObject>

@optional
- (void)didOrientationTransition:(long long)arg1;
- (void)willOrientationTransition:(long long)arg1;
- (void)viewDidDisappear;
- (void)viewWillDisappear;
- (void)viewDidAppear;
- (void)viewWillAppear;
- (void)didStartPlay:(HTSLiveStreamPlayer *)arg1;
- (void)didFirstFrame:(HTSLiveStreamPlayer *)arg1;
- (_Bool)couldCloseRoom;
- (void)didCloseRoomWithType:(unsigned long long)arg1 willReuse:(_Bool)arg2;
- (void)didEnterRoom:(id <IESLiveRoomService>)arg1;
- (void)didLoadRoomWithReuseFlag:(_Bool)arg1;
- (void)reuseWithContext:(IESLiveAudienceContainerContext *)arg1;
- (void)initWithContext:(IESLiveAudienceContainerContext *)arg1;
@end

