//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IOSClientComponent, NSString;

@protocol IESLiveBootableModel <NSObject>
@property(readonly, nonatomic, getter=isTemplateRoom) _Bool templateRoom;
@property(readonly, nonatomic) IOSClientComponent *iosClientComponentData;
@property(readonly, nonatomic) NSString *anchorIdentifier;
@property(readonly, nonatomic) _Bool isAnchor;
@property(readonly, copy, nonatomic) NSString *identifier;
@end

