//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IESLiveRebornGiftPanelInterface-Protocol.h>

@class IESLiveGiftPanelNonClipViewContainer, IESLiveRefactGiftPanelViewBuilderLayoutInfo, NSNumber, NSString, UIView;
@protocol IESLiveGiftPanelViewModelProtocol;

@protocol IESLiveGiftPanelViewProtocol <IESLiveRebornGiftPanelInterface>
- (void)showPanel;
- (void)jsbUpdateExtraInfoToReloadGiftPanelOperationSectionIfNeedWithGiftID:(NSNumber *)arg1 bizType:(NSString *)arg2;
- (void)hidePanel:(_Bool)arg1 source:(long long)arg2;
- (UIView *)topView;
- (UIView *)realPanelView;
- (UIView *)backgroundView;
- (IESLiveRefactGiftPanelViewBuilderLayoutInfo *)layoutInfo;
- (_Bool)marketingAreaDisplaying;
@property(nonatomic, readonly) _Bool onSearch;
@property(nonatomic, readonly) id <IESLiveGiftPanelViewModelProtocol> searchPanelViewModel;
@property(nonatomic, readonly) id <IESLiveGiftPanelViewModelProtocol> viewModel;
@property(nonatomic, readonly) IESLiveGiftPanelNonClipViewContainer *nonClipViewContainer;
@property(nonatomic, copy) CDUnknownBlockType onSearchBlock;
@property(nonatomic, copy) CDUnknownBlockType onWillShowBlock;
@property(nonatomic, copy) CDUnknownBlockType onHideBlock;

@optional
- (void)doAnimationWithView:(UIView *)arg1 expand:(_Bool)arg2 duration:(float)arg3 completion:(void (^)(_Bool))arg4;
@end

