//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDate;

@protocol IESLiveGiftPanelViewModelHelperDelegate <NSObject>
- (void)updateLastTrackTimeGiftSendFirstTime:(NSDate *)arg1;
- (void)hidePanel:(_Bool)arg1;
@end

