//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESLiveGeneralServiceLaunchParam, NSArray;

@protocol IESLiveGeneralServiceProtocol <NSObject>

@optional
+ (_Bool)serviceShouldActive:(IESLiveGeneralServiceLaunchParam *)arg1;
+ (NSArray *)serviceActionsWithParam:(IESLiveGeneralServiceLaunchParam *)arg1;
+ (NSArray *)serviceProtocolsWithParam:(IESLiveGeneralServiceLaunchParam *)arg1;
+ (unsigned long long)serviceImmediateLoadTypes;
- (_Bool)serviceNeedBringInAnchorRoom;
- (void)serviceDidReBind;
- (void)serviceUninstall;
- (void)serviceRoomDataReady:(id)arg1;
- (void)serviceDidLaunch;
- (void)serviceWillLaunchWithParam:(IESLiveGeneralServiceLaunchParam *)arg1;
@end

