//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class GPBInt64Array, NSNumber, NSString, PrivilegeInfo;

@protocol IESLiveRoomShowProtocol <NSObject>
@property(nonatomic) long long degradeLevel;
@property(readonly, nonatomic) NSNumber *currentGroupID;
@property(nonatomic) _Bool vsIsInnerFromDrawer;
@property(nonatomic) _Bool vsHasAppointmentTag;
@property(readonly, copy, nonatomic) NSString *cameraTypeTrackStr;
@property(readonly, nonatomic) _Bool isUnionLiveRoom;
@property(retain, nonatomic) GPBInt64Array *currentMainCameraEventIds;
@property(retain, nonatomic) NSString *currentMainCameraMatchID;
- (_Bool)isVRCamera;
- (_Bool)isUnpaidForVSPrivilegeCamera;
- (PrivilegeInfo *)cameraVSPrivilegeInfo;
- (NSString *)ticketType;
- (_Bool)hasVipPrivilegeInfo;
- (PrivilegeInfo *)vipPrivilegeInfo;
- (_Bool)isPaidStream;
@end

