//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESLLStatusBarController <NSObject>
- (long long)iesll_statusBarStyle;
- (_Bool)iesll_statusBarHidden;
@end

