//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMARModelAnchor, NSArray, NSData, NSDictionary, NSString, NSURL;

@protocol IESMMARProtocol <NSObject>
@property(nonatomic) _Bool slamWithoutExtraDeviceMotionData;
- (void)setAmbientLightColorTemperature:(double)arg1;
- (void)setAmbientLightIntensity:(double)arg1;
- (void)onReceiveEventData:(NSData *)arg1;
- (NSDictionary *)getARRootEntityTransformData;
- (NSData *)getARMeshSyncData;
- (void)setARMeshSyncData:(NSData *)arg1;
- (NSData *)getARSyncData;
- (void)setARSyncData:(NSData *)arg1;
- (void)updateEnvironmentCubeWithName:(NSString *)arg1 datas:(NSArray *)arg2 size:(struct CGSize)arg3;
- (_Bool)save3DObjectMeshToFile:(NSURL *)arg1;
- (_Bool)handleFinishManipulate3DObject;
- (_Bool)handleEndManipulate3DObject;
- (_Bool)handleManipulate3DObject;
- (_Bool)handleBeginManipulate3DObject;
- (void)updateEntityWithAnchor:(IESMMARModelAnchor *)arg1;
@end

