//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IESMMARProtocol-Protocol.h>
#import <AwemeCore/IESMMAudioProcessProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectBGMProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectChangeFaceProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectMessageProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectResourceProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectSLAMProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectTextProtocol-Protocol.h>
#import <AwemeCore/IESMMEffectTrackerDelegate-Protocol.h>
#import <AwemeCore/IESMMPixaloopProtocol-Protocol.h>
#import <AwemeCore/IVEEffectAlgorithmProtocol-Protocol.h>
#import <AwemeCore/IVEEffectEmojiProtocol-Protocol.h>
#import <AwemeCore/IVEEffectGeneralAudioProtocol-Protocol.h>
#import <AwemeCore/IVEGestureAmazingEngineProtocol-Protocol.h>
#import <AwemeCore/IVEGestureProtocol-Protocol.h>
#import <AwemeCore/VEEffectPrivateProtocol-Protocol.h>

@class HTSGLContext, HTSGLFilter, IESMMEffectConfig, IESMMEffectConnector, IESMMEffectTwoInputFilter, NSData, NSString;
@protocol IESMMEffectAlgorithmTwoInputFilterProtocol, IESMMEffectResourceProtocol><IESMMEffectBGMProtocol><IESMMARProtocol><IVEEffectFilterProtocol;

@protocol IESMMEffectGroupProtocol <VEEffectPrivateProtocol, IESMMEffectResourceProtocol, IESMMEffectMessageProtocol, IVEEffectAlgorithmProtocol, IESMMEffectChangeFaceProtocol, IESMMEffectBGMProtocol, IESMMEffectSLAMProtocol, IVEGestureProtocol, IVEGestureAmazingEngineProtocol, IESMMARProtocol, IESMMAudioProcessProtocol, IESMMEffectTrackerDelegate, IESMMEffectTextProtocol, IESMMPixaloopProtocol, IVEEffectEmojiProtocol, IVEEffectGeneralAudioProtocol>
+ (NSString *)effectVersion;
@property(retain, nonatomic) IESMMEffectTwoInputFilter *multiInputProcess;
@property(retain, nonatomic) id <IESMMEffectAlgorithmTwoInputFilterProtocol> twoInputAlgorithm;
@property(copy, nonatomic) CDUnknownBlockType effectBitmapRequestBlock;
@property(retain, nonatomic) IESMMEffectConnector *effectConnector;
@property(copy, nonatomic) CDUnknownBlockType getEffectPathBlock;
@property(nonatomic) _Bool disableEffects;
@property(nonatomic) _Bool enableFakeFace;
@property(nonatomic) struct __CVBuffer *currentPixelBuffer;
@property(nonatomic) _Bool isFrontCamera;
@property(nonatomic) unsigned long long usedEffect;
@property(readonly, nonatomic) IESMMEffectConfig *config;
- (void)setWarpxTrackingReinitType:(int)arg1;
- (NSData *)effect_get_et_data:(unsigned int)arg1;
- (void)effect_reset_et_data:(unsigned int)arg1;
- (CDStruct_d2b197d1)get_frame_cost_statistics;
- (void)reset_frame_cost_statistics;
- (void)preloadEffectAlgorithm;
- (void)setUseMakeupSegmentation:(_Bool)arg1;
- (void)setEffectClientState:(long long)arg1;
- (void)pauseEffectSticker:(_Bool)arg1;
- (void)getResourceMultiviewTag:(const char *)arg1 tag:(char *)arg2;
- (void)setFrameDeviceOrientation:(int)arg1;
- (void)setPreferredAlgorithmSize:(struct CGSize)arg1;
- (void)resetFilterChain:(_Bool)arg1 isProcessMultiInput:(_Bool)arg2;
- (void)releaseRenderManager;
- (id)initWithConfig:(IESMMEffectConfig *)arg1 context:(HTSGLContext *)arg2;
- (HTSGLFilter<IESMMEffectResourceProtocol><IESMMEffectBGMProtocol><IESMMARProtocol><IVEEffectFilterProtocol> *)effectFilter;
@end

