//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol IESMMEffectTextProtocol <NSObject>
@property(copy, nonatomic) CDUnknownBlockType effectBitmapRequestBlock;
- (NSArray *)getEffectTextArray;
- (void)setInputKeyboardHide:(_Bool)arg1;
- (void)setEffectText:(NSString *)arg1 arg1:(int)arg2 arg2:(int)arg3 arg3:(const char *)arg4;
- (void)setInputLanguage:(NSString *)arg1;
- (long long)effectTextLimit;
@end

