//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, VEABInfo, VEConfigCenter;

@protocol IESMMEffectHelperProtocol <NSObject>
- (void)setupEffectLogAppLogFunc;
- (void)setEffectLogLevel:(int)arg1;
- (void)enableEffectLog:(_Bool)arg1;
- (void)setupEffectLogMonitorFunc;
- (NSString *)getEffectVersion;
- (NSString *)effectSDKCommit;
- (void)setEffectDidLoadBlock:(void (^)(void))arg1;

@optional
- (void)configEffectABValue:(id)arg1 key:(NSString *)arg2 type:(unsigned long long)arg3;
- (VEABInfo *)getEffectABInfoByKey:(NSString *)arg1 type:(unsigned long long)arg2;
- (unsigned long long)veTypeFromEffectType:(int)arg1;
- (void)configRegisterABTest:(VEConfigCenter *)arg1;
@end

