//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESMMEffectSLAMProtocol <NSObject>
- (_Bool)isSLAMRunning;
- (_Bool)getSLAMPlaneDetectStatus;
- (long long)getSLAMStatus;
@end

