//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESMMAudioProcessProtocol <NSObject>
@property(nonatomic) _Bool useAudioBackend;
@property(nonatomic) _Bool effectNodeInAudioChainIsOn;
@property(nonatomic) _Bool useAudioEffectSticker;
- (_Bool)setMusicPlayMode:(long long)arg1;
- (void)sendAudioBuffer:(struct AudioBuffer)arg1;
- (void)finishAudioResolve;
- (void)resolveAudio:(struct opaqueCMSampleBuffer *)arg1;
- (_Bool)needResolveAudio;
- (void)finishAudioProcess;
- (void)processAudio:(struct opaqueCMSampleBuffer *)arg1;
- (_Bool)needProcessAudio;
- (void)setAudioSampleRate:(int)arg1 channel:(int)arg2;
@end

