//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMAlgorithmResultData, NSArray, NSDictionary, NSString, UIImage;

@protocol IESMMPixaloopProtocol <NSObject>
- (IESMMAlgorithmResultData *)detectPhoto:(UIImage *)arg1 withAlgorithm:(NSString *)arg2 withAlgorithmType:(unsigned long long)arg3;
- (long long)detectPhoto:(UIImage *)arg1 withAlgorithm:(NSString *)arg2;
- (void)renderMaterialsToPreview:(NSDictionary *)arg1;
- (void)renderPicImage:(NSArray *)arg1 keys:(NSArray *)arg2;
- (void)renderPicImage:(UIImage *)arg1 withKey:(NSString *)arg2;
- (void)renderPic:(NSString *)arg1 withKey:(NSString *)arg2;
- (_Bool)detectPhotoContent:(UIImage *)arg1 withAlgorithm:(NSString *)arg2;
@end

