//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESMMEffectBGMProtocol <NSObject>
- (void)amazingMuteBGM:(_Bool)arg1;
- (void)muteBGM:(_Bool)arg1;
- (void)pause:(unsigned long long)arg1;
- (void)start:(unsigned long long)arg1;
- (void)enableBGM:(_Bool)arg1;
@end

