//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMEffectConnector;

@protocol IESMMEffectConnectorDelegate <NSObject>

@optional
- (void)messageConnector:(IESMMEffectConnector *)arg1 didReciveAlgorithm:(unsigned long long)arg2;
@end

