//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMEffectMessage, NSString;

@protocol IESMMEffectMessageProtocol <NSObject>
@property(copy, nonatomic) CDUnknownBlockType messageHandler;
- (void)active;
- (void)inactive;
- (void)sendMessageToEffect:(IESMMEffectMessage *)arg1;

@optional
- (int)setEffectExportDestPath:(NSString *)arg1;
- (void)bef_effect_clear_event;
- (void *)getEffectHandle;
@end

