//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IESMMTrackerConfigure, NSDictionary, NSString;

@protocol IESMMTrackerHelperProtocol <NSObject>
+ (void)configureMMTracker:(IESMMTrackerConfigure *)arg1;
- (void)trackExceptionWithType:(NSString *)arg1 callback:(void (^)(NSError *))arg2;
- (void)hmdTrackService:(NSString *)arg1 status:(long long)arg2 extra:(NSDictionary *)arg3;
- (void)localConfigureMMTracker:(IESMMTrackerConfigure *)arg1;
@end

