//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class HTSVideoData, IESComposerJudgeResult, IESMMEffectStickerInfo, NSArray, NSMutableArray, NSString, VEColorSpaceInfo, VEComposerAction, VEComposerPreloadContextParam, VEEffectImage;

@protocol IESMMEffectResourceProtocol <NSObject>
@property(copy, nonatomic) CDUnknownBlockType playTimeCallback;
- (void)refreshEffectColorSpace:(VEColorSpaceInfo *)arg1;
- (void)releaseCaptureImage:(VEEffectImage *)arg1;
- (VEEffectImage *)getEffectCapturedImageWithKey:(NSString *)arg1;
- (void)setEffectAudioPlayerEndMessage:(long long)arg1;
- (void)setEffectVideoPlayerFactory:(void *)arg1;
- (void)setEffectAudioPlayerFactory:(void *)arg1;
- (void)setEffectGenBitmap:(int (^)(char **, int *, int *, int *, char *, int, struct))arg1 utf32Gen:(int (^)(char **, int *, int *, int *, unsigned int *, int, struct))arg2;
- (void)setEffectSrtData:(const struct IESSrtDdata *)arg1;
- (void)setEffectFontPath:(NSString *)arg1 faceIndex:(long long)arg2;
- (_Bool)getColorFilterIntensity:(NSString *)arg1 outIntensity:(float *)arg2;
- (int)setColorFilterIntensity:(NSString *)arg1 inIntensity:(float)arg2;
- (_Bool)switchColorFilterIntensity:(NSString *)arg1 inFilterPath:(NSString *)arg2 inPosition:(float)arg3 inLeftIntensity:(float)arg4 inRightIntensity:(float)arg5;
- (void)setMaxStickerMemoryCache:(unsigned long long)arg1;
- (void)applyMusicNodes:(NSString *)arg1;
- (int)switchFilterWithPathOne:(NSString *)arg1 pathTwo:(NSString *)arg2 progress:(double)arg3;
- (void)applyReshape:(NSString *)arg1 withIndensity:(struct IESIndensityParam_t)arg2;
- (void)applyIndensity:(struct IESIndensityParam_t)arg1 type:(long long)arg2;
- (NSArray *)queryPreloadComposerNodes;
- (_Bool)cancelPreloadComposerNodes:(NSArray *)arg1;
- (_Bool)updatePreloadComposerNodes:(NSArray *)arg1 preloadContext:(VEComposerPreloadContextParam *)arg2;
- (VEComposerAction *)dumpComposerNodes;
- (_Bool)dumpComposerNodes:(HTSVideoData *)arg1;
- (void)judgeComposersPriority:(NSMutableArray *)arg1 tag:(NSMutableArray *)arg2 completion:(void (^)(NSMutableArray *))arg3;
- (void)judgeComposerPriority:(NSString *)arg1 tag:(NSString *)arg2 completion:(void (^)(IESComposerJudgeResult *))arg3;
- (IESComposerJudgeResult *)judgeComposerPriority:(NSString *)arg1 tag:(NSString *)arg2;
- (IESComposerJudgeResult *)judgeComposerPriority:(NSString *)arg1 oldNodePath:(NSString *)arg2 tag:(NSString *)arg3;
- (NSArray *)getCurrentComposerNodes;
- (float)getValueForComposerNode:(NSString *)arg1 key:(NSString *)arg2;
- (_Bool)operateComposerNodes:(VEComposerAction *)arg1;
- (_Bool)enableEffectSuperResolution:(_Bool)arg1 targetWidth:(double)arg2;
- (_Bool)updateMutipleComposerNodes:(NSArray *)arg1 keys:(NSArray *)arg2 values:(NSArray *)arg3;
- (_Bool)updateComposerNode:(NSString *)arg1 key:(NSString *)arg2 value:(double)arg3;
- (_Bool)replaceComposerNodesWithNew:(NSArray *)arg1 old:(NSArray *)arg2;
- (_Bool)operateComposerNodes:(NSArray *)arg1 operation:(long long)arg2;
- (_Bool)setAgeMaleMakeupState:(_Bool)arg1;
- (_Bool)setMaleMakeupState:(_Bool)arg1;
- (_Bool)removeComposerNodes:(NSArray *)arg1;
- (_Bool)appendComposerNodes:(NSArray *)arg1;
- (_Bool)reloadComposerNodes:(NSArray *)arg1;
- (_Bool)applyComposerNodes:(NSArray *)arg1;
- (void)setEffectFaceMakeupOpacity:(NSString *)arg1 maleOpacity:(double)arg2 femaleOpacity:(double)arg3 completion:(void (^)(int))arg4;
- (void)applyEffectKey:(NSString *)arg1 pixelBuffer:(struct __CVBuffer *)arg2;
- (int)applyEffectKey:(NSString *)arg1 image:(NSString *)arg2;
- (int)applyEffectWithInfo:(IESMMEffectStickerInfo *)arg1 type:(long long)arg2 completion:(void (^)(int))arg3;
- (void)setRealPlayCallback:(CDUnknownFunctionPointerType)arg1 userdata:(void *)arg2;
@end

