//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AVAsset, NSString;

@protocol IESMMAudioProcessorExProtocol <NSObject>
@property(nonatomic) _Bool needsPreProcess;
- (NSString *)preProcessAudio:(AVAsset *)arg1;
- (const char *)getParameterAsChunk:(int *)arg1;
- (void)setPreprocessParametersFromChunk:(NSString *)arg1;
- (_Bool)setPreprocessing:(_Bool)arg1;
- (void)processSampleBuff:(struct opaqueCMSampleBuffer *)arg1;
- (void)seekToTime:(double)arg1;
- (void)processAudioBufferList:(struct AudioBufferList *)arg1 atTime:(double)arg2;
- (id)initWithAudioResPath:(NSString *)arg1 audioSample:(int)arg2 audioChannel:(int)arg3;
@end

