//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray;
@protocol IESServiceRegister;

@protocol IESServiceRegister <NSObject>
- (void)registIdentifiers:(NSArray *)arg1 scope:(long long)arg2 instance:(id)arg3;
- (void)registIdentifiers:(NSArray *)arg1 scope:(long long)arg2 provider:(id (^)(void))arg3;
@property(nonatomic, readonly) id <IESServiceRegister> parent;
@end

