//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IESDisposable;

@protocol IESServiceProvider <NSObject>
- (id)tryResolveObject:(id)arg1;
- (id <IESDisposable>)provideBlockNeedServiceResponse:(void (^)(id))arg1 forProtocol:(id)arg2;
- (id)resolveObject:(id)arg1;
@end

