//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IVEBrushProtocol-Protocol.h>
#import <AwemeCore/IVEBrushStickerProtocol-Protocol.h>
#import <AwemeCore/IVEGestureAmazingEngineProtocol-Protocol.h>
#import <AwemeCore/IVEGestureProtocol-Protocol.h>
#import <AwemeCore/IVEInfoStickerPinProtocol-Protocol.h>
#import <AwemeCore/IVEInfoStickerProtocol-Protocol.h>
#import <AwemeCore/IVESrtInfoStickerProtocol-Protocol.h>
#import <AwemeCore/IVETextInfoStickerProtocol-Protocol.h>

@class HTSGLContext, IESMMEngineConfig, NSMutableArray, NSString, VEColorSpaceInfo;

@protocol IESVideoEngineEffectProtocol <IVEBrushProtocol, IVEInfoStickerProtocol, IVEGestureProtocol, IVEGestureAmazingEngineProtocol, IVETextInfoStickerProtocol, IVESrtInfoStickerProtocol, IVEInfoStickerPinProtocol, IVEBrushStickerProtocol>
@property(copy, nonatomic) CDUnknownBlockType stickerSizeNeedChangeBlock;
@property(copy, nonatomic) CDUnknownBlockType stickerAddBlock;
@property(copy, nonatomic) CDUnknownBlockType imageBlock;
@property(nonatomic) _Bool needHighResolution;
@property(retain, nonatomic) NSMutableArray *infoStickers;
- (void)refreshEffectColorSpace:(VEColorSpaceInfo *)arg1;
- (NSString *)getInfoStickerKeyFrameInfo:(unsigned long long)arg1 stickerID:(unsigned long long)arg2;
- (void)updateInfoStickerKeyFrameInfoWithStickerId:(long long)arg1;
- (void)updateInfoStickerKeyFrameInfo;
- (void)removeAllTargets;
- (long long)stickerCount;
- (id)initWithConfig:(IESMMEngineConfig *)arg1 context:(HTSGLContext *)arg2;
@end

