//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSError, NSString, NSURL, TTVideoEngineLoadInfo;
@protocol IESVideoPlayerProtocol;

@protocol IESVideoPlayerDelegate <NSObject>

@optional
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubLoadFinished:(_Bool)arg2 info:(TTVideoEngineLoadInfo *)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubSwitchCompleted:(_Bool)arg2 currentSubtitleId:(long long)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubtitleInfoRequested:(id)arg2 error:(NSError *)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubtitleInfoCallBack:(NSDictionary *)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubtitleInfoCallBack:(NSString *)arg2 pts:(unsigned long long)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onSubtitleInfoCallBack:(NSDictionary *)arg2 context:(NSDictionary *)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 onMaskInfoCallBack:(NSString *)arg2 pts:(unsigned long long)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didUpdateVRHeadPoseWithYaw:(double)arg2 pitch:(double)arg3 roll:(double)arg4;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackRate:(double)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didFetchVideoModel:(id)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 noVideoDataToDownloadForURL:(NSURL *)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didFinishVideoDataDownloadForURL:(NSURL *)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didChangeStallState:(long long)arg2 actionType:(long long)arg3 reason:(unsigned long long)arg4;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didChangeStallState:(long long)arg2;
- (void)playerDidReadyForDisplay:(id <IESVideoPlayerProtocol>)arg1;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 playbackFailedForURL:(NSString *)arg2 error:(NSError *)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 playbackFailedWithError:(NSError *)arg2;
- (void)playerWillLoopPlaying:(id <IESVideoPlayerProtocol>)arg1;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 didChangePlaybackStateWithAction:(long long)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 downloadProgressWithKey:(NSString *)arg2 videoId:(NSString *)arg3 cacheSize:(long long)arg4 mediaSize:(long long)arg5;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 switchAudioInfoCompleted:(unsigned long long)arg2;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 avOutsyncStateDidChangedWithType:(unsigned long long)arg2 extraInfo:(NSDictionary *)arg3;
- (void)player:(id <IESVideoPlayerProtocol>)arg1 deviceOpenedWithStreamType:(long long)arg2;
@end

