//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol IGListDiffable, NSObject;

@protocol IGListDiffable
- (_Bool)isEqualToDiffableObject:(id <IGListDiffable>)arg1;
- (id <NSObject>)diffIdentifier;
@end

