//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString, VEAlgorithmPreConfig, VEEffectAlgorithmParam;

@protocol IVEAlgorithmPublicProtocol <NSObject>
- (void)setAlgorithmReplayMmode:(long long)arg1 filePath:(NSString *)arg2;
- (void)setAlgorithmResultsRequirement:(unsigned long long)arg1 callback:(void (^)(NSDictionary *))arg2;
- (void)setAlgorithmRequirement:(unsigned long long)arg1 algorithmParam:(unsigned long long)arg2 enableDetect:(_Bool)arg3;
- (void)setAlgorithmRuntimeParam:(NSDictionary *)arg1;
- (void)setAlgorithmExtraParam:(VEEffectAlgorithmParam *)arg1;
- (void)setAlgorithmPreConfig:(VEAlgorithmPreConfig *)arg1;
@end

