//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, VEBrushStickerInfo, VEBrushStickerParam;

@protocol IVEBrushStickerProtocol <NSObject>
- (VEBrushStickerInfo *)getBrushSticker:(long long)arg1 bboxCalculatedByPixel:(_Bool)arg2;
- (int)updateBrushSticker:(long long)arg1 param:(VEBrushStickerParam *)arg2;
- (long long)addBrushSticker:(NSString *)arg1 params:(NSString *)arg2;
@end

