//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIImage;

@protocol IVEEffectEmojiProtocol <NSObject>
- (void)setRenderCacheIntValueByKey:(NSString *)arg1 value:(int)arg2;
- (void)setRenderCacheTextureOrientationByKey:(NSString *)arg1 value:(long long)arg2;
- (void)setRenderCacheTextureWithBufferByKey:(NSString *)arg1 value:(UIImage *)arg2;
- (void)setRenderCacheTextureByKey:(NSString *)arg1 value:(NSString *)arg2;
- (void)setRenderCacheStringByKey:(NSString *)arg1 value:(NSString *)arg2;
@end

