//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/IVEAlgorithmPublicProtocol-Protocol.h>

@class HTSGLFramebuffer, IESMMAlgorithmResultEffectBachData, IESMMImageScanParam, NSString;

@protocol IVEEffectAlgorithmProtocol <IVEAlgorithmPublicProtocol>
- (Class)resultClassWithAlgoType:(unsigned long long)arg1;
- (IESMMAlgorithmResultEffectBachData *)getBachAlgorithmResultWithAlgoType:(unsigned long long)arg1;
- (void)removeAllBachAlgorithm;
- (void)addBachAlgorithmName:(NSString *)arg1 config:(NSString *)arg2 algoType:(unsigned long long)arg3;
- (void)applyEffectKey:(NSString *)arg1 pixelBuffer:(struct __CVBuffer *)arg2;
- (void)releaseAlgorithm;
- (void)cleanPipelineProcessorTask;
- (int)enableFilterAutomaticRecommmand:(_Bool)arg1 type:(unsigned long long)arg2;
- (void)forceDrawBuffer:(long long)arg1;
- (void)forceRenderBuffer:(long long)arg1;
- (void)diableOrientationWhenAlgorithmDetect:(_Bool)arg1;
- (void)forceDetectBuffer:(long long)arg1;
- (void)resetFaceResultDataBlock:(void (^)(NSArray *))arg1;
- (void)resetFaceResultBlock:(void (^)(_Bool))arg1;
- (void)detectFramewithImageData:(const void *)arg1 imageSize:(struct CGSize)arg2;
- (void)detectFramewithBuffer:(struct __CVBuffer *)arg1;
- (void)updateAlgorithmResultAccordMsg:(unsigned long long)arg1;
- (void)enableRefFrame:(_Bool)arg1 withFrameBuffer:(HTSGLFramebuffer *)arg2 size:(struct CGSize)arg3;
- (_Bool)enableAudioManager:(_Bool)arg1;
- (_Bool)resetAudioManagerCallback:(NSString * (^)(NSString *, NSString *))arg1;
- (void)setStyleAlgorithm:(_Bool)arg1;
- (void)getDistortionParam:(void (^)(NSString *, NSString *))arg1;
- (void)setStickerReq:(void *)arg1;
- (void)resetFaceResultCallback:(void (^)(void *))arg1;
- (void)resetFacePointBlock:(void (^)(struct CGPoint))arg1;
- (_Bool)setScanParam:(IESMMImageScanParam *)arg1;
- (_Bool)setMattingDetectModel:(_Bool)arg1;
- (_Bool)setHandDetectLowpower:(_Bool)arg1;
- (_Bool)updatFaceDectectIntervalTime:(int)arg1;
- (unsigned long long)currentExtraAlgorithmRequirements;

@optional
- (_Bool)getClustingResult;
@end

