//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IVEEffectPublicProtocol <NSObject>
@property(nonatomic) _Bool disableEffects;
- (void)enableStickerBGM:(_Bool)arg1;
- (void)setMaxStickerMemoryCache:(unsigned long long)arg1;
- (void)setEffectResouceLoadTimeout:(long long)arg1;
@end

