//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol IVEGestureAmazingEngineProtocol <NSObject>
- (_Bool)toggleGestureRecognition:(_Bool)arg1 type:(int)arg2;
- (_Bool)isTouchGestureRecognitionEnabled:(int)arg1;
- (_Bool)updateTouchInfoForRecognition:(struct _VETouchInfo)arg1;
@end

