//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IESInfoStickerPinSelectedArea, NSData;

@protocol IVEInfoStickerPinProtocol
- (void)setInfoStickerRestoreMode:(long long)arg1;
- (long long)getStickerPinStatus:(long long)arg1;
- (void)recoveryPinResult:(long long)arg1;
- (void)cancelPin:(long long)arg1;
- (void)stopPin:(long long)arg1;
- (int)startPin:(long long)arg1 pinTime:(float)arg2 startTime:(float)arg3 duration:(float)arg4;
- (void)preparePin:(CDStruct_1b6d18a9)arg1;

@optional
- (_Bool)getInfoStickerIsDynamic:(long long)arg1;
- (void)setPinTime:(long long)arg1 pinTime:(double)arg2;
- (void)clearStickerPinResult:(long long)arg1;
- (int)setPinSelectedArea:(long long)arg1 areaParams:(IESInfoStickerPinSelectedArea *)arg2;
- (NSData *)getPinResult:(long long)arg1 realVideoSize:(struct CGSize)arg2;
- (NSData *)getPinResult:(long long)arg1;
- (void)recoveryPinResult:(long long)arg1 withPinData:(NSData *)arg2;
- (void)savePinResult:(long long)arg1 realVideoSize:(struct CGSize)arg2;
- (void)savePinResult:(long long)arg1;
@end

