//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol IVESrtInfoStickerProtocol <NSObject>
- (void)getSrtOffset:(long long)arg1 offsetX:(float *)arg2 offsetY:(float *)arg3;
- (void)saveSrtInitialPos:(long long)arg1 posX:(double)arg2 posY:(double)arg3;
- (void)setSrtInitialPos:(long long)arg1 posX:(double)arg2 posY:(double)arg3;
- (void)setSrtAudioInfo:(long long)arg1 seqIn:(double)arg2 trimIn:(double)arg3 duration:(double)arg4 audioCycle:(_Bool)arg5;
- (void)setSrtManipulate:(long long)arg1 state:(_Bool)arg2;
- (void)setSrtFont:(long long)arg1 fontPath:(NSString *)arg2;
- (void)setSrtInfo:(long long)arg1 srt:(NSString *)arg2;
- (void)setSrtColor:(long long)arg1 red:(double)arg2 green:(double)arg3 blue:(double)arg4 alpha:(double)arg5;
@end

