//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol IVETextInfoStickerProtocol <NSObject>
- (int)setTextStickerTextParams:(long long)arg1 textParams:(NSString *)arg2;
- (long long)addTextStickerWithUserInfo:(NSDictionary *)arg1;
- (long long)addTextSticker;

@optional
+ (NSString *)convertTextToTextTemplate:(NSString *)arg1;
+ (NSString *)getInfoStickerTemplateParams:(NSString *)arg1;
- (long long)addRichTextStickerWithJson:(NSString *)arg1 userInfo:(NSDictionary *)arg2;
- (NSString *)getTemplateStickerTextParams:(long long)arg1;
- (int)setTemplateStickerTextParams:(long long)arg1 textParams:(NSString *)arg2;
- (unsigned long long)addTemplateWithResourcePath:(NSString *)arg1 dependResourceParams:(NSString *)arg2;
- (void)updateStickerID:(long long)arg1 toNewStickerID:(long long)arg2;
- (int)setTextStickerAnim:(long long)arg1 animType:(int)arg2 animPath:(NSString *)arg3 duration:(double)arg4;
- (int)setTextStickerPreviewMode:(long long)arg1 previewMode:(int)arg2;
@end

