//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IWKPluginHandleResultObj, WKWebView, WKWebViewConfiguration;

@protocol IWKPluginWebViewBuilder <NSObject>

@optional
- (IWKPluginHandleResultObj *)webViewWillDealloc:(WKWebView *)arg1;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didInitWithFrame:(struct CGRect)arg2 configuration:(WKWebViewConfiguration *)arg3;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 willInitWithFrame:(struct CGRect)arg2 configuration:(WKWebViewConfiguration *)arg3;
@end

