//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IWKPluginHandleResultObj, NSError, NSURLAuthenticationChallenge, WKNavigation, WKNavigationAction, WKNavigationResponse, WKWebView;

@protocol IWKPluginNavigationDelegate <NSObject>

@optional
- (IWKPluginHandleResultObj *)webViewWebContentProcessDidTerminate:(WKWebView *)arg1;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didReceiveAuthenticationChallenge:(NSURLAuthenticationChallenge *)arg2 completionHandler:(void (^)(long long, NSURLCredential *))arg3;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didFailNavigation:(WKNavigation *)arg2 withError:(NSError *)arg3;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didFinishNavigation:(WKNavigation *)arg2;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didCommitNavigation:(WKNavigation *)arg2;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didFailProvisionalNavigation:(WKNavigation *)arg2 withError:(NSError *)arg3;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didReceiveServerRedirectForProvisionalNavigation:(WKNavigation *)arg2;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 didStartProvisionalNavigation:(WKNavigation *)arg2;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 decidePolicyForNavigationResponse:(WKNavigationResponse *)arg2 decisionHandler:(void (^)(long long))arg3;
- (IWKPluginHandleResultObj *)webView:(WKWebView *)arg1 decidePolicyForNavigationAction:(WKNavigationAction *)arg2 decisionHandler:(void (^)(long long))arg3;
@end

