//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class IWKPluginHandleResultObj, NSDictionary, NSString;

@protocol IWKPluginObject <NSObject>
@property(retain, nonatomic) NSString *uniqueID;
@property(nonatomic) _Bool enable;
@property(readonly, nonatomic) long long priority;

@optional
- (IWKPluginHandleResultObj *)triggerCustomEvent:(NSString *)arg1 context:(NSDictionary *)arg2;
@end

