//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol JSModule <NSObject>
+ (NSDictionary *)methodLookup;
+ (NSString *)name;
- (id)initWithParam:(id)arg1;
- (id)init;

@optional
+ (NSDictionary *)attributeLookup;
@end

