//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class LiveStreamSession, NSString;

@protocol LiveStreamSessionProtocol <NSObject>
- (void)streamSession:(LiveStreamSession *)arg1 errorType:(long long)arg2 onError:(long long)arg3 errorMessage:(NSString *)arg4;
- (void)streamSession:(LiveStreamSession *)arg1 onStatusChanged:(long long)arg2;
@end

