//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AudioSource, NSDictionary;

@protocol LiveStreamAudioCaptureDelegate <NSObject>
- (void *)audioCoderSinkForByteAudio;
- (AudioSource *)audioCoderSinkForNormal;
- (void)callbackAudioLog:(NSDictionary *)arg1;
- (void)admCreatedSuccess:(_Bool)arg1;
- (void)processEarMonitorData:(void *)arg1 size:(unsigned int)arg2 sampleRate:(int)arg3 timeStamp:(long long)arg4 mNumberChannels:(unsigned int)arg5 numberOfFrames:(int)arg6;
- (void)pullMicAudio:(void *)arg1 size:(unsigned int)arg2 sampleRate:(int)arg3 timeStamp:(long long)arg4 mNumberChannels:(unsigned int)arg5 numberOfFrames:(int)arg6 processedData:(void *)arg7 earMonitorData:(void *)arg8;
- (void)pullMicAudio:(void *)arg1 size:(unsigned int)arg2 timeStamp:(long long)arg3 mNumberChannels:(unsigned int)arg4 numberOfFrames:(unsigned int)arg5 processedData:(void *)arg6 earMonitorData:(void *)arg7;
- (void)pushPlayerAECAudioData:(struct AudioBufferList *)arg1 frames:(int)arg2 bytesPerSample:(int)arg3 channels:(int)arg4 sampleRate:(int)arg5;
- (void)pushPlayerAudioData:(struct AudioBufferList *)arg1 frames:(int)arg2 bytesPerSample:(int)arg3 channels:(int)arg4 sampleRate:(int)arg5;

@optional
- (void)onAudioCaptureEvent:(long long)arg1;
@end

