//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol LSLiveEffectMusicProtocol <NSObject>
- (void)setMusicPlayTimeRequestCallback:(double (^)(void))arg1;
- (void)setMusicNodeFilepath:(NSString *)arg1;
@end

