//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString, UIImage;

@protocol LSLiveEffectPhotoProtocol <NSObject>
- (void)releaseEffectCapturedImage:(void *)arg1;
- (int)getEffectCapturedImage:(void *)arg1 withKey:(NSString *)arg2;
- (void)setEffectRenderCacheTextureWithImage:(UIImage *)arg1 algorithmType:(NSString *)arg2;
- (void)fetchEffectDetectPhotoContentWithImage:(UIImage *)arg1 algorithmType:(NSString *)arg2 isLastPhone:(_Bool)arg3 callback:(void (^)(int))arg4;
@end

