//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSString;

@protocol LSLiveEffectResourceProtocol <NSObject>
- (int)refreshResourceMemory;
- (NSDictionary *)getFrameCostStatistics;
- (int)resetFrameCostStatistics;
- (int)composerExclusionCompareWithNewNodePath:(NSString *)arg1 oldNodePath:(NSString *)arg2 nodeKey:(NSString *)arg3 result:(int *)arg4;
- (int)composerCheckNodeExclusionWithNodePath:(NSString *)arg1 nodeTag:(NSString *)arg2 result:(int *)arg3;
- (void)setDoubleViewRect:(double)arg1 leftY:(double)arg2 width:(double)arg3 height:(double)arg4;
- (void)setMaxStickerMemoryCache:(unsigned long long)arg1;
- (float)getFilterIntensity:(NSString *)arg1;
- (void)switchFilterWithPathOne:(NSString *)arg1 pathTwo:(NSString *)arg2 progress:(double)arg3 leftIntensity:(float)arg4 rightIntensity:(float)arg5;
- (void)switchFilterWithPathOne:(NSString *)arg1 pathTwo:(NSString *)arg2 progress:(double)arg3;
- (void)applyReshape:(NSString *)arg1 withIntensity:(struct LSLiveIntensityParam_t)arg2;
- (void)applyIntensity:(struct LSLiveIntensityParam_t)arg1 type:(long long)arg2;
- (int)updateComposerMultipleNodes:(int)arg1 paths:(NSArray *)arg2 keys:(NSArray *)arg3 values:(NSArray *)arg4;
- (int)updateComposerNode2:(const char *)arg1 tag:(const char *)arg2 value:(double)arg3;
- (int)updateComposerNode:(NSString *)arg1 tag:(NSString *)arg2 value:(double)arg3;
- (NSArray *)getComposerNodePath;
- (int)replaceComposerNodes:(NSArray *)arg1 withNewNodes:(NSArray *)arg2 andTags:(NSArray *)arg3;
- (int)executeComposerCommand:(unsigned long long)arg1 forNodes:(NSArray *)arg2 withTags:(NSArray *)arg3;
- (int)executeComposerCommand:(unsigned long long)arg1 forNodes:(NSArray *)arg2;
- (int)setComposerMode:(int)arg1 orderType:(int)arg2;
- (void)resumeEffect:(long long)arg1;
- (void)pauseEffect:(long long)arg1;
- (int)applyEffectKey:(NSString *)arg1 image:(NSString *)arg2;
- (int)setColorIntensity:(float)arg1;
- (int)executeEffectCommand:(long long)arg1 params:(NSDictionary *)arg2 callback:(void (^)(NSDictionary *))arg3;
- (int)applyEffect:(NSString *)arg1 type:(long long)arg2;
@end

