//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class LSGLContext, NSString;
@protocol LSEffectTrackHandleProtocol;

@protocol LSLiveEffectProcessProtocol <NSObject>

@optional
+ (NSString *)effectVersion;
- (void)updateAlgorithmUsedEffectFlagByTrackHandle;
- (void)recycleEffectTrackHandle:(id <LSEffectTrackHandleProtocol>)arg1;
- (id <LSEffectTrackHandleProtocol>)acquireEffectTrackHandle;
- (int)effectResetETDataWithType:(int)arg1;
- (int)effectGetETData:(id *)arg1 withType:(int)arg2;
- (int)setEffectNotifyKeyboardHide:(_Bool)arg1;
- (int)setEffectInputText:(NSString *)arg1 arg1:(int)arg2 arg2:(int)arg3 arg3:(NSString *)arg4;
- (void)setLogLevel:(int)arg1;
- (void *)getEffectHandle;
- (_Bool)releaseSDK;
- (void)initial;
- (void)setAudioPlayerFactory:(void *)arg1;
- (void)getExpressionInfo:(void *)arg1;
- (void)getAnimatedEmoticonsInfo:(void *)arg1;
- (int)getFaceCount;
- (void)getFaceInfo:(void *)arg1;
- (_Bool)setAuxWithTexture:(unsigned int)arg1 key:(NSString *)arg2 width:(unsigned int)arg3 height:(unsigned int)arg4;
- (_Bool)effectProcessingWithFBO:(id)arg1 dstFBO:(id)arg2 frameTime:(CDStruct_1b6d18a9)arg3 forceDetect:(_Bool)arg4;
- (_Bool)effectProcessingWithTexture:(unsigned int)arg1 dstTexture:(unsigned int)arg2 timeStamp:(double)arg3;
- (void)updateConfig:(id)arg1;
- (id)initWithConfig:(id)arg1 context:(LSGLContext *)arg2;
@end

