//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol LSLiveEffectABInfoProtocol <NSObject>
+ (NSString *)getEffectABInfoWithLicense:(NSString *)arg1;
+ (void)setEffectABInfoWithKey:(NSString *)arg1 value:(id)arg2 dataType:(int)arg3;
- (NSString *)getEffectABLicense;
- (void)setEffectCacheDirectory:(NSString *)arg1;
- (void)setEffectABLicense:(NSString *)arg1;
@end

