//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol LSLiveEffectAudioProtocol <NSObject>
- (int)audioEarMonitorEffectProcess:(float **)arg1 outBuffer:(float **)arg2 samplesPerChannel:(int)arg3 realSamplesPerChannel:(int *)arg4 channels:(int)arg5 sampleRate:(int)arg6;
- (int)audioEffectProcess:(float **)arg1 outBuffer:(float **)arg2 samplesPerChannel:(int)arg3 realSamplesPerChannel:(int *)arg4 channels:(int)arg5 sampleRate:(int)arg6;
- (int)get_audio_effect_status;
- (int)remove_effect_audio_config;
- (int)set_effect_set_audio_config:(NSString *)arg1;
- (int)setRendercacheIntValue:(NSString *)arg1 intValue:(int)arg2;
- (int)setRenderCacheStringValue:(NSString *)arg1 jsonStr:(NSString *)arg2;
- (_Bool)enableAudioRecognize;
- (int)recognizeAudio:(const short *)arg1 samplePerChannel:(int)arg2 realSamplesPerChannel:(int *)arg3;
- (NSDictionary *)getSpeechRecognitionKeywords;
- (int)setSpeechRecognitionKeywords:(NSDictionary *)arg1;
@end

