//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;
@protocol LSEffectContourInfoHelperDataSource;

@protocol LSLiveEffectAlgorithmProtocol <NSObject>
- (_Bool)setRoiInfoBlock:(void (^)(NSDictionary *))arg1;
- (_Bool)effectAddBachAlgorithmConfig:(NSString *)arg1;
- (void)updateAlgorithmResultAccordMsg:(unsigned long long)arg1;
- (void)setAlgorithmResultRequirement:(unsigned long long)arg1 withCallbackBlock:(void (^)(NSArray *, unsigned long long))arg2;
- (void)setAlgorithmRequirement:(unsigned long long)arg1 algorithmParam:(unsigned long long)arg2 enableDetect:(_Bool)arg3;
- (void)setEffectContourInfoHelperDataSource:(id <LSEffectContourInfoHelperDataSource>)arg1;
- (void)resetBachAlgorithmUncompressContourBlock:(void (^)(struct contour_info_st *))arg1;
- (void)resetBachAlgorithmContourBlock:(void (^)(void *, int, struct))arg1;
- (void)resetEffectMsgListnerBlock:(void (^)(int, int, int, NSString *))arg1;
- (void)resetFacePointBlock:(void (^)(struct CGPoint))arg1;
- (_Bool)setMattingDetectModel:(_Bool)arg1;
- (_Bool)setHandDetectLowpower:(_Bool)arg1;
- (_Bool)updatFaceDectectIntervalTime:(int)arg1;
@end

