//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSString;

@protocol LSSAppInfoDelegate <NSObject>
- (id)getAppInfoForKey:(NSString *)arg1 defaultValue:(id)arg2;
@end

