//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class AWEAwemeModel, AWECodeGenListenDiversionBtnModel, NSString;

@protocol LunaListenFeedBottomViewProtocol <NSObject>
- (void)updateModel:(AWEAwemeModel *)arg1 btnModel:(AWECodeGenListenDiversionBtnModel *)arg2;
@property(nonatomic, readonly) _Bool isWeakStyle;
@property(nonatomic, readonly) AWEAwemeModel *awemeModel;
@property(nonatomic, readonly) NSString *styleType;
@property(nonatomic, readonly) NSString *subTag;
@property(nonatomic, readonly) NSString *directText;
@property(nonatomic, copy) CDUnknownBlockType onCancelClicked;
@property(nonatomic, copy) CDUnknownBlockType onConfirmClicked;
@end

