//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/LynxEventTargetBase-Protocol.h>

@class LynxEventDetail, NSDictionary, NSMutableDictionary, NSSet, NSString, UIEvent, UIGestureRecognizer;
@protocol LynxEventTarget;

@protocol LynxEventTarget <LynxEventTargetBase>
- (void)onEventFire:(_Bool)arg1 withEventID:(long long)arg2;
- (void)startEventFire:(_Bool)arg1 withEventID:(long long)arg2;
- (void)onEventBubble:(_Bool)arg1 withEventID:(long long)arg2;
- (void)startEventBubble:(long long)arg1;
- (void)onEventCapture:(_Bool)arg1 withEventID:(long long)arg2;
- (void)startEventCapture:(long long)arg1;
- (void)setEventID:(long long)arg1;
- (id <LynxEventTarget>)rootLynxPageUI;
- (void)setChildrenLynxPageUI:(NSMutableDictionary *)arg1;
- (NSMutableDictionary *)childrenLynxPageUI;
- (void)setParentLynxPageUI:(id <LynxEventTarget>)arg1;
- (id <LynxEventTarget>)parentLynxPageUI;
- (long long)getGestureArenaMemberId;
- (_Bool)isOnResponseChain;
- (void)offResponseChain;
- (void)onResponseChain;
- (_Bool)dispatchEvent:(LynxEventDetail *)arg1;
- (_Bool)dispatchTouch:(NSString *)arg1 touches:(NSSet *)arg2 withEvent:(UIEvent *)arg3;
- (void)onPseudoStatusFrom:(int)arg1 changedTo:(int)arg2;
- (_Bool)enableTouchPseudoPropagation;
- (_Bool)eventThrough;
- (_Bool)blockNativeEvent:(UIGestureRecognizer *)arg1;
- (_Bool)consumeSlideEvent:(double)arg1;
- (_Bool)ignoreFocus;
- (_Bool)shouldHitTest:(struct CGPoint)arg1 withEvent:(UIEvent *)arg2;
- (NSDictionary *)gestureMap;
- (NSDictionary *)eventSet;
- (_Bool)containsPoint:(struct CGPoint)arg1;
- (id <LynxEventTarget>)hitTest:(struct CGPoint)arg1 withEvent:(UIEvent *)arg2;
- (id <LynxEventTarget>)parentTarget;
- (int)pseudoStatus;
- (long long)signature;
@end

