//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/MTLModel-Protocol.h>

@class NSDictionary, NSString, NSValueTransformer;
@protocol MTLTransformerErrorHandling;

@protocol MTLJSONSerializing <MTLModel>

@optional
+ (NSValueTransformer<MTLTransformerErrorHandling> *)customArrayValueTransformerForModelClass:(Class)arg1;
+ (NSDictionary *)propertyToModelClassInArrayMap;
+ (Class)classForParsingJSONDictionary:(NSDictionary *)arg1;
+ (NSValueTransformer *)JSONTransformerForKey:(NSString *)arg1;
+ (NSDictionary *)JSONKeyPathsByPropertyKey;
+ (_Bool)automaticallyDefaultMapping;
@end

