//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSCopying-Protocol.h>
#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSSet, NSString;
@protocol MTLModel;

@protocol MTLModel <NSObject, NSCopying>
+ (NSArray *)propertyKeysOfCurrentClass;
+ (NSSet *)propertyKeys;
+ (id)modelWithDictionary:(NSDictionary *)arg1 error:(id *)arg2;
- (_Bool)validate:(id *)arg1;
- (void)mergeValueForKey:(NSString *)arg1 fromModel:(id <MTLModel>)arg2;
- (id)initWithDictionary:(NSDictionary *)arg1 error:(id *)arg2;
@property(nonatomic, readonly) NSDictionary *dictionaryValue;
@end

