//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class Protocol;

@protocol RTVDynamicCast <NSObject>
- (id)dynamicCastProtocol:(Protocol *)arg1;
- (id)dynamicCast:(Class)arg1;
@end

