//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSObject;
@protocol SSWCTValueProtocol;

@protocol SSWCTColumnCoding
+ (unsigned long long)columnType;
+ (id)unarchiveWithWCTValue:(NSObject<SSWCTValueProtocol> *)arg1;
- (NSObject<SSWCTValueProtocol> *)archivedWCTValue;
@end

