//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData, NSNumber, NSString;

@protocol SSWCTValueProtocol
- (NSData *)dataValue;
- (NSNumber *)numberValue;
- (NSString *)stringValue;
@end

