//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol TMAUIViewControllerTrackProtocol <NSObject>

@optional
- (void)trackStartedByAppWillEnterForground;
- (void)trackEndedByAppWillEnterBackground;
@end

