//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/TMNetworkAspectProtocol-Protocol.h>

@class NSData, NSString, NSURL;

@protocol TMNetworkAspectRequestProtocol <TMNetworkAspectProtocol>
- (void)tm_net_dropRequest;
- (NSString *)tm_net_HTTPMethod;
- (void)tm_net_setHTTPBody:(NSData *)arg1;
- (NSData *)tm_net_HTTPBody;
- (void)tm_net_setValue:(NSString *)arg1 forHTTPHeaderField:(NSString *)arg2;
- (void)tm_net_setURL:(NSURL *)arg1;
@end

