//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/TMNetworkAspectProtocol-Protocol.h>

@class NSData, NSError, NSString;
@protocol TMNetworkAspectRequestProtocol;

@protocol TMNetworkAspectResponseProtocol <TMNetworkAspectProtocol>
- (void)tm_net_setResponseError:(NSError *)arg1;
- (NSError *)tm_net_responseError;
- (void)tm_net_setResponseData:(NSData *)arg1;
- (NSData *)tm_net_responseData;
- (NSString *)tm_net_MIMEType;
- (long long)tm_net_statusCode;
- (id <TMNetworkAspectRequestProtocol>)tm_net_request;
@end

