//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@protocol TMSilenceModeProtocol <NSObject>
+ (unsigned long long)silenceMode;
+ (double)silenceInterval;
+ (_Bool)isSilence;
+ (void)active;
@end

