//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSDictionary, NSError, NSString, TTVideoEngine, TTVideoEngineLoadInfo, TTVideoEngineModel, TTVideoEngineSubInfo;

@protocol TTVideoEngineDelegate <NSObject>
- (void)videoEngineCloseAysncFinish:(TTVideoEngine *)arg1;
- (void)videoEngineDidFinish:(TTVideoEngine *)arg1 videoStatusException:(long long)arg2;
- (void)videoEngineDidFinish:(TTVideoEngine *)arg1 error:(NSError *)arg2;
- (void)videoEngineUserStopped:(TTVideoEngine *)arg1;

@optional
- (void)videoEngine:(TTVideoEngine *)arg1 onSubLoadFinished:(_Bool)arg2 info:(TTVideoEngineLoadInfo *)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 onSubSwitchCompleted:(_Bool)arg2 currentSubtitleId:(long long)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 onSubtitleInfoRequested:(id)arg2 error:(NSError *)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 onSubtitleInfoCallBack:(TTVideoEngineSubInfo *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 onSubtitleInfoCallBack:(NSString *)arg2 pts:(unsigned long long)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 didFinishedWithEvent:(NSDictionary *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 crosstalkHappen:(NSDictionary *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 onAVBadInterlaced:(NSDictionary *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 switchMediaInfoCompleted:(long long)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 noVARenderStateDidChange:(unsigned long long)arg2 extraInfo:(NSDictionary *)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 avOutsyncStateDidChanged:(unsigned long long)arg2 extraInfo:(NSDictionary *)arg3;
- (void)videoEngineOutleterPaused:(TTVideoEngine *)arg1 streamType:(long long)arg2;
- (void)videoEngineBeforeViewRemove:(TTVideoEngine *)arg1;
- (void)videoEngineDeviceOpened:(TTVideoEngine *)arg1 streamType:(long long)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 mdlKey:(NSString *)arg2 hitCacheSze:(long long)arg3;
- (void)videoEngineStalledExcludeSeek:(TTVideoEngine *)arg1;
- (void)videoEngine:(TTVideoEngine *)arg1 retryForError:(NSError *)arg2;
- (void)videoEngineAudioRendered:(TTVideoEngine *)arg1;
- (void)videoEngineReadyToPlay:(TTVideoEngine *)arg1;
- (void)videoEnginePrepared:(TTVideoEngine *)arg1;
- (void)videoEngineReadyToDisPlay:(TTVideoEngine *)arg1;
- (void)videoEngine:(TTVideoEngine *)arg1 usingUrlInfos:(NSArray *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 fetchedVideoModel:(TTVideoEngineModel *)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 loadStateDidChanged:(unsigned long long)arg2 extra:(NSDictionary *)arg3;
- (void)videoEngine:(TTVideoEngine *)arg1 loadStateDidChanged:(unsigned long long)arg2;
- (void)videoEngine:(TTVideoEngine *)arg1 playbackStateDidChanged:(long long)arg2;
@end

