//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;

@protocol TVLABRSwitching <NSObject>
- (long long)performABRSwitchWithDecisionInfo:(NSDictionary *)arg1;
- (void)ABRSwitchDidRejectWithRequestResult:(unsigned long long)arg1 decisionInfo:(NSDictionary *)arg2;
- (unsigned long long)shouldPerformABRSwitchWithDecisionInfo:(NSDictionary *)arg1;
@end

