//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSArray, NSError, NSString;
@protocol TVLDNSParsing;

@protocol TVLDNSParserDelegate <NSObject>
- (void)parser:(id <TVLDNSParsing>)arg1 didCancelParsingHostname:(NSString *)arg2;
- (void)parser:(id <TVLDNSParsing>)arg1 didFinishParsingHostname:(NSString *)arg2 withParesedAddresses:(NSArray *)arg3 error:(NSError *)arg4;

@optional
- (void)parser:(id <TVLDNSParsing>)arg1 didGetRecordWithHostname:(NSString *)arg2 parsedAddresses:(NSArray *)arg3 timeToLive:(double)arg4;
- (void)parser:(id <TVLDNSParsing>)arg1 cacheOfHost:(NSString *)arg2 isHitted:(_Bool)arg3;
@end

