//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSError, NSNotification, NSNumber, NSString, TVLController;

@protocol TVLPlayerControllerDelegate <NSObject>
@property(readonly, nonatomic, getter=isPlaybackInterrupted) _Bool playbackInterrupted;
- (void)playerController:(TVLController *)arg1 readyToPlayVideoCodecID:(int)arg2 audioCodecID:(int)arg3;
- (void)preconnectWithStreamData:(NSDictionary *)arg1;
- (NSDictionary *)getLiveIOParamsIfNeeded;
- (NSDictionary *)nodeInfoWithHostFromLss:(NSString *)arg1 extraInfo:(NSDictionary *)arg2;
- (NSDictionary *)nodeInfoWithHostFromLss:(NSString *)arg1;
- (void)receivePlayerErrorForDebug:(NSError *)arg1;
- (_Bool)shouldTryNextURLs;
- (void)initLutFilterWhenNeeded;
- (_Bool)playerController:(TVLController *)arg1 shouldRetryWithReason:(long long)arg2 times:(long long)arg3 duration:(double)arg4;
- (void)playerController:(TVLController *)arg1 playerItemStatusDidChange:(long long)arg2;
- (void)playerController:(TVLController *)arg1 videoSizeDidChange:(struct CGSize)arg2;
- (void)itemStatusChanged:(NSNumber *)arg1;
- (void)loadStateChanged:(NSNumber *)arg1;
- (void)onMonitorLog:(NSDictionary *)arg1;
- (void)onReceiveSeiMessage:(NSString *)arg1;
- (void)onStreamDryup:(NSError *)arg1;
- (void)handleRenderStall:(NSNotification *)arg1;
- (void)stallEnd;
- (void)stallStart;
- (void)startAudioRender;
- (void)startVideoRender;
- (void)recieveError:(NSError *)arg1;
@end

