//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class TYPagerController, UIViewController;

@protocol TYPagerControllerDataSource <NSObject>
- (UIViewController *)pagerController:(TYPagerController *)arg1 controllerForIndex:(long long)arg2 prefetching:(_Bool)arg3;
- (long long)numberOfControllersInPagerController;
@end

