//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class TYPagerViewLayout;

@protocol TYPagerViewLayoutDelegate <NSObject>

@optional
- (void)pagerViewLayoutDidEndScrollingAnimation:(TYPagerViewLayout *)arg1;
- (void)pagerViewLayoutDidEndDecelerating:(TYPagerViewLayout *)arg1;
- (void)pagerViewLayoutWillBeginDecelerating:(TYPagerViewLayout *)arg1;
- (void)pagerViewLayoutDidEndDragging:(TYPagerViewLayout *)arg1 willDecelerate:(_Bool)arg2;
- (void)pagerViewLayoutWillBeginDragging:(TYPagerViewLayout *)arg1;
- (void)pagerViewLayoutDidEndScrollToView:(TYPagerViewLayout *)arg1 animate:(_Bool)arg2;
- (void)pagerViewLayoutWillBeginScrollToView:(TYPagerViewLayout *)arg1 animate:(_Bool)arg2;
- (void)pagerViewLayoutDidScroll:(TYPagerViewLayout *)arg1;
- (void)pagerViewLayout:(TYPagerViewLayout *)arg1 transitionFromIndex:(long long)arg2 toIndex:(long long)arg3 progress:(double)arg4;
- (void)pagerViewLayout:(TYPagerViewLayout *)arg1 transitionFromIndex:(long long)arg2 toIndex:(long long)arg3 animated:(_Bool)arg4;
@end

