//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class TYTabPagerBar, TYTabPagerBarLayout, UICollectionViewCell;
@protocol TYTabPagerBarCellProtocol;

@protocol TYTabPagerBarDelegate <NSObject>

@optional
- (void)pagerTabBar:(TYTabPagerBar *)arg1 transitionFromeCell:(UICollectionViewCell<TYTabPagerBarCellProtocol> *)arg2 toCell:(UICollectionViewCell<TYTabPagerBarCellProtocol> *)arg3 progress:(double)arg4;
- (void)pagerTabBar:(TYTabPagerBar *)arg1 transitionFromeCell:(UICollectionViewCell<TYTabPagerBarCellProtocol> *)arg2 toCell:(UICollectionViewCell<TYTabPagerBarCellProtocol> *)arg3 animated:(_Bool)arg4;
- (void)pagerTabBar:(TYTabPagerBar *)arg1 didSelectItemAtIndex:(long long)arg2;
- (double)pagerTabBar:(TYTabPagerBar *)arg1 widthForItemAtIndex:(long long)arg2;
- (void)pagerTabBar:(TYTabPagerBar *)arg1 configureLayout:(TYTabPagerBarLayout *)arg2;
@end

