//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/UIAdaptivePresentationControllerDelegate-Protocol.h>

@class UISheetPresentationController;

@protocol UISheetPresentationControllerDelegate <UIAdaptivePresentationControllerDelegate>

@optional
- (void)sheetPresentationControllerDidChangeSelectedDetentIdentifier:(UISheetPresentationController *)arg1;
@end

