//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary;
@protocol XPlayItemProtocol;

@protocol XPlayItemDeprecatedDelegate <NSObject>
- (void)playItem:(id <XPlayItemProtocol>)arg1 playStatusDidUpdated:(unsigned long long)arg2 info:(NSDictionary *)arg3;

@optional
- (void)playItem:(id <XPlayItemProtocol>)arg1 videoQualityChangeResult:(unsigned long long)arg2;
@end

