//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class NSDictionary, NSString;
@protocol XPlayAuthInfoProtocol, XPlayAuthProtocol, XPlayFollowProtocol, XPlayGameJoinGroupProtocol, XPlayGameRoomInviteProtocol, XPlayHighlightProtocol, XPlayItemProtocol, XPlayOrderProtocol;

@protocol XPlayItemBusinessDelegate <NSObject>

@optional
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveServerPushedCustomNotice:(NSDictionary *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveXPlayPodInfoData:(NSDictionary *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceivePushCDNFailed:(NSString *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 customMessage:(NSString *)arg2 didReceiveCustomRequest:(void (^)(long long, NSString *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveShareRequest:(void (^)(long long, NSString *))arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveJoinGroupRequest:(id <XPlayGameJoinGroupProtocol>)arg2 callback:(void (^)(NSDictionary *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveExitRequest:(void (^)(long long, NSString *))arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveGameRoomInviteRequest:(id <XPlayGameRoomInviteProtocol>)arg2 callback:(void (^)(long long, NSString *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveFollowRequest:(id <XPlayFollowProtocol>)arg2 callback:(void (^)(long long, NSString *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveAdRequest:(NSDictionary *)arg2 callback:(void (^)(NSDictionary *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveHighlightPostResult:(_Bool)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveHighlightPostRequest:(id <XPlayHighlightProtocol>)arg2 callback:(void (^)(long long))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveAuthEvent:(id <XPlayAuthInfoProtocol>)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveRealNameRequest:(id <XPlayAuthProtocol>)arg2 callback:(void (^)(long long, NSString *, NSString *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveAuthRequest:(id <XPlayAuthProtocol>)arg2 callback:(void (^)(long long, NSString *, NSString *))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveGameOrder:(id <XPlayOrderProtocol>)arg2 callback:(void (^)(long long, NSString *))arg3;
@end

