//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/XPlayItemDeprecatedDelegate-Protocol.h>

@class ByteRTCAudioFrame, NSData, NSDictionary, NSError, NSString, XPlayQueueConfiguration, XPlaySEIInfoModel;
@protocol XPLayQualityStats><NSCopying, XPlayBusinessConfigProtocol, XPlayItemProtocol, XPlayRTCVideoFrame, XPlayRemotePodEventInfo, XPlayUserInfoProtocol;

@protocol XPlayItemDelegate <XPlayItemDeprecatedDelegate>

@optional
- (void)playItem:(id <XPlayItemProtocol>)arg1 rtcAudioFrame:(ByteRTCAudioFrame *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 rtcVideoFrame:(id <XPlayRTCVideoFrame>)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 renderPixelBuffer:(struct __CVBuffer *)arg2 rotation:(long long)arg3 contentType:(long long)arg4 extendedData:(NSData *)arg5 pts:(CDStruct_1b6d18a9)arg6;
- (_Bool)checkIsShowing;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didAcceleratedQueueWithRes:(long long)arg2 configuration:(XPlayQueueConfiguration *)arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didExpireQueue:(XPlayQueueConfiguration *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didFinishQueue:(XPlayQueueConfiguration *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didDequeue:(XPlayQueueConfiguration *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didUpdateQueueInfo:(XPlayQueueConfiguration *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 canJoinQueue:(XPlayQueueConfiguration *)arg2 callback:(void (^)(_Bool))arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 onRemotePodEvent:(unsigned long long)arg2 info:(id <XPlayRemotePodEventInfo>)arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 remoteVideoRotationChanged:(long long)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 remoteVideoStateChangeWith:(long long)arg2 withVideoStateReason:(long long)arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 networkStatusChangedFrom:(unsigned long long)arg2 to:(unsigned long long)arg3;
- (void)dealWithArchivedFail:(NSError *)arg1 info:(NSDictionary *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 onCustomMessageReceivedWithCode:(int)arg2 uniqueSeq:(NSString *)arg3 message:(NSString *)arg4;
- (void)playItemDidLostConnection:(id <XPlayItemProtocol>)arg1;
- (void)playItem:(id <XPlayItemProtocol>)arg1 onNetworkDetectionStopped:(unsigned long long)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 onNetworkDetectionWithQuality:(unsigned long long)arg2 rtt:(int)arg3 lostRate:(double)arg4 bitrate:(int)arg5 jitter:(int)arg6 isQualified:(_Bool)arg7;
- (void)playItem:(id <XPlayItemProtocol>)arg1 config:(id <XPlayBusinessConfigProtocol>)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 updateUserInfo:(id <XPlayUserInfoProtocol>)arg2 oldUserInfo:(id <XPlayUserInfoProtocol>)arg3;
- (void)playItem:(id <XPlayItemProtocol>)arg1 taskFinishedWithCode:(int)arg2 type:(unsigned long long)arg3 time:(long long)arg4;
- (void)playItem:(id <XPlayItemProtocol>)arg1 increaseTimeResult:(NSDictionary *)arg2;
- (void)playItemcanChangeToFHD:(id <XPlayItemProtocol>)arg1;
- (void)playItem:(id <XPlayItemProtocol>)arg1 netStatus:(long long)arg2 rtt:(long long)arg3 needToast:(_Bool)arg4 needNotification:(_Bool)arg5;
- (void)playItem:(id <XPlayItemProtocol>)arg1 netStatus:(long long)arg2 needToast:(_Bool)arg3;
- (void)playItemViewTouchBegan:(id <XPlayItemProtocol>)arg1;
- (void)playItemViewWillAppear:(id <XPlayItemProtocol>)arg1;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveMessage:(NSString *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 didReceiveUserHeartbeatMessage:(NSDictionary *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 playTimeCountDown:(unsigned long long)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 onDetectOperationDelay:(XPlaySEIInfoModel *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 playQualityStats:(id <XPLayQualityStats><NSCopying>)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 preloadDidSucceed:(NSDictionary *)arg2;
- (void)playItem:(id <XPlayItemProtocol>)arg1 preloadDidFailed:(NSDictionary *)arg2;
@end

