//
//     Generated by class-dump 3.5 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AwemeCore/NSObject-Protocol.h>

@class CALayer, NSString, YYLabel;
@protocol CAAction;

@protocol YYLabelAnimationDelegate <NSObject>
- (id <CAAction>)label:(YYLabel *)arg1 actionForLayer:(CALayer *)arg2 forKey:(NSString *)arg3;
@end

